$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE A (A2) ---
    ("la capacité", "ability", "die Fähigkeit", "la capacidad", "nom", "A2"),
    ("capable", "able", "fähig", "capaz", "adjectif", "A2"),
    ("à l'étranger", "abroad", "im Ausland", "en el extranjero", "adverbe", "A2"),
    ("accepter", "accept", "akzeptieren", "aceptar", "verbe", "A2"),
    ("l'accident", "accident", "der Unfall", "el accidente", "nom", "A2"),
    ("atteindre / accomplir", "achieve", "erreichen", "lograr", "verbe", "A2"),
    ("agir", "act", "handeln", "actuar", "verbe", "A2"),
    ("actif", "active", "aktiv", "activo", "adjectif", "A2"),
    ("en fait", "actually", "eigentlich", "en realidad", "adverbe", "A2"),
    ("l'avantage", "advantage", "der Vorteil", "el beneficio", "nom", "A2"),
    ("l'aventure", "adventure", "das Abenteuer", "la aventura", "nom", "A2"),
    ("faire de la publicité", "advertise", "werben", "anunciar", "verbe", "A2"),
    ("la publicité", "advertisement", "die Werbung", "el anuncio", "nom", "A2"),
    ("la publicité (domaine)", "advertising", "die Werbung", "la publicidad", "nom", "A2"),
    ("le conseil", "advice", "der Rat", "el consejo", "nom", "A2"),
    ("affecter", "affect", "beeinflussen", "afectar", "verbe", "A2"),
    ("après", "after", "nachdem", "después de", "prep", "A2"),
    ("contre", "against", "gegen", "contra", "prep", "A2"),
    ("être d'accord", "agree", "zustimmen", "estar de acuerdo", "verbe", "A2"),
    ("ah", "ah", "ah", "ah", "interj", "A2"),
    ("la compagnie aérienne", "airline", "die Fluggesellschaft", "la aerolínea", "nom", "A2"),
    ("vivant", "alive", "lebendig", "vivo", "adjectif", "A2"),
    ("tout / tous", "all", "alle", "todo", "pron", "A2"),
    ("permettre", "allow", "erlauben", "permitir", "verbe", "A2"),
    ("presque", "almost", "fast", "casi", "adverbe", "A2"),
    ("seul", "alone", "allein", "solo", "adjectif", "A2"),
    ("le long de", "along", "entlang", "a lo largo de", "prep", "A2"),
    ("déjà", "already", "schon", "ya", "adverbe", "A2"),
    ("bien que", "although", "obwohl", "aunque", "conjonction", "A2"),
    ("parmi", "among", "unter", "entre", "prep", "A2"),
    ("la quantité", "amount", "die Menge", "la cantidad", "nom", "A2"),
    ("ancien", "ancient", "antik", "antiguo", "adjectif", "A2"),
    ("la cheville", "ankle", "der Knöchel", "el tobillo", "nom", "A2"),
    ("n'importe lequel", "any", "irgendein", "cualquiera", "pron", "A2"),
    ("n'importe qui", "anybody", "irgendjemand", "cualquiera", "pron", "A2"),
    ("plus (jamais)", "any more", "nicht mehr", "ya no", "adverbe", "A2"),
    ("de toute façon", "anyway", "jedenfalls", "de todos modos", "adverbe", "A2"),
    ("n'importe où", "anywhere", "überall", "en cualquier lugar", "adverbe", "A2"),
    ("l'application", "app", "die App", "la aplicación", "nom", "A2"),
    ("apparaître", "appear", "erscheinen", "aparecer", "verbe", "A2"),
    ("l'apparence", "appearance", "das Aussehen", "la apariencia", "nom", "A2"),
    ("appliquer / postuler", "apply", "sich bewerben", "aplicar", "verbe", "A2"),
    ("l'architecte", "architect", "der Architekt", "el arquitecto", "nom", "A2"),
    ("l'architecture", "architecture", "die Architektur", "la arquitectura", "nom", "A2"),
    ("se disputer / argumenter", "argue", "streiten", "discutir", "verbe", "A2"),
    ("l'argument", "argument", "das Argument", "el argumento", "nom", "A2"),
    ("l'armée", "army", "die Armee", "el ejército", "nom", "A2"),
    ("autour", "around", "herum", "alrededor", "adverbe", "A2"),
    ("arranger", "arrange", "arrangieren", "organizar", "verbe", "A2"),
    ("l'arrangement", "arrangement", "die Vereinbarung", "el acuerdo", "nom", "A2"),
    ("comme / en tant que", "as", "wie / als", "como", "prep", "A2"),
    ("endormi", "asleep", "schlafend", "dormido", "adjectif", "A2"),
    ("l'assistant", "assistant", "der Assistent", "el asistente", "nom", "A2"),
    ("l'athlète", "athlete", "der Athlet", "el atleta", "nom", "A2"),
    ("attaquer", "attack", "angreifen", "atacar", "verbe", "A2"),
    ("l'attaque", "attack", "der Angriff", "el ataque", "nom", "A2"),
    ("assister à", "attend", "teilnehmen", "asistir", "verbe", "A2"),
    ("l'attention", "attention", "die Aufmerksamkeit", "la atención", "nom", "A2"),
    ("attractif", "attractive", "attraktiv", "atractivo", "adjectif", "A2"),
    ("le public", "audience", "das Publikum", "el público", "nom", "A2"),
    ("l'auteur", "author", "der Autor", "el autor", "nom", "A2"),
    ("disponible", "available", "verfügbar", "disponible", "adjectif", "A2"),
    ("moyen", "average", "durchschnittlich", "promedio", "adjectif", "A2"),
    ("éviter", "avoid", "vermeiden", "evitar", "verbe", "A2"),
    ("le prix / la récompense", "award", "die Auszeichnung", "el premio", "nom", "A2"),
    ("terrible / affreux", "awful", "schrecklich", "terrible", "adjectif", "A2"),

    # --- LETTRE B (A2) ---
    ("le fond (historique)", "background", "der Hintergrund", "el fondo", "nom", "A2"),
    ("mal (adverbe)", "badly", "schlecht", "mal", "adverbe", "A2"),
    ("le baseball", "baseball", "der Baseball", "el béisbol", "nom", "A2"),
    ("le basketball", "basketball", "der Basketball", "el baloncesto", "nom", "A2"),
    ("la basse", "bass", "der Bass", "el bajo", "nom", "A2"),
    ("le haricot", "bean", "die Bohne", "el frijol", "nom", "A2"),
    ("l'ours", "bear", "der Bär", "el oso", "nom", "A2"),
    ("battre", "beat", "schlagen", "vencer", "verbe", "A2"),
    ("le bœuf (viande)", "beef", "das Rindfleisch", "la carne de res", "nom", "A2"),
    ("avant", "before", "bevor", "antes de", "prep", "A2"),
    ("se comporter", "behave", "sich verhalten", "comportarse", "verbe", "A2"),
    ("appartenir", "belong", "gehören", "pertenecer", "verbe", "A2"),
    ("la ceinture", "belt", "der Gürtel", "el cinturón", "nom", "A2"),
    ("le bénéfice", "benefit", "der Nutzen", "el beneficio", "nom", "A2"),
    ("le meilleur", "best", "beste", "mejor", "adjectif", "A2"),
    ("meilleur", "better", "besser", "mejor", "adjectif", "A2"),
    ("entre", "between", "zwischen", "entre", "prep", "A2"),
    ("le milliard", "billion", "die Milliarde", "el mil millones", "num", "A2"),
    ("la poubelle", "bin", "der Mülleimer", "el cubo de basura", "nom", "A2"),
    ("la biologie", "biology", "die Biologie", "la biología", "nom", "A2"),
    ("la naissance", "birth", "die Geburt", "el nacimiento", "nom", "A2"),
    ("le biscuit", "biscuit", "der Keks", "la galleta", "nom", "A2"),
    ("le morceau", "bit", "das Stück", "el pedazo", "nom", "A2"),
    ("vide / blanc", "blank", "leer", "en blanco", "adjectif", "A2"),
    ("le sang", "blood", "das Blut", "la sangre", "nom", "A2"),
    ("souffler", "blow", "blasen", "soplar", "verbe", "A2"),
    ("le tableau", "board", "das Brett / die Tafel", "la tabla", "nom", "A2"),
    ("bouillir", "boil", "kochen", "hervir", "verbe", "A2"),
    ("l'os", "bone", "der Knochen", "el hueso", "nom", "A2"),
    ("réserver", "book", "buchen", "reservar", "verbe", "A2"),
    ("emprunter", "borrow", "leihen", "pedir prestado", "verbe", "A2"),
    ("le patron", "boss", "der Chef", "el jefe", "nom", "A2"),
    ("le fond / le bas", "bottom", "der Boden", "el fondo", "nom", "A2"),
    ("le bol", "bowl", "die Schüssel", "el tazón", "nom", "A2"),
    ("le cerveau", "brain", "das Gehirn", "el cerebro", "nom", "A2"),
    ("le pont", "bridge", "die Brücke", "el puente", "nom", "A2"),
    ("brillant (lumineux)", "bright", "hell", "brillante", "adjectif", "A2"),
    ("génial", "brilliant", "brillant", "genial", "adjectif", "A2"),
    ("cassé", "broken", "kaputt", "roto", "adjectif", "A2"),
    ("la brosse", "brush", "die Bürste", "el cepillo", "nom", "A2"),
    ("brosser", "brush", "bürsten", "cepillar", "verbe", "A2"),
    ("le copain", "buddy", "der Kumpel", "el amigo", "nom", "A2"),
    ("brûler", "burn", "brennen", "quemar", "verbe", "A2"),
    ("l'homme d'affaires", "businessman", "der Geschäftsmann", "el empresario", "nom", "A2"),
    ("le papillon", "butterfly", "der Schmetterling", "la mariposa", "nom", "A2"),
    ("le bouton", "button", "der Knopf", "el botón", "nom", "A2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_a2_batch1.ps1", $new_words, $utf8NoBom)
