$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE C (A2) ---
    ("le camp", "camp", "das Lager", "el campamento", "nom", "A2"),
    ("camper", "camp", "campen", "acampar", "verbe", "A2"),
    ("le camping", "camping", "das Camping", "el camping", "nom", "A2"),
    ("la canette", "can", "die Dose", "la lata", "nom", "A2"),
    ("le soin", "care", "die Pflege", "el cuidado", "nom", "A2"),
    ("se soucier", "care", "sich kümmern", "importar", "verbe", "A2"),
    ("prudent", "careful", "vorsichtig", "cuidadoso", "adjectif", "A2"),
    ("soigneusement", "carefully", "vorsichtig", "cuidadosamente", "adverbe", "A2"),
    ("le tapis", "carpet", "der Teppich", "la alfombra", "nom", "A2"),
    ("le dessin animé", "cartoon", "der Zeichentrickfilm", "el dibujo animado", "nom", "A2"),
    ("le cas", "case", "der Fall", "el caso", "nom", "A2"),
    ("l'argent liquide", "cash", "das Bargeld", "el dinero en efectivo", "nom", "A2"),
    ("le casino", "casino", "das Casino", "el casino", "nom", "A2"),
    ("le château", "castle", "die Burg", "el castillo", "nom", "A2"),
    ("attraper", "catch", "fangen", "atrapar", "verbe", "A2"),
    ("causer", "cause", "verursachen", "causar", "verbe", "A2"),
    ("la cause", "cause", "die Ursache", "la causa", "nom", "A2"),
    ("célébrer", "celebrate", "feiern", "celebrar", "verbe", "A2"),
    ("la célébrité", "celebrity", "die Berühmtheit", "la celebridad", "nom", "A2"),
    ("certain", "certain", "sicher", "cierto", "adjectif", "A2"),
    ("certainement", "certainly", "sicherlich", "ciertamente", "adverbe", "A2"),
    ("la chance / l'opportunité", "chance", "die Chance", "la oportunidad", "nom", "A2"),
    ("le caractère", "character", "der Charakter", "el carácter", "nom", "A2"),
    ("l'association caritative", "charity", "die Wohltätigkeit", "la caridad", "nom", "A2"),
    ("discuter / bavarder", "chat", "plaudern", "charlar", "verbe", "A2"),
    ("la discussion", "chat", "der Plausch", "la charla", "nom", "A2"),
    ("le chef", "chef", "der Küchenchef", "el chef", "nom", "A2"),
    ("la chimie", "chemistry", "die Chemie", "la química", "nom", "A2"),
    ("la frite / la puce", "chip", "der Chip", "la patata frita", "nom", "A2"),
    ("le choix", "choice", "die Wahl", "la elección", "nom", "A2"),
    ("l'église", "church", "die Kirche", "la iglesia", "nom", "A2"),
    ("la cigarette", "cigarette", "die Zigarette", "la cigarrillo", "nom", "A2"),
    ("le cercle", "circle", "der Kreis", "el círculo", "nom", "A2"),
    ("classique", "classical", "klassisch", "clásico", "adjectif", "A2"),
    ("clair", "clear", "klar", "claro", "adjectif", "A2"),
    ("clairement", "clearly", "klar", "claramente", "adverbe", "A2"),
    ("intelligent", "clever", "klug", "inteligente", "adjectif", "A2"),
    ("le climat", "climate", "das Klima", "el clima", "nom", "A2"),
    ("proche", "close", "nah", "cerca", "adjectif", "A2"),
    ("fermé", "closed", "geschlossen", "cerrado", "adjectif", "A2"),
    ("les vêtements", "clothing", "die Kleidung", "la ropa", "nom", "A2"),
    ("le nuage", "cloud", "die Wolke", "la nube", "nom", "A2"),
    ("l'entraîneur", "coach", "der Trainer", "el entrenador", "nom", "A2"),
    ("la côte", "coast", "die Küste", "la costa", "nom", "A2"),
    ("le code", "code", "der Code", "el código", "nom", "A2"),
    ("la pièce de monnaie", "coin", "die Münze", "la moneda", "nom", "A2"),
    ("le collègue", "colleague", "der Kollege", "el colega", "nom", "A2"),
    ("collectionner", "collect", "sammeln", "recolectar", "verbe", "A2"),
    ("la colonne", "column", "die Spalte", "la columna", "nom", "A2"),
    ("la comédie", "comedy", "die Komödie", "la comedia", "nom", "A2"),
    ("confortable", "comfortable", "bequem", "cómodo", "adjectif", "A2"),
    ("commun", "common", "gemeinsam", "común", "adjectif", "A2"),
    ("le commentaire", "comment", "der Kommentar", "el comentario", "nom", "A2"),
    ("communiquer", "communicate", "kommunizieren", "comunicarse", "verbe", "A2"),
    ("la communauté", "community", "die Gemeinschaft", "la comunidad", "nom", "A2"),
    ("comparer", "compare", "vergleichen", "comparar", "verbe", "A2"),
    ("rivaliser", "compete", "konkurrieren", "competir", "verbe", "A2"),
    ("la compétition", "competition", "der Wettbewerb", "la competencia", "nom", "A2"),
    ("se plaindre", "complain", "sich beschweren", "quejarse", "verbe", "A2"),
    ("complètement", "completely", "vollständig", "completamente", "adverbe", "A2"),
    ("la condition", "condition", "die Bedingung", "la condición", "nom", "A2"),
    ("la conférence", "conference", "die Konferenz", "la conferencia", "nom", "A2"),
    ("connecter", "connect", "verbinden", "conectar", "verbe", "A2"),
    ("connecté", "connected", "verbunden", "conectado", "adjectif", "A2"),
    ("considérer", "consider", "betrachten", "considerar", "verbe", "A2"),
    ("contenir", "contain", "enthalten", "contener", "verbe", "A2"),
    ("le continent", "continent", "der Kontinent", "el continente", "nom", "A2"),
    ("continuer", "continue", "fortfahren", "continuar", "verbe", "A2"),
    ("la conversation", "conversation", "die Konversation", "la conversación", "nom", "A2"),
    ("le contrôle", "control", "die Kontrolle", "el control", "nom", "A2"),
    ("contrôler", "control", "kontrollieren", "controlar", "verbe", "A2"),
    ("le cuisinier", "cook", "der Koch", "el cocinero", "nom", "A2"),
    ("la cuisinière (four)", "cooker", "der Herd", "la cocina", "nom", "A2"),
    ("la copie", "copy", "die Kopie", "la copia", "nom", "A2"),
    ("copier", "copy", "kopieren", "copiar", "verbe", "A2"),
    ("le coin", "corner", "die Ecke", "la esquina", "nom", "A2"),
    ("correctement", "correctly", "richtig", "correctamente", "adverbe", "A2"),
    ("compter", "count", "zählen", "contar", "verbe", "A2"),
    ("le couple", "couple", "das Paar", "la pareja", "nom", "A2"),
    ("fou", "crazy", "verrückt", "loco", "adjectif", "A2"),
    ("créatif", "creative", "kreativ", "creativo", "adjectif", "A2"),
    ("le crime", "crime", "das Verbrechen", "el crimen", "nom", "A2"),
    ("le criminel", "criminal", "der Kriminelle", "el criminal", "nom", "A2"),
    ("traverser", "cross", "überqueren", "cruzar", "verbe", "A2"),
    ("la croix", "cross", "das Kreuz", "la cruz", "nom", "A2"),
    ("la foule", "crowd", "die Menge", "la multitud", "nom", "A2"),
    ("bondé", "crowded", "überfüllt", "lleno", "adjectif", "A2"),
    ("pleurer", "cry", "weinen", "llorar", "verbe", "A2"),
    ("le placard", "cupboard", "der Schrank", "el armario", "nom", "A2"),
    ("bouclé", "curly", "lockig", "rizado", "adjectif", "A2"),
    ("mignon", "cute", "niedlich", "lindo", "adjectif", "A2"),
    ("le cycle", "cycle", "der Zyklus", "el ciclo", "nom", "A2"),
    ("faire du vélo", "cycle", "Rad fahren", "ir en bicicleta", "verbe", "A2"),

    # --- LETTRE D (A2) ---
    ("quotidiennement", "daily", "täglich", "diariamente", "adverbe", "A2"),
    ("le danger", "danger", "die Gefahr", "el peligro", "nom", "A2"),
    ("sombre", "dark", "dunkel", "oscuro", "adjectif", "A2"),
    ("mort", "dead", "tot", "muerto", "adjectif", "A2"),
    ("gérer", "deal with", "sich befassen mit", "lidiar con", "verbe", "A2"),
    ("la mort", "death", "der Tod", "la muerte", "nom", "A2"),
    ("la décision", "decision", "die Entscheidung", "la decisión", "nom", "A2"),
    ("profond", "deep", "tief", "profundo", "adjectif", "A2"),
    ("définitivement", "definitely", "definitiv", "definitivamente", "adverbe", "A2"),
    ("le diplôme / le degré", "degree", "der Abschluss", "el grado", "nom", "A2"),
    ("le dentiste", "dentist", "der Zahnarzt", "el dentista", "nom", "A2"),
    ("le département", "department", "die Abteilung", "el departamento", "nom", "A2"),
    ("dépendre", "depend", "abhängen", "depender", "verbe", "A2"),
    ("décrire", "describe", "beschreiben", "describir", "verbe", "A2"),
    ("la description", "description", "die Beschreibung", "la descripción", "nom", "A2"),
    ("le désert", "desert", "die Wüste", "el desierto", "nom", "A2"),
    ("le design", "design", "das Design", "el diseño", "nom", "A2"),
    ("concevoir", "design", "entwerfen", "diseñar", "verbe", "A2"),
    ("le designer", "designer", "der Designer", "el diseñador", "nom", "A2"),
    ("détruire", "destroy", "zerstören", "destruir", "verbe", "A2"),
    ("le détective", "detective", "der Detektiv", "el detective", "nom", "A2"),
    ("développer", "develop", "entwickeln", "desarrollar", "verbe", "A2"),
    ("l'appareil", "device", "das Gerät", "el dispositivo", "nom", "A2"),
    ("le journal intime", "diary", "das Tagebuch", "el diario", "nom", "A2"),
    ("la différence", "difference", "der Unterschied", "la diferencia", "nom", "A2"),
    ("différemment", "differently", "anders", "diferentemente", "adverbe", "A2"),
    ("numérique", "digital", "digital", "digital", "adjectif", "A2"),
    ("direct", "direct", "direkt", "directo", "adjectif", "A2"),
    ("diriger", "direct", "leiten", "dirigir", "verbe", "A2"),
    ("la direction", "direction", "die Richtung", "la dirección", "nom", "A2"),
    ("le directeur", "director", "der Direktor", "el director", "nom", "A2"),
    ("être en désaccord", "disagree", "nicht zustimmen", "no estar de acuerdo", "verbe", "A2"),
    ("disparaître", "disappear", "verschwinden", "desaparecer", "verbe", "A2"),
    ("le désastre", "disaster", "die Katastrophe", "el desastre", "nom", "A2"),
    ("découvrir", "discover", "entdecken", "descubrir", "verbe", "A2"),
    ("la découverte", "discovery", "die Entdeckung", "el descubrimiento", "nom", "A2"),
    ("la discussion", "discussion", "die Diskussion", "la discusión", "nom", "A2"),
    ("la maladie", "disease", "die Krankheit", "la enfermedad", "nom", "A2"),
    ("la distance", "distance", "die Entfernung", "la distancia", "nom", "A2"),
    ("divorcé", "divorced", "geschieden", "divorciado", "adjectif", "A2"),
    ("le document", "document", "das Dokument", "el documento", "nom", "A2"),
    ("double", "double", "doppelt", "doble", "adjectif", "A2"),
    ("doubler", "double", "verdoppeln", "doblar", "verbe", "A2"),
    ("télécharger", "download", "herunterladen", "descargar", "verbe", "A2"),
    ("en bas (étage)", "downstairs", "unten", "abajo", "adverbe", "A2"),
    ("le drame", "drama", "das Drama", "el drama", "nom", "A2"),
    ("le dessin", "drawing", "die Zeichnung", "el dibujo", "nom", "A2"),
    ("le rêve", "dream", "der Traum", "el sueño", "nom", "A2"),
    ("rêver", "dream", "träumen", "soñar", "verbe", "A2"),
    ("le trajet (voiture)", "drive", "die Fahrt", "el viaje", "nom", "A2"),
    ("la conduite", "driving", "das Fahren", "la conducción", "nom", "A2"),
    ("laisser tomber", "drop", "fallen lassen", "dejar caer", "verbe", "A2"),
    ("la drogue / le médicament", "drug", "das Medikament", "la droga", "nom", "A2"),
    ("sec", "dry", "trocken", "seco", "adjectif", "A2"),
    ("sécher", "dry", "trocknen", "secar", "verbe", "A2"),
    ("le canard", "duck", "die Ente", "el pato", "nom", "A2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_a2_batch2.ps1", $new_words, $utf8NoBom)
