$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE A (B2) ---
    ("abandonner", "abandon", "verlassen / aufgeben", "abandonar", "verbe", "B2"),
    ("absent", "absent", "abwesend", "ausente", "adjectif", "B2"),
    ("absolu", "absolute", "absolut", "absoluto", "adjectif", "B2"),
    ("absorber", "absorb", "absorbieren / aufnehmen", "absorber", "verbe", "B2"),
    ("abstrait", "abstract", "abstrakt", "abstracto", "adjectif", "B2"),
    ("académique / universitaire", "academic", "akademisch", "académico", "adjectif", "B2"),
    ("l'universitaire", "academic", "der Akademiker", "el académico", "nom", "B2"),
    ("l'accent", "accent", "der Akzent", "el acento", "nom", "B2"),
    ("acceptable", "acceptable", "akzeptabel", "aceptable", "adjectif", "B2"),
    ("accidentellement", "accidentally", "zufällig", "accidentalmente", "adverbe", "B2"),
    ("accueillir / loger", "accommodate", "unterbringen", "alojar", "verbe", "B2"),
    ("accompagner", "accompany", "begleiten", "acompañar", "verbe", "B2"),
    ("accomplir", "accomplish", "erreichen", "lograr", "verbe", "B2"),
    ("expliquer / justifier", "account for", "erklären / ausmachen", "explicar", "verbe", "B2"),
    ("le comptable", "accountant", "der Buchhalter", "el contador", "nom", "B2"),
    ("la précision / l'exactitude", "accuracy", "die Genauigkeit", "la precisión", "nom", "B2"),
    ("précis / exact", "accurate", "genau", "preciso", "adjectif", "B2"),
    ("avec précision", "accurately", "genau", "con precisión", "adverbe", "B2"),
    ("accuser", "accuse", "beschuldigen", "acusar", "verbe", "B2"),
    ("reconnaître / admettre", "acknowledge", "anerkennen", "reconocer", "verbe", "B2"),
    ("acquérir", "acquire", "erwerben", "adquirir", "verbe", "B2"),
    ("l'acre (mesure agraire)", "acre", "der Morgen (Flächenmaß)", "el acre", "nom", "B2"),
    ("activer", "activate", "aktivieren", "activar", "verbe", "B2"),
    ("réel / véritable", "actual", "tatsächlich", "real", "adjectif", "B2"),
    ("adapter", "adapt", "anpassen", "adaptar", "verbe", "B2"),
    ("l'addiction", "addiction", "die Sucht", "la adicción", "nom", "B2"),
    ("supplémentaire", "additional", "zusätzlich", "adicional", "adjectif", "B2"),
    ("de plus / en outre", "additionally", "zusätzlich", "además", "adverbe", "B2"),
    ("s'adresser à / aborder", "address", "ansprechen", "dirigirse a", "verbe", "B2"),
    ("adéquat / suffisant", "adequate", "angemessen", "adecuado", "adjectif", "B2"),
    ("adéquatement", "adequately", "angemessen", "adecuadamente", "adverbe", "B2"),
    ("ajuster", "adjust", "anpassen", "ajustar", "verbe", "B2"),
    ("l'administration", "administration", "die Verwaltung", "la administración", "nom", "B2"),
    ("adopter", "adopt", "adoptieren / übernehmen", "adoptar", "verbe", "B2"),
    ("l'avance", "advance", "der Fortschritt", "el avance", "nom", "B2"),
    ("avancer", "advance", "vorrücken", "avanzar", "verbe", "B2"),
    ("l'affaire", "affair", "die Angelegenheit / die Affäre", "el asunto", "nom", "B2"),
    ("abordable", "affordable", "erschwinglich", "asequible", "adjectif", "B2"),
    ("ensuite / plus tard", "afterwards", "danach", "después", "adverbe", "B2"),
    ("l'agence", "agency", "die Agentur", "la agencia", "nom", "B2"),
    ("l'ordre du jour", "agenda", "die Tagesordnung", "la agenda", "nom", "B2"),
    ("agressif", "aggressive", "aggressiv", "agresivo", "adjectif", "B2"),
    ("l'agriculture", "agriculture", "die Landwirtschaft", "la agricultura", "nom", "B2"),
    ("l'aide", "aid", "die Hilfe", "la ayuda", "nom", "B2"),
    ("aider", "aid", "helfen", "ayudar", "verbe", "B2"),
    ("le SIDA", "AIDS", "Aids", "el SIDA", "nom", "B2"),
    ("l'aéronef", "aircraft", "das Flugzeug", "la aeronave", "nom", "B2"),
    ("alarmer", "alarm", "alarmieren", "alarmar", "verbe", "B2"),
    ("l'extraterrestre / l'étranger", "alien", "der Außerirdische", "el extraterrestre", "nom", "B2"),
    ("étranger / extraterrestre", "alien", "fremd", "alienígena", "adjectif", "B2"),
    ("aux côtés de", "alongside", "neben", "junto a", "prep", "B2"),
    ("modifier / altérer", "alter", "ändern", "alterar", "verbe", "B2"),
    ("tout à fait / dans l'ensemble", "altogether", "insgesamt", "totalmente", "adverbe", "B2"),
    ("l'ambulance", "ambulance", "der Krankenwagen", "la ambulancia", "nom", "B2"),
    ("amusant", "amusing", "amüsant", "divertido", "adjectif", "B2"),
    ("analyser", "analyse", "analysieren", "analizar", "verbe", "B2"),
    ("l'analyse", "analysis", "die Analyse", "el análisis", "nom", "B2"),
    ("l'analyste", "analyst", "der Analyst", "el analista", "nom", "B2"),
    ("l'ancêtre", "ancestor", "der Vorfahre", "el ancestro", "nom", "B2"),
    ("l'ange", "angel", "der Engel", "el ángel", "nom", "B2"),
    ("la colère", "anger", "der Zorn", "la ira", "nom", "B2"),
    ("l'angle", "angle", "der Winkel", "el ángulo", "nom", "B2"),
    ("l'animation", "animation", "die Animation", "la animación", "nom", "B2"),
    ("l'anniversaire (événement)", "anniversary", "der Jahrestag", "el aniversario", "nom", "B2"),
    ("annuel", "annual", "jährlich", "anual", "adjectif", "B2"),
    ("annuellement", "annually", "jährlich", "anualmente", "adverbe", "B2"),
    ("anticiper", "anticipate", "erwarten", "anticipar", "verbe", "B2"),
    ("l'anxiété", "anxiety", "die Angst", "la ansiedad", "nom", "B2"),
    ("anxieux", "anxious", "besorgt", "ansioso", "adjectif", "B2"),
    ("l'excuse (les excuses)", "apology", "die Entschuldigung", "la disculpa", "nom", "B2"),
    ("apparent", "apparent", "offensichtlich", "aparente", "adjectif", "B2"),
    ("apparemment", "apparently", "anscheinend", "aparentemente", "adverbe", "B2"),
    ("l'appel (justice) / l'attrait", "appeal", "der Einspruch / der Reiz", "la apelación / el atractivo", "nom", "B2"),
    ("faire appel / attirer", "appeal", "appellieren / reizen", "apelar / atraer", "verbe", "B2"),
    ("le candidat (emploi/inscription)", "applicant", "der Bewerber", "el solicitante", "nom", "B2"),
    ("l'approche", "approach", "der Ansatz / die Annäherung", "el enfoque", "nom", "B2"),
    ("approcher", "approach", "sich nähern", "acercarse", "verbe", "B2"),
    ("approprié", "appropriate", "angemessen", "apropiado", "adjectif", "B2"),
    ("de manière appropriée", "appropriately", "angemessen", "apropiadamente", "adverbe", "B2"),
    ("l'approbation", "approval", "die Zustimmung", "la aprobación", "nom", "B2"),
    ("approuver", "approve", "zustimmen", "aprobar", "verbe", "B2"),
    ("survenir / se poser", "arise", "entstehen", "surgir", "verbe", "B2"),
    ("armé", "armed", "bewaffnet", "armado", "adjectif", "B2"),
    ("les armes", "arms", "die Waffen", "las armas", "nom", "B2"),
    ("la flèche", "arrow", "der Pfeil", "la flecha", "nom", "B2"),
    ("artificiel", "artificial", "künstlich", "artificial", "adjectif", "B2"),
    ("artistique", "artistic", "künstlerisch", "artístico", "adjectif", "B2"),
    ("l'œuvre d'art", "artwork", "das Kunstwerk", "la obra de arte", "nom", "B2"),
    ("honteux (avoir honte)", "ashamed", "beschämt", "avergonzado", "adjectif", "B2"),
    ("l'aspect", "aspect", "der Aspekt", "el aspecto", "nom", "B2"),
    ("évaluer", "assess", "bewerten", "evaluar", "verbe", "B2"),
    ("l'évaluation", "assessment", "die Bewertung", "la evaluación", "nom", "B2"),
    ("l'atout / le bien", "asset", "der Vermögenswert", "el activo", "nom", "B2"),
    ("attribuer / assigner", "assign", "zuweisen", "asignar", "verbe", "B2"),
    ("l'assistance / l'aide", "assistance", "die Unterstützung", "la asistencia", "nom", "B2"),
    ("associer", "associate", "assoziieren", "asociar", "verbe", "B2"),
    ("associé", "associated", "verbunden", "asociado", "adjectif", "B2"),
    ("l'association", "association", "der Verband / die Vereinigung", "la asociación", "nom", "B2"),
    ("supposer / présumer", "assume", "annehmen", "suponer", "verbe", "B2"),
    ("la supposition", "assumption", "die Annahme", "la suposición", "nom", "B2"),
    ("assurer", "assure", "versichern", "asegurar", "verbe", "B2"),
    ("étonnant", "astonishing", "erstaunlich", "asombroso", "adjectif", "B2"),
    ("athlétique", "athletic", "athletisch", "atlético", "adjectif", "B2"),
    ("la pièce jointe / l'attachement", "attachment", "der Anhang", "el archivo adjunto", "nom", "B2"),
    ("la tentative", "attempt", "der Versuch", "el intento", "nom", "B2"),
    ("tenter", "attempt", "versuchen", "intentar", "verbe", "B2"),
    ("audio", "audio", "Audio-", "de audio", "adjectif", "B2"),
    ("la conscience (sensibilisation)", "awareness", "das Bewusstsein", "la conciencia", "nom", "B2"),
    ("maladroit / gênant", "awkward", "ungeschickt / peinlich", "incómodo / torpe", "adjectif", "B2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b2_batch1.ps1", $new_words, $utf8NoBom)
