$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE C (partie 1) (B2) ---
    ("la cabine / le chalet", "cabin", "die Hütte", "la cabaña", "nom", "B2"),
    ("le câble", "cable", "das Kabel", "el cable", "nom", "B2"),
    ("calculer", "calculate", "berechnen", "calcular", "verbe", "B2"),
    ("le canal", "canal", "der Kanal", "el canal", "nom", "B2"),
    ("annuler", "cancel", "absagen", "cancelar", "verbe", "B2"),
    ("le cancer", "cancer", "der Krebs", "el cáncer", "nom", "B2"),
    ("la bougie", "candle", "die Kerze", "la vela", "nom", "B2"),
    ("capable", "capable", "fähig", "capaz", "adjectif", "B2"),
    ("la capacité", "capacity", "die Kapazität", "la capacidad", "nom", "B2"),
    ("capturer", "capture", "einfangen", "capturar", "verbe", "B2"),
    ("le carbone", "carbon", "der Kohlenstoff", "el carbono", "nom", "B2"),
    ("le casting", "cast", "die Besetzung", "el elenco", "nom", "B2"),
    ("jeter / distribuer (rôle)", "cast", "werfen", "lanzar", "verbe", "B2"),
    ("décontracté", "casual", "lässig", "casual", "adjectif", "B2"),
    ("la catastrophe", "catastrophe", "die Katastrophe", "la catástrofe", "nom", "B2"),
    ("la grotte", "cave", "die Höhle", "la cueva", "nom", "B2"),
    ("la cellule", "cell", "die Zelle", "la célula", "nom", "B2"),
    ("la certitude", "certainty", "die Gewissheit", "la certeza", "nom", "B2"),
    ("le certificat", "certificate", "das Zertifikat", "el certificado", "nom", "B2"),
    ("le président (d'une réunion/comité)", "chairman", "der Vorsitzende", "el presidente", "nom", "B2"),
    ("stimulant / difficile", "challenging", "herausfordernd", "desafiante", "adjectif", "B2"),
    ("le championnat", "championship", "die Meisterschaft", "el campeonato", "nom", "B2"),
    ("la caractéristique", "characteristic", "die Eigenschaft", "la característica", "nom", "B2"),
    ("charmant", "charming", "charmant", "encantador", "adjectif", "B2"),
    ("poursuivre / chasser", "chase", "jagen", "perseguir", "verbe", "B2"),
    ("la joue", "cheek", "die Wange", "la mejilla", "nom", "B2"),
    ("acclamer / encourager", "cheer", "jubeln", "animar", "verbe", "B2"),
    ("le chef / principal", "chief", "der Chef", "el jefe", "adjectif", "B2"),
    ("hacher / couper", "chop", "hacken", "picar", "verbe", "B2"),
    ("le circuit", "circuit", "der Kreislauf", "el circuito", "nom", "B2"),
    ("la circonstance", "circumstance", "der Umstand", "la circunstancia", "nom", "B2"),
    ("citer (un texte)", "cite", "zitieren", "citar", "verbe", "B2"),
    ("le citoyen", "citizen", "der Bürger", "el ciudadano", "nom", "B2"),
    ("civil", "civil", "zivil", "civil", "adjectif", "B2"),
    ("la civilisation", "civilization", "die Zivilisation", "la civilización", "nom", "B2"),
    ("clarifier", "clarify", "klären", "aclarar", "verbe", "B2"),
    ("classique", "classic", "klassisch", "clásico", "adjectif", "B2"),
    ("classer", "classify", "klassifizieren", "clasificar", "verbe", "B2"),
    ("la clause / la proposition", "clause", "die Klausel", "la cláusula", "nom", "B2"),
    ("la falaise", "cliff", "die Klippe", "el acantilado", "nom", "B2"),
    ("la clinique", "clinic", "die Klinik", "la clínica", "nom", "B2"),
    ("le clip / la pince", "clip", "der Clip", "el clip", "nom", "B2"),
    ("étroitement / de près", "closely", "eng", "estrechamente", "adverbe", "B2"),
    ("la coïncidence", "coincidence", "der Zufall", "la coincidencia", "nom", "B2"),
    ("s'effondrer", "collapse", "zusammenbrechen", "colapsar", "verbe", "B2"),
    ("le collectionneur", "collector", "der Sammler", "el coleccionista", "nom", "B2"),
    ("la colonie", "colony", "die Kolonie", "la colonia", "nom", "B2"),
    ("coloré / vif", "colourful", "bunt", "colorido", "adjectif", "B2"),
    ("la combinaison", "combination", "die Kombination", "la combinación", "nom", "B2"),
    ("le confort", "comfort", "der Komfort", "el confort", "nom", "B2"),
    ("la bande dessinée", "comic", "der Comic", "el cómic", "nom", "B2"),
    ("comique", "comic", "komisch", "cómico", "adjectif", "B2"),
    ("le commandement / l'ordre", "command", "der Befehl", "el mando", "nom", "B2"),
    ("commander", "command", "befehlen", "comandar", "verbe", "B2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b2_batch3.ps1", $new_words, $utf8NoBom)
