$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE T-Z (A2) ---
    ("la tablette", "tablet", "das Tablet", "la tableta", "nom", "A2"),
    ("la discussion / l'exposé", "talk", "der Vortrag", "la charla", "nom", "A2"),
    ("la cible", "target", "das Ziel", "el objetivo", "nom", "A2"),
    ("la tâche", "task", "die Aufgabe", "la tarea", "nom", "A2"),
    ("le goût", "taste", "der Geschmack", "el sabor", "nom", "A2"),
    ("goûter", "taste", "schmecken", "probar", "verbe", "A2"),
    ("l'enseignement", "teaching", "das Lehren", "la enseñanza", "nom", "A2"),
    ("la technologie", "technology", "die Technologie", "la tecnología", "nom", "A2"),
    ("adolescent", "teenage", "im Teenageralter", "adolescente", "adjectif", "A2"),
    ("la température", "temperature", "die Temperatur", "la temperatura", "nom", "A2"),
    ("la tente", "tent", "das Zelt", "la tienda", "nom", "A2"),
    ("le terme / le trimestre", "term", "der Begriff / das Semester", "el término", "nom", "A2"),
    ("envoyer un texto", "text", "simsen", "enviar un mensaje de texto", "verbe", "A2"),
    ("eux-mêmes", "themselves", "sich selbst", "ellos mismos", "pron", "A2"),
    ("épais", "thick", "dick", "grueso", "adjectif", "A2"),
    ("le voleur", "thief", "der Dieb", "el ladrón", "nom", "A2"),
    ("mince", "thin", "dünn", "delgado", "adjectif", "A2"),
    ("la pensée / la réflexion", "thinking", "das Denken", "el pensamiento", "nom", "A2"),
    ("le tiers", "third", "das Drittel", "el tercio", "nom", "A2"),
    ("la pensée", "thought", "der Gedanke", "el pensamiento", "nom", "A2"),
    ("jeter", "throw", "werfen", "tirar", "verbe", "A2"),
    ("bien rangé", "tidy", "ordentlich", "ordenado", "adjectif", "A2"),
    ("ranger", "tidy", "aufräumen", "ordenar", "verbe", "A2"),
    ("la cravate", "tie", "die Krawatte", "la corbata", "nom", "A2"),
    ("attacher", "tie", "binden", "atar", "verbe", "A2"),
    ("le tigre", "tiger", "der Tiger", "el tigre", "nom", "A2"),
    ("le pourboire / le conseil", "tip", "das Trinkgeld / der Tipp", "la propina / el consejo", "nom", "A2"),
    ("l'orteil", "toe", "der Zeh", "el dedo del pie", "nom", "A2"),
    ("l'outil", "tool", "das Werkzeug", "la herramienta", "nom", "A2"),
    ("le haut / supérieur", "top", "die Spitze", "la parte superior", "nom", "A2"),
    ("total", "total", "gesamt", "total", "adjectif", "A2"),
    ("toucher", "touch", "berühren", "tocar", "verbe", "A2"),
    ("le tour / la visite", "tour", "die Tour", "el recorrido", "nom", "A2"),
    ("le tourisme", "tourism", "der Tourismus", "el turismo", "nom", "A2"),
    ("vers", "towards", "in Richtung", "hacia", "prep", "A2"),
    ("la serviette", "towel", "das Handtuch", "la toalla", "nom", "A2"),
    ("la tour", "tower", "der Turm", "la torre", "nom", "A2"),
    ("le jouet", "toy", "das Spielzeug", "el juguete", "nom", "A2"),
    ("la piste / la voie", "track", "die Spur", "la pista", "nom", "A2"),
    ("la tradition", "tradition", "die Tradition", "la tradición", "nom", "A2"),
    ("traditionnel", "traditional", "traditionell", "tradicional", "adjectif", "A2"),
    ("les baskets", "trainers", "die Turnschuhe", "las zapatillas", "nom", "A2"),
    ("l'entraînement", "training", "das Training", "el entrenamiento", "nom", "A2"),
    ("le transport", "transport", "der Transport", "el transporte", "nom", "A2"),
    ("le voyageur", "traveller", "der Reisende", "el viajero", "nom", "A2"),
    ("l'ennui / le problème", "trouble", "der Ärger / das Problem", "el problema", "nom", "A2"),
    ("le camion (US)", "truck", "der Lastwagen", "el camión", "nom", "A2"),
    ("le jumeau", "twin", "der Zwilling", "el gemelo", "nom", "A2"),
    ("typique", "typical", "typisch", "típico", "adjectif", "A2"),
    
    ("souterrain", "underground", "unterirdisch", "subterráneo", "adjectif", "A2"),
    ("la compréhension", "understanding", "das Verständnis", "la comprensión", "nom", "A2"),
    ("malheureusement", "unfortunately", "leider", "desafortunadamente", "adverbe", "A2"),
    ("malheureux", "unhappy", "unglücklich", "infeliz", "adjectif", "A2"),
    ("l'uniforme", "uniform", "die Uniform", "el uniforme", "nom", "A2"),
    ("l'unité", "unit", "die Einheit", "la unidad", "nom", "A2"),
    ("uni", "united", "vereint", "unido", "adjectif", "A2"),
    ("inhabituel", "unusual", "ungewöhnlich", "inusual", "adjectif", "A2"),
    ("contrarié", "upset", "verärgert", "molesto", "adjectif", "A2"),
    ("en haut", "upstairs", "oben", "arriba", "adverbe", "A2"),
    ("l'usage", "use", "der Gebrauch", "el uso", "nom", "A2"),
    ("avoir l'habitude de", "used to", "pflegte zu", "solía", "verbe", "A2"),
    ("utile", "useful", "nützlich", "útil", "adjectif", "A2"),
    ("l'utilisateur", "user", "der Benutzer", "el usuario", "nom", "A2"),
    ("habituel", "usual", "üblich", "habitual", "adjectif", "A2"),
    
    ("la vallée", "valley", "das Tal", "el valle", "nom", "A2"),
    ("la camionnette", "van", "der Lieferwagen", "la furgoneta", "nom", "A2"),
    ("la variété", "variety", "die Vielfalt", "la variedad", "nom", "A2"),
    ("la vue", "view", "die Aussicht", "la vista", "nom", "A2"),
    ("le virus", "virus", "das Virus", "el virus", "nom", "A2"),
    ("la voix", "voice", "die Stimme", "la voz", "nom", "A2"),
    
    ("la guerre", "war", "der Krieg", "la guerra", "nom", "A2"),
    ("la lessive / le lavage", "washing", "das Waschen", "el lavado", "nom", "A2"),
    ("la vague", "wave", "die Welle", "la ola", "nom", "A2"),
    ("faire signe (de la main)", "wave", "winken", "saludar (con la mano)", "verbe", "A2"),
    ("faible", "weak", "schwach", "débil", "adjectif", "A2"),
    ("la toile / le web", "web", "das Netz", "la red", "nom", "A2"),
    ("le mariage", "wedding", "die Hochzeit", "la boda", "nom", "A2"),
    ("le poids", "weight", "das Gewicht", "el peso", "nom", "A2"),
    ("le bienvenu", "welcome", "willkommen", "bienvenido", "adjectif", "A2"),
    ("souhaiter la bienvenue", "welcome", "begrüßen", "dar la bienvenida", "verbe", "A2"),
    ("mouillé", "wet", "nass", "mojado", "adjectif", "A2"),
    ("la roue", "wheel", "das Rad", "la rueda", "nom", "A2"),
    ("pendant que", "while", "während", "mientras", "conjonction", "A2"),
    ("entier", "whole", "ganz", "entero", "adjectif", "A2"),
    ("à qui / dont", "whose", "wessen", "cuyo", "pron", "A2"),
    ("large", "wide", "breit", "ancho", "adjectif", "A2"),
    ("sauvage", "wild", "wild", "salvaje", "adjectif", "A2"),
    ("le vent", "wind", "der Wind", "el viento", "nom", "A2"),
    ("le gagnant", "winner", "der Gewinner", "el ganador", "nom", "A2"),
    ("le souhait", "wish", "der Wunsch", "el deseo", "nom", "A2"),
    ("souhaiter", "wish", "wünschen", "desear", "verbe", "A2"),
    ("le bois", "wood", "das Holz", "la madera", "nom", "A2"),
    ("en bois", "wooden", "hölzern", "de madera", "adjectif", "A2"),
    ("qui travaille (en état de marche)", "working", "funktionierend", "trabajando", "adjectif", "A2"),
    ("inquiet", "worried", "besorgt", "preocupado", "adjectif", "A2"),
    ("s'inquiéter", "worry", "sich sorgen", "preocuparse", "verbe", "A2"),
    ("l'inquiétude", "worry", "die Sorge", "la preocupación", "nom", "A2"),
    ("pire", "worse", "schlechter", "peor", "adjectif", "A2"),
    ("le pire", "worst", "schlechteste", "el peor", "adjectif", "A2"),
    ("ouah", "wow", "wow", "guau", "interj", "A2"),
    
    ("encore (dans une phrase négative/question)", "yet", "noch", "todavía", "adverbe", "A2"),
    ("le tien / la vôtre", "yours", "deins", "tuyo", "pron", "A2"),
    ("zéro", "zero", "null", "cero", "num", "A2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_a2_batch8.ps1", $new_words, $utf8NoBom)
