$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE T-Z (B1) ---
    ("la queue (animal)", "tail", "der Schwanz", "la cola", "nom", "B1"),
    ("le talent", "talent", "das Talent", "el talento", "nom", "B1"),
    ("talentueux", "talented", "talentiert", "talentoso", "adjectif", "B1"),
    ("le ruban (adhésif) / la cassette", "tape", "das Klebeband / die Kassette", "la cinta", "nom", "B1"),
    ("l'impôt / la taxe", "tax", "die Steuer", "el impuesto", "nom", "B1"),
    ("technique", "technical", "technisch", "técnico", "adjectif", "B1"),
    ("la technique", "technique", "die Technik", "la técnica", "nom", "B1"),
    ("avoir tendance à", "tend", "neigen zu", "tender", "verbe", "B1"),
    ("le thème", "theme", "das Thema", "el tema", "nom", "B1"),
    ("bien que / cependant", "though", "obwohl", "aunque", "conjonction", "B1"),
    ("la gorge", "throat", "die Kehle", "la garganta", "nom", "B1"),
    ("tout au long de / partout dans", "throughout", "durchgehend / überall", "a lo largo de", "prep", "B1"),
    ("serré / étroit", "tight", "eng", "apretado", "adjectif", "B1"),
    ("jusqu'à (temps)", "till", "bis", "hasta", "prep", "B1"),
    ("la boîte de conserve / l'étain", "tin", "die Dose", "la lata / el estaño", "nom", "B1"),
    ("minuscule", "tiny", "winzig", "diminuto", "adjectif", "B1"),
    ("la langue (organe)", "tongue", "die Zunge", "la lengua", "nom", "B1"),
    ("le sujet (thème)", "topic", "das Thema", "el tema", "nom", "B1"),
    ("le total / total", "total", "insgesamt / total", "el total / total", "nom", "B1"),
    ("totalement", "totally", "völlig", "totalmente", "adverbe", "B1"),
    ("le commerce", "trade", "der Handel", "el comercio", "nom", "B1"),
    ("échanger / commercer", "trade", "handeln", "comerciar", "verbe", "B1"),
    ("la bande-annonce / la remorque", "trailer", "der Anhänger / der Trailer", "el remolque / el tráiler", "nom", "B1"),
    ("traduire", "translate", "übersetzen", "traducir", "verbe", "B1"),
    ("la traduction", "translation", "die Übersetzung", "la traducción", "nom", "B1"),
    ("traiter (qqn) / soigner", "treat", "behandeln", "tratar", "verbe", "B1"),
    ("le traitement", "treatment", "die Behandlung", "el tratamiento", "nom", "B1"),
    ("la tendance", "trend", "der Trend", "la tendencia", "nom", "B1"),
    ("l'astuce / le tour (de magie)", "trick", "der Trick", "el truco", "nom", "B1"),
    ("tromper / piéger", "trick", "austricksen", "engañar", "verbe", "B1"),
    ("la vérité", "truth", "die Wahrheit", "la verdad", "nom", "B1"),
    ("le tube / le métro (Londres)", "tube", "das Rohr / die U-Bahn", "el tubo", "nom", "B1"),
    ("la tortue (marine)", "turtle", "die Schildkröte", "la tortuga", "nom", "B1"),
    ("taper (clavier)", "type", "tippen", "escribir a máquina", "verbe", "B1"),
    ("typiquement", "typically", "typischerweise", "típicamente", "adverbe", "B1"),
    ("le pneu", "tyre", "der Reifen", "el neumático", "nom", "B1"),

    ("laid", "ugly", "hässlich", "feo", "adjectif", "B1"),
    ("incapable", "unable", "unfähig", "incapaz", "adjectif", "B1"),
    ("inconfortable", "uncomfortable", "unbequem", "incómodo", "adjectif", "B1"),
    ("les sous-vêtements", "underwear", "die Unterwäsche", "la ropa interior", "nom", "B1"),
    ("au chômage", "unemployed", "arbeitslos", "desempleado", "adjectif", "B1"),
    ("le chômage", "unemployment", "die Arbeitslosigkeit", "el desempleo", "nom", "B1"),
    ("injuste", "unfair", "ungerecht", "injusto", "adjectif", "B1"),
    ("le syndicat / l'union", "union", "die Gewerkschaft", "la unión", "nom", "B1"),
    ("à moins que", "unless", "es sei denn", "a menos que", "conjonction", "B1"),
    ("contrairement à", "unlike", "im Gegensatz zu", "a diferencia de", "prep", "B1"),
    ("peu probable", "unlikely", "unwahrscheinlich", "improbable", "adjectif", "B1"),
    ("inutile", "unnecessary", "unnötig", "innecesario", "adjectif", "B1"),
    ("désagréable", "unpleasant", "unangenehm", "desagradable", "adjectif", "B1"),
    ("mettre à jour", "update", "aktualisieren", "actualizar", "verbe", "B1"),
    ("sur (formel)", "upon", "auf", "sobre", "prep", "B1"),
    ("contrarier / bouleverser", "upset", "aufregen", "molestar", "verbe", "B1"),
    ("utilisé / d'occasion", "used", "gebraucht", "usado", "adjectif", "B1"),

    ("précieux / de valeur", "valuable", "wertvoll", "valioso", "adjectif", "B1"),
    ("la valeur", "value", "der Wert", "el valor", "nom", "B1"),
    ("divers", "various", "verschieden", "varios", "adjectif", "B1"),
    ("le véhicule", "vehicle", "das Fahrzeug", "el vehículo", "nom", "B1"),
    ("la version", "version", "die Version", "la versión", "nom", "B1"),
    ("la victime", "victim", "das Opfer", "la víctima", "nom", "B1"),
    ("le spectateur (TV)", "viewer", "der Zuschauer", "el espectador", "nom", "B1"),
    ("violent", "violent", "gewalttätig", "violento", "adjectif", "B1"),
    ("le bénévole", "volunteer", "der Freiwillige", "el voluntario", "nom", "B1"),
    ("se porter volontaire", "volunteer", "sich freiwillig melden", "ofrecerse", "verbe", "B1"),
    ("le vote", "vote", "die Abstimmung", "el voto", "nom", "B1"),
    ("voter", "vote", "wählen", "votar", "verbe", "B1"),

    ("avertir", "warn", "warnen", "advertir", "verbe", "B1"),
    ("l'avertissement", "warning", "die Warnung", "la advertencia", "nom", "B1"),
    ("le gaspillage / les déchets", "waste", "der Abfall", "el desperdicio", "nom", "B1"),
    ("gaspiller", "waste", "verschwenden", "desperdiciar", "verbe", "B1"),
    ("l'arme", "weapon", "die Waffe", "el arma", "nom", "B1"),
    ("peser", "weigh", "wiegen", "pesar", "verbe", "B1"),
    ("occidental / de l'ouest", "western", "westlich", "occidental", "adjectif", "B1"),
    ("la baleine", "whale", "der Wal", "la ballena", "nom", "B1"),
    ("quoi que ce soit / peu importe", "whatever", "was auch immer", "lo que sea", "pron", "B1"),
    ("à chaque fois que", "whenever", "wann auch immer", "siempre que", "conjonction", "B1"),
    ("si (oui ou non)", "whether", "ob", "si", "conjonction", "B1"),
    ("pendant que / bien que", "while", "während", "mientras", "conjonction", "B1"),
    ("l'aile", "wing", "der Flügel", "el ala", "nom", "B1"),
    ("à l'intérieur de / en l'espace de", "within", "innerhalb", "dentro de", "prep", "B1"),
    ("se demander", "wonder", "sich wundern", "preguntarse", "verbe", "B1"),
    ("la laine", "wool", "die Wolle", "la lana", "nom", "B1"),
    ("dans le monde entier", "worldwide", "weltweit", "a nivel mundial", "adjectif", "B1"),
    ("la valeur / valant", "worth", "der Wert / wert", "el valor / vale la pena", "adjectif", "B1"),
    ("la ride / le faux pli", "wrinkle", "die Falte", "la arruga", "nom", "B1"),
    ("écrit", "written", "geschrieben", "escrito", "adjectif", "B1"),

    ("la cour / le jardin (US)", "yard", "der Hof", "el patio", "nom", "B1"),
    ("hurler", "yell", "schreien", "gritar", "verbe", "B1"),
    ("la jeunesse", "youth", "die Jugend", "la juventud", "nom", "B1")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b1_batch8.ps1", $new_words, $utf8NoBom)
