$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE I (B2) ---
    ("l'icône", "icon", "die Ikone / das Symbol", "el icono", "nom", "B2"),
    ("la carte d'identité", "ID", "der Ausweis", "el carné de identidad", "nom", "B2"),
    ("l'idéal", "ideal", "das Ideal", "el ideal", "nom", "B2"),
    ("idéal", "ideal", "ideal", "ideal", "adjectif", "B2"),
    ("identique", "identical", "identisch", "idéntico", "adjectif", "B2"),
    ("l'identité", "identity", "die Identität", "la identidad", "nom", "B2"),
    ("l'illusion", "illusion", "die Illusion", "la ilusión", "nom", "B2"),
    ("illustrer", "illustrate", "veranschaulichen", "ilustrar", "verbe", "B2"),
    ("l'illustration", "illustration", "die Abbildung", "la ilustración", "nom", "B2"),
    ("l'imagination", "imagination", "die Vorstellungskraft", "la imaginación", "nom", "B2"),
    ("l'immigration", "immigration", "die Einwanderung", "la inmigración", "nom", "B2"),
    ("immunisé", "immune", "immun", "inmune", "adjectif", "B2"),
    ("impatient", "impatient", "ungeduldig", "impaciente", "adjectif", "B2"),
    ("mettre en œuvre", "implement", "umsetzen", "implementar", "verbe", "B2"),
    ("l'implication", "implication", "die Auswirkung", "la implicación", "nom", "B2"),
    ("impliquer / insinuer", "imply", "implizieren", "implicar", "verbe", "B2"),
    ("imposer", "impose", "aufzwingen", "imponer", "verbe", "B2"),
    ("impressionner", "impress", "beeindrucken", "impresionar", "verbe", "B2"),
    ("impressionné", "impressed", "beeindruckt", "impresionado", "adjectif", "B2"),
    ("l'incitation", "incentive", "der Anreiz", "el incentivo", "nom", "B2"),
    ("le pouce (mesure)", "inch", "der Zoll (Maß)", "la pulgada", "nom", "B2"),
    ("l'incident", "incident", "der Vorfall", "el incidente", "nom", "B2"),
    ("le revenu", "income", "das Einkommen", "los ingresos", "nom", "B2"),
    ("incorporer / intégrer", "incorporate", "einbeziehen", "incorporar", "verbe", "B2"),
    ("incorrect", "incorrect", "falsch", "incorrecto", "adjectif", "B2"),
    ("de plus en plus", "increasingly", "zunehmend", "cada vez más", "adverbe", "B2"),
    ("l'indépendance", "independence", "die Unabhängigkeit", "la independencia", "nom", "B2"),
    ("l'index / l'indice", "index", "der Index", "el índice", "nom", "B2"),
    ("l'indication", "indication", "der Hinweis", "la indicación", "nom", "B2"),
    ("industriel", "industrial", "industriell", "industrial", "adjectif", "B2"),
    ("inévitable", "inevitable", "unvermeidlich", "inevitable", "adjectif", "B2"),
    ("inévitablement", "inevitably", "unweigerlich", "inevitablemente", "adverbe", "B2"),
    ("l'infection", "infection", "die Infektion", "la infección", "nom", "B2"),
    ("déduire", "infer", "schließen", "inferir", "verbe", "B2"),
    ("l'inflation", "inflation", "die Inflation", "la inflación", "nom", "B2"),
    ("les infos (fam.)", "info", "die Info", "la información", "nom", "B2"),
    ("informer", "inform", "informieren", "informar", "verbe", "B2"),
    ("l'habitant", "inhabitant", "der Einwohner", "el habitante", "nom", "B2"),
    ("hériter", "inherit", "erben", "heredar", "verbe", "B2"),
    ("initial", "initial", "anfänglich", "inicial", "adjectif", "B2"),
    ("initialement", "initially", "anfangs", "inicialmente", "adverbe", "B2"),
    ("l'initiative", "initiative", "die Initiative", "la iniciativa", "nom", "B2"),
    ("l'encre", "ink", "die Tinte", "la tinta", "nom", "B2"),
    ("intérieur (plus profond)", "inner", "inner", "interior", "adjectif", "B2"),
    ("l'innovation", "innovation", "die Innovation", "la innovación", "nom", "B2"),
    ("innovant", "innovative", "innovativ", "innovador", "adjectif", "B2"),
    ("la contribution / la saisie", "input", "die Eingabe / der Beitrag", "la aportación", "nom", "B2"),
    ("insérer", "insert", "einfügen", "insertar", "verbe", "B2"),
    ("l'aperçu / la perspicacité", "insight", "die Erkenntnis", "la percepción", "nom", "B2"),
    ("insister", "insist", "darauf bestehen", "insistir", "verbe", "B2"),
    ("l'inspecteur", "inspector", "der Inspektor", "el inspector", "nom", "B2"),
    ("inspirer", "inspire", "inspirieren", "inspirar", "verbe", "B2"),
    ("installer", "install", "installieren", "instalar", "verbe", "B2"),
    ("l'installation", "installation", "die Installation", "la instalación", "nom", "B2"),
    ("l'exemple / le cas", "instance", "das Beispiel", "el caso", "nom", "B2"),
    ("instantané", "instant", "sofortig", "instantáneo", "adjectif", "B2"),
    ("instantanément", "instantly", "sofort", "instantáneamente", "adverbe", "B2"),
    ("l'institut", "institute", "das Institut", "el instituto", "nom", "B2"),
    ("l'institution", "institution", "die Institution", "la institución", "nom", "B2"),
    ("l'assurance", "insurance", "die Versicherung", "el seguro", "nom", "B2"),
    ("intégrer", "integrate", "integrieren", "integrar", "verbe", "B2"),
    ("intellectuel", "intellectual", "intellektuell", "intelectual", "adjectif", "B2"),
    ("prévu / voulu", "intended", "beabsichtigt", "previsto", "adjectif", "B2"),
    ("intense", "intense", "intensiv", "intenso", "adjectif", "B2"),
    ("interagir", "interact", "interagieren", "interactuar", "verbe", "B2"),
    ("l'interaction", "interaction", "die Interaktion", "la interacción", "nom", "B2"),
    ("interne", "internal", "intern", "interno", "adjectif", "B2"),
    ("interpréter", "interpret", "interpretieren", "interpretar", "verbe", "B2"),
    ("l'interprétation", "interpretation", "die Interpretation", "la interpretación", "nom", "B2"),
    ("interrompre", "interrupt", "unterbrechen", "interrumpir", "verbe", "B2"),
    ("l'intervalle / l'entracte", "interval", "das Intervall / die Pause", "el intervalo", "nom", "B2"),
    ("envahir", "invade", "einmarschieren", "invadir", "verbe", "B2"),
    ("l'invasion", "invasion", "die Invasion", "la invasión", "nom", "B2"),
    ("l'enquête", "investigation", "die Untersuchung", "la investigación", "nom", "B2"),
    ("l'investissement", "investment", "die Investition", "la inversión", "nom", "B2"),
    ("l'investisseur", "investor", "der Investor", "el inversor", "nom", "B2"),
    ("isoler", "isolate", "isolieren", "aislar", "verbe", "B2"),
    ("isolé", "isolated", "isoliert", "aislado", "adjectif", "B2"),
    ("émettre / délivrer", "issue", "ausstellen", "emitir", "verbe", "B2"),

    # --- LETTRE J (B2) ---
    ("la prison", "jail", "das Gefängnis", "la cárcel", "nom", "B2"),
    ("le jet (avion/eau)", "jet", "der Jet", "el jet", "nom", "B2"),
    ("l'articulation / le joint", "joint", "das Gelenk", "la articulación", "nom", "B2"),
    ("commun / conjoint", "joint", "gemeinsam", "conjunto", "adjectif", "B2"),
    ("le journalisme", "journalism", "der Journalismus", "el periodismo", "nom", "B2"),
    ("la joie", "joy", "die Freude", "la alegría", "nom", "B2"),
    ("le jugement", "judgement", "das Urteil", "el juicio", "nom", "B2"),
    ("le junior", "junior", "der Junior", "el menor", "nom", "B2"),
    ("le jury", "jury", "die Jury", "el jurado", "nom", "B2"),
    ("la justice", "justice", "die Gerechtigkeit", "la justicia", "nom", "B2"),
    ("justifier", "justify", "rechtfertigen", "justificar", "verbe", "B2"),

    # --- LETTRE K (B2) ---
    ("kidnapper", "kidnap", "entführen", "secuestrar", "verbe", "B2"),
    ("le rein", "kidney", "die Niere", "el riñón", "nom", "B2"),
    ("le jardin d'enfants", "kindergarten", "der Kindergarten", "el jardín de infancia", "nom", "B2"),
    ("le kit / l'équipement", "kit", "die Ausrüstung", "el kit", "nom", "B2"),

    # --- LETTRE L (B2) ---
    ("le travail (main d'œuvre)", "labour", "die Arbeit", "el trabajo (físico)", "nom", "B2"),
    ("l'échelle", "ladder", "die Leiter", "la escalera", "nom", "B2"),
    ("l'atterrissage", "landing", "die Landung", "el aterrizaje", "nom", "B2"),
    ("le paysage", "landscape", "die Landschaft", "el paisaje", "nom", "B2"),
    ("la voie (route)", "lane", "die Fahrspur", "el carril", "nom", "B2"),
    ("largement / en grande partie", "largely", "größtenteils", "en gran parte", "adverbe", "B2"),
    ("le laser", "laser", "der Laser", "el láser", "nom", "B2"),
    ("dernièrement", "lately", "kürzlich", "últimamente", "adverbe", "B2"),
    ("lancer (produit/fusée)", "launch", "starten", "lanzar", "verbe", "B2"),
    ("le leadership", "leadership", "die Führung", "el liderazgo", "nom", "B2"),
    ("la ligue", "league", "die Liga", "la liga", "nom", "B2"),
    ("s'appuyer / se pencher", "lean", "sich anlehnen", "apoyarse", "verbe", "B2"),
    ("la légende", "legend", "die Legende", "la leyenda", "nom", "B2"),
    ("la lentille / l'objectif", "lens", "die Linse / das Objektiv", "la lente", "nom", "B2"),
    ("la licence / le permis", "licence", "die Lizenz", "la licencia", "nom", "B2"),
    ("la durée de vie", "lifetime", "die Lebenszeit", "la vida útil", "nom", "B2"),
    ("l'éclairage", "lighting", "die Beleuchtung", "la iluminación", "nom", "B2"),
    ("de même", "likewise", "ebenso", "igualmente", "adverbe", "B2"),
    ("la limitation", "limitation", "die Einschränkung", "la limitación", "nom", "B2"),
    ("limité", "limited", "begrenzt", "limitado", "adjectif", "B2"),
    ("littéralement", "literally", "buchstäblich", "literalmente", "adverbe", "B2"),
    ("littéraire", "literary", "literarisch", "literario", "adjectif", "B2"),
    ("les déchets (jetés par terre)", "litter", "der Abfall", "la basura", "nom", "B2"),
    ("animé / vivant", "lively", "lebhaft", "animado", "adjectif", "B2"),
    ("le foie", "liver", "die Leber", "el hígado", "nom", "B2"),
    ("la charge", "load", "die Ladung", "la carga", "nom", "B2"),
    ("charger (camion/arme)", "load", "laden", "cargar", "verbe", "B2"),
    ("le prêt", "loan", "der Kredit", "el préstamo", "nom", "B2"),
    ("logique", "logical", "logisch", "lógico", "adjectif", "B2"),
    ("le logo", "logo", "das Logo", "el logo", "nom", "B2"),
    ("à long terme", "long-term", "langfristig", "a largo plazo", "adjectif", "B2"),
    ("lâche (pas serré)", "loose", "lose", "suelto", "adjectif", "B2"),
    ("le seigneur", "lord", "der Herr", "el señor", "nom", "B2"),
    ("la loterie", "lottery", "die Lotterie", "la lotería", "nom", "B2"),
    ("baisser", "lower", "senken", "bajar", "verbe", "B2"),
    ("fidèle / loyal", "loyal", "treu", "leal", "adjectif", "B2"),
    ("le poumon", "lung", "die Lunge", "el pulmón", "nom", "B2"),
    ("les paroles (de chanson)", "lyric", "der Liedtext", "la letra (de canción)", "nom", "B2"),

    # --- LETTRE M (B2) ---
    ("magnifique", "magnificent", "großartig", "magnífico", "adjectif", "B2"),
    ("maintenir", "maintain", "aufrechterhalten", "mantener", "verbe", "B2"),
    ("la majorité", "majority", "die Mehrheit", "la mayoría", "nom", "B2"),
    ("le maquillage", "makeup", "das Make-up", "el maquillaje", "nom", "B2"),
    ("la fabrication / la création", "making", "die Herstellung", "la fabricación", "nom", "B2"),
    ("fabriquer", "manufacture", "herstellen", "fabricar", "verbe", "B2"),
    ("la fabrication / l'industrie", "manufacturing", "die Fertigung", "la manufactura", "nom", "B2"),
    ("le marathon", "marathon", "der Marathon", "el maratón", "nom", "B2"),
    ("la marge", "margin", "der Spielraum", "el margen", "nom", "B2"),
    ("le marqueur", "marker", "der Marker", "el marcador", "nom", "B2"),
    ("martial (arts)", "martial", "kriegerisch (Kampf-)", "marcial", "adjectif", "B2"),
    ("la masse / de masse", "mass", "die Masse", "la masa", "nom", "B2"),
    ("massif", "massive", "massiv", "masivo", "adjectif", "B2"),
    ("le maître", "master", "der Meister", "el maestro", "nom", "B2"),
    ("maîtriser", "master", "meistern", "dominar", "verbe", "B2"),
    ("assorti / correspondant", "matching", "passend", "a juego", "adjectif", "B2"),
    ("le compagnon / le pote", "mate", "der Kumpel", "el compañero", "nom", "B2"),
    ("s'accoupler", "mate", "sich paaren", "aparearse", "verbe", "B2"),
    ("le maximum", "maximum", "das Maximum", "el máximo", "nom", "B2"),
    ("les moyens", "means", "die Mittel", "los medios", "nom", "B2"),
    ("la mesure", "measurement", "die Messung", "la medición", "nom", "B2"),
    ("le mécanicien", "mechanic", "der Mechaniker", "el mecánico", "nom", "B2"),
    ("mécanique", "mechanical", "mechanisch", "mecánico", "adjectif", "B2"),
    ("le mécanisme", "mechanism", "der Mechanismus", "el mecanismo", "nom", "B2"),
    ("la médaille", "medal", "die Medaille", "la medalla", "nom", "B2"),
    ("le médicament", "medication", "das Medikament", "la medicación", "nom", "B2"),
    ("le moyen / le support", "medium", "das Medium", "el medio", "nom", "B2"),
    ("fondre", "melt", "schmelzen", "derretir", "verbe", "B2"),
    ("l'adhésion / l'affiliation", "membership", "die Mitgliedschaft", "la membresía", "nom", "B2"),
    ("mémorable", "memorable", "unvergesslich", "memorable", "adjectif", "B2"),
    ("la métaphore", "metaphor", "die Metapher", "la metáfora", "nom", "B2"),
    ("la méthode", "method", "die Methode", "el método", "nom", "B2"),
    ("militaire", "military", "militärisch", "militar", "adjectif", "B2"),
    ("le mineur (mine)", "miner", "der Bergmann", "el minero", "nom", "B2"),
    ("le minéral", "mineral", "das Mineral", "el mineral", "nom", "B2"),
    ("le minimum", "minimum", "das Minimum", "el mínimo", "nom", "B2"),
    ("le ministre", "minister", "der Minister", "el ministro", "nom", "B2"),
    ("mineur / de moindre importance", "minor", "geringfügig", "menor", "adjectif", "B2"),
    ("la minorité", "minority", "die Minderheit", "la minoría", "nom", "B2"),
    ("misérable / malheureux", "miserable", "elend", "miserable", "adjectif", "B2"),
    ("la mission", "mission", "die Mission", "la misión", "nom", "B2"),
    ("erroné / dans l'erreur", "mistaken", "falsch", "equivocado", "adjectif", "B2"),
    ("mélangé / mixte", "mixed", "gemischt", "mezclado", "adjectif", "B2"),
    ("le mode", "mode", "der Modus", "el modo", "nom", "B2"),
    ("modeste", "modest", "bescheiden", "modesto", "adjectif", "B2"),
    ("modifier", "modify", "ändern", "modificar", "verbe", "B2"),
    ("le moniteur / l'écran", "monitor", "der Monitor", "el monitor", "nom", "B2"),
    ("surveiller", "monitor", "überwachen", "monitorear", "verbe", "B2"),
    ("le monstre", "monster", "das Monster", "el monstruo", "nom", "B2"),
    ("mensuel", "monthly", "monatlich", "mensual", "adjectif", "B2"),
    ("le monument", "monument", "das Denkmal", "el monumento", "nom", "B2"),
    ("moral", "moral", "moralisch", "moral", "adjectif", "B2"),
    ("de plus / en outre", "moreover", "außerdem", "además", "adverbe", "B2"),
    ("l'hypothèque", "mortgage", "die Hypothek", "la hipoteca", "nom", "B2"),
    ("la mosquée", "mosque", "die Moschee", "la mezquita", "nom", "B2"),
    ("le moustique", "mosquito", "die Mücke", "el mosquito", "nom", "B2"),
    ("le mouvement", "motion", "die Bewegung", "el movimiento", "nom", "B2"),
    ("motiver", "motivate", "motivieren", "motivar", "verbe", "B2"),
    ("la motivation", "motivation", "die Motivation", "la motivación", "nom", "B2"),
    ("le moteur", "motor", "der Motor", "el motor", "nom", "B2"),
    ("monter (à cheval/assembler)", "mount", "aufsteigen / montieren", "montar", "verbe", "B2"),
    ("émouvant", "moving", "bewegend", "conmovedor", "adjectif", "B2"),
    ("multiple", "multiple", "mehrfach", "múltiple", "adjectif", "B2"),
    ("multiplier", "multiply", "multiplizieren", "multiplicar", "verbe", "B2"),
    ("mystérieux", "mysterious", "geheimnisvoll", "misterioso", "adjectif", "B2"),
    ("le mythe", "myth", "der Mythos", "el mito", "nom", "B2"),

    # --- LETTRE N (B2) ---
    ("nu", "naked", "nackt", "desnudo", "adjectif", "B2"),
    ("méchant / désagréable", "nasty", "gemein", "desagradable", "adjectif", "B2"),
    ("la navigation", "navigation", "die Navigation", "la navegación", "nom", "B2"),
    ("à proximité", "nearby", "in der Nähe", "cercano", "adjectif", "B2"),
    ("soigné / propre", "neat", "ordentlich", "limpio / ordenado", "adjectif", "B2"),
    ("la nécessité", "necessity", "die Notwendigkeit", "la necesidad", "nom", "B2"),
    ("le négatif", "negative", "das Negativ", "el negativo", "nom", "B2"),
    ("négocier", "negotiate", "verhandeln", "negociar", "verbe", "B2"),
    ("la négociation", "negotiation", "die Verhandlung", "la negociación", "nom", "B2"),
    ("le nerf", "nerve", "der Nerv", "el nervio", "nom", "B2"),
    ("neutre", "neutral", "neutral", "neutral", "adjectif", "B2"),
    ("néanmoins", "nevertheless", "dennoch", "sin embargo", "adverbe", "B2"),
    ("nouvellement", "newly", "neu", "recientemente", "adverbe", "B2"),
    ("le nickel", "nickel", "das Nickel", "el níquel", "nom", "B2"),
    ("le cauchemar", "nightmare", "der Albtraum", "la pesadilla", "nom", "B2"),
    ("la nostalgie", "nostalgia", "die Nostalgie", "la nostalgia", "nom", "B2"),
    ("le carnet", "notebook", "das Notizbuch", "el cuaderno", "nom", "B2"),
    ("la notion", "notion", "die Vorstellung", "la noción", "nom", "B2"),
    ("le romancier", "novelist", "der Romanschriftsteller", "el novelista", "nom", "B2"),
    ("de nos jours", "nowadays", "heutzutage", "hoy en día", "adverbe", "B2"),
    ("nombreux", "numerous", "zahlreich", "numeroso", "adjectif", "B2"),
    ("les soins infirmiers", "nursing", "die Pflege", "la enfermería", "nom", "B2"),
    ("la nutrition", "nutrition", "die Ernährung", "la nutrición", "nom", "B2"),

    # --- LETTRE O (B2) ---
    ("l'obésité", "obesity", "die Fettleibigkeit", "la obesidad", "nom", "B2"),
    ("obéir", "obey", "gehorchen", "obedecer", "verbe", "B2"),
    ("l'objet", "object", "das Objekt", "el objeto", "nom", "B2"),
    ("objecter / s'opposer", "object", "widersprechen", "objetar", "verbe", "B2"),
    ("l'objectif", "objective", "das Ziel", "el objetivo", "nom", "B2"),
    ("obligatoire", "obligatory", "obligatorisch", "obligatorio", "adjectif", "B2"),
    ("l'obligation", "obligation", "die Verpflichtung", "la obligación", "nom", "B2"),
    ("l'observation", "observation", "die Beobachtung", "la observación", "nom", "B2"),
    ("observer", "observe", "beobachten", "observar", "verbe", "B2"),
    ("l'observateur", "observer", "der Beobachter", "el observador", "nom", "B2"),
    ("l'obstacle", "obstacle", "das Hindernis", "el obstáculo", "nom", "B2"),
    ("obtenir", "obtain", "erhalten", "obtener", "verbe", "B2"),
    ("occasionnellement", "occasionally", "gelegentlich", "ocasionalmente", "adverbe", "B2"),
    ("l'occupation / la profession", "occupation", "die Beschäftigung", "la ocupación", "nom", "B2"),
    ("occuper", "occupy", "besetzen", "ocupar", "verbe", "B2"),
    ("l'infraction / l'offense", "offence", "das Vergehen", "la ofensa", "nom", "B2"),
    ("offenser", "offend", "beleidigen", "ofender", "verbe", "B2"),
    ("le délinquant", "offender", "der Straftäter", "el delincuente", "nom", "B2"),
    ("offensant", "offensive", "beleidigend", "ofensivo", "adjectif", "B2"),
    ("en cours", "ongoing", "laufend", "en curso", "adjectif", "B2"),
    ("en avant / à partir de", "onwards", "vorwärts", "en adelante", "adverbe", "B2"),
    ("l'ouverture", "opening", "die Eröffnung", "la apertura", "nom", "B2"),
    ("ouvertement", "openly", "offen", "abiertamente", "adverbe", "B2"),
    ("l'opéra", "opera", "die Oper", "la ópera", "nom", "B2"),
    ("opérer / fonctionner", "operate", "operieren / bedienen", "operar", "verbe", "B2"),
    ("l'opérateur", "operator", "der Betreiber", "el operador", "nom", "B2"),
    ("l'adversaire", "opponent", "der Gegner", "el oponente", "nom", "B2"),
    ("s'opposer", "oppose", "sich widersetzen", "oponerse", "verbe", "B2"),
    ("opposé", "opposed", "dagegen", "opuesto", "adjectif", "B2"),
    ("l'opposition", "opposition", "die Opposition", "la oposición", "nom", "B2"),
    ("optique", "optical", "optisch", "óptico", "adjectif", "B2"),
    ("optimiste", "optimistic", "optimistisch", "optimista", "adjectif", "B2"),
    ("l'orchestre", "orchestra", "das Orchester", "la orquesta", "nom", "B2"),
    ("l'organe", "organ", "das Organ", "el órgano", "nom", "B2"),
    ("organique", "organic", "biologisch", "orgánico", "adjectif", "B2"),
    ("l'origine", "origin", "der Ursprung", "el origen", "nom", "B2"),
    ("sinon / autrement", "otherwise", "sonst", "de lo contrario", "adverbe", "B2"),
    ("le résultat / l'issue", "outcome", "das Ergebnis", "el resultado", "nom", "B2"),
    ("extérieur", "outer", "äußere", "exterior", "adjectif", "B2"),
    ("la tenue", "outfit", "das Outfit", "el atuendo", "nom", "B2"),
    ("le contour / le résumé", "outline", "der Umriss", "el contorno", "nom", "B2"),
    ("esquisser", "outline", "skizzieren", "esbozar", "verbe", "B2"),
    ("le rendement / la sortie", "output", "die Ausgabe / die Leistung", "la salida / la producción", "nom", "B2"),
    ("exceptionnel", "outstanding", "hervorragend", "sobresaliente", "adjectif", "B2"),
    ("global / en général", "overall", "insgesamt", "en general", "adjectif", "B2"),
    ("surmonter", "overcome", "überwinden", "superar", "verbe", "B2"),
    ("pendant la nuit / du jour au lendemain", "overnight", "über Nacht", "de la noche a la mañana", "adverbe", "B2"),
    ("à l'étranger / outre-mer", "overseas", "in Übersee", "en el extranjero", "adverbe", "B2"),
    ("devoir (argent)", "owe", "schulden", "deber (dinero)", "verbe", "B2"),
    ("la propriété (fait de posséder)", "ownership", "das Eigentum", "la propiedad", "nom", "B2"),
    ("l'oxygène", "oxygen", "der Sauerstoff", "el oxígeno", "nom", "B2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b2_batch7.ps1", $new_words, $utf8NoBom)
