$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE E (B1) ---
    ("le tremblement de terre", "earthquake", "das Erdbeben", "el terremoto", "nom", "B1"),
    ("oriental / de l'est", "eastern", "östlich", "oriental", "adjectif", "B1"),
    ("économique", "economic", "wirtschaftlich", "económico", "adjectif", "B1"),
    ("l'économie", "economy", "die Wirtschaft", "la economía", "nom", "B1"),
    ("le bord", "edge", "der Rand", "el borde", "nom", "B1"),
    ("l'éditeur / le rédacteur", "editor", "der Redakteur", "el editor", "nom", "B1"),
    ("éduquer", "educate", "ausbilden", "educar", "verbe", "B1"),
    ("éduqué", "educated", "gebildet", "educado", "adjectif", "B1"),
    ("éducatif", "educational", "lehrreich", "educativo", "adjectif", "B1"),
    ("l'effet", "effect", "die Auswirkung", "el efecto", "nom", "B1"),
    ("efficace", "effective", "effektiv", "efectivo", "adjectif", "B1"),
    ("efficacement", "effectively", "effektiv", "eficazmente", "adverbe", "B1"),
    ("l'effort", "effort", "die Anstrengung", "el esfuerzo", "nom", "B1"),
    ("l'élection", "election", "die Wahl", "la elección", "nom", "B1"),
    ("gêné / embarrassé", "embarrassed", "verlegen", "avergonzado", "adjectif", "B1"),
    ("gênant / embarrassant", "embarrassing", "peinlich", "vergonzoso", "adjectif", "B1"),
    ("l'urgence", "emergency", "der Notfall", "la emergencia", "nom", "B1"),
    ("l'émotion", "emotion", "die Emotion", "la emoción", "nom", "B1"),
    ("l'emploi", "employment", "die Beschäftigung", "el empleo", "nom", "B1"),
    ("encourager", "encourage", "ermutigen", "animar", "verbe", "B1"),
    ("l'ennemi", "enemy", "der Feind", "el enemigo", "nom", "B1"),
    ("fiancé / occupé", "engaged", "verlobt / besetzt", "comprometido", "adjectif", "B1"),
    ("l'ingénierie", "engineering", "das Ingenieurwesen", "la ingeniería", "nom", "B1"),
    ("divertir", "entertain", "unterhalten", "entretener", "verbe", "B1"),
    ("le divertissement", "entertainment", "die Unterhaltung", "el entretenimiento", "nom", "B1"),
    ("l'entrée", "entrance", "der Eingang", "la entrada", "nom", "B1"),
    ("l'entrée (droit/action)", "entry", "der Eintritt", "la entrada", "nom", "B1"),
    ("l'environnement", "environment", "die Umwelt", "el medio ambiente", "nom", "B1"),
    ("environnemental", "environmental", "Umwelt-", "ambiental", "adjectif", "B1"),
    ("l'épisode", "episode", "die Episode", "el episodio", "nom", "B1"),
    ("égal", "equal", "gleich", "igual", "adjectif", "B1"),
    ("également", "equally", "gleichermaßen", "igualmente", "adverbe", "B1"),
    ("s'échapper", "escape", "entkommen", "escapar", "verbe", "B1"),
    ("essentiel", "essential", "essenziell", "esencial", "adjectif", "B1"),
    ("l'événement", "event", "das Ereignis", "el evento", "nom", "B1"),
    ("finalement", "eventually", "schließlich", "finalmente", "adverbe", "B1"),
    ("examiner", "examine", "untersuchen", "examinar", "verbe", "B1"),
    ("l'échange", "exchange", "der Austausch", "el intercambio", "nom", "B1"),
    ("échanger", "exchange", "austauschen", "intercambiar", "verbe", "B1"),
    ("l'excitation", "excitement", "die Aufregung", "la emoción", "nom", "B1"),
    ("l'exposition", "exhibition", "die Ausstellung", "la exposición", "nom", "B1"),
    ("étendre / se développer", "expand", "erweitern", "expandir", "verbe", "B1"),
    ("attendu", "expected", "erwartet", "esperado", "adjectif", "B1"),
    ("l'expédition", "expedition", "die Expedition", "la expedición", "nom", "B1"),
    ("expérimenté", "experienced", "erfahren", "experimentado", "adjectif", "B1"),
    ("exploser", "explode", "explodieren", "explotar", "verbe", "B1"),
    ("explorer", "explore", "erkunden", "explorar", "verbe", "B1"),
    ("l'explosion", "explosion", "die Explosion", "la explosión", "nom", "B1"),
    ("l'exportation", "export", "der Export", "la exportación", "nom", "B1"),
    ("exporter", "export", "exportieren", "exportar", "verbe", "B1"),

    # --- LETTRE F (B1) ---
    ("faire face à", "face", "sich stellen", "enfrentar", "verbe", "B1"),
    ("le fait", "fact", "die Tatsache", "el hecho", "nom", "B1"),
    ("assez / plutôt", "fairly", "ziemlich", "bastante", "adverbe", "B1"),
    ("familier", "familiar", "vertraut", "familiar", "adjectif", "B1"),
    ("avoir envie de", "fancy", "Lust haben auf", "apetecer", "verbe", "B1"),
    ("fascinant", "fascinating", "faszinierend", "fascinante", "adjectif", "B1"),
    ("à la mode", "fashionable", "modisch", "de moda", "adjectif", "B1"),
    ("attacher", "fasten", "befestigen", "abrochar", "verbe", "B1"),
    ("la faveur", "favour", "der Gefallen", "el favor", "nom", "B1"),
    ("la peur", "fear", "die Angst", "el miedo", "nom", "B1"),
    ("craindre", "fear", "fürchten", "temer", "verbe", "B1"),
    ("la caractéristique", "feature", "das Merkmal", "la característica", "nom", "B1"),
    ("présenter (avoir pour vedette)", "feature", "in der Hauptrolle zeigen", "presentar", "verbe", "B1"),
    ("nourrir", "feed", "füttern", "alimentar", "verbe", "B1"),
    ("la clôture", "fence", "der Zaun", "la valla", "nom", "B1"),
    ("le combat", "fighting", "das Kämpfen", "la pelea", "nom", "B1"),
    ("la figure / le chiffre", "figure", "die Figur / die Zahl", "la figura / la cifra", "nom", "B1"),
    ("le dossier / le fichier", "file", "die Datei / die Akte", "el archivo", "nom", "B1"),
    ("classer (dossier)", "file", "ablegen", "archivar", "verbe", "B1"),
    ("financier", "financial", "finanziell", "financiero", "adjectif", "B1"),
    ("l'amende", "fine", "die Geldstrafe", "la multa", "nom", "B1"),
    ("la forme (physique)", "fitness", "die Fitness", "la aptitud física", "nom", "B1"),
    ("fixe", "fixed", "fest", "fijo", "adjectif", "B1"),
    ("le flash", "flash", "der Blitz", "el flash", "nom", "B1"),
    ("l'inondation", "flood", "die Überschwemmung", "la inundación", "nom", "B1"),
    ("inonder", "flood", "überschwemmen", "inundar", "verbe", "B1"),
    ("la farine", "flour", "das Mehl", "la harina", "nom", "B1"),
    ("le flux", "flow", "der Fluss", "el flujo", "nom", "B1"),
    ("couler", "flow", "fließen", "fluir", "verbe", "B1"),
    ("le brouillard", "fog", "der Nebel", "la niebla", "nom", "B1"),
    ("plier", "fold", "falten", "doblar", "verbe", "B1"),
    ("les gens / folklorique", "folk", "die Leute / volkstümlich", "la gente / popular", "nom", "B1"),
    ("suivant", "following", "folgend", "siguiente", "adjectif", "B1"),
    ("la force", "force", "die Kraft", "la fuerza", "nom", "B1"),
    ("forcer", "force", "zwingen", "forzar", "verbe", "B1"),
    ("pour toujours", "forever", "für immer", "para siempre", "adverbe", "B1"),
    ("le cadre", "frame", "der Rahmen", "el marco", "nom", "B1"),
    ("geler", "freeze", "frieren", "congelar", "verbe", "B1"),
    ("fréquemment", "frequently", "häufig", "frecuentemente", "adverbe", "B1"),
    ("l'amitié", "friendship", "die Freundschaft", "la amistad", "nom", "B1"),
    ("effrayer", "frighten", "erschrecken", "asustar", "verbe", "B1"),
    ("effrayé", "frightened", "erschrocken", "asustado", "adjectif", "B1"),
    ("effrayant", "frightening", "beängstigend", "aterrador", "adjectif", "B1"),
    ("gelé", "frozen", "gefroren", "congelado", "adjectif", "B1"),
    ("frire", "fry", "braten", "freír", "verbe", "B1"),
    ("le carburant", "fuel", "der Treibstoff", "el combustible", "nom", "B1"),
    ("la fonction", "function", "die Funktion", "la función", "nom", "B1"),
    ("fonctionner", "function", "funktionieren", "funcionar", "verbe", "B1"),
    ("la fourrure", "fur", "das Fell", "la piel (de animal)", "nom", "B1")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b1_batch3.ps1", $new_words, $utf8NoBom)
