$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE T (B2) ---
    ("l'étiquette / le tag", "tag", "das Etikett", "la etiqueta", "nom", "B2"),
    ("étiqueter / taguer", "tag", "markieren", "etiquetar", "verbe", "B2"),
    ("le conte", "tale", "das Märchen", "el cuento", "nom", "B2"),
    ("le réservoir / le char", "tank", "der Panzer / der Tank", "el tanque", "nom", "B2"),
    ("le robinet / le petit coup", "tap", "der Wasserhahn", "el grifo", "nom", "B2"),
    ("taper doucement", "tap", "klopfen", "dar golpecitos", "verbe", "B2"),
    ("la larme / la déchirure", "tear", "die Träne / der Riss", "la lágrima / el desgarro", "nom", "B2"),
    ("déchirer", "tear", "reißen", "romper / desgarrar", "verbe", "B2"),
    ("technologique", "technological", "technologisch", "tecnológico", "adjectif", "B2"),
    ("l'adolescent (familier)", "teen", "der Teenager", "el adolescente", "nom", "B2"),
    ("le temple", "temple", "der Tempel", "el templo", "nom", "B2"),
    ("temporairement", "temporarily", "vorübergehend", "temporalmente", "adverbe", "B2"),
    ("temporaire", "temporary", "vorübergehend", "temporal", "adjectif", "B2"),
    ("la tendance", "tendency", "die Neigung", "la tendencia", "nom", "B2"),
    ("la tension", "tension", "die Spannung", "la tensión", "nom", "B2"),
    ("le terminal", "terminal", "das Terminal", "la terminal", "nom", "B2"),
    ("terminal (phase finale)", "terminal", "im Endstadium", "terminal", "adjectif", "B2"),
    ("les termes (conditions)", "terms", "die Bedingungen", "los términos", "nom", "B2"),
    ("terriblement", "terribly", "schrecklich", "terriblemente", "adverbe", "B2"),
    ("terrifier", "terrify", "erschrecken", "aterrorizar", "verbe", "B2"),
    ("le territoire", "territory", "das Gebiet", "el territorio", "nom", "B2"),
    ("la terreur", "terror", "der Schrecken", "el terror", "nom", "B2"),
    ("le terrorisme", "terrorism", "der Terrorismus", "el terrorismo", "nom", "B2"),
    ("le terroriste", "terrorist", "der Terrorist", "el terrorista", "nom", "B2"),
    ("les tests", "testing", "das Testen", "las pruebas", "nom", "B2"),
    ("le manuel scolaire", "textbook", "das Lehrbuch", "el libro de texto", "nom", "B2"),
    ("le vol (délit)", "theft", "der Diebstahl", "el robo", "nom", "B2"),
    ("le thérapeute", "therapist", "der Therapeut", "el terapeuta", "nom", "B2"),
    ("la thérapie", "therapy", "die Therapie", "la terapia", "nom", "B2"),
    ("la théorie", "theory", "die Theorie", "la teoría", "nom", "B2"),
    ("par conséquent / donc", "therefore", "daher", "por lo tanto", "adverbe", "B2"),
    ("minutieux / approfondi", "thorough", "gründlich", "exhaustivo", "adjectif", "B2"),
    ("minutieusement", "thoroughly", "gründlich", "exhaustivamente", "adverbe", "B2"),
    ("la menace", "threat", "die Bedrohung", "la amenaza", "nom", "B2"),
    ("menacer", "threaten", "bedrohen", "amenazar", "verbe", "B2"),
    ("le pouce", "thumb", "der Daumen", "el pulgar", "nom", "B2"),
    ("ainsi", "thus", "somit", "así", "adverbe", "B2"),
    ("le timing / la synchronisation", "timing", "das Timing", "el tiempo", "nom", "B2"),
    ("le tissu (cellulaire) / le mouchoir", "tissue", "das Gewebe / das Taschentuch", "el tejido / el pañuelo", "nom", "B2"),
    ("le ton", "tone", "der Ton", "el tono", "nom", "B2"),
    ("dur / difficile", "tough", "zäh / hart", "duro / difícil", "adjectif", "B2"),
    ("le tournoi", "tournament", "das Turnier", "el torneo", "nom", "B2"),
    ("toxique", "toxic", "giftig", "tóxico", "adjectif", "B2"),
    ("la trace", "trace", "die Spur", "el rastro", "nom", "B2"),
    ("retracer / tracer", "trace", "zurückverfolgen", "rastrear", "verbe", "B2"),
    ("la piste / le chemin", "track", "die Spur", "la pista", "nom", "B2"),
    ("suivre (à la trace)", "track", "verfolgen", "rastrear", "verbe", "B2"),
    ("le commerce (activité)", "trading", "der Handel", "el comercio", "nom", "B2"),
    ("la tragédie", "tragedy", "die Tragödie", "la tragedia", "nom", "B2"),
    ("tragique", "tragic", "tragisch", "trágico", "adjectif", "B2"),
    ("le trait (de caractère)", "trait", "der Charakterzug", "el rasgo", "nom", "B2"),
    ("le transfert", "transfer", "die Übertragung", "la transferencia", "nom", "B2"),
    ("transférer", "transfer", "übertragen", "transferir", "verbe", "B2"),
    ("transformer", "transform", "verwandeln", "transformar", "verbe", "B2"),
    ("la transition", "transition", "der Übergang", "la transición", "nom", "B2"),
    ("transmettre", "transmit", "übertragen", "transmitir", "verbe", "B2"),
    ("le piège", "trap", "die Falle", "la trampa", "nom", "B2"),
    ("piéger", "trap", "in die Falle locken", "atrapar", "verbe", "B2"),
    ("le trésor", "treasure", "der Schatz", "el tesoro", "nom", "B2"),
    ("le procès / l'essai", "trial", "der Prozess", "el juicio", "nom", "B2"),
    ("la tribu", "tribe", "der Stamm", "la tribu", "nom", "B2"),
    ("le billion (mille milliards)", "trillion", "die Billion", "el billón", "num", "B2"),
    ("la troupe", "troop", "die Truppe", "la tropa", "nom", "B2"),
    ("tropical", "tropical", "tropisch", "tropical", "adjectif", "B2"),
    ("vraiment / véritablement", "truly", "wirklich", "verdaderamente", "adverbe", "B2"),
    ("la confiance", "trust", "das Vertrauen", "la confianza", "nom", "B2"),
    ("faire confiance à", "trust", "vertrauen", "confiar en", "verbe", "B2"),
    ("le tsunami", "tsunami", "der Tsunami", "el tsunami", "nom", "B2"),
    ("l'air (mélodie)", "tune", "die Melodie", "la melodía", "nom", "B2"),
    ("le tunnel", "tunnel", "der Tunnel", "el túnel", "nom", "B2"),

    # --- LETTRE U (B2) ---
    ("ultime", "ultimate", "ultimativ", "último", "adjectif", "B2"),
    ("finalement", "ultimately", "letztendlich", "finalmente", "adverbe", "B2"),
    ("inacceptable", "unacceptable", "inakzeptabel", "inaceptable", "adjectif", "B2"),
    ("l'incertitude", "uncertainty", "die Unsicherheit", "la incertidumbre", "nom", "B2"),
    ("inconscient", "unconscious", "bewusstlos", "inconsciente", "adjectif", "B2"),
    ("subir / éprouver", "undergo", "durchmachen", "someterse a", "verbe", "B2"),
    ("entreprendre", "undertake", "unternehmen", "emprender", "verbe", "B2"),
    ("inattendu", "unexpected", "unerwartet", "inesperado", "adjectif", "B2"),
    ("se dérouler / déplier", "unfold", "sich entfalten", "desarrollarse / desplegar", "verbe", "B2"),
    ("malheureux", "unfortunate", "unglücklich", "desafortunado", "adjectif", "B2"),
    ("unique", "unique", "einzigartig", "único", "adjectif", "B2"),
    ("unir", "unite", "vereinen", "unir", "verbe", "B2"),
    ("l'unité", "unity", "die Einheit", "la unidad", "nom", "B2"),
    ("universel", "universal", "universell", "universal", "adjectif", "B2"),
    ("l'univers", "universe", "das Universum", "el universo", "nom", "B2"),
    ("inconnu", "unknown", "unbekannt", "desconocido", "adjectif", "B2"),
    ("supérieur", "upper", "ober", "superior", "adjectif", "B2"),
    ("vers le haut", "upwards", "aufwärts", "hacia arriba", "adverbe", "B2"),
    ("urbain", "urban", "städtisch", "urbano", "adjectif", "B2"),
    ("exhorter / pousser", "urge", "drängen", "instar", "verbe", "B2"),
    ("urgent", "urgent", "dringend", "urgente", "adjectif", "B2"),
    ("l'usage", "usage", "die Nutzung", "el uso", "nom", "B2"),
    ("inutile", "useless", "nutzlos", "inútil", "adjectif", "B2"),

    # --- LETTRE V (B2) ---
    ("valide", "valid", "gültig", "válido", "adjectif", "B2"),
    ("la variation", "variation", "die Schwankung", "la variación", "nom", "B2"),
    ("varier", "vary", "variieren", "variar", "verbe", "B2"),
    ("vaste", "vast", "riesig", "vasto", "adjectif", "B2"),
    ("le lieu (événement)", "venue", "der Veranstaltungsort", "el lugar", "nom", "B2"),
    ("vertical", "vertical", "vertikal", "vertical", "adjectif", "B2"),
    ("via / par", "via", "über", "vía", "prep", "B2"),
    ("la victoire", "victory", "der Sieg", "la victoria", "nom", "B2"),
    ("victorieux", "victorious", "siegreich", "victorioso", "adjectif", "B2"),
    ("le point de vue", "viewpoint", "der Standpunkt", "el punto de vista", "nom", "B2"),
    ("la violence", "violence", "die Gewalt", "la violencia", "nom", "B2"),
    ("virtuel", "virtual", "virtuell", "virtual", "adjectif", "B2"),
    ("le visa", "visa", "das Visum", "el visado", "nom", "B2"),
    ("visible", "visible", "sichtbar", "visible", "adjectif", "B2"),
    ("la vision", "vision", "die Vision", "la visión", "nom", "B2"),
    ("visuel", "visual", "visuell", "visual", "adjectif", "B2"),
    ("vital", "vital", "lebenswichtig", "vital", "adjectif", "B2"),
    ("la vitamine", "vitamin", "das Vitamin", "la vitamina", "nom", "B2"),
    ("le volume", "volume", "die Lautstärke", "el volumen", "nom", "B2"),
    ("volontairement", "voluntarily", "freiwillig", "voluntariamente", "adverbe", "B2"),
    ("volontaire", "voluntary", "freiwillig", "voluntario", "adjectif", "B2"),
    ("le vote (action)", "voting", "die Abstimmung", "la votación", "nom", "B2"),

    # --- LETTRE W (B2) ---
    ("le salaire", "wage", "der Lohn", "el salario", "nom", "B2"),
    ("errer / se promener", "wander", "wandern", "deambular", "verbe", "B2"),
    ("le réchauffement", "warming", "die Erwärmung", "el calentamiento", "nom", "B2"),
    ("la faiblesse", "weakness", "die Schwäche", "la debilidad", "nom", "B2"),
    ("la richesse", "wealth", "der Reichtum", "la riqueza", "nom", "B2"),
    ("riche", "wealthy", "wohlhabend", "rico", "adjectif", "B2"),
    ("hebdomadaire", "weekly", "wöchentlich", "semanal", "adjectif", "B2"),
    ("bizarre", "weird", "seltsam", "raro", "adjectif", "B2"),
    ("le bien-être / l'aide sociale", "welfare", "die Wohlfahrt", "el bienestar", "nom", "B2"),
    ("le blé", "wheat", "der Weizen", "el trigo", "nom", "B2"),
    ("tandis que", "whereas", "wohingegen", "mientras que", "conj", "B2"),
    ("partout où", "wherever", "wo auch immer", "dondequiera que", "conj", "B2"),
    ("chuchoter", "whisper", "flüstern", "susurrar", "verbe", "B2"),
    ("quiconque", "whoever", "wer auch immer", "quienquiera que", "pron", "B2"),
    ("qui / que (complément)", "whom", "wem / wen", "a quien", "pron", "B2"),
    ("largement", "widely", "weit", "ampliamente", "adverbe", "B2"),
    ("répandu", "widespread", "weit verbreitet", "generalizado", "adjectif", "B2"),
    ("la veuve", "widow", "die Witwe", "la viuda", "nom", "B2"),
    ("la faune", "wildlife", "die Tierwelt", "la vida silvestre", "nom", "B2"),
    ("disposé à", "willing", "bereit", "dispuesto", "adjectif", "B2"),
    ("le fil (de fer/électrique)", "wire", "der Draht", "el alambre", "nom", "B2"),
    ("la sagesse", "wisdom", "die Weisheit", "la sabiduría", "nom", "B2"),
    ("sage", "wise", "weise", "sabio", "adjectif", "B2"),
    ("retirer", "withdraw", "zurückziehen", "retirar", "verbe", "B2"),
    ("le témoin", "witness", "der Zeuge", "el testigo", "nom", "B2"),
    ("être témoin de", "witness", "bezeugen", "presenciar", "verbe", "B2"),
    ("le loup", "wolf", "der Wolf", "el lobo", "nom", "B2"),
    ("la main-d'œuvre", "workforce", "die Belegschaft", "la fuerza laboral", "nom", "B2"),
    ("le lieu de travail", "workplace", "der Arbeitsplatz", "el lugar de trabajo", "nom", "B2"),
    ("l'atelier / l'entraînement", "workshop", "die Werkstatt", "el taller", "nom", "B2"),
    ("le ver", "worm", "der Wurm", "el gusano", "nom", "B2"),
    ("la blessure", "wound", "die Wunde", "la herida", "nom", "B2"),
    ("blesser", "wound", "verwunden", "herir", "verbe", "B2"),
    ("emballer / envelopper", "wrap", "einwickeln", "envolver", "verbe", "B2"),
    ("le poignet", "wrist", "das Handgelenk", "la muñeca", "nom", "B2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b2_batch10.ps1", $new_words, $utf8NoBom)
