$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE E (B2) ---
    ("impatient / avide", "eager", "eifrig", "ansioso / entusiasta", "adjectif", "B2"),
    ("l'économie (science)", "economics", "die Wirtschaftswissenschaften", "la economía", "nom", "B2"),
    ("l'économiste", "economist", "der Ökonom", "el economista", "nom", "B2"),
    ("éditer / modifier", "edit", "bearbeiten", "editar", "verbe", "B2"),
    ("l'édition (publication)", "edition", "die Ausgabe", "la edición", "nom", "B2"),
    ("éditorial", "editorial", "redaktionell", "editorial", "adjectif", "B2"),
    ("efficace (rendement)", "efficient", "effizient", "eficiente", "adjectif", "B2"),
    ("efficacement", "efficiently", "effizient", "eficientemente", "adverbe", "B2"),
    ("le coude", "elbow", "der Ellbogen", "el codo", "nom", "B2"),
    ("âgé (personne)", "elderly", "ältere", "anciano", "adjectif", "B2"),
    ("élire", "elect", "wählen", "elegir", "verbe", "B2"),
    ("l'élément", "element", "das Element", "el elemento", "nom", "B2"),
    ("l'électronique", "electronics", "die Elektronik", "la electrónica", "nom", "B2"),
    ("élégant", "elegant", "elegant", "elegante", "adjectif", "B2"),
    ("élémentaire", "elementary", "elementar", "elemental", "adjectif", "B2"),
    ("éliminer", "eliminate", "beseitigen", "eliminar", "verbe", "B2"),
    ("ailleurs", "elsewhere", "woanders", "en otro lugar", "adverbe", "B2"),
    ("embrasser (idée) / enlacer", "embrace", "umarmen", "abrazar", "verbe", "B2"),
    ("émerger", "emerge", "auftauchen", "emerger", "verbe", "B2"),
    ("l'émission (gaz)", "emission", "die Emission", "la emisión", "nom", "B2"),
    ("émotionnel", "emotional", "emotional", "emocional", "adjectif", "B2"),
    ("émotionnellement", "emotionally", "emotional", "emocionalmente", "adverbe", "B2"),
    ("l'accent / l'importance", "emphasis", "die Betonung", "el énfasis", "nom", "B2"),
    ("souligner / mettre l'accent sur", "emphasise", "betonen", "enfatizar", "verbe", "B2"),
    ("l'empire", "empire", "das Reich", "el imperio", "nom", "B2"),
    ("permettre (rendre capable)", "enable", "ermöglichen", "permitir", "verbe", "B2"),
    ("rencontrer (problème/personne)", "encounter", "begegnen", "encontrar", "verbe", "B2"),
    ("s'engager / impliquer", "engage", "engagieren", "involucrar", "verbe", "B2"),
    ("améliorer / mettre en valeur", "enhance", "verbessern", "mejorar", "verbe", "B2"),
    ("agréable", "enjoyable", "angenehm", "agradable", "adjectif", "B2"),
    ("la demande / l'enquête", "enquiry", "die Anfrage", "la consulta", "nom", "B2"),
    ("assurer / garantir", "ensure", "sicherstellen", "asegurar", "verbe", "B2"),
    ("divertissant", "entertaining", "unterhaltsam", "entretenido", "adjectif", "B2"),
    ("l'enthousiasme", "enthusiasm", "die Begeisterung", "el entusiasmo", "nom", "B2"),
    ("enthousiaste", "enthusiastic", "begeistert", "entusiasta", "adjectif", "B2"),
    ("entier", "entire", "ganz", "entero", "adjectif", "B2"),
    ("entièrement", "entirely", "vollständig", "enteramente", "adverbe", "B2"),
    ("l'entrepreneur", "entrepreneur", "der Unternehmer", "el emprendedor", "nom", "B2"),
    ("l'enveloppe", "envelope", "der Umschlag", "el sobre", "nom", "B2"),
    ("équiper", "equip", "ausstatten", "equipar", "verbe", "B2"),
    ("équivalent", "equivalent", "äquivalent", "equivalente", "adjectif", "B2"),
    ("l'ère", "era", "die Ära", "la era", "nom", "B2"),
    ("entrer en éruption", "erupt", "ausbrechen", "entrar en erupción", "verbe", "B2"),
    ("essentiellement", "essentially", "im Wesentlichen", "esencialmente", "adverbe", "B2"),
    ("établir", "establish", "gründen / etablieren", "establecer", "verbe", "B2"),
    ("le domaine / la propriété", "estate", "das Anwesen", "la propiedad", "nom", "B2"),
    ("l'estimation", "estimate", "die Schätzung", "la estimación", "nom", "B2"),
    ("estimer", "estimate", "schätzen", "estimar", "verbe", "B2"),
    ("l'éthique", "ethic", "die Ethik", "la ética", "nom", "B2"),
    ("éthique", "ethical", "ethisch", "ético", "adjectif", "B2"),
    ("ethnique", "ethnic", "ethnisch", "étnico", "adjectif", "B2"),
    ("évaluer", "evaluate", "auswerten", "evaluar", "verbe", "B2"),
    ("l'évaluation", "evaluation", "die Bewertung", "la evaluación", "nom", "B2"),
    ("même (adv)", "even", "sogar", "incluso", "adverbe", "B2"),
    ("la preuve", "evidence", "der Beweis", "la evidencia", "nom", "B2"),
    ("évident", "evident", "offensichtlich", "evidente", "adjectif", "B2"),
    ("le mal", "evil", "das Böse", "el mal", "nom", "B2"),
    ("maléfique", "evil", "böse", "malvado", "adjectif", "B2"),
    ("l'évolution", "evolution", "die Evolution", "la evolución", "nom", "B2"),
    ("évoluer", "evolve", "sich entwickeln", "evolucionar", "verbe", "B2"),
    ("l'examen", "examination", "die Prüfung", "el examen", "nom", "B2"),
    ("dépasser / excéder", "exceed", "überschreiten", "exceder", "verbe", "B2"),
    ("l'exception", "exception", "die Ausnahme", "la excepción", "nom", "B2"),
    ("excessif", "excessive", "übermäßig", "excesivo", "adjectif", "B2"),
    ("exclure", "exclude", "ausschließen", "excluir", "verbe", "B2"),
    ("l'excuse", "excuse", "die Ausrede", "la excusa", "nom", "B2"),
    ("excuser", "excuse", "entschuldigen", "excusar", "verbe", "B2"),
    ("le cadre / l'exécutif", "executive", "die Führungskraft", "el ejecutivo", "nom", "B2"),
    ("l'existence", "existence", "die Existenz", "la existencia", "nom", "B2"),
    ("exotique", "exotic", "exotisch", "exótico", "adjectif", "B2"),
    ("l'expansion", "expansion", "die Erweiterung", "la expansión", "nom", "B2"),
    ("l'attente", "expectation", "die Erwartung", "la expectativa", "nom", "B2"),
    ("la dépense", "expense", "die Ausgabe", "el gasto", "nom", "B2"),
    ("l'expertise", "expertise", "das Fachwissen", "la experiencia (técnica)", "nom", "B2"),
    ("exploiter", "exploit", "ausbeuten", "explotar", "verbe", "B2"),
    ("l'exploration", "exploration", "die Erkundung", "la exploración", "nom", "B2"),
    ("exposer", "expose", "aussetzen", "exponer", "verbe", "B2"),
    ("l'exposition", "exposure", "die Aussetzung", "la exposición", "nom", "B2"),
    ("étendre / prolonger", "extend", "erweitern", "extender", "verbe", "B2"),
    ("l'extension", "extension", "die Erweiterung", "la extensión", "nom", "B2"),
    ("extensif / vaste", "extensive", "umfangreich", "extenso", "adjectif", "B2"),
    ("largement (extensivement)", "extensively", "ausführlich", "extensamente", "adverbe", "B2"),
    ("l'étendue", "extent", "das Ausmaß", "la medida", "nom", "B2"),
    ("externe", "external", "extern", "externo", "adjectif", "B2"),
    ("l'extrait", "extract", "der Auszug", "el extracto", "nom", "B2"),
    ("extraire", "extract", "extrahieren", "extraer", "verbe", "B2"),
    ("extraordinaire", "extraordinary", "außergewöhnlich", "extraordinario", "adjectif", "B2"),

    # --- LETTRE F (B2) ---
    ("le tissu", "fabric", "der Stoff", "la tela", "nom", "B2"),
    ("fabuleux", "fabulous", "fabelhaft", "fabuloso", "adjectif", "B2"),
    ("l'installation / l'équipement", "facility", "die Einrichtung", "la instalación", "nom", "B2"),
    ("le facteur", "factor", "der Faktor", "el factor", "nom", "B2"),
    ("la faculté", "faculty", "die Fakultät", "la facultad", "nom", "B2"),
    ("échoué / raté", "failed", "gescheitert", "fallido", "adjectif", "B2"),
    ("l'échec", "failure", "das Scheitern", "el fracaso", "nom", "B2"),
    ("la foi", "faith", "der Glaube", "la fe", "nom", "B2"),
    ("le faux", "fake", "die Fälschung", "lo falso", "nom", "B2"),
    ("faux", "fake", "falsch", "falso", "adjectif", "B2"),
    ("la renommée", "fame", "der Ruhm", "la fama", "nom", "B2"),
    ("la fantaisie", "fantasy", "die Fantasie", "la fantasía", "nom", "B2"),
    ("le tarif (transport)", "fare", "der Fahrpreis", "la tarifa", "nom", "B2"),
    ("la faute / le défaut", "fault", "der Fehler", "la culpa", "nom", "B2"),
    ("favoriser", "favour", "bevorzugen", "favorecer", "verbe", "B2"),
    ("la plume", "feather", "die Feder", "la pluma", "nom", "B2"),
    ("les frais", "fee", "die Gebühr", "la tarifa", "nom", "B2"),
    ("le retour (d'information)", "feedback", "die Rückmeldung", "los comentarios", "nom", "B2"),
    ("le confrère / le compagnon", "fellow", "der Kollege", "el compañero", "nom", "B2"),
    ("la finance", "finance", "die Finanzen", "las finanzas", "nom", "B2"),
    ("financer", "finance", "finanzieren", "financiar", "verbe", "B2"),
    ("la découverte / le résultat", "finding", "der Befund", "el hallazgo", "nom", "B2"),
    ("le pompier", "firefighter", "der Feuerwehrmann", "el bombero", "nom", "B2"),
    ("le feu d'artifice", "firework", "das Feuerwerk", "el fuego artificial", "nom", "B2"),
    ("l'entreprise", "firm", "die Firma", "la empresa", "nom", "B2"),
    ("ferme", "firm", "fest", "firme", "adjectif", "B2"),
    ("fermement", "firmly", "fest", "firmemente", "adverbe", "B2"),
    ("la flamme", "flame", "die Flamme", "la llama", "nom", "B2"),
    ("clignoter", "flash", "blinken", "parpadear", "verbe", "B2"),
    ("la saveur", "flavour", "der Geschmack", "el sabor", "nom", "B2"),
    ("flexible", "flexible", "flexibel", "flexible", "adjectif", "B2"),
    ("flotter", "float", "schweben", "flotar", "verbe", "B2"),
    ("pliant", "folding", "zusammenklappbar", "plegable", "adjectif", "B2"),
    ("affectueux", "fond", "liebevoll", "aficionado", "adjectif", "B2"),
    ("l'imbécile / le fou", "fool", "der Narr", "el tonto", "nom", "B2"),
    ("tromper", "fool", "täuschen", "engañar", "verbe", "B2"),
    ("interdire", "forbid", "verbieten", "prohibir", "verbe", "B2"),
    ("les prévisions", "forecast", "die Vorhersage", "el pronóstico", "nom", "B2"),
    ("prévoir", "forecast", "vorhersagen", "pronosticar", "verbe", "B2"),
    ("pardonner", "forgive", "vergeben", "perdonar", "verbe", "B2"),
    ("le format", "format", "das Format", "el formato", "nom", "B2"),
    ("la formation (géologique/sportive)", "formation", "die Formation", "la formación", "nom", "B2"),
    ("ancien / précédent", "former", "früher", "anterior", "adjectif", "B2"),
    ("autrefois", "formerly", "früher", "anteriormente", "adverbe", "B2"),
    ("chanceux", "fortunate", "glücklich", "afortunado", "adjectif", "B2"),
    ("la fortune", "fortune", "das Vermögen", "la fortuna", "nom", "B2"),
    ("le forum", "forum", "das Forum", "el foro", "nom", "B2"),
    ("fonder", "found", "gründen", "fundar", "verbe", "B2"),
    ("la fondation", "foundation", "die Gründung", "la fundación", "nom", "B2"),
    ("le fondateur", "founder", "der Gründer", "el fundador", "nom", "B2"),
    ("la fraction", "fraction", "der Bruchteil", "la fracción", "nom", "B2"),
    ("le fragment", "fragment", "das Fragment", "el fragmento", "nom", "B2"),
    ("le cadre / la structure", "framework", "der Rahmen", "el marco", "nom", "B2"),
    ("la fraude", "fraud", "der Betrug", "el fraude", "nom", "B2"),
    ("la liberté", "freedom", "die Freiheit", "la libertad", "nom", "B2"),
    ("librement", "freely", "frei", "libremente", "adverbe", "B2"),
    ("la fréquence", "frequency", "die Häufigkeit", "la frecuencia", "nom", "B2"),
    ("fréquent", "frequent", "häufig", "frecuente", "adjectif", "B2"),
    ("frustré", "frustrated", "frustriert", "frustrado", "adjectif", "B2"),
    ("accomplir / remplir (promesse)", "fulfil", "erfüllen", "cumplir", "verbe", "B2"),
    ("à temps plein", "full-time", "Vollzeit-", "a tiempo completo", "adjectif", "B2"),
    ("pleinement", "fully", "vollständig", "plenamente", "adverbe", "B2"),
    ("le fonds", "fund", "der Fonds", "el fondo", "nom", "B2"),
    ("financer", "fund", "finanzieren", "financiar", "verbe", "B2"),
    ("fondamental", "fundamental", "grundlegend", "fundamental", "adjectif", "B2"),
    ("fondamentalement", "fundamentally", "grundsätzlich", "fundamentalmente", "adverbe", "B2"),
    ("le financement", "funding", "die Finanzierung", "la financiación", "nom", "B2"),
    ("les funérailles", "funeral", "das Begräbnis", "el funeral", "nom", "B2"),
    ("furieux", "furious", "wütend", "furioso", "adjectif", "B2"),
    ("de plus", "furthermore", "außerdem", "además", "adverbe", "B2"),

    # --- LETTRE G (B2) ---
    ("gagner / obtenir", "gain", "gewinnen", "ganar / obtener", "verbe", "B2"),
    ("le gallon", "gallon", "die Gallone", "el galón", "nom", "B2"),
    ("le jeu vidéo", "gaming", "das Spielen", "el juego", "nom", "B2"),
    ("le gang / la bande", "gang", "die Bande", "la pandilla", "nom", "B2"),
    ("gay", "gay", "schwul", "gay", "adjectif", "B2"),
    ("le genre (masculin/féminin)", "gender", "das Geschlecht", "el género", "nom", "B2"),
    ("le gène", "gene", "das Gen", "el gen", "nom", "B2"),
    ("générer", "generate", "erzeugen", "generar", "verbe", "B2"),
    ("génétique", "genetic", "genetisch", "genético", "adjectif", "B2"),
    ("le génie", "genius", "das Genie", "el genio", "nom", "B2"),
    ("le genre (style)", "genre", "das Genre", "el género", "nom", "B2"),
    ("véritable / authentique", "genuine", "echt", "genuino", "adjectif", "B2"),
    ("véritablement", "genuinely", "wirklich", "genuinamente", "adverbe", "B2"),
    ("le geste", "gesture", "die Geste", "el gesto", "nom", "B2"),
    ("la mondialisation", "globalization", "die Globalisierung", "la globalización", "nom", "B2"),
    ("le globe", "globe", "der Globus", "el globo", "nom", "B2"),
    ("doré", "golden", "golden", "dorado", "adjectif", "B2"),
    ("la bonté", "goodness", "die Güte", "la bondad", "nom", "B2"),
    ("magnifique", "gorgeous", "wunderschön", "hermoso", "adjectif", "B2"),
    ("gouverner", "govern", "regieren", "gobernar", "verbe", "B2"),
    ("saisir / attraper", "grab", "greifen", "agarrar", "verbe", "B2"),
    ("progressivement", "gradually", "allmählich", "gradualmente", "adverbe", "B2"),
    ("grandiose", "grand", "großartig", "grandioso", "adjectif", "B2"),
    ("la subvention", "grant", "der Zuschuss", "la subvención", "nom", "B2"),
    ("accorder", "grant", "gewähren", "conceder", "verbe", "B2"),
    ("graphique", "graphic", "grafisch", "gráfico", "adjectif", "B2"),
    ("les graphismes", "graphics", "die Grafik", "los gráficos", "nom", "B2"),
    ("la tombe", "grave", "das Grab", "la tumba", "nom", "B2"),
    ("grandement", "greatly", "sehr", "grandemente", "adverbe", "B2"),
    ("la serre", "greenhouse", "das Gewächshaus", "el invernadero", "nom", "B2"),
    ("garantir", "guarantee", "garantieren", "garantizar", "verbe", "B2"),
    ("la directive", "guideline", "die Richtlinie", "la pauta", "nom", "B2"),

    # --- LETTRE H (B2) ---
    ("l'habitat", "habitat", "der Lebensraum", "el hábitat", "nom", "B2"),
    ("gérer / manipuler", "handle", "handhaben", "manejar", "verbe", "B2"),
    ("le port", "harbour", "der Hafen", "el puerto", "nom", "B2"),
    ("le mal / le tort", "harm", "der Schaden", "el daño", "nom", "B2"),
    ("nuire à", "harm", "schaden", "dañar", "verbe", "B2"),
    ("nuisible", "harmful", "schädlich", "dañino", "adjectif", "B2"),
    ("le siège social", "headquarters", "der Hauptsitz", "la sede", "nom", "B2"),
    ("guérir", "heal", "heilen", "sanar", "verbe", "B2"),
    ("les soins de santé", "healthcare", "die Gesundheitsversorgung", "la atención sanitaria", "nom", "B2"),
    ("l'ouïe / l'audience", "hearing", "das Gehör / die Anhörung", "la audición / la audiencia", "nom", "B2"),
    ("le paradis", "heaven", "der Himmel", "el cielo", "nom", "B2"),
    ("le talon", "heel", "die Ferse", "el talón", "nom", "B2"),
    ("l'enfer", "hell", "die Hölle", "el infierno", "nom", "B2"),
    ("le casque", "helmet", "der Helm", "el casco", "nom", "B2"),
    ("l'herbe (aromatique)", "herb", "das Kraut", "la hierba", "nom", "B2"),
    ("hésiter", "hesitate", "zögern", "dudar", "verbe", "B2"),
    ("caché", "hidden", "versteckt", "oculto", "adjectif", "B2"),
    ("hilarant", "hilarious", "sehr lustig", "divertidísimo", "adjectif", "B2"),
    ("la hanche", "hip", "die Hüfte", "la cadera", "nom", "B2"),
    ("l'historien", "historian", "der Historiker", "el historiador", "nom", "B2"),
    ("creux", "hollow", "hohl", "hueco", "adjectif", "B2"),
    ("saint", "holy", "heilig", "santo", "adjectif", "B2"),
    ("sans-abri", "homeless", "obdachlos", "sin hogar", "adjectif", "B2"),
    ("l'honnêteté", "honesty", "die Ehrlichkeit", "la honestidad", "nom", "B2"),
    ("l'honneur", "honour", "die Ehre", "el honor", "nom", "B2"),
    ("le crochet", "hook", "der Haken", "el gancho", "nom", "B2"),
    ("avec un peu de chance", "hopefully", "hoffentlich", "con suerte", "adverbe", "B2"),
    ("le ménage / le foyer", "household", "der Haushalt", "el hogar", "nom", "B2"),
    ("le logement", "housing", "das Wohnungswesen", "la vivienda", "nom", "B2"),
    ("humoristique", "humorous", "humorvoll", "humorístico", "adjectif", "B2"),
    ("l'humour", "humour", "der Humor", "el humor", "nom", "B2"),
    ("la faim", "hunger", "der Hunger", "el hambre", "nom", "B2"),
    ("la chasse", "hunting", "die Jagd", "la caza", "nom", "B2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b2_batch6.ps1", $new_words, $utf8NoBom)
