$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE L (B1) ---
    ("l'étiquette", "label", "das Etikett", "la etiqueta", "nom", "B1"),
    ("étiqueter", "label", "beschriften", "etiquetar", "verbe", "B1"),
    ("le laboratoire", "laboratory", "das Labor", "el laboratorio", "nom", "B1"),
    ("le manque", "lack", "der Mangel", "la falta", "nom", "B1"),
    ("manquer de", "lack", "mangeln", "carecer", "verbe", "B1"),
    ("le plus récent / dernier", "latest", "neueste", "último", "adjectif", "B1"),
    ("poser / pondre", "lay", "legen", "poner / colocar", "verbe", "B1"),
    ("la couche", "layer", "die Schicht", "la capa", "nom", "B1"),
    ("le plomb (métal)", "lead", "das Blei", "el plomo", "nom", "B1"),
    ("principal / de tête", "leading", "führend", "principal", "adjectif", "B1"),
    ("la feuille (arbre)", "leaf", "das Blatt", "la hoja", "nom", "B1"),
    ("le cuir", "leather", "das Leder", "el cuero", "nom", "B1"),
    ("légal", "legal", "legal", "legal", "adjectif", "B1"),
    ("le loisir", "leisure", "die Freizeit", "el ocio", "nom", "B1"),
    ("la longueur", "length", "die Länge", "la longitud", "nom", "B1"),
    ("niveler / égaliser", "level", "ebnen", "nivelar", "verbe", "B1"),
    ("mentir", "lie", "lügen", "mentir", "verbe", "B1"),
    ("la limite", "limit", "das Limit", "el límite", "nom", "B1"),
    ("limiter", "limit", "begrenzen", "limitar", "verbe", "B1"),
    ("la lèvre", "lip", "die Lippe", "el labio", "nom", "B1"),
    ("le liquide", "liquid", "die Flüssigkeit", "el líquido", "nom", "B1"),
    ("la littérature", "literature", "die Literatur", "la literatura", "nom", "B1"),
    ("le mode de vie / le salaire pour vivre", "living", "der Lebensunterhalt", "el modo de vida", "nom", "B1"),
    ("vivant", "living", "lebendig", "vivo", "adjectif", "B1"),
    ("localiser", "locate", "lokalisieren", "ubicar", "verbe", "B1"),
    ("situé", "located", "gelegen", "ubicado", "adjectif", "B1"),
    ("l'emplacement / le lieu", "location", "der Standort", "la ubicación", "nom", "B1"),
    ("le journal de bord / le registre", "log", "das Protokoll", "el registro", "nom", "B1"),
    ("solitaire", "lonely", "einsam", "solitario", "adjectif", "B1"),
    ("la perte", "loss", "der Verlust", "la pérdida", "nom", "B1"),
    ("le luxe", "luxury", "der Luxus", "el lujo", "nom", "B1"),

    # --- LETTRE M (B1) ---
    ("fou", "mad", "verrückt", "loco", "adjectif", "B1"),
    ("la magie", "magic", "die Magie", "la magia", "nom", "B1"),
    ("principalement", "mainly", "hauptsächlich", "principalmente", "adverbe", "B1"),
    ("le centre commercial", "mall", "das Einkaufszentrum", "el centro comercial", "nom", "B1"),
    ("la gestion", "management", "das Management", "la gestión", "nom", "B1"),
    ("le marketing", "marketing", "das Marketing", "el marketing", "nom", "B1"),
    ("le mariage", "marriage", "die Ehe", "el matrimonio", "nom", "B1"),
    ("le matériau / la matière", "material", "das Material", "el material", "nom", "B1"),
    ("pendant ce temps", "meanwhile", "in der Zwischenzeit", "mientras tanto", "adverbe", "B1"),
    ("la mesure", "measure", "die Maßnahme", "la medida", "nom", "B1"),
    ("mesurer", "measure", "messen", "medir", "verbe", "B1"),
    ("moyen", "medium", "mittel", "medio", "adjectif", "B1"),
    ("mental", "mental", "geistig", "mental", "adjectif", "B1"),
    ("le désordre", "mess", "die Unordnung", "el desorden", "nom", "B1"),
    ("doux / léger", "mild", "mild", "suave", "adjectif", "B1"),
    ("le moulin", "mill", "die Mühle", "el molino", "nom", "B1"),
    ("la mine (trou)", "mine", "die Mine", "la mina", "nom", "B1"),
    ("mélanger", "mix", "mischen", "mezclar", "verbe", "B1"),
    ("le mélange", "mixture", "die Mischung", "la mezcla", "nom", "B1"),
    ("le modèle", "model", "das Modell", "el modelo", "nom", "B1"),
    ("l'humeur", "mood", "die Stimmung", "el estado de ánimo", "nom", "B1"),
    ("la boue", "mud", "der Schlamm", "el barro", "nom", "B1"),
    ("le meurtre", "murder", "der Mord", "el asesinato", "nom", "B1"),
    ("assassiner", "murder", "ermorden", "asesinar", "verbe", "B1"),
    ("le muscle", "muscle", "der Muskel", "el músculo", "nom", "B1"),
    ("le mystère", "mystery", "das Mysterium", "el misterio", "nom", "B1")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b1_batch5.ps1", $new_words, $utf8NoBom)
