$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE E (A2) ---
    ("gagner (argent)", "earn", "verdienen", "ganar", "verbe", "A2"),
    ("la terre", "earth", "die Erde", "la tierra", "nom", "A2"),
    ("facilement", "easily", "leicht", "fácilmente", "adverbe", "A2"),
    ("l'éducation", "education", "die Bildung", "la educación", "nom", "A2"),
    ("soit / non plus", "either", "entweder / auch nicht", "tampoco / o", "adverbe", "A2"),
    ("électrique", "electric", "elektrisch", "eléctrico", "adjectif", "A2"),
    ("électrique (matériel)", "electrical", "elektrisch", "eléctrico", "adjectif", "A2"),
    ("l'électricité", "electricity", "die Elektrizität", "la electricidad", "nom", "A2"),
    ("électronique", "electronic", "elektronisch", "electrónico", "adjectif", "A2"),
    ("employer", "employ", "beschäftigen", "emplear", "verbe", "A2"),
    ("l'employé", "employee", "der Mitarbeiter", "el empleado", "nom", "A2"),
    ("l'employeur", "employer", "der Arbeitgeber", "el empleador", "nom", "A2"),
    ("vide", "empty", "leer", "vacío", "adjectif", "A2"),
    ("la fin (d'une histoire)", "ending", "das Ende", "el final", "nom", "A2"),
    ("l'énergie", "energy", "die Energie", "la energía", "nom", "A2"),
    ("le moteur", "engine", "der Motor", "el motor", "nom", "A2"),
    ("l'ingénieur", "engineer", "der Ingenieur", "el ingeniero", "nom", "A2"),
    ("énorme", "enormous", "enorm", "enorme", "adjectif", "A2"),
    ("entrer", "enter", "eintreten", "entrar", "verbe", "A2"),
    ("assez (quantité)", "enough", "genug", "suficiente", "adverbe", "A2"),
    ("l'équipement", "equipment", "die Ausrüstung", "el equipo", "nom", "A2"),
    ("l'erreur", "error", "der Fehler", "el error", "nom", "A2"),
    ("surtout / particulièrement", "especially", "besonders", "especialmente", "adverbe", "A2"),
    ("l'essai / la dissertation", "essay", "der Aufsatz", "el ensayo", "nom", "A2"),
    ("quotidien", "everyday", "alltäglich", "cotidiano", "adjectif", "A2"),
    ("partout", "everywhere", "überall", "en todas partes", "adverbe", "A2"),
    ("exact", "exact", "exakt", "exacto", "adjectif", "A2"),
    ("exactement", "exactly", "genau", "exactamente", "adverbe", "A2"),
    ("excellent", "excellent", "ausgezeichnet", "excelente", "adjectif", "A2"),
    ("sauf", "except", "außer", "excepto", "prep", "A2"),
    ("exister", "exist", "existieren", "existir", "verbe", "A2"),
    ("s'attendre à", "expect", "erwarten", "esperar", "verbe", "A2"),
    ("l'expérience", "experience", "die Erfahrung", "la experiencia", "nom", "A2"),
    ("l'expérience scientifique", "experiment", "das Experiment", "el experimento", "nom", "A2"),
    ("l'expert", "expert", "der Experte", "el experto", "nom", "A2"),
    ("l'explication", "explanation", "die Erklärung", "la explicación", "nom", "A2"),
    ("exprimer", "express", "ausdrücken", "expresar", "verbe", "A2"),
    ("l'expression", "expression", "der Ausdruck", "la expresión", "nom", "A2"),
    ("extrême", "extreme", "extrem", "extremo", "adjectif", "A2"),
    ("extrêmement", "extremely", "extrem", "extremadamente", "adverbe", "A2"),

    # --- LETTRE F (A2) ---
    ("l'usine", "factory", "die Fabrik", "la fábrica", "nom", "A2"),
    ("échouer", "fail", "scheitern", "fallar", "verbe", "A2"),
    ("juste / équitable", "fair", "fair", "justo", "adjectif", "A2"),
    ("le fan", "fan", "der Fan", "el fan", "nom", "A2"),
    ("l'agriculture", "farming", "die Landwirtschaft", "la agricultura", "nom", "A2"),
    ("la mode", "fashion", "die Mode", "la moda", "nom", "A2"),
    ("gros / gras", "fat", "fett", "gordo", "adjectif", "A2"),
    ("la graisse", "fat", "das Fett", "la grasa", "nom", "A2"),
    ("la peur", "fear", "die Angst", "el miedo", "nom", "A2"),
    ("le sentiment", "feeling", "das Gefühl", "el sentimiento", "nom", "A2"),
    ("la femelle / féminin", "female", "weiblich", "la hembra", "nom", "A2"),
    ("la fiction", "fiction", "die Fiktion", "la ficción", "nom", "A2"),
    ("le champ", "field", "das Feld", "el campo", "nom", "A2"),
    ("le combat", "fight", "der Kampf", "la pelea", "nom", "A2"),
    ("combattre", "fight", "kämpfen", "pelear", "verbe", "A2"),
    ("le chiffre / la silhouette", "figure", "die Figur / die Zahl", "la figura", "nom", "A2"),
    ("filmer", "film", "filmen", "filmar", "verbe", "A2"),
    ("le film", "film", "der Film", "la película", "nom", "A2"),
    ("finalement", "finally", "schließlich", "finalmente", "adverbe", "A2"),
    ("le doigt", "finger", "der Finger", "el dedo", "nom", "A2"),
    ("premier", "first", "zuerst", "primero", "adverbe", "A2"),
    ("premièrement", "firstly", "erstens", "en primer lugar", "adverbe", "A2"),
    ("pêcher", "fish", "angeln", "pescar", "verbe", "A2"),
    ("la pêche", "fishing", "das Angeln", "la pesca", "nom", "A2"),
    ("en forme (santé)", "fit", "fit", "en forma", "adjectif", "A2"),
    ("le drapeau", "flag", "die Flagge", "la bandera", "nom", "A2"),
    ("plat", "flat", "flach", "plano", "adjectif", "A2"),
    ("la grippe", "flu", "die Grippe", "la gripe", "nom", "A2"),
    ("volant", "flying", "fliegend", "volador", "adjectif", "A2"),
    ("se concentrer", "focus", "fokussieren", "enfocarse", "verbe", "A2"),
    ("suivant", "following", "folgend", "siguiente", "adjectif", "A2"),
    ("étranger", "foreign", "ausländisch", "extranjero", "adjectif", "A2"),
    ("la forêt", "forest", "der Wald", "el bosque", "nom", "A2"),
    ("la fourchette", "fork", "die Gabel", "el tenedor", "nom", "A2"),
    ("formel", "formal", "formell", "formal", "adjectif", "A2"),
    ("heureusement", "fortunately", "glücklicherweise", "afortunadamente", "adverbe", "A2"),
    ("en avant", "forward", "vorwärts", "adelante", "adverbe", "A2"),
    ("frais", "fresh", "frisch", "fresco", "adjectif", "A2"),
    ("le réfrigérateur", "fridge", "der Kühlschrank", "el refrigerador", "nom", "A2"),
    ("la grenouille", "frog", "der Frosch", "la rana", "nom", "A2"),
    ("les meubles", "furniture", "die Möbel", "los muebles", "nom", "A2"),
    ("plus loin", "further", "weiter", "más lejos", "adverbe", "A2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_a2_batch3.ps1", $new_words, $utf8NoBom)
