$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE G (A2) ---
    ("la galerie", "gallery", "die Galerie", "la galería", "nom", "A2"),
    ("l'écart / le trou", "gap", "die Lücke", "el hueco", "nom", "A2"),
    ("le gaz / l'essence", "gas", "das Gas / das Benzin", "el gas", "nom", "A2"),
    ("le portail", "gate", "das Tor", "la puerta", "nom", "A2"),
    ("général", "general", "allgemein", "general", "adjectif", "A2"),
    ("le cadeau", "gift", "das Geschenk", "el regalo", "nom", "A2"),
    ("le but", "goal", "das Ziel", "la meta", "nom", "A2"),
    ("la chèvre", "goat", "die Ziege", "la cabra", "nom", "A2"),
    ("le dieu", "god", "der Gott", "el dios", "nom", "A2"),
    ("l'or", "gold", "das Gold", "el oro", "nom", "A2"),
    ("le golf", "golf", "das Golf", "el golf", "nom", "A2"),
    ("le gouvernement", "government", "die Regierung", "el gobierno", "nom", "A2"),
    ("le raisin", "grape", "die Traube", "la uva", "nom", "A2"),
    ("l'herbe", "grass", "das Gras", "la hierba", "nom", "A2"),
    ("saluer", "greet", "grüßen", "saludar", "verbe", "A2"),
    ("le sol / la terre", "ground", "der Boden", "el suelo", "nom", "A2"),
    ("l'invité", "guest", "der Gast", "el invitado", "nom", "A2"),
    ("le guide", "guide", "der Führer", "el guía", "nom", "A2"),
    ("guider", "guide", "führen", "guiar", "verbe", "A2"),
    ("le pistolet", "gun", "die Waffe", "el arma", "nom", "A2"),
    ("le gars", "guy", "der Typ", "el chico", "nom", "A2"),

    # --- LETTRE H (A2) ---
    ("l'habitude", "habit", "die Gewohnheit", "el hábito", "nom", "A2"),
    ("la moitié", "half", "die Hälfte", "la mitad", "nom", "A2"),
    ("le hall / le couloir", "hall", "die Halle", "el pasillo", "nom", "A2"),
    ("joyeusement", "happily", "glücklich", "felizmente", "adverbe", "A2"),
    ("le mal de tête", "headache", "die Kopfschmerzen", "el dolor de cabeza", "nom", "A2"),
    ("le cœur", "heart", "das Herz", "el corazón", "nom", "A2"),
    ("la chaleur", "heat", "die Hitze", "el calor", "nom", "A2"),
    ("lourd", "heavy", "schwer", "pesado", "adjectif", "A2"),
    ("la taille / la hauteur", "height", "die Höhe", "la altura", "nom", "A2"),
    ("utile", "helpful", "hilfreich", "útil", "adjectif", "A2"),
    ("le héros", "hero", "der Held", "el héroe", "nom", "A2"),
    ("le sien / la sienne (à elle)", "hers", "ihrer", "suyo (de ella)", "pron", "A2"),
    ("elle-même", "herself", "sie selbst", "ella misma", "pron", "A2"),
    ("cacher", "hide", "verstecken", "esconder", "verbe", "A2"),
    ("haut", "high", "hoch", "alto", "adjectif", "A2"),
    ("la colline", "hill", "der Hügel", "la colina", "nom", "A2"),
    ("lui-même", "himself", "er selbst", "él mismo", "pron", "A2"),
    ("le sien (à lui)", "his", "sein", "suyo (de él)", "pron", "A2"),
    ("le coup", "hit", "der Schlag", "el golpe", "nom", "A2"),
    ("frapper", "hit", "schlagen", "golpear", "verbe", "A2"),
    ("le hockey", "hockey", "das Hockey", "el hockey", "nom", "A2"),
    ("tenir", "hold", "halten", "sostener", "verbe", "A2"),
    ("le trou", "hole", "das Loch", "el agujero", "nom", "A2"),
    ("l'espoir", "hope", "die Hoffnung", "la esperanza", "nom", "A2"),
    ("la corne / le klaxon", "horn", "das Horn", "el cuerno", "nom", "A2"),
    ("immense", "huge", "riesig", "enorme", "adjectif", "A2"),
    ("humain", "human", "menschlich", "humano", "adjectif", "A2"),
    ("se dépêcher", "hurry", "sich beeilen", "apurarse", "verbe", "A2"),
    ("la hâte", "hurry", "die Eile", "la prisa", "nom", "A2"),
    ("blesser / faire mal", "hurt", "verletzen", "doler", "verbe", "A2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_a2_batch4.ps1", $new_words, $utf8NoBom)
