$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE S (A2) ---
    ("malheureusement", "sadly", "leider", "tristemente", "adverbe", "A2"),
    ("sûr / en sécurité", "safe", "sicher", "seguro", "adjectif", "A2"),
    ("la voile", "sail", "das Segel", "la vela", "nom", "A2"),
    ("naviguer", "sail", "segeln", "navegar", "verbe", "A2"),
    ("la voile (sport)", "sailing", "das Segeln", "la navegación", "nom", "A2"),
    ("le salaire", "salary", "das Gehalt", "el salario", "nom", "A2"),
    ("la vente", "sale", "der Verkauf", "la venta", "nom", "A2"),
    ("la sauce", "sauce", "die Soße", "la salsa", "nom", "A2"),
    ("sauver / économiser", "save", "sparen / retten", "guardar / salvar", "verbe", "A2"),
    ("effrayé", "scared", "verängstigt", "asustado", "adjectif", "A2"),
    ("l'écharpe", "scarf", "der Schal", "la bufanda", "nom", "A2"),
    ("effrayant", "scary", "gruselig", "aterrador", "adjectif", "A2"),
    ("la scène", "scene", "die Szene", "la escena", "nom", "A2"),
    ("le programme / l'emploi du temps", "schedule", "der Zeitplan", "el horario", "nom", "A2"),
    ("le score", "score", "das Ergebnis", "el puntaje", "nom", "A2"),
    ("marquer un point", "score", "punkten", "marcar (puntos)", "verbe", "A2"),
    ("l'écran", "screen", "der Bildschirm", "la pantalla", "nom", "A2"),
    ("la recherche", "search", "die Suche", "la búsqueda", "nom", "A2"),
    ("chercher", "search", "suchen", "buscar", "verbe", "A2"),
    ("la saison", "season", "die Jahreszeit", "la temporada", "nom", "A2"),
    ("le siège", "seat", "der Sitz", "el asiento", "nom", "A2"),
    ("deuxième", "second", "zweite", "segundo", "adjectif", "A2"),
    ("deuxièmement", "secondly", "zweitens", "en segundo lugar", "adverbe", "A2"),
    ("le secret", "secret", "das Geheimnis", "el secreto", "nom", "A2"),
    ("le secrétaire", "secretary", "der Sekretär", "el secretario", "nom", "A2"),
    ("sembler", "seem", "scheinen", "parecer", "verbe", "A2"),
    ("vendre", "sell", "verkaufen", "vender", "verbe", "A2"),
    ("le sens", "sense", "der Sinn", "el sentido", "nom", "A2"),
    ("séparé", "separate", "getrennt", "separado", "adjectif", "A2"),
    ("la série", "series", "die Serie", "la serie", "nom", "A2"),
    ("sérieux", "serious", "ernst", "serio", "adjectif", "A2"),
    ("servir", "serve", "servieren", "servir", "verbe", "A2"),
    ("le service", "service", "der Service", "el servicio", "nom", "A2"),
    ("plusieurs", "several", "mehrere", "varios", "adverbe", "A2"),
    ("secouer", "shake", "schütteln", "agitar", "verbe", "A2"),
    ("devoir (auxiliaire)", "shall", "sollen", "deber", "verbe", "A2"),
    ("partager", "share", "teilen", "compartir", "verbe", "A2"),
    ("la forme", "shape", "die Form", "la forma", "nom", "A2"),
    ("la feuille", "sheet", "das Blatt", "la hoja", "nom", "A2"),
    ("le navire", "ship", "das Schiff", "el barco", "nom", "A2"),
    ("l'épaule", "shoulder", "die Schulter", "el hombro", "nom", "A2"),
    ("crier", "shout", "schreien", "gritar", "verbe", "A2"),
    ("fermer", "shut", "schließen", "cerrar", "verbe", "A2"),
    ("le côté", "side", "die Seite", "el lado", "nom", "A2"),
    ("le signe / le panneau", "sign", "das Schild", "la señal", "nom", "A2"),
    ("l'argent (métal)", "silver", "das Silber", "la plata", "nom", "A2"),
    ("similaire", "similar", "ähnlich", "similar", "adjectif", "A2"),
    ("simple", "simple", "einfach", "simple", "adjectif", "A2"),
    ("depuis", "since", "seit", "desde", "prep", "A2"),
    ("le chant", "singing", "der Gesang", "el canto", "nom", "A2"),
    ("célibataire / unique", "single", "ledig / einzeln", "soltero / solo", "adjectif", "A2"),
    ("monsieur", "sir", "mein Herr", "señor", "nom", "A2"),
    ("le site", "site", "der Standort", "el sitio", "nom", "A2"),
    ("la taille", "size", "die Größe", "el tamaño", "nom", "A2"),
    ("le ski", "ski", "der Ski", "el esquí", "nom", "A2"),
    ("skier", "ski", "Ski fahren", "esquiar", "verbe", "A2"),
    ("le ski (sport)", "skiing", "das Skifahren", "el esquí", "nom", "A2"),
    ("la peau", "skin", "die Haut", "la piel", "nom", "A2"),
    ("le ciel", "sky", "der Himmel", "el cielo", "nom", "A2"),
    ("lentement", "slowly", "langsam", "lentamente", "adverbe", "A2"),
    ("le smartphone", "smartphone", "das Smartphone", "el teléfono inteligente", "nom", "A2"),
    ("l'odeur", "smell", "der Geruch", "el olor", "nom", "A2"),
    ("sentir", "smell", "riechen", "oler", "verbe", "A2"),
    ("le sourire", "smile", "das Lächeln", "la sonrisa", "nom", "A2"),
    ("sourire", "smile", "lächeln", "sonreír", "verbe", "A2"),
    ("la fumée", "smoke", "der Rauch", "el humo", "nom", "A2"),
    ("fumer", "smoke", "rauchen", "fumar", "verbe", "A2"),
    ("le tabagisme", "smoking", "das Rauchen", "fumar", "nom", "A2"),
    ("le savon", "soap", "die Seife", "el jabón", "nom", "A2"),
    ("le football", "soccer", "der Fußball", "el fútbol", "nom", "A2"),
    ("social", "social", "sozial", "social", "adjectif", "A2"),
    ("la chaussette", "sock", "die Socke", "el calcetín", "nom", "A2"),
    ("doux / mou", "soft", "weich", "suave", "adjectif", "A2"),
    ("le soldat", "soldier", "der Soldat", "el soldado", "nom", "A2"),
    ("la solution", "solution", "die Lösung", "la solución", "nom", "A2"),
    ("quelque part", "somewhere", "irgendwo", "en algún lugar", "adverbe", "A2"),
    ("la sorte", "sort", "die Art", "el tipo", "nom", "A2"),
    ("l'orateur / le haut-parleur", "speaker", "der Sprecher", "el altavoz / el orador", "nom", "A2"),
    ("spécifique", "specific", "spezifisch", "específico", "adjectif", "A2"),
    ("le discours", "speech", "die Rede", "el discurso", "nom", "A2"),
    ("la vitesse", "speed", "die Geschwindigkeit", "la velocidad", "nom", "A2"),
    ("l'araignée", "spider", "die Spinne", "la araña", "nom", "A2"),
    ("la cuillère", "spoon", "der Löffel", "la cuchara", "nom", "A2"),
    ("le carré / la place", "square", "das Quadrat / der Platz", "el cuadrado / la plaza", "nom", "A2"),
    ("l'écureuil", "squirrel", "das Eichhörnchen", "la ardilla", "nom", "A2"),
    ("la scène (théâtre)", "stage", "die Bühne", "el escenario", "nom", "A2"),
    ("l'escalier", "stair", "die Treppe", "la escalera", "nom", "A2"),
    ("le timbre", "stamp", "die Briefmarke", "el sello", "nom", "A2"),
    ("l'étoile", "star", "der Stern", "la estrella", "nom", "A2"),
    ("l'état", "state", "der Staat", "el estado", "nom", "A2"),
    ("la déclaration", "statement", "die Aussage", "la declaración", "nom", "A2"),
    ("rester", "stay", "bleiben", "quedarse", "verbe", "A2"),
    ("voler (dérober)", "steal", "stehlen", "robar", "verbe", "A2"),
    ("le pas / l'étape", "step", "der Schritt", "el paso", "nom", "A2"),
    ("marcher / faire un pas", "step", "treten", "dar un paso", "verbe", "A2"),
    ("encore / toujours", "still", "noch", "todavía", "adverbe", "A2"),
    ("l'estomac", "stomach", "der Magen", "el estómago", "nom", "A2"),
    ("la pierre", "stone", "der Stein", "la piedra", "nom", "A2"),
    ("le magasin", "store", "das Geschäft", "la tienda", "nom", "A2"),
    ("la tempête", "storm", "der Sturm", "la tormenta", "nom", "A2"),
    ("droit", "straight", "gerade", "recto", "adjectif", "A2"),
    ("étrange", "strange", "seltsam", "extraño", "adjectif", "A2"),
    ("la fraise", "strawberry", "die Erdbeere", "la fresa", "nom", "A2"),
    ("le stress", "stress", "der Stress", "el estrés", "nom", "A2"),
    ("stupide", "stupid", "dumm", "estúpido", "adjectif", "A2"),
    ("réussir", "succeed", "Erfolg haben", "tener éxito", "verbe", "A2"),
    ("couronné de succès", "successful", "erfolgreich", "exitoso", "adjectif", "A2"),
    ("tel", "such", "solcher", "tal", "adjectif", "A2"),
    ("soudainement", "suddenly", "plötzlich", "de repente", "adverbe", "A2"),
    ("suggérer", "suggest", "vorschlagen", "sugerir", "verbe", "A2"),
    ("la suggestion", "suggestion", "der Vorschlag", "la sugerencia", "nom", "A2"),
    ("le costume", "suit", "der Anzug", "el traje", "nom", "A2"),
    ("le soutien", "support", "die Unterstützung", "el apoyo", "nom", "A2"),
    ("soutenir", "support", "unterstützen", "apoyar", "verbe", "A2"),
    ("supposer", "suppose", "annehmen", "suponer", "verbe", "A2"),
    ("la surprise", "surprise", "die Überraschung", "la sorpresa", "nom", "A2"),
    ("surprendre", "surprise", "überraschen", "sorprender", "verbe", "A2"),
    ("surpris", "surprised", "überrascht", "sorprendido", "adjectif", "A2"),
    ("surprenant", "surprising", "überraschend", "sorprendente", "adjectif", "A2"),
    ("doux / sucré", "sweet", "süß", "dulce", "adjectif", "A2"),
    ("la balançoire", "swing", "die Schaukel", "el columpio", "nom", "A2"),
    ("se balancer", "swing", "schaukeln", "balancearse", "verbe", "A2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_a2_batch7.ps1", $new_words, $utf8NoBom)
