$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE C (partie 2) (B2) ---
    ("le commandant", "commander", "der Kommandant", "el comandante", "nom", "B2"),
    ("la commission", "commission", "die Kommission", "la comisión", "nom", "B2"),
    ("l'engagement", "commitment", "das Engagement", "el compromiso", "nom", "B2"),
    ("le comité", "committee", "das Komitee", "el comité", "nom", "B2"),
    ("communément", "commonly", "gewöhnlich", "comúnmente", "adverbe", "B2"),
    ("comparatif", "comparative", "vergleichend", "comparativo", "adjectif", "B2"),
    ("l'achèvement", "completion", "der Abschluss", "la finalización", "nom", "B2"),
    ("compliqué", "complicated", "kompliziert", "complicado", "adjectif", "B2"),
    ("le composant", "component", "die Komponente", "el componente", "nom", "B2"),
    ("composer", "compose", "komponieren", "componer", "verbe", "B2"),
    ("le compositeur", "composer", "der Komponist", "el compositor", "nom", "B2"),
    ("le composé / l'enceinte", "compound", "die Verbindung", "el compuesto", "nom", "B2"),
    ("complet / exhaustif", "comprehensive", "umfassend", "exhaustivo", "adjectif", "B2"),
    ("obligatoire", "compulsory", "verpflichtend", "obligatorio", "adjectif", "B2"),
    ("la concentration", "concentration", "die Konzentration", "la concentración", "nom", "B2"),
    ("le concept", "concept", "das Konzept", "el concepto", "nom", "B2"),
    ("la préoccupation / le souci", "concern", "die Sorge", "la preocupación", "nom", "B2"),
    ("concerner", "concern", "betreffen", "concernir", "verbe", "B2"),
    ("concerné / inquiet", "concerned", "besorgt", "preocupado", "adjectif", "B2"),
    ("la conclusion", "conclusion", "die Schlussfolgerung", "la conclusión", "nom", "B2"),
    ("le béton / concret", "concrete", "der Beton", "el hormigón / concreto", "nom", "B2"),
    ("mener / conduire", "conduct", "durchführen", "conducir", "verbe", "B2"),
    ("avouer", "confess", "gestehen", "confesar", "verbe", "B2"),
    ("la confiance", "confidence", "das Vertrauen", "la confianza", "nom", "B2"),
    ("le conflit", "conflict", "der Konflikt", "el conflicto", "nom", "B2"),
    ("déroutant", "confusing", "verwirrend", "confuso", "adjectif", "B2"),
    ("la confusion", "confusion", "die Verwirrung", "la confusión", "nom", "B2"),
    ("conscient", "conscious", "bewusst", "consciente", "adjectif", "B2"),
    ("la conséquence", "consequence", "die Konsequenz", "la consecuencia", "nom", "B2"),
    ("par conséquent", "consequently", "folglich", "en consecuencia", "adverbe", "B2"),
    ("la conservation", "conservation", "die Erhaltung", "la conservación", "nom", "B2"),
    ("conservateur", "conservative", "konservativ", "conservador", "adjectif", "B2"),
    ("considérable", "considerable", "erheblich", "considerable", "adjectif", "B2"),
    ("considérablement", "considerably", "erheblich", "considerablemente", "adverbe", "B2"),
    ("la considération", "consideration", "die Überlegung", "la consideración", "nom", "B2"),
    ("consister en", "consist of", "bestehen aus", "consistir en", "verbe", "B2"),
    ("cohérent / constant", "consistent", "konsequent", "coherente", "adjectif", "B2"),
    ("régulièrement / constamment", "consistently", "konsequent", "consistentemente", "adverbe", "B2"),
    ("la conspiration", "conspiracy", "die Verschwörung", "la conspiración", "nom", "B2"),
    ("constant", "constant", "konstant", "constante", "adjectif", "B2"),
    ("constamment", "constantly", "ständig", "constantemente", "adverbe", "B2"),
    ("construire", "construct", "konstruieren", "construir", "verbe", "B2"),
    ("la construction", "construction", "die Konstruktion", "la construcción", "nom", "B2"),
    ("consulter", "consult", "konsultieren", "consultar", "verbe", "B2"),
    ("le consultant", "consultant", "der Berater", "el consultor", "nom", "B2"),
    ("le consommateur", "consumer", "der Verbraucher", "el consumidor", "nom", "B2"),
    ("la consommation", "consumption", "der Verbrauch", "el consumo", "nom", "B2"),
    ("contemporain", "contemporary", "zeitgenössisch", "contemporáneo", "adjectif", "B2"),
    ("le concours / la compétition", "contest", "der Wettbewerb", "el concurso", "nom", "B2"),
    ("le contexte", "context", "der Kontext", "el contexto", "nom", "B2"),
    ("le contrat", "contract", "der Vertrag", "el contrato", "nom", "B2"),
    ("contribuer", "contribute", "beitragen", "contribuir", "verbe", "B2"),
    ("la contribution", "contribution", "der Beitrag", "la contribución", "nom", "B2"),
    ("controversé", "controversial", "umstritten", "controvertido", "adjectif", "B2"),
    ("la controverse", "controversy", "die Kontroverse", "la controversia", "nom", "B2"),
    ("la commodité", "convenience", "die Bequemlichkeit", "la conveniencia", "nom", "B2"),
    ("la convention", "convention", "die Konvention", "la convención", "nom", "B2"),
    ("conventionnel", "conventional", "konventionell", "convencional", "adjectif", "B2"),
    ("convertir", "convert", "konvertieren", "convertir", "verbe", "B2"),
    ("transmettre", "convey", "vermitteln", "transmitir", "verbe", "B2"),
    ("convaincu", "convinced", "überzeugt", "convencido", "adjectif", "B2"),
    ("convaincant", "convincing", "überzeugend", "convincente", "adjectif", "B2"),
    ("faire face (à une difficulté)", "cope", "bewältigen", "hacer frente", "verbe", "B2"),
    ("le noyau / le centre", "core", "der Kern", "el núcleo", "nom", "B2"),
    ("d'entreprise", "corporate", "Unternehmens-", "corporativo", "adjectif", "B2"),
    ("la société (entreprise)", "corporation", "das Unternehmen", "la corporación", "nom", "B2"),
    ("le couloir", "corridor", "der Flur", "el pasillo", "nom", "B2"),
    ("le conseil", "council", "der Rat", "el consejo", "nom", "B2"),
    ("le comptoir / le plan de travail", "counter", "die Theke", "el mostrador", "nom", "B2"),
    ("le comté", "county", "der Landkreis", "el condado", "nom", "B2"),
    ("le courage", "courage", "der Mut", "el coraje", "nom", "B2"),
    ("la couverture (médiatique / réseau)", "coverage", "die Berichterstattung", "la cobertura", "nom", "B2"),
    ("le cow-boy", "cowboy", "der Cowboy", "el vaquero", "nom", "B2"),
    ("craquer / fendre", "crack", "knacken", "agrietar", "verbe", "B2"),
    ("le crash / l'accident", "crash", "der Absturz", "el choque", "nom", "B2"),
    ("s'écraser", "crash", "abstürzen", "chocar", "verbe", "B2"),
    ("la création", "creation", "die Kreation", "la creación", "nom", "B2"),
    ("la créativité", "creativity", "die Kreativität", "la creatividad", "nom", "B2"),
    ("la créature", "creature", "die Kreatur", "la criatura", "nom", "B2"),
    ("l'équipage", "crew", "die Besatzung", "la tripulación", "nom", "B2"),
    ("la crise", "crisis", "die Krise", "la crisis", "nom", "B2"),
    ("le critique", "critic", "der Kritiker", "el crítico", "nom", "B2"),
    ("critique", "critical", "kritisch", "crítico", "adjectif", "B2"),
    ("gravement / d'un œil critique", "critically", "kritisch", "críticamente", "adverbe", "B2"),
    ("la critique", "criticism", "die Kritik", "la crítica", "nom", "B2"),
    ("critiquer", "criticise", "kritisieren", "criticar", "verbe", "B2"),
    ("la culture (agricole)", "crop", "die Ernte", "la cosecha", "nom", "B2"),
    ("crucial", "crucial", "entscheidend", "crucial", "adjectif", "B2"),
    ("la croisière", "cruise", "die Kreuzfahrt", "el crucero", "nom", "B2"),
    ("le signal / la réplique", "cue", "das Stichwort", "la señal", "nom", "B2"),
    ("le remède", "cure", "das Heilmittel", "la cura", "nom", "B2"),
    ("guérir", "cure", "heilen", "curar", "verbe", "B2"),
    ("curieux", "curious", "neugierig", "curioso", "adjectif", "B2"),
    ("le programme d'études", "curriculum", "der Lehrplan", "el plan de estudios", "nom", "B2"),
    ("la courbe", "curve", "die Kurve", "la curva", "nom", "B2"),
    ("courber", "curve", "biegen", "curvar", "verbe", "B2"),
    ("courbe (adj)", "curved", "gebogen", "curvado", "adjectif", "B2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b2_batch4.ps1", $new_words, $utf8NoBom)
