$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE A (B1) ---
    ("absolument", "absolutely", "absolut", "absolutamente", "adverbe", "B1"),
    ("académique / universitaire", "academic", "akademisch", "académico", "adjectif", "B1"),
    ("l'accès", "access", "der Zugang", "el acceso", "nom", "B1"),
    ("accéder", "access", "zugreifen", "acceder", "verbe", "B1"),
    ("le logement", "accommodation", "die Unterkunft", "el alojamiento", "nom", "B1"),
    ("le compte", "account", "das Konto / der Bericht", "la cuenta", "nom", "B1"),
    ("selon", "according to", "laut / nach", "según", "prep", "B1"),
    ("l'accomplissement", "achievement", "die Leistung", "el logro", "nom", "B1"),
    ("l'annonce / la publicité", "ad", "die Anzeige", "el anuncio", "nom", "B1"),
    ("l'addition / l'ajout", "addition", "die Ergänzung / der Zusatz", "la adición", "nom", "B1"),
    ("admirer", "admire", "bewundern", "admirar", "verbe", "B1"),
    ("admettre", "admit", "zugeben", "admitir", "verbe", "B1"),
    ("avancé", "advanced", "fortgeschritten", "avanzado", "adjectif", "B1"),
    ("conseiller", "advise", "raten", "aconsejar", "verbe", "B1"),
    ("avoir les moyens de", "afford", "sich leisten", "permitirse", "verbe", "B1"),
    ("âgé", "aged", "gealtert", "envejecido", "adjectif", "B1"),
    ("l'agent", "agent", "der Agent", "el agente", "nom", "B1"),
    ("l'accord", "agreement", "die Vereinbarung", "el acuerdo", "nom", "B1"),
    ("en avant / devant", "ahead", "voraus", "adelante", "adverbe", "B1"),
    ("le but", "aim", "das Ziel", "el objetivo", "nom", "B1"),
    ("viser", "aim", "zielen", "apuntar", "verbe", "B1"),
    ("l'alarme", "alarm", "der Alarm", "la alarma", "nom", "B1"),
    ("l'album", "album", "das Album", "el álbum", "nom", "B1"),
    ("l'alcool", "alcohol", "der Alkohol", "el alcohol", "nom", "B1"),
    ("alcoolique", "alcoholic", "alkoholisch", "alcohólico", "adjectif", "B1"),
    ("l'alternative", "alternative", "die Alternative", "la alternativa", "nom", "B1"),
    ("émerveillé", "amazed", "erstaunt", "asombrado", "adjectif", "B1"),
    ("l'ambition", "ambition", "die Ambition", "la ambición", "nom", "B1"),
    ("ambitieux", "ambitious", "ehrgeizig", "ambicioso", "adjectif", "B1"),
    ("annoncer", "announce", "ankündigen", "anunciar", "verbe", "B1"),
    ("l'annonce", "announcement", "die Ankündigung", "el anuncio", "nom", "B1"),
    ("agacer", "annoy", "ärgern", "molestar", "verbe", "B1"),
    ("agacé", "annoyed", "verärgert", "molesto", "adjectif", "B1"),
    ("agaçant", "annoying", "ärgerlich", "molesto", "adjectif", "B1"),
    ("à part / séparé", "apart", "auseinander", "aparte", "adverbe", "B1"),
    ("s'excuser", "apologise", "sich entschuldigen", "disculparse", "verbe", "B1"),
    ("la candidature / la demande", "application", "die Bewerbung", "la solicitud", "nom", "B1"),
    ("le rendez-vous", "appointment", "der Termin", "la cita", "nom", "B1"),
    ("apprécier", "appreciate", "schätzen", "apreciar", "verbe", "B1"),
    ("approximativement", "approximately", "ungefähr", "aproximadamente", "adverbe", "B1"),
    ("arrêter (police)", "arrest", "verhaften", "arrestar", "verbe", "B1"),
    ("l'arrivée", "arrival", "die Ankunft", "la llegada", "nom", "B1"),
    ("le devoir / la mission", "assignment", "die Aufgabe", "la asignación", "nom", "B1"),
    ("assister / aider", "assist", "helfen", "asistir", "verbe", "B1"),
    ("l'atmosphère", "atmosphere", "die Atmosphäre", "la atmósfera", "nom", "B1"),
    ("attacher / joindre", "attach", "anhängen", "adjuntar", "verbe", "B1"),
    ("l'attitude", "attitude", "die Einstellung", "la actitud", "nom", "B1"),
    ("attirer", "attract", "anziehen", "atraer", "verbe", "B1"),
    ("l'attraction", "attraction", "die Attraktion", "la atracción", "nom", "B1"),
    ("l'autorité", "authority", "die Behörde", "la autoridad", "nom", "B1"),
    ("la moyenne", "average", "der Durchschnitt", "el promedio", "nom", "B1"),
    ("décerner un prix", "award", "verleihen", "premiar", "verbe", "B1"),
    ("conscient", "aware", "bewusst", "consciente", "adjectif", "B1"),

    # --- LETTRE B (B1) ---
    ("en arrière", "backwards", "rückwärts", "hacia atrás", "adverbe", "B1"),
    ("cuisiner (au four)", "bake", "backen", "hornear", "verbe", "B1"),
    ("l'équilibre", "balance", "das Gleichgewicht", "el equilibrio", "nom", "B1"),
    ("équilibrer", "balance", "ausgleichen", "equilibrar", "verbe", "B1"),
    ("l'interdiction", "ban", "das Verbot", "la prohibición", "nom", "B1"),
    ("interdire", "ban", "verbieten", "prohibir", "verbe", "B1"),
    ("la rive (d'une rivière)", "bank", "das Ufer", "la orilla", "nom", "B1"),
    ("la base", "base", "die Basis", "la base", "nom", "B1"),
    ("baser", "base", "basieren", "basar", "verbe", "B1"),
    ("basique / fondamental", "basic", "grundlegend", "básico", "adjectif", "B1"),
    ("la batterie", "battery", "die Batterie", "la batería", "nom", "B1"),
    ("la bataille", "battle", "die Schlacht", "la batalla", "nom", "B1"),
    ("la beauté", "beauty", "die Schönheit", "la belleza", "nom", "B1"),
    ("l'abeille", "bee", "die Biene", "la abeja", "nom", "B1"),
    ("le comportement", "behaviour", "das Verhalten", "el comportamiento", "nom", "B1"),
    ("la croyance", "belief", "der Glaube", "la creencia", "nom", "B1"),
    ("la cloche / la sonnette", "bell", "die Glocke", "la campana", "nom", "B1"),
    ("plier / se pencher", "bend", "biegen", "doblar", "verbe", "B1"),
    ("bénéficier", "benefit", "profitieren", "beneficiarse", "verbe", "B1"),
    ("mordre", "bite", "beißen", "morder", "verbe", "B1"),
    ("le bloc", "block", "der Block", "el bloque", "nom", "B1"),
    ("bloquer", "block", "blockieren", "bloquear", "verbe", "B1"),
    ("embarquer", "board", "einsteigen", "abordar", "verbe", "B1"),
    ("la bombe", "bomb", "die Bombe", "la bomba", "nom", "B1"),
    ("bombarder", "bomb", "bombardieren", "bombardear", "verbe", "B1"),
    ("la réservation", "booking", "die Buchung", "la reserva", "nom", "B1"),
    ("la frontière", "border", "die Grenze", "la frontera", "nom", "B1"),
    ("déranger", "bother", "belästigen / stören", "molestar", "verbe", "B1"),
    ("la branche / la succursale", "branch", "der Zweig", "la rama / sucursal", "nom", "B1"),
    ("la marque", "brand", "die Marke", "la marca", "nom", "B1"),
    ("courageux", "brave", "mutig", "valiente", "adjectif", "B1"),
    ("la respiration / le souffle", "breath", "der Atem", "la respiración", "nom", "B1"),
    ("respirer", "breathe", "atmen", "respirar", "verbe", "B1"),
    ("la respiration (action)", "breathing", "die Atmung", "la respiración", "nom", "B1"),
    ("la mariée", "bride", "die Braut", "la novia", "nom", "B1"),
    ("la bulle", "bubble", "die Blase", "la burbuja", "nom", "B1"),
    ("éclater", "burst", "platzen", "estallar", "verbe", "B1"),
    ("enterrer", "bury", "begraben", "enterrar", "verbe", "B1")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b1_batch1.ps1", $new_words, $utf8NoBom)
