$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE N (B1) ---
    ("l'ongle / le clou", "nail", "der Nagel", "la uña / el clavo", "nom", "B1"),
    ("le récit", "narrative", "die Erzählung", "la narrativa", "nom", "B1"),
    ("la nation", "nation", "die Nation", "la nación", "nom", "B1"),
    ("natif / indigène", "native", "einheimisch", "nativo", "adjectif", "B1"),
    ("naturellement", "naturally", "natürlich", "naturalmente", "adverbe", "B1"),
    ("nécessairement", "necessarily", "notwendigerweise", "necesariamente", "adverbe", "B1"),
    ("l'aiguille", "needle", "die Nadel", "la aguja", "nom", "B1"),
    ("négatif", "negative", "negativ", "negativo", "adjectif", "B1"),
    ("le quartier", "neighbourhood", "die Nachbarschaft", "el barrio", "nom", "B1"),
    ("ni l'un ni l'autre", "neither", "weder", "tampoco", "conjonction", "B1"),
    ("ni", "nor", "noch", "ni", "conjonction", "B1"),
    ("normal", "normal", "normal", "normal", "adjectif", "B1"),
    ("du nord", "northern", "nördlich", "del norte", "adjectif", "B1"),
    ("noter", "note", "notieren", "anotar", "verbe", "B1"),
    ("nucléaire", "nuclear", "nuklear", "nuclear", "adjectif", "B1"),

    # --- LETTRE O (B1) ---
    ("évident", "obvious", "offensichtlich", "obvio", "adjectif", "B1"),
    ("évidemment", "obviously", "offensichtlich", "obviamente", "adverbe", "B1"),
    ("l'occasion", "occasion", "die Gelegenheit", "la ocasión", "nom", "B1"),
    ("se produire", "occur", "auftreten", "ocurrir", "verbe", "B1"),
    ("étrange / impair", "odd", "seltsam / ungerade", "extraño / impar", "adjectif", "B1"),
    ("officiel", "official", "offiziell", "oficial", "adjectif", "B1"),
    ("démodé", "old-fashioned", "altmodisch", "anticuado", "adjectif", "B1"),
    ("une fois que", "once", "sobald", "una vez que", "conjonction", "B1"),
    ("l'opinion", "opinion", "die Meinung", "la opinión", "nom", "B1"),
    ("l'opération", "operation", "der Betrieb / die Operation", "la operación", "nom", "B1"),
    ("l'opportunité", "opportunity", "die Gelegenheit", "la oportunidad", "nom", "B1"),
    ("organisé", "organised", "organisiert", "organizado", "adjectif", "B1"),
    ("l'organisateur", "organiser", "der Organisator", "el organizador", "nom", "B1"),
    ("original", "original", "originell", "original", "adjectif", "B1"),
    ("à l'origine", "originally", "ursprünglich", "originalmente", "adverbe", "B1"),
    ("devrait", "ought to", "sollte", "debería", "verbe", "B1"),
    ("le nôtre", "ours", "unsere", "nuestro", "pron", "B1"),
    ("en plein air (adj)", "outdoor", "im Freien", "al aire libre", "adjectif", "B1"),
    ("en plein air (adv)", "outdoors", "draußen", "afuera", "adverbe", "B1"),

    # --- LETTRE P (B1) ---
    ("le colis", "package", "das Paket", "el paquete", "nom", "B1"),
    ("le bloc-notes / la compresse", "pad", "der Block", "la almohadilla", "nom", "B1"),
    ("douloureux", "painful", "schmerzhaft", "doloroso", "adjectif", "B1"),
    ("pâle", "pale", "blass", "pálido", "adjectif", "B1"),
    ("la casserole / la poêle", "pan", "die Pfanne", "la sartén", "nom", "B1"),
    ("participer", "participate", "teilnehmen", "participar", "verbe", "B1"),
    ("particulièrement", "particularly", "besonders", "particularmente", "adverbe", "B1"),
    ("la passion", "passion", "die Leidenschaft", "la pasión", "nom", "B1"),
    ("le chemin", "path", "der Weg", "el camino", "nom", "B1"),
    ("le paiement", "payment", "die Zahlung", "el pago", "nom", "B1"),
    ("paisible", "peaceful", "friedlich", "pacífico", "adjectif", "B1"),
    ("le pourcentage", "percentage", "der Prozentsatz", "el porcentaje", "nom", "B1"),
    ("parfaitement", "perfectly", "perfekt", "perfectamente", "adverbe", "B1"),
    ("la performance", "performance", "die Leistung", "el rendimiento", "nom", "B1"),
    ("personnellement", "personally", "persönlich", "personalmente", "adverbe", "B1"),
    ("pessimiste", "pessimistic", "pessimistisch", "pesimista", "adjectif", "B1"),
    ("persuader", "persuade", "überreden", "persuadir", "verbe", "B1"),
    ("le photographe", "photographer", "der Fotograf", "el fotógrafo", "nom", "B1"),
    ("la photographie (art)", "photography", "die Fotografie", "la fotografía", "nom", "B1"),
    ("l'épingle", "pin", "die Nadel", "el alfiler", "nom", "B1"),
    ("épingler", "pin", "anstecken", "fijar (con alfiler)", "verbe", "B1"),
    ("le tuyau", "pipe", "das Rohr", "la tubería", "nom", "B1"),
    ("la planification", "planning", "die Planung", "la planificación", "nom", "B1"),
    ("agréable", "pleasant", "angenehm", "agradable", "adjectif", "B1"),
    ("le plaisir", "pleasure", "das Vergnügen", "el placer", "nom", "B1"),
    ("beaucoup / plein de", "plenty", "viel", "mucho", "pron", "B1"),
    ("l'intrigue (histoire)", "plot", "die Handlung", "la trama", "nom", "B1"),
    ("plus", "plus", "plus", "más", "prep", "B1"),
    ("le poème", "poem", "das Gedicht", "el poema", "nom", "B1"),
    ("le poète", "poet", "der Dichter", "el poeta", "nom", "B1"),
    ("la poésie", "poetry", "die Poesie", "la poesía", "nom", "B1"),
    ("pointer / indiquer", "point", "zeigen", "señalar", "verbe", "B1"),
    ("le poison", "poison", "das Gift", "el veneno", "nom", "B1"),
    ("empoisonner", "poison", "vergiften", "envenenar", "verbe", "B1"),
    ("vénéneux", "poisonous", "giftig", "venenoso", "adjectif", "B1"),
    ("la politique (règle)", "policy", "die Richtlinie", "la política", "nom", "B1"),
    ("politique", "political", "politisch", "político", "adjectif", "B1"),
    ("le politicien", "politician", "der Politiker", "el político", "nom", "B1"),
    ("la politique (domaine)", "politics", "die Politik", "la política", "nom", "B1"),
    ("le port", "port", "der Hafen", "el puerto", "nom", "B1"),
    ("le portrait", "portrait", "das Porträt", "el retrato", "nom", "B1"),
    ("la position", "position", "die Position", "la posición", "nom", "B1"),
    ("positif", "positive", "positiv", "positivo", "adjectif", "B1"),
    ("probablement", "possibly", "möglicherweise", "posiblemente", "adverbe", "B1"),
    ("le pot", "pot", "der Topf", "la olla", "nom", "B1"),
    ("verser", "pour", "gießen", "verter", "verbe", "B1"),
    ("la pauvreté", "poverty", "die Armut", "la pobreza", "nom", "B1"),
    ("la poudre", "powder", "das Pulver", "el polvo", "nom", "B1"),
    ("le pouvoir / l'électricité", "power", "die Macht / der Strom", "el poder", "nom", "B1"),
    ("puissant", "powerful", "mächtig", "poderoso", "adjectif", "B1"),
    ("pratique", "practical", "praktisch", "práctico", "adjectif", "B1"),
    ("prier", "pray", "beten", "rezar", "verbe", "B1"),
    ("la prière", "prayer", "das Gebet", "la oración", "nom", "B1"),
    ("la prédiction", "prediction", "die Vorhersage", "la predicción", "nom", "B1"),
    ("préparé", "prepared", "vorbereitet", "preparado", "adjectif", "B1"),
    ("la présentation", "presentation", "die Präsentation", "la presentación", "nom", "B1"),
    ("la presse", "press", "die Presse", "la prensa", "nom", "B1"),
    ("la pression", "pressure", "der Druck", "la presión", "nom", "B1"),
    ("prétendre / faire semblant", "pretend", "so tun als ob", "fingir", "verbe", "B1"),
    ("précédent", "previous", "vorherig", "anterior", "adjectif", "B1"),
    ("précédemment", "previously", "zuvor", "previamente", "adverbe", "B1"),
    ("le prêtre", "priest", "der Priester", "el sacerdote", "nom", "B1"),
    ("primaire / principal", "primary", "primär", "primario", "adjectif", "B1"),
    ("le prince", "prince", "der Prinz", "el príncipe", "nom", "B1"),
    ("la princesse", "princess", "die Prinzessin", "la princesa", "nom", "B1"),
    ("l'impression", "printing", "das Drucken", "la impresión", "nom", "B1"),
    ("le prisonnier", "prisoner", "der Gefangene", "el prisionero", "nom", "B1"),
    ("privé", "private", "privat", "privado", "adjectif", "B1"),
    ("probablement", "probably", "wahrscheinlich", "probablemente", "adverbe", "B1"),
    ("le processus", "process", "der Prozess", "el proceso", "nom", "B1"),
    ("produire", "produce", "produzieren", "producir", "verbe", "B1"),
    ("le producteur", "producer", "der Produzent", "el productor", "nom", "B1"),
    ("le produit", "product", "das Produkt", "el producto", "nom", "B1"),
    ("la production", "production", "die Produktion", "la producción", "nom", "B1"),
    ("la profession", "profession", "der Beruf", "la profesión", "nom", "B1"),
    ("le profit", "profit", "der Gewinn", "el beneficio", "nom", "B1"),
    ("le projet", "project", "das Projekt", "el proyecto", "nom", "B1"),
    ("promouvoir", "promote", "fördern", "promover", "verbe", "B1"),
    ("approprié", "proper", "angemessen", "adecuado", "adjectif", "B1"),
    ("correctement", "properly", "richtig", "correctamente", "adverbe", "B1"),
    ("la propriété", "property", "das Eigentum", "la propiedad", "nom", "B1"),
    ("la protestation", "protest", "der Protest", "la protesta", "nom", "B1"),
    ("protester", "protest", "protestieren", "protestar", "verbe", "B1"),
    ("fier", "proud", "stolz", "orgulloso", "adjectif", "B1"),
    ("prouver", "prove", "beweisen", "probar", "verbe", "B1"),
    ("pomper", "pump", "pumpen", "bombear", "verbe", "B1"),
    ("donner un coup de poing", "punch", "schlagen", "golpear", "verbe", "B1"),
    ("punir", "punish", "bestrafen", "castigar", "verbe", "B1"),
    ("la punition", "punishment", "die Bestrafung", "el castigo", "nom", "B1")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b1_batch6.ps1", $new_words, $utf8NoBom)
