$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE O-R (A2) ---
    ("l'océan", "ocean", "der Ozean", "el océano", "nom", "A2"),
    ("l'offre", "offer", "das Angebot", "la oferta", "nom", "A2"),
    ("offrir", "offer", "anbieten", "ofrecer", "verbe", "A2"),
    ("l'officier", "officer", "der Offizier", "el oficial", "nom", "A2"),
    ("l'huile / le pétrole", "oil", "das Öl", "el aceite", "nom", "A2"),
    ("sur (mouvement)", "onto", "auf", "sobre", "prep", "A2"),
    ("l'option", "option", "die Option", "la opción", "nom", "A2"),
    ("ordinaire", "ordinary", "gewöhnlich", "ordinario", "adjectif", "A2"),
    ("l'organisation", "organisation", "die Organisation", "la organización", "nom", "A2"),
    ("organiser", "organise", "organisieren", "organizar", "verbe", "A2"),
    ("original", "original", "originell", "original", "adjectif", "A2"),
    ("nous-mêmes", "ourselves", "wir selbst", "nosotros mismos", "pron", "A2"),
    ("à l'extérieur", "outside", "draußen", "afuera", "adverbe", "A2"),
    ("le four", "oven", "der Ofen", "el horno", "nom", "A2"),
    ("le propriétaire", "owner", "der Besitzer", "el propietario", "nom", "A2"),
    
    ("emballer", "pack", "packen", "empacar", "verbe", "A2"),
    ("la douleur", "pain", "der Schmerz", "el dolor", "nom", "A2"),
    ("le peintre", "painter", "der Maler", "el pintor", "nom", "A2"),
    ("le palais", "palace", "der Palast", "el palacio", "nom", "A2"),
    ("le pantalon", "pants", "die Hose", "los pantalones", "nom", "A2"),
    ("le parking", "parking", "das Parken", "el estacionamiento", "nom", "A2"),
    ("particulier", "particular", "besonders", "particular", "adjectif", "A2"),
    ("passer", "pass", "bestehen", "pasar", "verbe", "A2"),
    ("le passager", "passenger", "der Passagier", "el pasajero", "nom", "A2"),
    ("le passé", "past", "die Vergangenheit", "el pasado", "nom", "A2"),
    ("le patient", "patient", "der Patient", "el paciente", "nom", "A2"),
    ("le motif / le modèle", "pattern", "das Muster", "el patrón", "nom", "A2"),
    ("la paix", "peace", "der Frieden", "la paz", "nom", "A2"),
    ("la poire", "pear", "die Birne", "la pera", "nom", "A2"),
    ("le centime", "penny", "der Penny", "el penique", "nom", "A2"),
    ("par", "per", "pro", "por", "prep", "A2"),
    ("le pour cent", "per cent", "das Prozent", "el por ciento", "nom", "A2"),
    ("performer / accomplir", "perform", "aufführen", "realizar", "verbe", "A2"),
    ("peut-être", "perhaps", "vielleicht", "quizás", "adverbe", "A2"),
    ("la permission", "permission", "die Erlaubnis", "el permiso", "nom", "A2"),
    ("la personnalité", "personality", "die Persönlichkeit", "la personalidad", "nom", "A2"),
    ("l'animal de compagnie", "pet", "das Haustier", "la mascota", "nom", "A2"),
    ("l'essence", "petrol", "das Benzin", "la gasolina", "nom", "A2"),
    ("photographier", "photograph", "fotografieren", "fotografiar", "verbe", "A2"),
    ("physique", "physical", "physisch", "físico", "adjectif", "A2"),
    ("la physique", "physics", "die Physik", "la física", "nom", "A2"),
    ("choisir / cueillir", "pick", "pflücken / auswählen", "recoger / elegir", "verbe", "A2"),
    ("le pilote", "pilot", "der Pilot", "el piloto", "nom", "A2"),
    ("le pirate", "pirate", "der Pirat", "el pirata", "nom", "A2"),
    ("la planète", "planet", "der Planet", "el planeta", "nom", "A2"),
    ("planter", "plant", "pflanzen", "plantar", "verbe", "A2"),
    ("le plastique", "plastic", "das Plastik", "el plástico", "nom", "A2"),
    ("l'assiette", "plate", "der Teller", "el plato", "nom", "A2"),
    ("la plateforme / le quai", "platform", "der Bahnsteig", "el andén", "nom", "A2"),
    ("content", "pleased", "erfreut", "contento", "adjectif", "A2"),
    ("la prise (électrique)", "plug", "der Stecker", "el enchufe", "nom", "A2"),
    ("la poche", "pocket", "die Tasche", "el bolsillo", "nom", "A2"),
    ("poli", "polite", "höflich", "educado", "adjectif", "A2"),
    ("la pollution", "pollution", "die Verschmutzung", "la contaminación", "nom", "A2"),
    ("l'étang", "pond", "der Teich", "el estanque", "nom", "A2"),
    ("la pop", "pop", "der Pop", "el pop", "nom", "A2"),
    ("la population", "population", "die Bevölkerung", "la población", "nom", "A2"),
    ("la position", "position", "die Position", "la posición", "nom", "A2"),
    ("la possession", "possession", "der Besitz", "la posesión", "nom", "A2"),
    ("la possibilité", "possibility", "die Möglichkeit", "la posibilidad", "nom", "A2"),
    ("l'affiche", "poster", "das Poster", "el póster", "nom", "A2"),
    ("le pouvoir / l'énergie", "power", "die Macht / die Kraft", "el poder", "nom", "A2"),
    ("prédire", "predict", "vorhersagen", "predecir", "verbe", "A2"),
    ("préférer", "prefer", "bevorzugen", "preferir", "verbe", "A2"),
    ("préparer", "prepare", "vorbereiten", "preparar", "verbe", "A2"),
    ("le président", "president", "der Präsident", "el presidente", "nom", "A2"),
    ("empêcher", "prevent", "verhindern", "prevenir", "verbe", "A2"),
    ("imprimer", "print", "drucken", "imprimir", "verbe", "A2"),
    ("l'imprimante", "printer", "der Drucker", "la impresora", "nom", "A2"),
    ("la prison", "prison", "das Gefängnis", "la prisión", "nom", "A2"),
    ("le prix / la récompense", "prize", "der Preis", "el premio", "nom", "A2"),
    ("professionnel", "professional", "professionell", "profesional", "adjectif", "A2"),
    ("le professeur", "professor", "der Professor", "el profesor", "nom", "A2"),
    ("le profil", "profile", "das Profil", "el perfil", "nom", "A2"),
    ("le programme", "program", "das Programm", "el programa", "nom", "A2"),
    ("le progrès", "progress", "der Fortschritt", "el progreso", "nom", "A2"),
    ("promettre", "promise", "versprechen", "prometer", "verbe", "A2"),
    ("prononcer", "pronounce", "aussprechen", "pronunciar", "verbe", "A2"),
    ("protéger", "protect", "schützen", "proteger", "verbe", "A2"),
    ("le pub", "pub", "die Kneipe", "el pub", "nom", "A2"),
    ("public", "public", "öffentlich", "público", "adjectif", "A2"),
    ("publier", "publish", "veröffentlichen", "publicar", "verbe", "A2"),
    ("tirer", "pull", "ziehen", "tirar", "verbe", "A2"),
    ("pousser", "push", "drücken", "empujar", "verbe", "A2"),

    ("la qualité", "quality", "die Qualität", "la calidad", "nom", "A2"),
    ("la quantité", "quantity", "die Menge", "la cantidad", "nom", "A2"),
    ("la reine", "queen", "die Königin", "la reina", "nom", "A2"),
    ("silencieusement", "quietly", "leise", "silenciosamente", "adverbe", "A2"),

    ("la course", "race", "das Rennen", "la carrera", "nom", "A2"),
    ("le chemin de fer", "railway", "die Eisenbahn", "el ferrocarril", "nom", "A2"),
    ("lever", "raise", "heben", "levantar", "verbe", "A2"),
    ("le rat", "rat", "die Ratte", "la rata", "nom", "A2"),
    ("le taux", "rate", "die Rate", "la tasa", "nom", "A2"),
    ("plutôt", "rather", "eher", "más bien", "adverbe", "A2"),
    ("atteindre", "reach", "erreichen", "alcanzar", "verbe", "A2"),
    ("réagir", "react", "reagieren", "reaccionar", "verbe", "A2"),
    ("se rendre compte", "realise", "erkennen", "darse cuenta", "verbe", "A2"),
    ("recevoir", "receive", "erhalten", "recibir", "verbe", "A2"),
    ("récent", "recent", "kürzlich", "reciente", "adjectif", "A2"),
    ("récemment", "recently", "kürzlich", "recientemente", "adverbe", "A2"),
    ("la réception", "reception", "der Empfang", "la recepción", "nom", "A2"),
    ("la recette", "recipe", "das Rezept", "la receta", "nom", "A2"),
    ("reconnaître", "recognise", "erkennen", "reconocer", "verbe", "A2"),
    ("recommander", "recommend", "empfehlen", "recomendar", "verbe", "A2"),
    ("l'enregistrement", "record", "die Aufnahme", "el disco / el récord", "nom", "A2"),
    ("enregistrer", "record", "aufnehmen", "grabar", "verbe", "A2"),
    ("l'enregistrement", "recording", "die Aufnahme", "la grabación", "nom", "A2"),
    ("recycler", "recycle", "recyceln", "reciclar", "verbe", "A2"),
    ("réduire", "reduce", "reduzieren", "reducir", "verbe", "A2"),
    ("se référer", "refer", "sich beziehen", "referirse", "verbe", "A2"),
    ("refuser", "refuse", "ablehnen", "rechazar", "verbe", "A2"),
    ("la région", "region", "die Region", "la región", "nom", "A2"),
    ("régulier", "regular", "regelmäßig", "regular", "adjectif", "A2"),
    ("la relation", "relationship", "die Beziehung", "la relación", "nom", "A2"),
    ("enlever / retirer", "remove", "entfernen", "quitar", "verbe", "A2"),
    ("réparer", "repair", "reparieren", "reparar", "verbe", "A2"),
    ("remplacer", "replace", "ersetzen", "reemplazar", "verbe", "A2"),
    ("répondre", "reply", "antworten", "responder", "verbe", "A2"),
    ("le rapport", "report", "der Bericht", "el informe", "nom", "A2"),
    ("rapporter", "report", "berichten", "informar", "verbe", "A2"),
    ("le reporter", "reporter", "der Reporter", "el reportero", "nom", "A2"),
    ("la demande", "request", "die Anfrage", "la solicitud", "nom", "A2"),
    ("demander", "request", "anfordern", "solicitar", "verbe", "A2"),
    ("le chercheur", "researcher", "der Forscher", "el investigador", "nom", "A2"),
    ("se reposer", "rest", "sich ausruhen", "descansar", "verbe", "A2"),
    ("le repos", "rest", "die Ruhe", "el descanso", "nom", "A2"),
    ("la revue / la critique", "review", "die Bewertung", "la reseña", "nom", "A2"),
    ("passer en revue", "review", "überprüfen", "revisar", "verbe", "A2"),
    ("le trajet", "ride", "die Fahrt", "el paseo", "nom", "A2"),
    ("la bague", "ring", "der Ring", "el anillo", "nom", "A2"),
    ("sonner", "ring", "klingeln", "sonar", "verbe", "A2"),
    ("le rock", "rock", "der Rock", "el rock", "nom", "A2"),
    ("le rôle", "role", "die Rolle", "el papel", "nom", "A2"),
    ("le toit", "roof", "das Dach", "el techo", "nom", "A2"),
    ("rond", "round", "rund", "redondo", "adjectif", "A2"),
    ("la routine", "routine", "die Routine", "la rutina", "nom", "A2"),
    ("les déchets", "rubbish", "der Müll", "la basura", "nom", "A2"),
    ("impoli", "rude", "unhöflich", "grosero", "adjectif", "A2"),
    ("la course", "run", "der Lauf", "la carrera", "nom", "A2"),
    ("le coureur", "runner", "der Läufer", "el corredor", "nom", "A2"),
    ("la course à pied", "running", "das Laufen", "la carrera", "nom", "A2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_a2_batch6.ps1", $new_words, $utf8NoBom)
