$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE Q (B1) ---
    ("la qualification / le diplôme", "qualification", "die Qualifikation", "la cualificación", "nom", "B1"),
    ("qualifié", "qualified", "qualifiziert", "cualificado", "adjectif", "B1"),
    ("se qualifier", "qualify", "sich qualifizieren", "clasificarse", "verbe", "B1"),
    ("la file d'attente", "queue", "die Schlange", "la cola", "nom", "B1"),
    ("faire la queue", "queue", "Schlange stehen", "hacer cola", "verbe", "B1"),
    ("quitter / abandonner", "quit", "aufgeben / verlassen", "renunciar", "verbe", "B1"),
    ("la citation / le devis", "quotation", "das Zitat / das Angebot", "la cita / el presupuesto", "nom", "B1"),
    ("la citation", "quote", "das Zitat", "la cita", "nom", "B1"),
    ("citer", "quote", "zitieren", "citar", "verbe", "B1"),

    # --- LETTRE R (B1) ---
    ("la race (peuple)", "race", "die Rasse", "la raza", "nom", "B1"),
    ("la course (sport)", "racing", "das Rennen", "las carreras", "nom", "B1"),
    ("la gamme / la portée", "range", "das Sortiment / die Reichweite", "la gama / el alcance", "nom", "B1"),
    ("rare", "rare", "selten", "raro", "adjectif", "B1"),
    ("rarement", "rarely", "selten", "raramente", "adverbe", "B1"),
    ("la réaction", "reaction", "die Reaktion", "la reacción", "nom", "B1"),
    ("la réalité", "reality", "die Realität", "la realidad", "nom", "B1"),
    ("le reçu", "receipt", "die Quittung", "el recibo", "nom", "B1"),
    ("la recommandation", "recommendation", "die Empfehlung", "la recomendación", "nom", "B1"),
    ("la référence", "reference", "die Referenz", "la referencia", "nom", "B1"),
    ("refléter / réfléchir", "reflect", "widerspiegeln", "reflejar", "verbe", "B1"),
    ("régulièrement", "regularly", "regelmäßig", "regularmente", "adverbe", "B1"),
    ("rejeter", "reject", "ablehnen", "rechazar", "verbe", "B1"),
    ("raconter / relier", "relate", "erzählen / verbinden", "relatar / relacionar", "verbe", "B1"),
    ("lié / apparenté", "related", "verwandt / verbunden", "relacionado", "adjectif", "B1"),
    ("la relation", "relation", "die Beziehung", "la relación", "nom", "B1"),
    ("le parent (famille)", "relative", "der Verwandte", "el pariente", "nom", "B1"),
    ("détendu", "relaxed", "entspannt", "relajado", "adjectif", "B1"),
    ("relaxant", "relaxing", "entspannend", "relajante", "adjectif", "B1"),
    ("libérer / sortir", "release", "freilassen / veröffentlichen", "liberar / lanzar", "verbe", "B1"),
    ("fiable", "reliable", "zuverlässig", "fiable", "adjectif", "B1"),
    ("la religion", "religion", "die Religion", "la religión", "nom", "B1"),
    ("religieux", "religious", "religiös", "religioso", "adjectif", "B1"),
    ("rester / demeurer", "remain", "bleiben", "permanecer", "verbe", "B1"),
    ("rappeler (qqch à qqn)", "remind", "erinnern", "recordar", "verbe", "B1"),
    ("éloigné / à distance", "remote", "abgelegen", "remoto", "adjectif", "B1"),
    ("le loyer", "rent", "die Miete", "el alquiler", "nom", "B1"),
    ("louer", "rent", "mieten", "alquilar", "verbe", "B1"),
    ("répété", "repeated", "wiederholt", "repetido", "adjectif", "B1"),
    ("représenter", "represent", "vertreten", "representar", "verbe", "B1"),
    ("exiger / nécessiter", "require", "erfordern", "requerir", "verbe", "B1"),
    ("la réservation", "reservation", "die Reservierung", "la reserva", "nom", "B1"),
    ("la ressource", "resource", "die Ressource", "el recurso", "nom", "B1"),
    ("le respect", "respect", "der Respekt", "el respeto", "nom", "B1"),
    ("respecter", "respect", "respektieren", "respetar", "verbe", "B1"),
    ("la réponse", "response", "die Antwort", "la respuesta", "nom", "B1"),
    ("la responsabilité", "responsibility", "die Verantwortung", "la responsabilidad", "nom", "B1"),
    ("responsable", "responsible", "verantwortlich", "responsable", "adjectif", "B1"),
    ("le résultat", "result", "das Ergebnis", "el resultado", "nom", "B1"),
    ("prendre sa retraite", "retire", "in Rente gehen", "jubilarse", "verbe", "B1"),
    ("retraité", "retired", "im Ruhestand", "jubilado", "adjectif", "B1"),
    ("réviser", "revise", "überarbeiten", "revisar", "verbe", "B1"),
    ("le fusil", "rifle", "das Gewehr", "el rifle", "nom", "B1"),
    ("s'élever / augmenter", "rise", "steigen", "subir", "verbe", "B1"),
    ("le risque", "risk", "das Risiko", "el riesgo", "nom", "B1"),
    ("risquer", "risk", "riskieren", "arriesgar", "verbe", "B1"),
    ("le robot", "robot", "der Roboter", "el robot", "nom", "B1"),
    ("rouler", "roll", "rollen", "rodar", "verbe", "B1"),
    ("romantique", "romantic", "romantisch", "romántico", "adjectif", "B1"),
    ("la corde", "rope", "das Seil", "la cuerda", "nom", "B1"),
    ("rugueux / brutal", "rough", "rau", "áspero / duro", "adjectif", "B1"),
    ("la rangée", "row", "die Reihe", "la fila", "nom", "B1"),
    ("royal", "royal", "königlich", "real", "adjectif", "B1"),
    ("le rugby", "rugby", "das Rugby", "el rugby", "nom", "B1"),
    ("diriger / gouverner", "rule", "regieren", "gobernar", "verbe", "B1"),

    # --- LETTRE S (B1) ---
    ("la sécurité", "safety", "die Sicherheit", "la seguridad", "nom", "B1"),
    ("le marin", "sailor", "der Matrose", "el marinero", "nom", "B1"),
    ("l'échantillon", "sample", "das Muster", "la muestra", "nom", "B1"),
    ("le sable", "sand", "der Sand", "la arena", "nom", "B1"),
    ("scanner / balayer", "scan", "scannen", "escanear", "verbe", "B1"),
    ("scientifique", "scientific", "wissenschaftlich", "científico", "adjectif", "B1"),
    ("le scénario / le script", "script", "das Skript", "el guion", "nom", "B1"),
    ("la sculpture", "sculpture", "die Skulptur", "la escultura", "nom", "B1"),
    ("secondaire", "secondary", "sekundär", "secundario", "adjectif", "B1"),
    ("la sécurité", "security", "die Sicherheit", "la seguridad", "nom", "B1"),
    ("la graine", "seed", "der Samen", "la semilla", "nom", "B1"),
    ("sensé / raisonnable", "sensible", "vernünftig", "sensato", "adjectif", "B1"),
    ("séparer", "separate", "trennen", "separar", "verbe", "B1"),
    ("sérieusement", "seriously", "ernsthaft", "seriamente", "adverbe", "B1"),
    ("le serviteur", "servant", "der Diener", "el sirviente", "nom", "B1"),
    ("fixer / placer", "set", "setzen", "colocar / establecer", "verbe", "B1"),
    ("l'ensemble", "set", "das Set", "el conjunto", "nom", "B1"),
    ("le cadre / le réglage", "setting", "die Einstellung", "el entorno", "nom", "B1"),
    ("le sexe", "sex", "das Geschlecht", "el sexo", "nom", "B1"),
    ("sexuel", "sexual", "sexuell", "sexual", "adjectif", "B1"),
    ("pointu / tranchant", "sharp", "scharf", "afilado", "adjectif", "B1"),
    ("l'étagère", "shelf", "das Regal", "el estante", "nom", "B1"),
    ("la coquille", "shell", "die Schale", "la concha", "nom", "B1"),
    ("le changement / le quart de travail", "shift", "die Verschiebung / die Schicht", "el turno", "nom", "B1"),
    ("déplacer / décaler", "shift", "verschieben", "desplazar", "verbe", "B1"),
    ("briller", "shine", "scheinen", "brillar", "verbe", "B1"),
    ("brillant", "shiny", "glänzend", "brillante", "adjectif", "B1"),
    ("tirer (arme) / filmer", "shoot", "schießen / filmen", "disparar / filmar", "verbe", "B1"),
    ("le choc", "shock", "der Schock", "el choque", "nom", "B1"),
    ("choquer", "shock", "schockieren", "conmocionar", "verbe", "B1"),
    ("le tir / le coup", "shot", "der Schuss", "el tiro", "nom", "B1"),
    ("timide", "shy", "schüchtern", "tímido", "adjectif", "B1"),
    ("la vue", "sight", "die Sicht", "la vista", "nom", "B1"),
    ("le signal", "signal", "das Signal", "la señal", "nom", "B1"),
    ("silencieux", "silent", "still", "silencioso", "adjectif", "B1"),
    ("bête / stupide", "silly", "albern", "tonto", "adjectif", "B1"),
    ("la similarité", "similarity", "die Ähnlichkeit", "la similitud", "nom", "B1"),
    ("de la même manière", "similarly", "ebenso", "de manera similar", "adverbe", "B1"),
    ("simplement", "simply", "einfach", "simplemente", "adverbe", "B1"),
    ("puisque", "since", "da", "ya que", "conjonction", "B1"),
    ("couler (navire) / sombrer", "sink", "sinken", "hundirse", "verbe", "B1"),
    ("la compétence", "skill", "die Fähigkeit", "la habilidad", "nom", "B1"),
    ("sauter / omettre", "skip", "überspringen", "saltar", "verbe", "B1"),
    ("claquer", "slam", "zuschlagen", "dar un portazo", "verbe", "B1"),
    ("gifler", "slap", "ohrfeigen", "abofetear", "verbe", "B1"),
    ("la tranche", "slice", "die Scheibe", "la rebanada", "nom", "B1"),
    ("trancher", "slice", "in Scheiben schneiden", "rebanar", "verbe", "B1"),
    ("légèrement", "slightly", "leicht", "ligeramente", "adverbe", "B1"),
    ("élégant / intelligent", "smart", "schick / schlau", "elegante / inteligente", "adjectif", "B1"),
    ("lisse", "smooth", "glatt", "suave / liso", "adjectif", "B1"),
    ("la société", "society", "die Gesellschaft", "la sociedad", "nom", "B1"),
    ("le logiciel", "software", "die Software", "el software", "nom", "B1"),
    ("le sol", "soil", "der Boden", "el suelo", "nom", "B1"),
    ("solide", "solid", "fest", "sólido", "adjectif", "B1"),
    ("résoudre", "solve", "lösen", "resolver", "verbe", "B1"),
    ("trier", "sort", "sortieren", "ordenar", "verbe", "B1"),
    ("du sud", "southern", "südlich", "del sur", "adjectif", "B1"),
    ("le spam / le pourriel", "spam", "der Spam", "el correo no deseado", "nom", "B1"),
    ("spécifiquement", "specifically", "spezifisch", "específicamente", "adverbe", "B1"),
    ("la vitesse", "speed", "die Geschwindigkeit", "la velocidad", "nom", "B1"),
    ("les dépenses", "spending", "die Ausgaben", "los gastos", "nom", "B1"),
    ("épicé", "spicy", "würzig", "picante", "adjectif", "B1"),
    ("l'esprit", "spirit", "der Geist", "el espíritu", "nom", "B1"),
    ("parlé / oral", "spoken", "gesprochen", "hablado", "adjectif", "B1"),
    ("l'endroit / la tache", "spot", "der Fleck / der Ort", "la mancha / el lugar", "nom", "B1"),
    ("repérer", "spot", "entdecken", "detectar", "verbe", "B1"),
    ("répandre / étaler", "spread", "verbreiten", "extender / propagar", "verbe", "B1"),
    ("la source (eau)", "spring", "die Quelle", "el manantial", "nom", "B1"),
    ("l'espion", "spy", "der Spion", "el espía", "nom", "B1"),
    ("espionner", "spy", "spionieren", "espiar", "verbe", "B1"),
    ("le stade", "stadium", "das Stadion", "el estadio", "nom", "B1"),
    ("le personnel (employés)", "staff", "das Personal", "el personal", "nom", "B1"),
    ("le standard / la norme", "standard", "der Standard", "el estándar", "nom", "B1"),
    ("déclarer", "state", "aussagen", "declarar", "verbe", "B1"),
    ("la statue", "statue", "die Statue", "la estatua", "nom", "B1"),
    ("coller / attacher", "stick", "kleben", "pegar", "verbe", "B1"),
    ("le bâton", "stick", "der Stock", "el palo", "nom", "B1"),
    ("stocker", "store", "lagern", "almacenar", "verbe", "B1"),
    ("l'étranger (personne)", "stranger", "der Fremde", "el extraño", "nom", "B1"),
    ("la force", "strength", "die Stärke", "la fuerza", "nom", "B1"),
    ("la ficelle / la corde", "string", "die Schnur", "la cuerda", "nom", "B1"),
    ("fortement", "strongly", "stark", "fuertemente", "adverbe", "B1"),
    ("le studio", "studio", "das Studio", "el estudio", "nom", "B1"),
    ("les affaires / les trucs", "stuff", "das Zeug", "las cosas", "nom", "B1"),
    ("avec succès", "successfully", "erfolgreich", "exitosamente", "adverbe", "B1"),
    ("soudain", "sudden", "plötzlich", "repentino", "adjectif", "B1"),
    ("souffrir", "suffer", "leiden", "sufrir", "verbe", "B1"),
    ("convenir à", "suit", "passen", "convenir / adaptar", "verbe", "B1"),
    ("approprié", "suitable", "geeignet", "adecuado", "adjectif", "B1"),
    ("le succès", "success", "der Erfolg", "el éxito", "nom", "B1"),
    ("résumer", "summarise", "zusammenfassen", "resumir", "verbe", "B1"),
    ("le résumé", "summary", "die Zusammenfassung", "el resumen", "nom", "B1"),
    ("l'approvisionnement", "supply", "die Versorgung", "el suministro", "nom", "B1"),
    ("fournir", "supply", "liefern", "suministrar", "verbe", "B1"),
    ("le supporter / le partisan", "supporter", "der Anhänger", "el partidario", "nom", "B1"),
    ("sûrement", "surely", "sicherlich", "seguramente", "adverbe", "B1"),
    ("la surface", "surface", "die Oberfläche", "la superficie", "nom", "B1"),
    ("survivre", "survive", "überleben", "sobrevivir", "verbe", "B1"),
    ("le sondage / l'enquête", "survey", "die Umfrage", "la encuesta", "nom", "B1"),
    ("l'interrupteur", "switch", "der Schalter", "el interruptor", "nom", "B1"),
    ("changer / échanger", "switch", "wechseln", "cambiar", "verbe", "B1"),
    ("l'épée", "sword", "das Schwert", "la espada", "nom", "B1"),
    ("le symptôme", "symptom", "das Symptom", "el síntoma", "nom", "B1")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b1_batch7.ps1", $new_words, $utf8NoBom)
