$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE I-N (A2) ---
    ("idéal", "ideal", "ideal", "ideal", "adjectif", "A2"),
    ("l'idiot", "idiot", "der Idiot", "el idiota", "nom", "A2"),
    ("malade", "ill", "krank", "enfermo", "adjectif", "A2"),
    ("la maladie", "illness", "die Krankheit", "la enfermedad", "nom", "A2"),
    ("l'image", "image", "das Bild", "la imagen", "nom", "A2"),
    ("imaginer", "imagine", "sich vorstellen", "imaginar", "verbe", "A2"),
    ("immédiatement", "immediately", "sofort", "inmediatamente", "adverbe", "A2"),
    ("impossible", "impossible", "unmöglich", "imposible", "adjectif", "A2"),
    ("inclus", "included", "inbegriffen", "incluido", "adjectif", "A2"),
    ("y compris", "including", "einschließlich", "incluyendo", "prep", "A2"),
    ("augmenter", "increase", "erhöhen", "aumentar", "verbe", "A2"),
    ("incroyable", "incredible", "unglaublich", "increíble", "adjectif", "A2"),
    ("indépendant", "independent", "unabhängig", "independiente", "adjectif", "A2"),
    ("individuel", "individual", "individuell", "individual", "adjectif", "A2"),
    ("l'industrie", "industry", "die Industrie", "la industria", "nom", "A2"),
    ("informel", "informal", "informell", "informal", "adjectif", "A2"),
    ("la blessure", "injury", "die Verletzung", "la lesión", "nom", "A2"),
    ("l'encre", "ink", "die Tinte", "la tinta", "nom", "A2"),
    ("l'insecte", "insect", "das Insekt", "el insecto", "nom", "A2"),
    ("à l'intérieur", "inside", "drinnen", "adentro", "adverbe", "A2"),
    ("au lieu de", "instead", "stattdessen", "en lugar de", "adverbe", "A2"),
    ("l'instruction", "instruction", "die Anweisung", "la instrucción", "nom", "A2"),
    ("l'instructeur", "instructor", "der Ausbilder", "el instructor", "nom", "A2"),
    ("l'instrument", "instrument", "das Instrument", "el instrumento", "nom", "A2"),
    ("intelligent", "intelligent", "intelligent", "inteligente", "adjectif", "A2"),
    ("international", "international", "international", "internacional", "adjectif", "A2"),
    ("l'introduction", "introduction", "die Einführung", "la introducción", "nom", "A2"),
    ("inventer", "invent", "erfinden", "inventar", "verbe", "A2"),
    ("l'invention", "invention", "die Erfindung", "la invención", "nom", "A2"),
    ("l'invitation", "invitation", "die Einladung", "la invitación", "nom", "A2"),
    ("inviter", "invite", "einladen", "invitar", "verbe", "A2"),
    ("impliquer", "involve", "beinhalten", "involucrar", "verbe", "A2"),
    ("l'article / l'élément", "item", "der Artikel", "el artículo", "nom", "A2"),
    ("lui-même (chose)", "itself", "sich selbst", "sí mismo", "pron", "A2"),
    
    ("la confiture", "jam", "die Marmelade", "la mermelada", "nom", "A2"),
    ("le jazz", "jazz", "der Jazz", "el jazz", "nom", "A2"),
    ("les bijoux", "jewellery", "der Schmuck", "las joyas", "nom", "A2"),
    ("la blague", "joke", "der Witz", "la broma", "nom", "A2"),
    ("le journaliste", "journalist", "der Journalist", "el periodista", "nom", "A2"),
    ("sauter", "jump", "springen", "saltar", "verbe", "A2"),
    
    ("donner un coup de pied", "kick", "treten", "patear", "verbe", "A2"),
    ("le gamin", "kid", "das Kind", "el niño", "nom", "A2"),
    ("tuer", "kill", "töten", "matar", "verbe", "A2"),
    ("le roi", "king", "der König", "el rey", "nom", "A2"),
    ("embrasser", "kiss", "küssen", "besar", "verbe", "A2"),
    ("le bisou", "kiss", "der Kuss", "el beso", "nom", "A2"),
    ("le genou", "knee", "das Knie", "la rodilla", "nom", "A2"),
    ("le couteau", "knife", "das Messer", "el cuchillo", "nom", "A2"),
    ("frapper (à la porte)", "knock", "klopfen", "tocar", "verbe", "A2"),
    ("la connaissance", "knowledge", "das Wissen", "el conocimiento", "nom", "A2"),

    ("le labo", "lab", "das Labor", "el laboratorio", "nom", "A2"),
    ("la dame", "lady", "die Dame", "la dama", "nom", "A2"),
    ("le lac", "lake", "der See", "el lago", "nom", "A2"),
    ("la lampe", "lamp", "die Lampe", "la lámpara", "nom", "A2"),
    ("atterrir", "land", "landen", "aterrizar", "verbe", "A2"),
    ("l'ordinateur portable", "laptop", "der Laptop", "la computadora portátil", "nom", "A2"),
    ("le rire", "laughter", "das Gelächter", "la risa", "nom", "A2"),
    ("la loi", "law", "das Gesetz", "la ley", "nom", "A2"),
    ("l'avocat", "lawyer", "der Anwalt", "el abogado", "nom", "A2"),
    ("paresseux", "lazy", "faul", "perezoso", "adjectif", "A2"),
    ("mener", "lead", "führen", "guiar", "verbe", "A2"),
    ("le leader", "leader", "der Anführer", "el líder", "nom", "A2"),
    ("l'apprentissage", "learning", "das Lernen", "el aprendizaje", "nom", "A2"),
    ("le moins", "least", "am wenigsten", "el menos", "adverbe", "A2"),
    ("la conférence (cours)", "lecture", "die Vorlesung", "la conferencia", "nom", "A2"),
    ("le citron", "lemon", "die Zitrone", "el limón", "nom", "A2"),
    ("prêter", "lend", "leihen", "prestar", "verbe", "A2"),
    ("moins", "less", "weniger", "menos", "adverbe", "A2"),
    ("le niveau", "level", "das Niveau", "el nivel", "nom", "A2"),
    ("le mode de vie", "lifestyle", "der Lebensstil", "el estilo de vida", "nom", "A2"),
    ("l'ascenseur", "lift", "der Aufzug", "el ascensor", "nom", "A2"),
    ("soulever", "lift", "heben", "levantar", "verbe", "A2"),
    ("léger", "light", "leicht", "ligero", "adjectif", "A2"),
    ("probable", "likely", "wahrscheinlich", "probable", "adjectif", "A2"),
    ("le lien", "link", "die Verbindung", "el enlace", "nom", "A2"),
    ("lier", "link", "verbinden", "enlazar", "verbe", "A2"),
    ("l'auditeur", "listener", "der Zuhörer", "el oyente", "nom", "A2"),
    ("le litre", "litre", "der Liter", "el litro", "nom", "A2"),
    ("le cadenas", "lock", "das Schloss", "la cerradura", "nom", "A2"),
    ("verrouiller", "lock", "abschließen", "cerrar con llave", "verbe", "A2"),
    ("le regard / le look", "look", "der Blick / der Look", "la mirada", "nom", "A2"),
    ("le camion", "lorry", "der Lastwagen", "el camión", "nom", "A2"),
    ("perdu", "lost", "verloren", "perdido", "adjectif", "A2"),
    ("fort (bruit)", "loud", "laut", "fuerte", "adjectif", "A2"),
    ("fortement", "loudly", "laut", "fuertemente", "adverbe", "A2"),
    ("charmant", "lovely", "lieblich", "encantador", "adjectif", "A2"),
    ("bas", "low", "niedrig", "bajo", "adjectif", "A2"),
    ("la chance", "luck", "das Glück", "la suerte", "nom", "A2"),
    ("chanceux", "lucky", "glücklich", "afortunado", "adjectif", "A2"),
    
    ("le courrier", "mail", "die Post", "el correo", "nom", "A2"),
    ("envoyer par courrier", "mail", "per Post senden", "enviar por correo", "verbe", "A2"),
    ("majeur", "major", "wichtig", "mayor", "adjectif", "A2"),
    ("mâle / masculin", "male", "männlich", "masculino", "adjectif", "A2"),
    ("gérer", "manage", "verwalten", "manejar", "verbe", "A2"),
    ("le manager", "manager", "der Manager", "el gerente", "nom", "A2"),
    ("la manière", "manner", "die Art und Weise", "la manera", "nom", "A2"),
    ("la marque / la note", "mark", "die Note", "la marca", "nom", "A2"),
    ("marquer", "mark", "markieren", "marcar", "verbe", "A2"),
    ("se marier", "marry", "heiraten", "casarse", "verbe", "A2"),
    ("le masque", "mask", "die Maske", "la máscara", "nom", "A2"),
    ("le matériel / la matière", "material", "das Material", "el material", "nom", "A2"),
    ("les mathématiques", "mathematics", "die Mathematik", "las matemáticas", "nom", "A2"),
    ("pourrait", "may", "darf", "podría", "verbe", "A2"),
    ("les médias", "media", "die Medien", "los medios", "nom", "A2"),
    ("médical", "medical", "medizinisch", "médico", "adjectif", "A2"),
    ("le médicament", "medicine", "die Medizin", "la medicina", "nom", "A2"),
    ("la mémoire", "memory", "die Erinnerung", "la memoria", "nom", "A2"),
    ("mentionner", "mention", "erwähnen", "mencionar", "verbe", "A2"),
    ("le métal", "metal", "das Metall", "el metal", "nom", "A2"),
    ("le milieu", "middle", "die Mitte", "el medio", "nom", "A2"),
    ("pourrait (conditionnel)", "might", "könnte", "podría", "verbe", "A2"),
    ("l'esprit", "mind", "der Verstand", "la mente", "nom", "A2"),
    ("s'en soucier", "mind", "etwas ausmachen", "importar", "verbe", "A2"),
    ("le mien", "mine", "meiner", "mío", "pron", "A2"),
    ("le miroir", "mirror", "der Spiegel", "el espejo", "nom", "A2"),
    ("manquant", "missing", "fehlend", "desaparecido", "adjectif", "A2"),
    ("mobile", "mobile", "mobil", "móvil", "adjectif", "A2"),
    ("le singe", "monkey", "der Affe", "el mono", "nom", "A2"),
    ("la lune", "moon", "der Mond", "la luna", "nom", "A2"),
    ("principalement", "mostly", "meistens", "principalmente", "adverbe", "A2"),
    ("la moto", "motorcycle", "das Motorrad", "la motocicleta", "nom", "A2"),
    ("le mouvement", "movement", "die Bewegung", "el movimiento", "nom", "A2"),
    ("musical", "musical", "musikalisch", "musical", "adjectif", "A2"),
    ("le musicien", "musician", "der Musiker", "el músico", "nom", "A2"),
    ("moi-même", "myself", "ich selbst", "yo mismo", "pron", "A2"),

    ("étroit", "narrow", "schmal", "estrecho", "adjectif", "A2"),
    ("national", "national", "national", "nacional", "adjectif", "A2"),
    ("naturel", "natural", "natürlich", "natural", "adjectif", "A2"),
    ("la nature", "nature", "die Natur", "la naturaleza", "nom", "A2"),
    ("presque", "nearly", "fast", "casi", "adverbe", "A2"),
    ("nécessaire", "necessary", "notwendig", "necesario", "adjectif", "A2"),
    ("le cou", "neck", "der Hals", "el cuello", "nom", "A2"),
    ("le besoin", "need", "das Bedürfnis", "la necesidad", "nom", "A2"),
    ("aucun / ni l'un ni l'autre", "neither", "weder", "ninguno", "pron", "A2"),
    ("nerveux", "nervous", "nervös", "nervioso", "adjectif", "A2"),
    ("le nid", "nest", "das Nest", "el nido", "nom", "A2"),
    ("le filet", "net", "das Netz", "la red", "nom", "A2"),
    ("le réseau", "network", "das Netzwerk", "la red", "nom", "A2"),
    ("le bruit", "noise", "der Lärm", "el ruido", "nom", "A2"),
    ("bruyant", "noisy", "laut", "ruidoso", "adjectif", "A2"),
    ("aucun", "none", "keiner", "ninguno", "pron", "A2"),
    ("normal", "normal", "normal", "normal", "adjectif", "A2"),
    ("normalement", "normally", "normalerweise", "normalmente", "adverbe", "A2"),
    ("remarquer", "notice", "bemerken", "notar", "verbe", "A2"),
    ("l'avis", "notice", "die Notiz", "el aviso", "nom", "A2"),
    ("le roman", "novel", "der Roman", "la novela", "nom", "A2"),
    ("nulle part", "nowhere", "nirgendwo", "en ninguna parte", "adverbe", "A2"),
    ("la noix", "nut", "die Nuss", "la nuez", "nom", "A2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_a2_batch5.ps1", $new_words, $utf8NoBom)
