$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE B (B2) ---
    ("la bactérie", "bacteria", "die Bakterien", "la bacteria", "nom", "B2"),
    ("le badge / l'insigne", "badge", "das Abzeichen", "la insignia", "nom", "B2"),
    ("équilibré", "balanced", "ausgewogen", "equilibrado", "adjectif", "B2"),
    ("le ballet", "ballet", "das Ballett", "el ballet", "nom", "B2"),
    ("le ballon (baudruche)", "balloon", "der Ballon", "el globo", "nom", "B2"),
    ("à peine", "barely", "kaum", "apenas", "adverbe", "B2"),
    ("la bonne affaire", "bargain", "das Schnäppchen", "la ganga", "nom", "B2"),
    ("la barrière", "barrier", "die Barriere", "la barrera", "nom", "B2"),
    ("basé sur", "based on", "basierend auf", "basado en", "adjectif", "B2"),
    ("le sous-sol", "basement", "der Keller", "el sótano", "nom", "B2"),
    ("fondamentalement / en gros", "basically", "grundsätzlich", "básicamente", "adverbe", "B2"),
    ("la base / le fondement", "basis", "die Basis", "la base", "nom", "B2"),
    ("le panier", "basket", "der Korb", "la cesta", "nom", "B2"),
    ("la batte / la chauve-souris", "bat", "der Schläger / die Fledermaus", "el bate / el murciélago", "nom", "B2"),
    ("supporter / endurer", "bear", "ertragen", "soportar", "verbe", "B2"),
    ("supplier", "beg", "betteln", "rogar", "verbe", "B2"),
    ("l'être", "being", "das Wesen", "el ser", "nom", "B2"),
    ("bénéfique", "beneficial", "vorteilhaft", "beneficioso", "adjectif", "B2"),
    ("courbé / plié", "bent", "gebogen", "doblado", "adjectif", "B2"),
    ("à côté de", "beside", "neben", "al lado de", "prep", "B2"),
    ("en outre / d'ailleurs", "besides", "außerdem", "además", "adverbe", "B2"),
    ("parier", "bet", "wetten", "apostar", "verbe", "B2"),
    ("au-delà de", "beyond", "jenseits", "más allá de", "prep", "B2"),
    ("le biais / le préjugé", "bias", "die Voreingenommenheit", "el sesgo", "nom", "B2"),
    ("faire une offre (enchère)", "bid", "bieten", "pujar", "verbe", "B2"),
    ("biologique", "biological", "biologisch", "biológico", "adjectif", "B2"),
    ("amer", "bitter", "bitter", "amargo", "adjectif", "B2"),
    ("le blâme", "blame", "die Schuld", "la culpa", "nom", "B2"),
    ("blâmer", "blame", "beschuldigen", "culpar", "verbe", "B2"),
    ("la couverture", "blanket", "die Decke", "la manta", "nom", "B2"),
    ("aveugle", "blind", "blind", "ciego", "adjectif", "B2"),
    ("audacieux / en gras", "bold", "mutig / fett (Schrift)", "audaz / negrita", "adjectif", "B2"),
    ("le bombardement", "bombing", "der Bombenangriff", "el bombardeo", "nom", "B2"),
    ("le lien (affectif/chimique)", "bond", "die Bindung", "el vínculo", "nom", "B2"),
    ("stimuler / booster", "boost", "ankurbeln", "impulsar", "verbe", "B2"),
    ("lié / contraint", "bound", "gebunden", "atado", "adjectif", "B2"),
    ("le sein / la poitrine", "breast", "die Brust", "el pecho", "nom", "B2"),
    ("la brique", "brick", "der Ziegel", "el ladrillo", "nom", "B2"),
    ("bref / court", "brief", "kurz", "breve", "adjectif", "B2"),
    ("brièvement", "briefly", "kurz", "brevemente", "adverbe", "B2"),
    ("large / vaste", "broad", "breit", "amplio", "adjectif", "B2"),
    ("l'émission (TV/radio)", "broadcast", "die Sendung", "la transmisión", "nom", "B2"),
    ("diffuser", "broadcast", "senden", "transmitir", "verbe", "B2"),
    ("le diffuseur / le présentateur", "broadcaster", "der Sender", "el locutor", "nom", "B2"),
    ("largement", "broadly", "weitgehend", "ampliamente", "adverbe", "B2"),
    ("le dollar (familier)", "buck", "der Dollar", "el dólar", "nom", "B2"),
    ("le budget", "budget", "das Budget", "el presupuesto", "nom", "B2"),
    ("le bug / l'insecte", "bug", "der Käfer", "el insecto / el error", "nom", "B2"),
    ("la balle (fusil)", "bullet", "die Kugel", "la bala", "nom", "B2"),
    ("le bouquet / la bande", "bunch", "der Haufen", "el manojo / el grupo", "nom", "B2"),
    ("le buisson", "bush", "der Busch", "el arbusto", "nom", "B2"),
    ("sauf / à part", "but", "außer", "sino / excepto", "prep", "B2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b2_batch2.ps1", $new_words, $utf8NoBom)
