$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE G (B1) ---
    ("le garage", "garage", "die Garage", "el garaje", "nom", "B1"),
    ("rassembler", "gather", "sammeln", "reunir", "verbe", "B1"),
    ("généralement", "generally", "allgemein", "generalmente", "adverbe", "B1"),
    ("la génération", "generation", "die Generation", "la generación", "nom", "B1"),
    ("généreux", "generous", "großzügig", "generoso", "adjectif", "B1"),
    ("doux / gentil", "gentle", "sanft", "suave", "adjectif", "B1"),
    ("le monsieur / le gentleman", "gentleman", "der Herr", "el caballero", "nom", "B1"),
    ("le fantôme", "ghost", "der Geist", "el fantasma", "nom", "B1"),
    ("le géant", "giant", "der Riese", "el gigante", "nom", "B1"),
    ("géant", "giant", "riesig", "gigante", "adjectif", "B1"),
    ("le concert", "gig", "der Auftritt", "el concierto", "nom", "B1"),
    ("content", "glad", "froh", "contento", "adjectif", "B1"),
    ("mondial", "global", "global", "global", "adjectif", "B1"),
    ("le gant", "glove", "der Handschuh", "el guante", "nom", "B1"),
    ("les marchandises", "goods", "die Waren", "los bienes", "nom", "B1"),
    ("la note / l'année scolaire", "grade", "die Note / die Klasse", "el grado", "nom", "B1"),
    ("obtenir un diplôme", "graduate", "einen Abschluss machen", "graduarse", "verbe", "B1"),
    ("le grain", "grain", "das Korn", "el grano", "nom", "B1"),
    ("reconnaissant", "grateful", "dankbar", "agradecido", "adjectif", "B1"),
    ("la croissance", "growth", "das Wachstum", "el crecimiento", "nom", "B1"),
    ("le garde", "guard", "der Wächter", "el guardia", "nom", "B1"),
    ("garder", "guard", "bewachen", "vigilar", "verbe", "B1"),
    ("coupable", "guilty", "schuldig", "culpable", "adjectif", "B1"),

    # --- LETTRE H (B1) ---
    ("pendre / accrocher", "hang", "hängen", "colgar", "verbe", "B1"),
    ("le bonheur", "happiness", "das Glück", "la felicidad", "nom", "B1"),
    ("à peine", "hardly", "kaum", "apenas", "adverbe", "B1"),
    ("le gros titre", "headline", "die Schlagzeile", "el titular", "nom", "B1"),
    ("le chauffage", "heating", "die Heizung", "la calefacción", "nom", "B1"),
    ("lourdement", "heavily", "schwer", "pesadamente", "adverbe", "B1"),
    ("l'hélicoptère", "helicopter", "der Hubschrauber", "el helicóptero", "nom", "B1"),
    ("surligner / mettre en évidence", "highlight", "hervorheben", "resaltar", "verbe", "B1"),
    ("hautement", "highly", "höchst", "altamente", "adverbe", "B1"),
    ("embaucher / louer", "hire", "einstellen / mieten", "contratar / alquilar", "verbe", "B1"),
    ("l'indice / l'astuce", "hint", "der Hinweis", "la pista", "nom", "B1"),
    ("insinuer", "hint", "andeuten", "insinuar", "verbe", "B1"),
    ("historique", "historic", "historisch", "histórico", "adjectif", "B1"),
    ("historique (relatif à l'histoire)", "historical", "historisch", "histórico", "adjectif", "B1"),
    ("honnête", "honest", "ehrlich", "honesto", "adjectif", "B1"),
    ("le miel", "honey", "der Honig", "la miel", "nom", "B1"),
    ("horrible", "horrible", "schrecklich", "horrible", "adjectif", "B1"),
    ("l'horreur", "horror", "der Horror", "el horror", "nom", "B1"),
    ("l'hôte", "host", "der Gastgeber", "el anfitrión", "nom", "B1"),
    ("héberger / animer", "host", "veranstalten", "albergar", "verbe", "B1"),
    ("cependant", "however", "jedoch", "sin embargo", "adverbe", "B1"),
    ("chasser", "hunt", "jagen", "cazar", "verbe", "B1"),
    ("l'ouragan", "hurricane", "der Hurrikan", "el huracán", "nom", "B1"),

    # --- LETTRE I-K (B1) ---
    ("ignorant", "ignorant", "unwissend", "ignorante", "adjectif", "B1"),
    ("ignorer", "ignore", "ignorieren", "ignorar", "verbe", "B1"),
    ("illégal", "illegal", "illegal", "ilegal", "adjectif", "B1"),
    ("imaginaire", "imaginary", "imaginär", "imaginario", "adjectif", "B1"),
    ("immédiat", "immediate", "sofortig", "inmediato", "adjectif", "B1"),
    ("l'immigrant", "immigrant", "der Einwanderer", "el inmigrante", "nom", "B1"),
    ("l'impact", "impact", "die Auswirkung", "el impacto", "nom", "B1"),
    ("l'importation", "import", "der Import", "la importación", "nom", "B1"),
    ("importer", "import", "importieren", "importar", "verbe", "B1"),
    ("l'importance", "importance", "die Wichtigkeit", "la importancia", "nom", "B1"),
    ("l'impression", "impression", "der Eindruck", "la impresión", "nom", "B1"),
    ("impressionnant", "impressive", "beeindruckend", "impresionante", "adjectif", "B1"),
    ("améliorer", "improve", "verbessern", "mejorar", "verbe", "B1"),
    ("l'amélioration", "improvement", "die Verbesserung", "la mejora", "nom", "B1"),
    ("incroyablement", "incredibly", "unglaublich", "increíblemente", "adverbe", "B1"),
    ("en effet", "indeed", "tatsächlich", "de hecho", "adverbe", "B1"),
    ("indiquer", "indicate", "anzeigen", "indicar", "verbe", "B1"),
    ("indirect", "indirect", "indirekt", "indirecto", "adjectif", "B1"),
    ("intérieur (adj)", "indoor", "Innen-", "interior", "adjectif", "B1"),
    ("à l'intérieur", "indoors", "drinnen", "adentro", "adverbe", "B1"),
    ("le nourrisson / le bébé", "infant", "der Säugling", "el infante", "nom", "B1"),
    ("l'influence", "influence", "der Einfluss", "la influencia", "nom", "B1"),
    ("influencer", "influence", "beeinflussen", "influir", "verbe", "B1"),
    ("l'ingrédient", "ingredient", "die Zutat", "el ingrediente", "nom", "B1"),
    ("blesser", "injure", "verletzen", "herir", "verbe", "B1"),
    ("blessé", "injured", "verletzt", "herido", "adjectif", "B1"),
    ("innocent", "innocent", "unschuldig", "inocente", "adjectif", "B1"),
    ("l'intelligence", "intelligence", "die Intelligenz", "la inteligencia", "nom", "B1"),
    ("avoir l'intention de", "intend", "beabsichtigen", "tener la intención", "verbe", "B1"),
    ("l'intention", "intention", "die Absicht", "la intención", "nom", "B1"),
    ("investir", "invest", "investieren", "invertir", "verbe", "B1"),
    ("enquêter", "investigate", "untersuchen", "investigar", "verbe", "B1"),
    ("impliqué", "involved", "beteiligt", "involucrado", "adjectif", "B1"),
    ("le fer / le fer à repasser", "iron", "das Eisen / das Bügeleisen", "el hierro", "nom", "B1"),
    ("repasser", "iron", "bügeln", "planchar", "verbe", "B1"),
    ("le problème / l'édition", "issue", "das Problem / die Ausgabe", "el asunto", "nom", "B1"),
    ("l'informatique (IT)", "IT", "die Informatik", "la informática", "nom", "B1"),

    ("le journal (publication)", "journal", "das Journal", "la revista / el diario", "nom", "B1"),
    ("le juge", "judge", "der Richter", "el juez", "nom", "B1"),
    ("juger", "judge", "urteilen", "juzgar", "verbe", "B1"),
    
    ("vif / passionné", "keen", "eifrig", "entusiasta", "adjectif", "B1"),
    ("clé (principal)", "key", "Haupt-", "clave", "adjectif", "B1"),
    ("le clavier", "keyboard", "die Tastatur", "el teclado", "nom", "B1"),
    ("le meurtre", "killing", "die Tötung", "el asesinato", "nom", "B1"),
    ("gentil / attentionné", "kind", "freundlich", "amable", "adjectif", "B1"),
    ("le royaume", "kingdom", "das Königreich", "el reino", "nom", "B1")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b1_batch4.ps1", $new_words, $utf8NoBom)
