$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE S (B2) ---
    ("le satellite", "satellite", "der Satellit", "el satélite", "nom", "B2"),
    ("la satisfaction", "satisfaction", "die Zufriedenheit", "la satisfacción", "nom", "B2"),
    ("satisfait", "satisfied", "zufrieden", "satisfecho", "adjectif", "B2"),
    ("satisfaire", "satisfy", "befriedigen", "satisfacer", "verbe", "B2"),
    ("l'économie (argent mis de côté)", "saving", "die Ersparnis", "el ahorro", "nom", "B2"),
    ("l'échelle / la balance", "scale", "die Waage / der Maßstab", "la escala", "nom", "B2"),
    ("le scandale", "scandal", "der Skandal", "el escándalo", "nom", "B2"),
    ("effrayer", "scare", "erschrecken", "asustar", "verbe", "B2"),
    ("l'érudit / le boursier", "scholar", "der Gelehrte", "el erudito", "nom", "B2"),
    ("la bourse d'études", "scholarship", "das Stipendium", "la beca", "nom", "B2"),
    ("gratter", "scratch", "kratzen", "rascar", "verbe", "B2"),
    ("hurler / crier", "scream", "schreien", "gritar", "verbe", "B2"),
    ("le dépistage / la projection", "screening", "das Screening / die Vorführung", "la proyección / el cribado", "nom", "B2"),
    ("le secteur", "sector", "der Sektor", "el sector", "nom", "B2"),
    ("sécuriser / obtenir", "secure", "sichern", "asegurar", "verbe", "B2"),
    ("chercher", "seek", "suchen", "buscar", "verbe", "B2"),
    ("le chercheur / le demandeur", "seeker", "der Suchende", "el buscador", "nom", "B2"),
    ("sélectionner", "select", "auswählen", "seleccionar", "verbe", "B2"),
    ("la sélection", "selection", "die Auswahl", "la selección", "nom", "B2"),
    ("le soi / la propre personne", "self", "das Selbst", "el yo", "nom", "B2"),
    ("le séminaire", "seminar", "das Seminar", "el seminario", "nom", "B2"),
    ("supérieur / aîné", "senior", "senior", "mayor / superior", "adjectif", "B2"),
    ("sensible", "sensitive", "sensibel", "sensible", "adjectif", "B2"),
    ("la séquence", "sequence", "die Sequenz", "la secuencia", "nom", "B2"),
    ("la session", "session", "die Sitzung", "la sesión", "nom", "B2"),
    ("régler / s'installer", "settle", "siedeln / klären", "establecerse / resolver", "verbe", "B2"),
    ("le colon (qui s'établit)", "settler", "der Siedler", "el colono", "nom", "B2"),
    ("sévère / grave", "severe", "schwer", "severo", "adjectif", "B2"),
    ("sévèrement", "severely", "schwerwiegend", "severamente", "adverbe", "B2"),
    ("sexy", "sexy", "sexy", "sexy", "adjectif", "B2"),
    ("l'ombre (espace ombragé)", "shade", "der Schatten", "la sombra", "nom", "B2"),
    ("l'ombre (forme projetée)", "shadow", "der Schatten", "la sombra (silueta)", "nom", "B2"),
    ("peu profond / superficiel", "shallow", "flach", "poco profundo", "adjectif", "B2"),
    ("la honte", "shame", "die Schande", "la vergüenza", "nom", "B2"),
    ("en forme de", "shaped", "geformt", "en forma de", "adjectif", "B2"),
    ("l'abri", "shelter", "der Unterschlupf", "el refugio", "nom", "B2"),
    ("la fusillade / le tournage", "shooting", "die Schießerei", "el tiroteo / el rodaje", "nom", "B2"),
    ("le rivage", "shore", "das Ufer", "la orilla", "nom", "B2"),
    ("à court terme", "short-term", "kurzfristig", "a corto plazo", "adjectif", "B2"),
    ("la pénurie", "shortage", "der Mangel", "la escasez", "nom", "B2"),
    ("bientôt / sous peu", "shortly", "in Kürze", "en breve", "adverbe", "B2"),
    ("le frère ou la sœur", "sibling", "das Geschwister", "el hermano o hermana", "nom", "B2"),
    ("le trottoir (US)", "sidewalk", "der Bürgersteig", "la acera", "nom", "B2"),
    ("la signature", "signature", "die Unterschrift", "la firma", "nom", "B2"),
    ("la signification / l'importance", "significance", "die Bedeutung", "el significado / la importancia", "nom", "B2"),
    ("significatif", "significant", "bedeutend", "significativo", "adjectif", "B2"),
    ("significativement", "significantly", "erheblich", "significativamente", "adverbe", "B2"),
    ("le silence", "silence", "die Stille", "el silencio", "nom", "B2"),
    ("la soie", "silk", "die Seide", "la seda", "nom", "B2"),
    ("sincère", "sincere", "aufrichtig", "sincero", "adjectif", "B2"),
    ("qualifié / habile", "skilled", "qualifiziert", "experto", "adjectif", "B2"),
    ("le crâne", "skull", "der Schädel", "el cráneo", "nom", "B2"),
    ("l'esclave", "slave", "der Sklave", "el esclavo", "nom", "B2"),
    ("glisser", "slide", "rutschen", "deslizarse", "verbe", "B2"),
    ("léger / infime", "slight", "leicht", "ligero", "adjectif", "B2"),
    ("glisser / déraper", "slip", "ausrutschen", "resbalar", "verbe", "B2"),
    ("le slogan", "slogan", "der Slogan", "el eslogan", "nom", "B2"),
    ("la pente", "slope", "der Hang", "la pendiente", "nom", "B2"),
    ("soi-disant", "so-called", "sogenannt", "llamado", "adjectif", "B2"),
    ("solaire", "solar", "Solar-", "solar", "adjectif", "B2"),
    ("d'une manière ou d'une autre", "somehow", "irgendwie", "de alguna manera", "adverbe", "B2"),
    ("un jour (futur/passé)", "sometime", "irgendwann", "algún día", "adverbe", "B2"),
    ("quelque peu", "somewhat", "etwas", "un poco", "adverbe", "B2"),
    ("sophistiqué", "sophisticated", "anspruchsvoll", "sofisticado", "adjectif", "B2"),
    ("l'âme", "soul", "die Seele", "el alma", "nom", "B2"),
    ("la source", "source", "die Quelle", "la fuente", "nom", "B2"),
    ("de rechange / libre", "spare", "überschüssig / Ersatz-", "de repuesto", "adjectif", "B2"),
    ("se spécialiser", "specialise", "sich spezialisieren", "especializarse", "verbe", "B2"),
    ("le spécialiste", "specialist", "der Spezialist", "el especialista", "nom", "B2"),
    ("l'espèce", "species", "die Art", "la especie", "nom", "B2"),
    ("spécifier", "specify", "angeben", "especificar", "verbe", "B2"),
    ("spectaculaire", "spectacular", "spektakulär", "espectacular", "adjectif", "B2"),
    ("le spectateur (sport)", "spectator", "der Zuschauer", "el espectador", "nom", "B2"),
    ("spéculer", "speculate", "spekulieren", "especular", "verbe", "B2"),
    ("la spéculation", "speculation", "die Spekulation", "la especulación", "nom", "B2"),
    ("l'épice", "spice", "das Gewürz", "la especia", "nom", "B2"),
    ("renverser (liquide)", "spill", "verschütten", "derramar", "verbe", "B2"),
    ("spirituel", "spiritual", "spirituell", "espiritual", "adjectif", "B2"),
    ("en dépit de", "in spite of", "trotz", "a pesar de", "prep", "B2"),
    ("fendre / diviser", "split", "teilen", "dividir", "verbe", "B2"),
    ("gâcher / gâter", "spoil", "verderben", "estropear", "verbe", "B2"),
    ("le porte-parole", "spokesman", "der Sprecher", "el portavoz", "nom", "B2"),
    ("le porte-parole (neutre)", "spokesperson", "der Sprecher", "el portavoz", "nom", "B2"),
    ("la porte-parole", "spokeswoman", "die Sprecherin", "la portavoz", "nom", "B2"),
    ("le sponsor / le parrain", "sponsor", "der Sponsor", "el patrocinador", "nom", "B2"),
    ("sponsoriser", "sponsor", "sponsern", "patrocinar", "verbe", "B2"),
    ("le parrainage", "sponsorship", "das Sponsoring", "el patrocinio", "nom", "B2"),
    ("stable", "stable", "stabil", "estable", "adjectif", "B2"),
    ("le stand", "stall", "der Stand", "el puesto", "nom", "B2"),
    ("la position (opinion)", "stance", "die Haltung", "la postura", "nom", "B2"),
    ("fixer (du regard)", "stare", "starren", "mirar fijamente", "verbe", "B2"),
    ("mourir de faim", "starve", "verhungern", "morir de hambre", "verbe", "B2"),
    ("la statistique", "statistic", "die Statistik", "la estadística", "nom", "B2"),
    ("le statut", "status", "der Status", "el estatus", "nom", "B2"),
    ("régulièrement", "steadily", "stetig", "constantemente", "adverbe", "B2"),
    ("constant / régulier", "steady", "stetig", "estable", "adjectif", "B2"),
    ("la vapeur", "steam", "der Dampf", "el vapor", "nom", "B2"),
    ("l'acier", "steel", "der Stahl", "el acero", "nom", "B2"),
    ("raide / abrupt", "steep", "steil", "empinado", "adjectif", "B2"),
    ("collant", "sticky", "klebrig", "pegajoso", "adjectif", "B2"),
    ("rigide / raide", "stiff", "steif", "rígido", "adjectif", "B2"),
    ("stimuler", "stimulate", "stimulieren", "estimular", "verbe", "B2"),
    ("le stock / l'action (bourse)", "stock", "der Bestand / die Aktie", "las acciones / el inventario", "nom", "B2"),
    ("le ruisseau / le flux", "stream", "der Bach", "el arroyo", "nom", "B2"),
    ("renforcer", "strengthen", "stärken", "fortalecer", "verbe", "B2"),
    ("s'étirer / étendre", "stretch", "strecken", "estirar", "verbe", "B2"),
    ("strict", "strict", "streng", "estricto", "adjectif", "B2"),
    ("strictement", "strictly", "streng", "estrictamente", "adverbe", "B2"),
    ("la grève", "strike", "der Streik", "la huelga", "nom", "B2"),
    ("frapper", "strike", "schlagen", "golpear", "verbe", "B2"),
    ("frappant", "striking", "auffallend", "llamativo", "adjectif", "B2"),
    ("l'accident vasculaire cérébral / le coup", "stroke", "der Schlaganfall", "el derrame cerebral / el golpe", "nom", "B2"),
    ("lutter", "struggle", "kämpfen", "luchar", "verbe", "B2"),
    ("superbe / éblouissant", "stunning", "atemberaubend", "deslumbrante", "adjectif", "B2"),
    ("soumettre", "submit", "einreichen", "enviar / someter", "verbe", "B2"),
    ("la substance", "substance", "die Substanz", "la sustancia", "nom", "B2"),
    ("la banlieue", "suburb", "der Vorort", "el suburbio", "nom", "B2"),
    ("la souffrance", "suffering", "das Leiden", "el sufrimiento", "nom", "B2"),
    ("suffisant", "sufficient", "ausreichend", "suficiente", "adjectif", "B2"),
    ("suffisamment", "sufficiently", "ausreichend", "suficientemente", "adverbe", "B2"),
    ("la somme", "sum", "die Summe", "la suma", "nom", "B2"),
    ("super", "super", "super", "súper", "adjectif", "B2"),
    ("le chirurgien", "surgeon", "der Chirurg", "el cirujano", "nom", "B2"),
    ("la chirurgie", "surgery", "die Operation", "la cirugía", "nom", "B2"),
    ("entourer", "surround", "umgeben", "rodear", "verbe", "B2"),
    ("environnant", "surrounding", "umliegend", "circundante", "adjectif", "B2"),
    ("la survie", "survival", "das Überleben", "la supervivencia", "nom", "B2"),
    ("le survivant", "survivor", "der Überlebende", "el sobreviviente", "nom", "B2"),
    ("le suspect", "suspect", "der Verdächtige", "el sospechoso", "nom", "B2"),
    ("suspecter / se douter", "suspect", "verdächtigen", "sospechar", "verbe", "B2"),
    ("suspendre", "suspend", "suspendieren", "suspender", "verbe", "B2"),
    ("la durabilité", "sustainability", "die Nachhaltigkeit", "la sostenibilidad", "nom", "B2"),
    ("durable", "sustainable", "nachhaltig", "sostenible", "adjectif", "B2"),
    ("avaler", "swallow", "schlucken", "tragar", "verbe", "B2"),
    ("jurer", "swear", "schwören", "jurar", "verbe", "B2"),
    ("balayer", "sweep", "fegen", "barrer", "verbe", "B2"),
    ("le symbole", "symbol", "das Symbol", "el símbolo", "nom", "B2"),
    ("symboliser", "symbolise", "symbolisieren", "simbolizar", "verbe", "B2"),
    ("compatissant", "sympathetic", "mitfühlend", "compasivo", "adjectif", "B2"),
    ("la compassion / la sympathie", "sympathy", "das Mitgefühl", "la simpatía", "nom", "B2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b2_batch9.ps1", $new_words, $utf8NoBom)
