$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE D (B2) ---
    ("les produits laitiers", "dairy", "die Molkereiprodukte", "los lácteos", "nom", "B2"),
    ("laitier", "dairy", "Molkerei-", "lácteo", "adjectif", "B2"),
    ("oser", "dare", "wagen", "atreverse", "verbe", "B2"),
    ("l'obscurité", "darkness", "die Dunkelheit", "la oscuridad", "nom", "B2"),
    ("les données", "data", "die Daten", "los datos", "nom", "B2"),
    ("la base de données", "database", "die Datenbank", "la base de datos", "nom", "B2"),
    ("la date limite", "deadline", "die Frist", "la fecha límite", "nom", "B2"),
    ("mortel", "deadly", "tödlich", "mortal", "adjectif", "B2"),
    ("le concessionnaire / le revendeur", "dealer", "der Händler", "el distribuidor", "nom", "B2"),
    ("le débat", "debate", "die Debatte", "el debate", "nom", "B2"),
    ("débattre", "debate", "debattieren", "debatir", "verbe", "B2"),
    ("la dette", "debt", "die Schulden", "la deuda", "nom", "B2"),
    ("décent", "decent", "anständig", "decente", "adjectif", "B2"),
    ("le pont (bateau)", "deck", "das Deck", "la cubierta", "nom", "B2"),
    ("déclarer", "declare", "erklären", "declarar", "verbe", "B2"),
    ("le déclin", "decline", "der Rückgang", "el declive", "nom", "B2"),
    ("décliner", "decline", "ablehnen / abnehmen", "rechazar / declinar", "verbe", "B2"),
    ("la décoration", "decoration", "die Dekoration", "la decoración", "nom", "B2"),
    ("la diminution", "decrease", "die Abnahme", "la disminución", "nom", "B2"),
    ("diminuer", "decrease", "abnehmen", "disminuir", "verbe", "B2"),
    ("profondément", "deeply", "tief", "profundamente", "adverbe", "B2"),
    ("la défaite", "defeat", "die Niederlage", "la derrota", "nom", "B2"),
    ("vaincre", "defeat", "besiegen", "derrotar", "verbe", "B2"),
    ("la défense", "defence", "die Verteidigung", "la defensa", "nom", "B2"),
    ("défendre", "defend", "verteidigen", "defender", "verbe", "B2"),
    ("le défenseur", "defender", "der Verteidiger", "el defensor", "nom", "B2"),
    ("définir", "define", "definieren", "definir", "verbe", "B2"),
    ("la définition", "definition", "die Definition", "la definición", "nom", "B2"),
    ("le retard", "delay", "die Verzögerung", "el retraso", "nom", "B2"),
    ("retarder", "delay", "verzögern", "retrasar", "verbe", "B2"),
    ("supprimer / effacer", "delete", "löschen", "eliminar", "verbe", "B2"),
    ("délibéré", "deliberate", "absichtlich", "deliberado", "adjectif", "B2"),
    ("délibérément", "deliberately", "absichtlich", "deliberadamente", "adverbe", "B2"),
    ("le plaisir / le délice", "delight", "die Freude", "el deleite", "nom", "B2"),
    ("ravi", "delighted", "erfreut", "encantado", "adjectif", "B2"),
    ("la livraison", "delivery", "die Lieferung", "la entrega", "nom", "B2"),
    ("la demande / l'exigence", "demand", "die Nachfrage", "la demanda", "nom", "B2"),
    ("exiger", "demand", "fordern", "exigir", "verbe", "B2"),
    ("la démocratie", "democracy", "die Demokratie", "la democracia", "nom", "B2"),
    ("démocratique", "democratic", "demokratisch", "democrático", "adjectif", "B2"),
    ("démontrer / manifester", "demonstrate", "demonstrieren", "demostrar", "verbe", "B2"),
    ("la manifestation / la démonstration", "demonstration", "die Demonstration", "la manifestación", "nom", "B2"),
    ("nier", "deny", "leugnen", "negar", "verbe", "B2"),
    ("partir / décoller", "depart", "abreisen", "partir", "verbe", "B2"),
    ("dépendant", "dependent", "abhängig", "dependiente", "adjectif", "B2"),
    ("l'acompte / le dépôt", "deposit", "die Anzahlung", "el depósito", "nom", "B2"),
    ("déposer", "deposit", "deponieren", "depositar", "verbe", "B2"),
    ("déprimé", "depressed", "deprimiert", "deprimido", "adjectif", "B2"),
    ("déprimant", "depressing", "deprimierend", "deprimente", "adjectif", "B2"),
    ("la dépression", "depression", "die Depression", "la depresión", "nom", "B2"),
    ("la profondeur", "depth", "die Tiefe", "la profundidad", "nom", "B2"),
    ("dériver / tirer", "derive", "ableiten", "derivar", "verbe", "B2"),
    ("mériter", "deserve", "verdienen", "merecer", "verbe", "B2"),
    ("le désir", "desire", "das Verlangen", "el deseo", "nom", "B2"),
    ("désirer", "desire", "begehren", "desear", "verbe", "B2"),
    ("désespéré", "desperate", "verzweifelt", "desesperado", "adjectif", "B2"),
    ("désespérément", "desperately", "verzweifelt", "desesperadamente", "adverbe", "B2"),
    ("la destruction", "destruction", "die Zerstörung", "la destrucción", "nom", "B2"),
    ("détaillé", "detailed", "detailliert", "detallado", "adjectif", "B2"),
    ("détecter", "detect", "erkennen", "detectar", "verbe", "B2"),
    ("déterminer", "determine", "bestimmen", "determinar", "verbe", "B2"),
    ("la détermination", "determination", "die Entschlossenheit", "la determinación", "nom", "B2"),
    ("le diable", "devil", "der Teufel", "el diablo", "nom", "B2"),
    ("consacrer", "devote", "widmen", "dedicar", "verbe", "B2"),
    ("différer", "differ", "sich unterscheiden", "diferir", "verbe", "B2"),
    ("creuser", "dig", "graben", "cavar", "verbe", "B2"),
    ("la pièce de 10 cents", "dime", "der Zehnpfennig", "la moneda de diez centavos", "nom", "B2"),
    ("le handicap", "disability", "die Behinderung", "la discapacidad", "nom", "B2"),
    ("handicapé", "disabled", "behindert", "discapacitado", "adjectif", "B2"),
    ("le désaccord", "disagreement", "die Meinungsverschiedenheit", "el desacuerdo", "nom", "B2"),
    ("décevoir", "disappoint", "enttäuschen", "decepcionar", "verbe", "B2"),
    ("la déception", "disappointment", "die Enttäuschung", "la decepción", "nom", "B2"),
    ("le disque", "disc", "die Scheibe", "el disco", "nom", "B2"),
    ("la discipline", "discipline", "die Disziplin", "la disciplina", "nom", "B2"),
    ("décourager", "discourage", "entmutigen", "desanimar", "verbe", "B2"),
    ("malhonnête", "dishonest", "unehrlich", "deshonesto", "adjectif", "B2"),
    ("rejeter / renvoyer", "dismiss", "entlassen", "despedir / descartar", "verbe", "B2"),
    ("le trouble / le désordre", "disorder", "die Störung", "el trastorno", "nom", "B2"),
    ("l'affichage", "display", "die Anzeige", "la pantalla / la exhibición", "nom", "B2"),
    ("afficher / exposer", "display", "anzeigen", "exhibir / mostrar", "verbe", "B2"),
    ("lointain", "distant", "entfernt", "distante", "adjectif", "B2"),
    ("distinct", "distinct", "deutlich", "distinto", "adjectif", "B2"),
    ("distinguer", "distinguish", "unterscheiden", "distinguir", "verbe", "B2"),
    ("distraire", "distract", "ablenken", "distraer", "verbe", "B2"),
    ("distribuer", "distribute", "verteilen", "distribuir", "verbe", "B2"),
    ("la distribution", "distribution", "die Verteilung", "la distribución", "nom", "B2"),
    ("le district", "district", "der Bezirk", "el distrito", "nom", "B2"),
    ("déranger", "disturb", "stören", "molestar", "verbe", "B2"),
    ("plonger", "dive", "tauchen", "bucear", "verbe", "B2"),
    ("divers", "diverse", "vielfältig", "diverso", "adjectif", "B2"),
    ("la diversité", "diversity", "die Vielfalt", "la diversidad", "nom", "B2"),
    ("la division", "division", "die Abteilung", "la división", "nom", "B2"),
    ("le divorce", "divorce", "die Scheidung", "el divorcio", "nom", "B2"),
    ("divorcer", "divorce", "sich scheiden lassen", "divorciarse", "verbe", "B2"),
    ("le document", "document", "das Dokument", "el documento", "nom", "B2"),
    ("documenter", "document", "dokumentieren", "documentar", "verbe", "B2"),
    ("domestique", "domestic", "inländisch / häuslich", "nacional / doméstico", "adjectif", "B2"),
    ("dominant", "dominant", "dominant", "dominante", "adjectif", "B2"),
    ("dominer", "dominate", "dominieren", "dominar", "verbe", "B2"),
    ("le don", "donation", "die Spende", "la donación", "nom", "B2"),
    ("le point", "dot", "der Punkt", "el punto", "nom", "B2"),
    ("vers le bas", "downwards", "abwärts", "hacia abajo", "adverbe", "B2"),
    ("la douzaine", "dozen", "das Dutzend", "la docena", "nom", "B2"),
    ("le brouillon", "draft", "der Entwurf", "el borrador", "nom", "B2"),
    ("rédiger (un brouillon)", "draft", "entwerfen", "redactar", "verbe", "B2"),
    ("traîner (par terre)", "drag", "ziehen", "arrastrar", "verbe", "B2"),
    ("dramatique / spectaculaire", "dramatic", "dramatisch", "dramático", "adjectif", "B2"),
    ("spectaculairement", "dramatically", "dramatisch", "dramáticamente", "adverbe", "B2"),
    ("la sécheresse", "drought", "die Dürre", "la sequía", "nom", "B2"),
    ("terne / ennuyeux", "dull", "langweilig", "aburrido", "adjectif", "B2"),
    ("jeter / larguer", "dump", "abladen", "arrojar", "verbe", "B2"),
    ("la durée", "duration", "die Dauer", "la duración", "nom", "B2"),
    ("dynamique", "dynamic", "dynamisch", "dinámico", "adjectif", "B2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b2_batch5.ps1", $new_words, $utf8NoBom)
