$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE P (B2) ---
    ("le rythme / l'allure", "pace", "das Tempo", "el ritmo", "nom", "B2"),
    ("faire les cent pas", "pace", "auf und ab gehen", "caminar de un lado a otro", "verbe", "B2"),
    ("le paquet", "packet", "das Paket", "el paquete", "nom", "B2"),
    ("la paume / le palmier", "palm", "die Handfläche / die Palme", "la palma", "nom", "B2"),
    ("le panneau / le comité", "panel", "das Panel", "el panel", "nom", "B2"),
    ("la panique", "panic", "die Panik", "el pánico", "nom", "B2"),
    ("paniquer", "panic", "in Panik geraten", "entrar en pánico", "verbe", "B2"),
    ("le défilé", "parade", "die Parade", "el desfile", "nom", "B2"),
    ("parallèle", "parallel", "parallel", "paralelo", "adjectif", "B2"),
    ("le parlement", "parliament", "das Parlament", "el parlamento", "nom", "B2"),
    ("à temps partiel", "part-time", "Teilzeit-", "a tiempo parcial", "adjectif", "B2"),
    ("le participant", "participant", "der Teilnehmer", "el participante", "nom", "B2"),
    ("la participation", "participation", "die Teilnahme", "la participación", "nom", "B2"),
    ("en partie", "partly", "teilweise", "en parte", "adverbe", "B2"),
    ("le partenariat", "partnership", "die Partnerschaft", "la asociación", "nom", "B2"),
    ("le passage", "passage", "die Durchfahrt / der Abschnitt", "el pasaje", "nom", "B2"),
    ("passionné", "passionate", "leidenschaftlich", "apasionado", "adjectif", "B2"),
    ("le mot de passe", "password", "das Passwort", "la contraseña", "nom", "B2"),
    ("la rustine / le patch", "patch", "der Flicken", "el parche", "nom", "B2"),
    ("la patience", "patience", "die Geduld", "la paciencia", "nom", "B2"),
    ("la pause", "pause", "die Pause", "la pausa", "nom", "B2"),
    ("faire une pause", "pause", "pausieren", "hacer una pausa", "verbe", "B2"),
    ("le pair (collègue/égal)", "peer", "der Gleichaltrige", "el compañero", "nom", "B2"),
    ("la peine / la pénalité", "penalty", "die Strafe", "la penalidad", "nom", "B2"),
    ("la pension (retraite)", "pension", "die Rente", "la pensión", "nom", "B2"),
    ("percevoir", "perceive", "wahrnehmen", "percibir", "verbe", "B2"),
    ("la perception", "perception", "die Wahrnehmung", "la percepción", "nom", "B2"),
    ("permanent", "permanent", "dauerhaft", "permanente", "adjectif", "B2"),
    ("en permanence", "permanently", "dauerhaft", "permanentemente", "adverbe", "B2"),
    ("le permis", "permit", "die Genehmigung", "el permiso", "nom", "B2"),
    ("permettre", "permit", "erlauben", "permitir", "verbe", "B2"),
    ("la perspective", "perspective", "die Perspektive", "la perspectiva", "nom", "B2"),
    ("la pharmacie", "pharmacy", "die Apotheke", "la farmacia", "nom", "B2"),
    ("la phase", "phase", "die Phase", "la fase", "nom", "B2"),
    ("le phénomène", "phenomenon", "das Phänomen", "el fenómeno", "nom", "B2"),
    ("la philosophie", "philosophy", "die Philosophie", "la filosofía", "nom", "B2"),
    ("le médecin", "physician", "der Arzt", "el médico", "nom", "B2"),
    ("le tas / la pile", "pile", "der Stapel", "la pila", "nom", "B2"),
    ("empiler", "pile", "stapeln", "apilar", "verbe", "B2"),
    ("la pilule", "pill", "die Pille", "la píldora", "nom", "B2"),
    ("le terrain / la hauteur (son)", "pitch", "das Spielfeld / die Tonhöhe", "el campo / el tono", "nom", "B2"),
    ("la pitié / le dommage", "pity", "das Mitleid", "la piedad / la lástima", "nom", "B2"),
    ("le placement / le stage", "placement", "die Vermittlung / das Praktikum", "la colocación", "nom", "B2"),
    ("uni / simple (pas compliqué)", "plain", "schlicht", "liso / simple", "adjectif", "B2"),
    ("pointu", "pointed", "spitz", "puntiagudo", "adjectif", "B2"),
    ("la popularité", "popularity", "die Popularität", "la popularidad", "nom", "B2"),
    ("la portion", "portion", "die Portion", "la porción", "nom", "B2"),
    ("la pose", "pose", "die Pose", "la pose", "nom", "B2"),
    ("poser (pour photo) / constituer", "pose", "posieren", "posar", "verbe", "B2"),
    ("positif", "positive", "positiv", "positivo", "adjectif", "B2"),
    ("posséder", "possess", "besitzen", "poseer", "verbe", "B2"),
    ("le potentiel", "potential", "das Potenzial", "el potencial", "nom", "B2"),
    ("potentiel", "potential", "potenziell", "potencial", "adjectif", "B2"),
    ("potentiellement", "potentially", "möglicherweise", "potencialmente", "adverbe", "B2"),
    ("louer (féliciter)", "praise", "loben", "alabar", "verbe", "B2"),
    ("précieux", "precious", "wertvoll", "precioso", "adjectif", "B2"),
    ("précis", "precise", "präzise", "preciso", "adjectif", "B2"),
    ("précisément", "precisely", "genau", "precisamente", "adverbe", "B2"),
    ("prévisible", "predictable", "vorhersehbar", "predecible", "adjectif", "B2"),
    ("la préférence", "preference", "die Vorliebe", "la preferencia", "nom", "B2"),
    ("enceinte", "pregnant", "schwanger", "embarazada", "adjectif", "B2"),
    ("la préparation", "preparation", "die Vorbereitung", "la preparación", "nom", "B2"),
    ("la présence", "presence", "die Präsenz", "la presencia", "nom", "B2"),
    ("préserver", "preserve", "erhalten", "preservar", "verbe", "B2"),
    ("présidentiel", "presidential", "präsidentiell", "presidencial", "adjectif", "B2"),
    ("la fierté", "pride", "der Stolz", "el orgullo", "nom", "B2"),
    ("principalement", "primarily", "hauptsächlich", "principalmente", "adverbe", "B2"),
    ("premier / de premier ordre", "prime", "Haupt-", "principal", "adjectif", "B2"),
    ("principal / le directeur", "principal", "Haupt-", "principal", "adjectif", "B2"),
    ("le principe", "principle", "das Prinzip", "el principio", "nom", "B2"),
    ("préalable", "prior", "vorherig", "previo", "adjectif", "B2"),
    ("la priorité", "priority", "die Priorität", "la prioridad", "nom", "B2"),
    ("la vie privée", "privacy", "die Privatsphäre", "la privacidad", "nom", "B2"),
    ("la probabilité", "probability", "die Wahrscheinlichkeit", "la probabilidad", "nom", "B2"),
    ("probable", "probable", "wahrscheinlich", "probable", "adjectif", "B2"),
    ("la procédure", "procedure", "das Verfahren", "el procedimiento", "nom", "B2"),
    ("procéder / avancer", "proceed", "fortfahren", "proceder", "verbe", "B2"),
    ("professionnel", "professional", "professionell", "profesional", "adjectif", "B2"),
    ("la programmation", "programming", "die Programmierung", "la programación", "nom", "B2"),
    ("progressif", "progressive", "fortschrittlich", "progresivo", "adjectif", "B2"),
    ("interdire", "prohibit", "verbieten", "prohibir", "verbe", "B2"),
    ("prometteur", "promising", "vielversprechend", "prometedor", "adjectif", "B2"),
    ("la promotion", "promotion", "die Beförderung", "la promoción", "nom", "B2"),
    ("inciter / provoquer", "prompt", "veranlassen", "provocar", "verbe", "B2"),
    ("la preuve", "proof", "der Beweis", "la prueba", "nom", "B2"),
    ("la proportion", "proportion", "die Proportion", "la proporción", "nom", "B2"),
    ("la proposition", "proposal", "der Vorschlag", "la propuesta", "nom", "B2"),
    ("proposer", "propose", "vorschlagen", "proponer", "verbe", "B2"),
    ("la perspective (d'avenir)", "prospect", "die Aussicht", "la perspectiva", "nom", "B2"),
    ("la protection", "protection", "der Schutz", "la protección", "nom", "B2"),
    ("la protéine", "protein", "das Protein", "la proteína", "nom", "B2"),
    ("le manifestant", "protester", "der Demonstrant", "el manifestante", "nom", "B2"),
    ("prouvé", "proven", "erwiesen", "probado", "adjectif", "B2"),
    ("psychologique", "psychological", "psychologisch", "psicológico", "adjectif", "B2"),
    ("le psychologue", "psychologist", "der Psychologe", "el psicólogo", "nom", "B2"),
    ("la psychologie", "psychology", "die Psychologie", "la psicología", "nom", "B2"),
    ("la publication", "publication", "die Veröffentlichung", "la publicación", "nom", "B2"),
    ("la publicité (attention médiatique)", "publicity", "die Öffentlichkeit", "la publicidad", "nom", "B2"),
    ("l'édition (industrie)", "publishing", "das Verlagswesen", "la edición", "nom", "B2"),
    ("le punk", "punk", "der Punk", "el punk", "nom", "B2"),
    ("l'élève", "pupil", "der Schüler", "el alumno", "nom", "B2"),
    ("l'achat", "purchase", "der Kauf", "la compra", "nom", "B2"),
    ("acheter", "purchase", "kaufen", "comprar", "verbe", "B2"),
    ("pur", "pure", "rein", "puro", "adjectif", "B2"),
    ("purement", "purely", "rein", "puramente", "adverbe", "B2"),
    ("poursuivre", "pursue", "verfolgen", "perseguir", "verbe", "B2"),
    ("la poursuite", "pursuit", "das Streben", "la búsqueda / la persecución", "nom", "B2"),
    ("le casse-tête / le puzzle", "puzzle", "das Rätsel", "el rompecabezas", "nom", "B2"),

    # --- LETTRE Q (B2) ---
    ("interroger / remettre en question", "question", "hinterfragen", "cuestionar", "verbe", "B2"),
    ("le questionnaire", "questionnaire", "der Fragebogen", "el cuestionario", "nom", "B2"),

    # --- LETTRE R (B2) ---
    ("racial", "racial", "rassisch", "racial", "adjectif", "B2"),
    ("le racisme", "racism", "der Rassismus", "el racismo", "nom", "B2"),
    ("raciste", "racist", "rassistisch", "racista", "adjectif", "B2"),
    ("le radar", "radar", "das Radar", "el radar", "nom", "B2"),
    ("les radiations / le rayonnement", "radiation", "die Strahlung", "la radiación", "nom", "B2"),
    ("le rail", "rail", "die Schiene", "el riel", "nom", "B2"),
    ("aléatoire", "random", "zufällig", "aleatorio", "adjectif", "B2"),
    ("le rang", "rank", "der Rang", "el rango", "nom", "B2"),
    ("classer", "rank", "einstufen", "clasificar", "verbe", "B2"),
    ("rapide", "rapid", "schnell", "rápido", "adjectif", "B2"),
    ("rapidement", "rapidly", "schnell", "rápidamente", "adverbe", "B2"),
    ("cru", "raw", "roh", "crudo", "adjectif", "B2"),
    ("réaliste", "realistic", "realistisch", "realista", "adjectif", "B2"),
    ("raisonnable", "reasonable", "vernünftig", "razonable", "adjectif", "B2"),
    ("raisonnablement", "reasonably", "angemessen", "razonablemente", "adverbe", "B2"),
    ("reconstruire", "rebuild", "wiederaufbauen", "reconstruir", "verbe", "B2"),
    ("se rappeler", "recall", "sich erinnern", "recordar", "verbe", "B2"),
    ("le récepteur", "receiver", "der Empfänger", "el receptor", "nom", "B2"),
    ("la récession", "recession", "die Rezession", "la recesión", "nom", "B2"),
    ("estimer / calculer", "reckon", "schätzen", "calcular", "verbe", "B2"),
    ("la reconnaissance", "recognition", "die Anerkennung", "el reconocimiento", "nom", "B2"),
    ("récupérer / se rétablir", "recover", "sich erholen", "recuperarse", "verbe", "B2"),
    ("la récupération / le rétablissement", "recovery", "die Genesung", "la recuperación", "nom", "B2"),
    ("recruter", "recruit", "rekrutieren", "reclutar", "verbe", "B2"),
    ("la réduction", "reduction", "die Reduzierung", "la reducción", "nom", "B2"),
    ("l'arbitre", "referee", "der Schiedsrichter", "el árbitro", "nom", "B2"),
    ("le réfugié", "refugee", "der Flüchtling", "el refugiado", "nom", "B2"),
    ("considérer", "regard", "betrachten", "considerar", "verbe", "B2"),
    ("régional", "regional", "regional", "regional", "adjectif", "B2"),
    ("inscrire / enregistrer", "register", "registrieren", "registrar", "verbe", "B2"),
    ("l'inscription", "registration", "die Registrierung", "el registro", "nom", "B2"),
    ("regretter", "regret", "bedauern", "arrepentirse", "verbe", "B2"),
    ("réguler / réglementer", "regulate", "regulieren", "regular", "verbe", "B2"),
    ("le règlement", "regulation", "die Vorschrift", "la regulación", "nom", "B2"),
    ("renforcer", "reinforce", "verstärken", "reforzar", "verbe", "B2"),
    ("relativement", "relatively", "relativ", "relativamente", "adverbe", "B2"),
    ("pertinent", "relevant", "relevant", "relevante", "adjectif", "B2"),
    ("le soulagement", "relief", "die Erleichterung", "el alivio", "nom", "B2"),
    ("soulager", "relieve", "erleichtern", "aliviar", "verbe", "B2"),
    ("soulagé", "relieved", "erleichtert", "aliviado", "adjectif", "B2"),
    ("compter sur", "rely on", "sich verlassen auf", "confiar en", "verbe", "B2"),
    ("la remarque", "remark", "die Bemerkung", "el comentario", "nom", "B2"),
    ("remarquer", "remark", "bemerken", "comentar", "verbe", "B2"),
    ("remarquable", "remarkable", "bemerkenswert", "notable", "adjectif", "B2"),
    ("remarquablement", "remarkably", "bemerkenswert", "notablemente", "adverbe", "B2"),
    ("le signalement / le reportage", "reporting", "die Berichterstattung", "los informes", "nom", "B2"),
    ("le représentant", "representative", "der Vertreter", "el representante", "nom", "B2"),
    ("représentatif", "representative", "repräsentativ", "representativo", "adjectif", "B2"),
    ("la réputation", "reputation", "der Ruf", "la reputación", "nom", "B2"),
    ("l'exigence", "requirement", "die Anforderung", "el requisito", "nom", "B2"),
    ("secourir / sauver", "rescue", "retten", "rescatar", "verbe", "B2"),
    ("la recherche (étude)", "research", "die Forschung", "la investigación", "nom", "B2"),
    ("faire des recherches", "research", "forschen", "investigar", "verbe", "B2"),
    ("réserver", "reserve", "reservieren", "reservar", "verbe", "B2"),
    ("le résident", "resident", "der Bewohner", "el residente", "nom", "B2"),
    ("démissionner", "resign", "zurücktreten", "renunciar", "verbe", "B2"),
    ("résister", "resist", "widerstehen", "resistir", "verbe", "B2"),
    ("la résolution", "resolution", "die Lösung / der Vorsatz", "la resolución", "nom", "B2"),
    ("résoudre (problème)", "resolve", "lösen", "resolver", "verbe", "B2"),
    ("la station (vacances) / le recours", "resort", "das Resort", "el centro vacacional", "nom", "B2"),
    ("restaurer", "restore", "wiederherstellen", "restaurar", "verbe", "B2"),
    ("restreindre", "restrict", "einschränken", "restringir", "verbe", "B2"),
    ("la restriction", "restriction", "die Einschränkung", "la restricción", "nom", "B2"),
    ("le CV (curriculum vitae)", "résumé", "der Lebenslauf", "el currículum", "nom", "B2"),
    ("la vente au détail", "retail", "der Einzelhandel", "la venta al por menor", "nom", "B2"),
    ("retenir / conserver", "retain", "behalten", "retener", "verbe", "B2"),
    ("la retraite", "retirement", "der Ruhestand", "la jubilación", "nom", "B2"),
    ("révéler", "reveal", "enthüllen", "revelar", "verbe", "B2"),
    ("le revenu (État/entreprise)", "revenue", "die Einnahmen", "los ingresos", "nom", "B2"),
    ("la révision", "revision", "die Überarbeitung", "la revisión", "nom", "B2"),
    ("la révolution", "revolution", "die Revolution", "la revolución", "nom", "B2"),
    ("la récompense", "reward", "die Belohnung", "la recompensa", "nom", "B2"),
    ("récompenser", "reward", "belohnen", "recompensar", "verbe", "B2"),
    ("le rythme", "rhythm", "der Rhythmus", "el ritmo", "nom", "B2"),
    ("débarrassé de", "rid", "losgeworden", "librado (de)", "adjectif", "B2"),
    ("ridicule", "ridiculous", "lächerlich", "ridículo", "adjectif", "B2"),
    ("risqué", "risky", "riskant", "arriesgado", "adjectif", "B2"),
    ("le rival", "rival", "der Rivale", "el rival", "nom", "B2"),
    ("voler (quelqu'un)", "rob", "ausrauben", "robar", "verbe", "B2"),
    ("le vol (à main armée)", "robbery", "der Raub", "el robo", "nom", "B2"),
    ("la fusée", "rocket", "die Rakete", "el cohete", "nom", "B2"),
    ("la romance", "romance", "die Romantik", "el romance", "nom", "B2"),
    ("la racine", "root", "die Wurzel", "la raíz", "nom", "B2"),
    ("la rose", "rose", "die Rose", "la rosa", "nom", "B2"),
    ("approximativement / grossièrement", "roughly", "ungefähr", "aproximadamente", "adverbe", "B2"),
    ("frotter", "rub", "reiben", "frotar", "verbe", "B2"),
    ("le caoutchouc", "rubber", "der Gummi", "el caucho", "nom", "B2"),
    ("ruiner", "ruin", "ruinieren", "arruinar", "verbe", "B2"),
    ("rural", "rural", "ländlich", "rural", "adjectif", "B2"),
    ("se précipiter", "rush", "eilen", "apresurarse", "verbe", "B2")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b2_batch8.ps1", $new_words, $utf8NoBom)
