$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE C (B1) ---
    ("calme", "calm", "ruhig", "tranquilo", "adjectif", "B1"),
    ("la campagne (militaire/pub)", "campaign", "die Kampagne", "la campaña", "nom", "B1"),
    ("le campus", "campus", "der Campus", "el campus", "nom", "B1"),
    ("le candidat", "candidate", "der Kandidat", "el candidato", "nom", "B1"),
    ("la casquette", "cap", "die Mütze", "la gorra", "nom", "B1"),
    ("le capitaine", "captain", "der Kapitän", "el capitán", "nom", "B1"),
    ("la carrière", "career", "die Karriere", "la carrera", "nom", "B1"),
    ("négligent / imprudent", "careless", "unvorsichtig", "descuidado", "adjectif", "B1"),
    ("la catégorie", "category", "die Kategorie", "la categoría", "nom", "B1"),
    ("le plafond", "ceiling", "die Decke", "el techo", "nom", "B1"),
    ("la célébration", "celebration", "die Feier", "la celebración", "nom", "B1"),
    ("central", "central", "zentral", "central", "adjectif", "B1"),
    ("le siècle", "century", "das Jahrhundert", "el siglo", "nom", "B1"),
    ("la cérémonie", "ceremony", "die Zeremonie", "la ceremonia", "nom", "B1"),
    ("la chaîne", "chain", "die Kette", "la cadena", "nom", "B1"),
    ("le défi", "challenge", "die Herausforderung", "el desafío", "nom", "B1"),
    ("défier", "challenge", "herausfordern", "desafiar", "verbe", "B1"),
    ("le champion", "champion", "der Meister", "el campeón", "nom", "B1"),
    ("le canal / la chaîne", "channel", "der Kanal", "el canal", "nom", "B1"),
    ("le chapitre", "chapter", "das Kapitel", "el capítulo", "nom", "B1"),
    ("la charge (électrique) / l'accusation", "charge", "die Ladung", "la carga", "nom", "B1"),
    ("charger (facturer / accuser)", "charge", "berechnen", "cobrar", "verbe", "B1"),
    ("tricher", "cheat", "betrügen", "hacer trampa", "verbe", "B1"),
    ("joyeux", "cheerful", "fröhlich", "alegre", "adjectif", "B1"),
    ("le produit chimique", "chemical", "die Chemikalie", "el producto químico", "nom", "B1"),
    ("chimique", "chemical", "chemisch", "químico", "adjectif", "B1"),
    ("la poitrine / le coffre", "chest", "die Brust", "el pecho", "nom", "B1"),
    ("l'enfance", "childhood", "die Kindheit", "la infancia", "nom", "B1"),
    ("réclamer / prétendre", "claim", "behaupten", "reclamar", "verbe", "B1"),
    ("la réclamation", "claim", "der Anspruch", "el reclamo", "nom", "B1"),
    ("le clic", "click", "der Klick", "el clic", "nom", "B1"),
    ("cliquer", "click", "klicken", "hacer clic", "verbe", "B1"),
    ("le client", "client", "der Kunde", "el cliente", "nom", "B1"),
    ("proche (relation)", "close", "nah", "cercano", "adjectif", "B1"),
    ("le tissu / le chiffon", "cloth", "das Tuch", "la tela", "nom", "B1"),
    ("l'indice", "clue", "der Hinweis", "la pista", "nom", "B1"),
    ("le coach (sport/vie)", "coach", "der Trainer", "el entrenador", "nom", "B1"),
    ("le charbon", "coal", "die Kohle", "el carbón", "nom", "B1"),
    ("la collection", "collection", "die Sammlung", "la colección", "nom", "B1"),
    ("coloré", "coloured", "farbig", "coloreado", "adjectif", "B1"),
    ("combiner", "combine", "kombinieren", "combinar", "verbe", "B1"),
    ("commenter", "comment", "kommentieren", "comentar", "verbe", "B1"),
    ("commercial", "commercial", "kommerziell", "comercial", "adjectif", "B1"),
    ("la publicité (télé / radio)", "commercial", "der Werbespot", "el anuncio comercial", "nom", "B1"),
    ("s'engager / commettre", "commit", "begehen", "cometer", "verbe", "B1"),
    ("la communication", "communication", "die Kommunikation", "la comunicación", "nom", "B1"),
    ("la comparaison", "comparison", "der Vergleich", "la comparación", "nom", "B1"),
    ("le concurrent", "competitor", "der Konkurrent", "el competidor", "nom", "B1"),
    ("compétitif", "competitive", "wettbewerbsfähig", "competitivo", "adjectif", "B1"),
    ("la plainte", "complaint", "die Beschwerde", "la queja", "nom", "B1"),
    ("complexe", "complex", "komplex", "complejo", "adjectif", "B1"),
    ("se concentrer", "concentrate", "sich konzentrieren", "concentrarse", "verbe", "B1"),
    ("conclure", "conclude", "schließen", "concluir", "verbe", "B1"),
    ("confiant", "confident", "selbstbewusst", "seguro", "adjectif", "B1"),
    ("confirmer", "confirm", "bestätigen", "confirmar", "verbe", "B1"),
    ("confondre", "confuse", "verwirren", "confundir", "verbe", "B1"),
    ("confus", "confused", "verwirrt", "confundido", "adjectif", "B1"),
    ("la connexion", "connection", "die Verbindung", "la conexión", "nom", "B1"),
    ("contacter", "contact", "kontaktieren", "contactar", "verbe", "B1"),
    ("le contact", "contact", "der Kontakt", "el contacto", "nom", "B1"),
    ("le conteneur", "container", "der Behälter", "el contenedor", "nom", "B1"),
    ("le contenu", "content", "der Inhalt", "el contenido", "nom", "B1"),
    ("continu", "continuous", "kontinuierlich", "continuo", "adjectif", "B1"),
    ("le contraste", "contrast", "der Kontrast", "el contraste", "nom", "B1"),
    ("contraster", "contrast", "kontrastieren", "contrastar", "verbe", "B1"),
    ("pratique", "convenient", "praktisch", "conveniente", "adjectif", "B1"),
    ("convaincre", "convince", "überzeugen", "convencer", "verbe", "B1"),
    ("le cuivre", "copper", "das Kupfer", "el cobre", "nom", "B1"),
    ("le costume / le déguisement", "costume", "das Kostüm", "el disfraz", "nom", "B1"),
    ("la chaumière / le chalet", "cottage", "das Ferienhaus", "la cabaña", "nom", "B1"),
    ("le coton", "cotton", "die Baumwolle", "el algodón", "nom", "B1"),
    ("la campagne (paysage)", "countryside", "die Landschaft", "el campo", "nom", "B1"),
    ("le tribunal / le terrain", "court", "das Gericht", "la corte", "nom", "B1"),
    ("la couverture", "cover", "die Abdeckung", "la cubierta", "nom", "B1"),
    ("couvrir", "cover", "bedecken", "cubrir", "verbe", "B1"),
    ("couvert", "covered", "bedeckt", "cubierto", "adjectif", "B1"),
    ("créer", "create", "erstellen", "crear", "verbe", "B1"),
    ("le crédit", "credit", "der Kredit", "el crédito", "nom", "B1"),
    ("cruel", "cruel", "grausam", "cruel", "adjectif", "B1"),
    ("culturel", "cultural", "kulturell", "cultural", "adjectif", "B1"),
    ("la culture", "culture", "die Kultur", "la cultura", "nom", "B1"),
    ("la devise / la monnaie", "currency", "die Währung", "la moneda", "nom", "B1"),
    ("actuel", "current", "aktuell", "actual", "adjectif", "B1"),
    ("actuellement", "currently", "derzeit", "actualmente", "adverbe", "B1"),
    ("le rideau", "curtain", "der Vorhang", "la cortina", "nom", "B1"),
    ("la coutume", "custom", "der Brauch", "la costumbre", "nom", "B1"),

    # --- LETTRE D (B1) ---
    ("les dégâts", "damage", "der Schaden", "el daño", "nom", "B1"),
    ("endommager", "damage", "beschädigen", "dañar", "verbe", "B1"),
    ("traiter / négocier", "deal", "handeln", "tratar", "verbe", "B1"),
    ("la décennie", "decade", "das Jahrzehnt", "la década", "nom", "B1"),
    ("décorer", "decorate", "dekorieren", "decorar", "verbe", "B1"),
    ("le cerf", "deer", "der Hirsch", "el ciervo", "nom", "B1"),
    ("définitif", "definite", "definitiv", "definitivo", "adjectif", "B1"),
    ("livrer", "deliver", "liefern", "entregar", "verbe", "B1"),
    ("le départ", "departure", "die Abfahrt", "la salida", "nom", "B1"),
    ("le bureau (informatique)", "desktop", "der Desktop", "el escritorio", "nom", "B1"),
    ("malgré", "despite", "trotz", "a pesar de", "prep", "B1"),
    ("la destination", "destination", "das Ziel", "el destino", "nom", "B1"),
    ("déterminé", "determined", "entschlossen", "determinado", "adjectif", "B1"),
    ("le développement", "development", "die Entwicklung", "el desarrollo", "nom", "B1"),
    ("le diagramme", "diagram", "das Diagramm", "el diagrama", "nom", "B1"),
    ("le diamant", "diamond", "der Diamant", "el diamante", "nom", "B1"),
    ("la difficulté", "difficulty", "die Schwierigkeit", "la dificultad", "nom", "B1"),
    ("direct / diriger", "direct", "direkt", "directo", "verbe", "B1"),
    ("directement", "directly", "direkt", "directamente", "adverbe", "B1"),
    ("la saleté / la terre", "dirt", "der Schmutz", "la suciedad", "nom", "B1"),
    ("le désavantage", "disadvantage", "der Nachteil", "la desventaja", "nom", "B1"),
    ("déçu", "disappointed", "enttäuscht", "decepcionado", "adjectif", "B1"),
    ("décevant", "disappointing", "enttäuschend", "decepcionante", "adjectif", "B1"),
    ("la remise (prix)", "discount", "der Rabatt", "el descuento", "nom", "B1"),
    ("discuter", "discuss", "diskutieren", "discutir", "verbe", "B1"),
    ("ne pas aimer", "dislike", "nicht mögen", "no gustar", "verbe", "B1"),
    ("diviser", "divide", "teilen", "dividir", "verbe", "B1"),
    ("le documentaire", "documentary", "der Dokumentarfilm", "el documental", "nom", "B1"),
    ("faire un don", "donate", "spenden", "donar", "verbe", "B1"),
    ("le doute", "doubt", "der Zweifel", "la duda", "nom", "B1"),
    ("douter", "doubt", "zweifeln", "dudar", "verbe", "B1"),
    ("habillé", "dressed", "gekleidet", "vestido", "adjectif", "B1"),
    ("ivre", "drunk", "betrunken", "borracho", "adjectif", "B1"),
    ("attendu / dû", "due", "fällig", "debido", "adjectif", "B1"),
    ("la poussière", "dust", "der Staub", "el polvo", "nom", "B1"),
    ("le devoir", "duty", "die Pflicht", "el deber", "nom", "B1")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\add_b1_batch2.ps1", $new_words, $utf8NoBom)
