$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE M ---
    ("la machine", "machine", "die Maschine", "la m\u00e1quina", "nom", "A1"),
    ("le magazine", "magazine", "das Magazin", "la revista", "nom", "A1"),
    ("principal", "main", "haupt-", "principal", "adjectif", "A1"),
    ("faire / fabriquer", "make", "machen", "hacer", "verbe", "A1"),
    ("l'homme", "man", "der Mann", "el hombre", "nom", "A1"),
    ("beaucoup (d\u00e9nombrable)", "many", "viele", "muchos", "det", "A1"),
    ("la carte (g\u00e9ographique)", "map", "die Karte", "el mapa", "nom", "A1"),
    ("mars", "March", "M\u00e4rz", "marzo", "nom", "A1"),
    ("le march\u00e9", "market", "der Markt", "el mercado", "nom", "A1"),
    ("mari\u00e9", "married", "verheiratet", "casado", "adjectif", "A1"),
    ("le match", "match", "das Spiel", "el partido", "nom", "A1"),
    ("la mati\u00e8re / le probl\u00e8me", "matter", "die Angelegenheit", "el asunto", "nom", "A1"),
    ("mai", "May", "Mai", "mayo", "nom", "A1"),
    ("peut-\u00eatre", "maybe", "vielleicht", "tal vez", "adverbe", "A1"),
    ("moi", "me", "mich / mir", "m\u00ed", "pron", "A1"),
    ("le repas", "meal", "die Mahlzeit", "la comida", "nom", "A1"),
    ("signifier", "mean", "bedeuten", "significar", "verbe", "A1"),
    ("la viande", "meat", "das Fleisch", "la carne", "nom", "A1"),
    ("rencontrer", "meet", "treffen", "conocer", "verbe", "A1"),
    ("la r\u00e9union", "meeting", "das Meeting", "la reuni\u00f3n", "nom", "A1"),
    ("le membre", "member", "das Mitglied", "el miembro", "nom", "A1"),
    ("le menu", "menu", "die Speisekarte", "el men\u00fa", "nom", "A1"),
    ("le message", "message", "die Nachricht", "el mensaje", "nom", "A1"),
    ("le m\u00e8tre", "metre", "der Meter", "el metro", "nom", "A1"),
    ("le minuit", "midnight", "die Mitternacht", "la medianoche", "nom", "A1"),
    ("le mile", "mile", "die Meile", "la milla", "nom", "A1"),
    ("le lait", "milk", "die Milch", "la leche", "nom", "A1"),
    ("le million", "million", "die Million", "el mill\u00f3n", "num", "A1"),
    ("la minute", "minute", "die Minute", "el minuto", "nom", "A1"),
    ("manquer", "miss", "vermissen", "extra\u00f1ar", "verbe", "A1"),
    ("l'erreur", "mistake", "der Fehler", "el error", "nom", "A1"),
    ("le mod\u00e8le", "model", "das Modell", "el modelo", "nom", "A1"),
    ("moderne", "modern", "modern", "moderno", "adjectif", "A1"),
    ("le moment", "moment", "der Moment", "el momento", "nom", "A1"),
    ("lundi", "Monday", "Montag", "lunes", "nom", "A1"),
    ("l'argent", "money", "das Geld", "el dinero", "nom", "A1"),
    ("le mois", "month", "der Monat", "el mes", "nom", "A1"),
    ("plus", "more", "mehr", "m\u00e1s", "adverbe", "A1"),
    ("le matin", "morning", "der Morgen", "la ma\u00f1ana", "nom", "A1"),
    ("la plupart", "most", "die meisten", "la mayor\u00eda", "det", "A1"),
    ("la m\u00e8re", "mother", "die Mutter", "la madre", "nom", "A1"),
    ("la montagne", "mountain", "der Berg", "la monta\u00f1a", "nom", "A1"),
    ("la souris", "mouse", "die Maus", "el rat\u00f3n", "nom", "A1"),
    ("la bouche", "mouth", "der Mund", "la boca", "nom", "A1"),
    ("bouger", "move", "bewegen", "mover", "verbe", "A1"),
    ("le film (US)", "movie", "der Film", "la pel\u00edcula", "nom", "A1"),
    ("beaucoup (ind\u00e9nombrable)", "much", "viel", "mucho", "det", "A1"),
    ("le mus\u00e9e", "museum", "das Museum", "el museo", "nom", "A1"),
    ("la musique", "music", "die Musik", "la m\u00fasica", "nom", "A1"),
    ("devoir (obligation)", "must", "m\u00fcssen", "deber", "verbe", "A1"),
    ("mon / ma / mes", "my", "mein", "mi", "det", "A1"),

    # --- LETTRE N ---
    ("le nom", "name", "der Name", "el nombre", "nom", "A1"),
    ("naturel", "natural", "nat\u00fcrlich", "natural", "adjectif", "A1"),
    ("la nature", "nature", "die Natur", "la naturaleza", "nom", "A1"),
    ("pr\u00e8s", "near", "in der N\u00e4he", "cerca", "prep", "A1"),
    ("le besoin", "need", "das Bed\u00fcrfnis", "la necesidad", "nom", "A1"),
    ("avoir besoin", "need", "brauchen", "necesitar", "verbe", "A1"),
    ("n\u00e9gatif", "negative", "negativ", "negativo", "adjectif", "A1"),
    ("jamais", "never", "nie", "nunca", "adverbe", "A1"),
    ("nouveau", "new", "neu", "nuevo", "adjectif", "A1"),
    ("les informations / nouvelles", "news", "die Nachrichten", "las noticias", "nom", "A1"),
    ("le journal", "newspaper", "die Zeitung", "el peri\u00f3dico", "nom", "A1"),
    ("suivant", "next", "n\u00e4chste", "siguiente", "adjectif", "A1"),
    ("agr\u00e9able", "nice", "nett", "agradable", "adjectif", "A1"),
    ("la nuit", "night", "die Nacht", "la noche", "nom", "A1"),
    ("neuf", "nine", "neun", "nueve", "num", "A1"),
    ("dix-neuf", "nineteen", "neunzehn", "diecinueve", "num", "A1"),
    ("quatre-vingt-dix", "ninety", "neunzig", "noventa", "num", "A1"),
    ("non", "no", "nein", "no", "adverbe", "A1"),
    ("personne", "no one", "niemand", "nadie", "pron", "A1"),
    ("personne", "nobody", "niemand", "nadie", "pron", "A1"),
    ("le nord", "north", "der Norden", "el norte", "nom", "A1"),
    ("le nez", "nose", "die Nase", "la nariz", "nom", "A1"),
    ("pas", "not", "nicht", "no", "adverbe", "A1"),
    ("la note", "note", "die Notiz", "la nota", "nom", "A1"),
    ("rien", "nothing", "nichts", "nada", "pron", "A1"),
    ("novembre", "November", "November", "noviembre", "nom", "A1"),
    ("maintenant", "now", "jetzt", "ahora", "adverbe", "A1"),
    ("le nombre / le num\u00e9ro", "number", "die Nummer", "el n\u00famero", "nom", "A1"),
    ("l'infirmi\u00e8re", "nurse", "die Krankenschwester", "la enfermera", "nom", "A1"),

    # --- LETTRE O ---
    ("l'objet", "object", "das Objekt", "el objeto", "nom", "A1"),
    ("octobre", "October", "Oktober", "octubre", "nom", "A1"),
    ("de", "of", "von", "de", "prep", "A1"),
    ("\u00e9teint / d\u00e9tach\u00e9", "off", "aus", "apagado", "adverbe", "A1"),
    ("le bureau (lieu)", "office", "das B\u00fcro", "la oficina", "nom", "A1"),
    ("souvent", "often", "oft", "a menudo", "adverbe", "A1"),
    ("d'accord", "ok", "okay", "vale", "adjectif", "A1"),
    ("vieux", "old", "alt", "viejo", "adjectif", "A1"),
    ("sur", "on", "auf", "en", "prep", "A1"),
    ("une fois", "once", "einmal", "una vez", "adverbe", "A1"),
    ("un", "one", "eins", "uno", "num", "A1"),
    ("l'oignon", "onion", "die Zwiebel", "la cebolla", "nom", "A1"),
    ("en ligne", "online", "online", "en l\u00ednea", "adjectif", "A1"),
    ("seulement", "only", "nur", "s\u00f3lo", "adverbe", "A1"),
    ("ouvert", "open", "offen", "abierto", "adjectif", "A1"),
    ("l'opinion", "opinion", "die Meinung", "la opini\u00f3n", "nom", "A1"),
    ("ou", "or", "oder", "o", "conjonction", "A1"),
    ("l'orange (fruit)", "orange", "die Orange", "la naranja", "nom", "A1"),
    ("autre", "other", "andere", "otro", "det", "A1"),
    ("notre", "our", "unser", "nuestro", "det", "A1"),
    ("dehors", "out", "heraus", "fuera", "adverbe", "A1"),
    ("\u00e0 l'ext\u00e9rieur", "outside", "drau\u00dfen", "afuera", "adverbe", "A1"),
    ("au-dessus", "over", "\u00fcber", "sobre", "prep", "A1"),
    ("propre (\u00e0 soi)", "own", "eigen", "propio", "adjectif", "A1"),

    # --- LETTRE P (Part 1) ---
    ("la page", "page", "die Seite", "la p\u00e1gina", "nom", "A1"),
    ("peindre", "paint", "malen", "pintar", "verbe", "A1"),
    ("la peinture", "painting", "das Gem\u00e4lde", "la pintura", "nom", "A1"),
    ("la paire", "pair", "das Paar", "el par", "nom", "A1"),
    ("le pantalon (US)", "pants", "die Hose", "los pantalones", "nom", "A1"),
    ("le papier", "paper", "das Papier", "el papel", "nom", "A1"),
    ("le parent", "parent", "das Elternteil", "el padre/madre", "nom", "A1"),
    ("le parc", "park", "der Park", "el parque", "nom", "A1"),
    ("la partie", "part", "der Teil", "la parte", "nom", "A1")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\append_part4.ps1", $new_words, $utf8NoBom)
