$utf8NoBom = New-Object System.Text.UTF8Encoding $False
$content = [System.IO.File]::ReadAllText("$PSScriptRoot\generate_data.py", $utf8NoBom)

$new_words = @"
    # --- LETTRE A ---
    ("un / une", "a / an", "ein / eine", "un / una", "det", "A1"),
    ("au sujet de", "about", "über", "sobre", "prep", "A1"),
    ("au-dessus", "above", "über", "encima", "prep", "A1"),
    ("à travers", "across", "über", "a través de", "prep", "A1"),
    ("l'action", "action", "die Aktion", "la acción", "nom", "A1"),
    ("l'activité", "activity", "die Aktivität", "la actividad", "nom", "A1"),
    ("l'acteur", "actor", "der Schauspieler", "el actor", "nom", "A1"),
    ("l'actrice", "actress", "die Schauspielerin", "la actriz", "nom", "A1"),
    ("ajouter", "add", "hinzufügen", "añadir", "verbe", "A1"),
    ("l'adresse", "address", "die Adresse", "la dirección", "nom", "A1"),
    ("l'adulte", "adult", "der Erwachsene", "el adulto", "nom", "A1"),
    ("effrayé", "afraid", "verängstigt", "asustado", "adjectif", "A1"),
    ("après", "after", "nach", "después", "prep", "A1"),
    ("l'après-midi", "afternoon", "der Nachmittag", "la tarde", "nom", "A1"),
    ("encore", "again", "wieder", "otra vez", "adverbe", "A1"),
    ("l'âge", "age", "das Alter", "la edad", "nom", "A1"),
    ("il y a (temps)", "ago", "vor", "hace", "adverbe", "A1"),
    ("l'air", "air", "die Luft", "el aire", "nom", "A1"),
    ("l'aéroport", "airport", "der Flughafen", "el aeropuerto", "nom", "A1"),
    ("tout", "all", "alles", "todo", "det", "A1"),
    ("d'accord", "all right", "in Ordnung", "de acuerdo", "adjectif", "A1"),
    ("aussi", "also", "auch", "también", "adverbe", "A1"),
    ("toujours", "always", "immer", "siempre", "adverbe", "A1"),
    ("incroyable", "amazing", "erstaunlich", "increíble", "adjectif", "A1"),
    ("et", "and", "und", "y", "conjonction", "A1"),
    ("en colère", "angry", "wütend", "enojado", "adjectif", "A1"),
    ("l'animal", "animal", "das Tier", "el animal", "nom", "A1"),
    ("un autre", "another", "ein anderer", "otro", "det", "A1"),
    ("répondre", "answer", "antworten", "responder", "verbe", "A1"),
    ("la réponse", "answer", "die Antwort", "la respuesta", "nom", "A1"),
    ("n'importe quel", "any", "irgendein", "cualquier", "det", "A1"),
    ("n'importe qui", "anyone", "jemand", "alguien", "pron", "A1"),
    ("n'importe quoi", "anything", "etwas", "algo", "pron", "A1"),
    ("l'appartement", "apartment", "die Wohnung", "el apartamento", "nom", "A1"),
    ("la pomme", "apple", "der Apfel", "la manzana", "nom", "A1"),
    ("avril", "April", "April", "abril", "nom", "A1"),
    ("la zone", "area", "das Gebiet", "el área", "nom", "A1"),
    ("le bras", "arm", "der Arm", "el brazo", "nom", "A1"),
    ("autour", "around", "um", "alrededor", "prep", "A1"),
    ("arriver", "arrive", "ankommen", "llegar", "verbe", "A1"),
    ("l'art", "art", "die Kunst", "el arte", "nom", "A1"),
    ("l'article", "article", "der Artikel", "el artículo", "nom", "A1"),
    ("l'artiste", "artist", "der Künstler", "el artista", "nom", "A1"),
    ("comme", "as", "wie", "como", "prep", "A1"),
    ("demander", "ask", "fragen", "preguntar", "verbe", "A1"),
    ("à", "at", "an / um", "en", "prep", "A1"),
    ("août", "August", "August", "agosto", "nom", "A1"),
    ("la tante", "aunt", "die Tante", "la tía", "nom", "A1"),
    ("l'automne", "autumn", "der Herbst", "el otoño", "nom", "A1"),
    ("loin", "away", "weg", "lejos", "adverbe", "A1"),

    # --- LETTRE B ---
    ("le bébé", "baby", "das Baby", "el bebé", "nom", "A1"),
    ("en arrière", "back", "zurück", "atrás", "adverbe", "A1"),
    ("mauvais", "bad", "schlecht", "malo", "adjectif", "A1"),
    ("le sac", "bag", "die Tasche", "la bolsa", "nom", "A1"),
    ("la balle", "ball", "der Ball", "la pelota", "nom", "A1"),
    ("la banane", "banana", "die Banane", "el plátano", "nom", "A1"),
    ("le groupe", "band", "die Band", "la banda", "nom", "A1"),
    ("la banque", "bank", "die Bank", "el banco", "nom", "A1"),
    ("le bar", "bar", "die Bar", "el bar", "nom", "A1"),
    ("le bain", "bath", "das Bad", "el baño", "nom", "A1"),
    ("la salle de bain", "bathroom", "das Badezimmer", "el baño", "nom", "A1"),
    ("être", "be", "sein", "ser / estar", "verbe", "A1"),
    ("la plage", "beach", "der Strand", "la playa", "nom", "A1"),
    ("beau", "beautiful", "schön", "hermoso", "adjectif", "A1"),
    ("parce que", "because", "weil", "porque", "conjonction", "A1"),
    ("devenir", "become", "werden", "convertirse", "verbe", "A1"),
    ("le lit", "bed", "das Bett", "la cama", "nom", "A1"),
    ("la chambre", "bedroom", "das Schlafzimmer", "el dormitorio", "nom", "A1"),
    ("la bière", "beer", "das Bier", "la cerveza", "nom", "A1"),
    ("avant", "before", "vor", "antes", "prep", "A1"),
    ("commencer", "begin", "beginnen", "empezar", "verbe", "A1"),
    ("le début", "beginning", "der Anfang", "el principio", "nom", "A1"),
    ("derrière", "behind", "hinter", "detrás", "prep", "A1"),
    ("croire", "believe", "glauben", "creer", "verbe", "A1"),
    ("en dessous", "below", "unter", "debajo", "prep", "A1"),
    ("le meilleur", "best", "am besten", "mejor", "adjectif", "A1"),
    ("mieux", "better", "besser", "mejor", "adjectif", "A1"),
    ("entre", "between", "zwischen", "entre", "prep", "A1"),
    ("le vélo", "bicycle", "das Fahrrad", "la bicicleta", "nom", "A1"),
    ("grand", "big", "groß", "grande", "adjectif", "A1"),
    ("le vélo (familier)", "bike", "das Fahrrad", "la bici", "nom", "A1"),
    ("l'addition", "bill", "die Rechnung", "la cuenta", "nom", "A1"),
    ("l'oiseau", "bird", "der Vogel", "el pájaro", "nom", "A1"),
    ("l'anniversaire", "birthday", "der Geburtstag", "el cumpleaños", "nom", "A1"),
    ("noir", "black", "schwarz", "negro", "adjectif", "A1"),
    ("le blog", "blog", "der Blog", "el blog", "nom", "A1"),
    ("blond", "blonde", "blond", "rubio", "adjectif", "A1"),
    ("bleu", "blue", "blau", "azul", "adjectif", "A1"),
    ("le bateau", "boat", "das Boot", "el barco", "nom", "A1"),
    ("le corps", "body", "der Körper", "el cuerpo", "nom", "A1"),
    ("le livre", "book", "das Buch", "el libro", "nom", "A1"),
    ("la botte", "boot", "der Stiefel", "la bota", "nom", "A1"),
    ("ennuyé", "bored", "gelangweilt", "aburrido", "adjectif", "A1"),
    ("ennuyeux", "boring", "langweilig", "aburrido", "adjectif", "A1"),
    ("né", "born", "geboren", "nacido", "adjectif", "A1"),
    ("les deux", "both", "beide", "ambos", "det", "A1"),
    ("la bouteille", "bottle", "die Flasche", "la botella", "nom", "A1"),
    ("le fond", "bottom", "der Boden", "el fondo", "nom", "A1"),
    ("la boîte", "box", "die Box", "la caja", "nom", "A1"),
    ("le garçon", "boy", "der Junge", "el chico", "nom", "A1"),
    ("le petit-ami", "boyfriend", "der Freund", "el novio", "nom", "A1"),
    ("le pain", "bread", "das Brot", "el pan", "nom", "A1"),
    ("casser", "break", "brechen", "romper", "verbe", "A1"),
    ("le petit-déjeuner", "breakfast", "das Frühstück", "el desayuno", "nom", "A1"),
    ("apporter", "bring", "bringen", "traer", "verbe", "A1"),
    ("le frère", "brother", "der Bruder", "el hermano", "nom", "A1"),
    ("marron", "brown", "braun", "marrón", "adjectif", "A1"),
    ("construire", "build", "bauen", "construir", "verbe", "A1"),
    ("le bâtiment", "building", "das Gebäude", "el edificio", "nom", "A1"),
    ("le bus", "bus", "der Bus", "el autobús", "nom", "A1"),
    ("l'entreprise", "business", "das Geschäft", "el negocio", "nom", "A1"),
    ("occupé", "busy", "beschäftigt", "ocupado", "adjectif", "A1"),
    ("mais", "but", "aber", "pero", "conjonction", "A1"),
    ("le beurre", "butter", "die Butter", "la mantequilla", "nom", "A1"),
    ("acheter", "buy", "kaufen", "comprar", "verbe", "A1"),
    ("par", "by", "von / durch", "por", "prep", "A1"),
    ("au revoir", "bye", "tschüss", "adiós", "interj", "A1"),

    # --- LETTRE C ---
    ("le café (lieu)", "cafe", "das Café", "la cafetería", "nom", "A1"),
    ("le gâteau", "cake", "der Kuchen", "el pastel", "nom", "A1"),
    ("appeler", "call", "anrufen", "llamar", "verbe", "A1"),
    ("l'appareil photo", "camera", "die Kamera", "la cámara", "nom", "A1"),
    ("pouvoir", "can", "können", "poder", "verbe", "A1"),
    ("ne pas pouvoir", "cannot", "nicht können", "no poder", "verbe", "A1"),
    ("la capitale", "capital", "die Hauptstadt", "la capital", "nom", "A1"),
    ("la voiture", "car", "das Auto", "el coche", "nom", "A1"),
    ("la carte", "card", "die Karte", "la tarjeta", "nom", "A1"),
    ("la carotte", "carrot", "die Karotte", "la zanahoria", "nom", "A1"),
    ("porter", "carry", "tragen", "llevar", "verbe", "A1"),
    ("le chat", "cat", "die Katze", "el gato", "nom", "A1"),
    ("le CD", "CD", "die CD", "el CD", "nom", "A1"),
    ("le centime", "cent", "der Cent", "el céntimo", "nom", "A1"),
    ("le centre", "centre", "das Zentrum", "el centro", "nom", "A1"),
    ("la chaise", "chair", "der Stuhl", "la silla", "nom", "A1"),
    ("changer", "change", "ändern", "cambiar", "verbe", "A1"),
    ("le graphique", "chart", "das Diagramm", "el gráfico", "nom", "A1"),
    ("bon marché", "cheap", "billig", "barato", "adjectif", "A1"),
    ("vérifier", "check", "überprüfen", "comprobar", "verbe", "A1"),
    ("le fromage", "cheese", "der Käse", "el queso", "nom", "A1"),
    ("le poulet", "chicken", "das Hähnchen", "el pollo", "nom", "A1"),
    ("l'enfant", "child", "das Kind", "el niño", "nom", "A1"),
    ("le chocolat", "chocolate", "die Schokolade", "el chocolate", "nom", "A1"),
    ("choisir", "choose", "wählen", "elegir", "verbe", "A1"),
    ("le cinéma", "cinema", "das Kino", "el cine", "nom", "A1"),
    ("la ville", "city", "die Stadt", "la ciudad", "nom", "A1"),
    ("la classe", "class", "die Klasse", "la clase", "nom", "A1"),
    ("la salle de classe", "classroom", "das Klassenzimmer", "el aula", "nom", "A1"),
    ("nettoyer", "clean", "putzen", "limpiar", "verbe", "A1"),
    ("propre", "clean", "sauber", "limpio", "adjectif", "A1"),
    ("grimper", "climb", "klettern", "escalar", "verbe", "A1"),
    ("l'horloge", "clock", "die Uhr", "el reloj", "nom", "A1"),
    ("fermer", "close", "schließen", "cerrar", "verbe", "A1"),
    ("les vêtements", "clothes", "die Kleidung", "la ropa", "nom", "A1"),
    ("le club", "club", "der Club", "el club", "nom", "A1"),
    ("le manteau", "coat", "der Mantel", "el abrigo", "nom", "A1"),
    ("le café (boisson)", "coffee", "der Kaffee", "el café", "nom", "A1"),
    ("froid", "cold", "kalt", "frío", "adjectif", "A1"),
    ("le collège", "college", "das College", "la universidad", "nom", "A1"),
    ("la couleur", "colour", "die Farbe", "el color", "nom", "A1"),
    ("venir", "come", "kommen", "venir", "verbe", "A1"),
    ("l'entreprise (2)", "company", "das Unternehmen", "la empresa", "nom", "A1"),
    ("compléter", "complete", "vervollständigen", "completar", "verbe", "A1"),
    ("l'ordinateur", "computer", "der Computer", "el ordenador", "nom", "A1"),
    ("le concert", "concert", "das Konzert", "el concierto", "nom", "A1"),
    ("cuisiner", "cook", "kochen", "cocinar", "verbe", "A1"),
    ("la cuisine (action)", "cooking", "das Kochen", "la cocina", "nom", "A1"),
    ("génial / frais", "cool", "cool", "genial / fresco", "adjectif", "A1"),
    ("correct", "correct", "richtig", "correcto", "adjectif", "A1"),
    ("coûter", "cost", "kosten", "costar", "verbe", "A1"),
    ("pourrait", "could", "könnte", "podría", "verbe", "A1"),
    ("le pays", "country", "das Land", "el país", "nom", "A1"),
    ("le cours", "course", "der Kurs", "el curso", "nom", "A1"),
    ("le cousin", "cousin", "der Cousin", "el primo", "nom", "A1"),
    ("la vache", "cow", "die Kuh", "la vaca", "nom", "A1"),
    ("la crème", "cream", "die Sahne", "la crema", "nom", "A1"),
    ("la tasse", "cup", "die Tasse", "la taza", "nom", "A1"),
    ("le client", "customer", "der Kunde", "el cliente", "nom", "A1"),
    ("couper", "cut", "schneiden", "cortar", "verbe", "A1"),

    # --- LETTRE D ---
    ("le papa", "dad", "der Papa", "el papá", "nom", "A1"),
    ("quotidien", "daily", "täglich", "diario", "adjectif", "A1"),
    ("danser", "dance", "tanzen", "bailar", "verbe", "A1"),
    ("le danseur", "dancer", "der Tänzer", "el bailarín", "nom", "A1"),
    ("la danse", "dancing", "das Tanzen", "el baile", "nom", "A1"),
    ("dangereux", "dangerous", "gefährlich", "peligroso", "adjectif", "A1"),
    ("sombre", "dark", "dunkel", "oscuro", "adjectif", "A1"),
    ("la date", "date", "das Datum", "la fecha", "nom", "A1"),
    ("la fille (enfant)", "daughter", "die Tochter", "la hija", "nom", "A1"),
    ("le jour", "day", "der Tag", "el día", "nom", "A1"),
    ("cher (affection)", "dear", "lieb", "querido", "adjectif", "A1"),
    ("décembre", "December", "Dezember", "diciembre", "nom", "A1"),
    ("décider", "decide", "entscheiden", "decidir", "verbe", "A1"),
    ("délicieux", "delicious", "köstlich", "delicioso", "adjectif", "A1"),
    ("le bureau", "desk", "der Schreibtisch", "el escritorio", "nom", "A1"),
    ("le détail", "detail", "das Detail", "el detalle", "nom", "A1"),
    ("le dialogue", "dialogue", "der Dialog", "el diálogo", "nom", "A1"),
    ("le dictionnaire", "dictionary", "das Wörterbuch", "el diccionario", "nom", "A1"),
    ("mourir", "die", "sterben", "morir", "verbe", "A1"),
    ("le régime", "diet", "die Diät", "la dieta", "nom", "A1"),
    ("différent", "different", "anders", "diferente", "adjectif", "A1"),
    ("difficile", "difficult", "schwierig", "difícil", "adjectif", "A1"),
    ("le dîner", "dinner", "das Abendessen", "la cena", "nom", "A1"),
    ("sale", "dirty", "schmutzig", "sucio", "adjectif", "A1"),
    ("le plat", "dish", "das Gericht", "el plato", "nom", "A1"),
    ("faire", "do", "tun / machen", "hacer", "verbe", "A1"),
    ("le docteur", "doctor", "der Arzt", "el médico", "nom", "A1"),
    ("le chien", "dog", "der Hund", "el perro", "nom", "A1"),
    ("le dollar", "dollar", "der Dollar", "el dólar", "nom", "A1"),
    ("la porte", "door", "die Tür", "la puerta", "nom", "A1"),
    ("en bas", "down", "unten", "abajo", "adverbe", "A1"),
    ("en bas (escaliers)", "downstairs", "unten", "abajo", "adverbe", "A1"),
    ("dessiner", "draw", "zeichnen", "dibujar", "verbe", "A1"),
    ("la robe", "dress", "das Kleid", "el vestido", "nom", "A1"),
    ("boire", "drink", "trinken", "beber", "verbe", "A1"),
    ("conduire", "drive", "fahren", "conducir", "verbe", "A1"),
    ("le chauffeur", "driver", "der Fahrer", "el conductor", "nom", "A1"),
    ("la conduite", "driving", "das Fahren", "la conducción", "nom", "A1"),
    ("sec", "dry", "trocken", "seco", "adjectif", "A1"),
    ("pendant", "during", "während", "durante", "prep", "A1"),
    ("le DVD", "DVD", "die DVD", "el DVD", "nom", "A1")
"@

$content = $content -replace 'vocab_list = \[', "vocab_list = [$new_words"

[System.IO.File]::WriteAllText("$PSScriptRoot\generate_data.py", $content, $utf8NoBom)
Write-Host "Part 1 (A-D) injected."
