$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE P (Part 2) ---
    ("la f\u00eate", "party", "die Party", "la fiesta", "nom", "A1"),
    ("le pass", "pass", "der Pass", "el pase", "nom", "A1"),
    ("pass\u00e9", "past", "vergangen", "pasado", "adjectif", "A1"),
    ("payer", "pay", "bezahlen", "pagar", "verbe", "A1"),
    ("le stylo", "pen", "der Stift", "el bol\u00edgrafo", "nom", "A1"),
    ("le crayon", "pencil", "der Bleistift", "el l\u00e1piz", "nom", "A1"),
    ("les gens", "people", "die Leute", "la gente", "nom", "A1"),
    ("le poivre", "pepper", "der Pfeffer", "la pimienta", "nom", "A1"),
    ("parfait", "perfect", "perfekt", "perfecto", "adjectif", "A1"),
    ("la personne", "person", "die Person", "la persona", "nom", "A1"),
    ("la photo", "photo", "das Foto", "la foto", "nom", "A1"),
    ("la photographie", "photograph", "die Fotografie", "la fotograf\u00eda", "nom", "A1"),
    ("le piano", "piano", "das Klavier", "el piano", "nom", "A1"),
    ("la photo / image", "picture", "das Bild", "la imagen", "nom", "A1"),
    ("le morceau / la pi\u00e8ce", "piece", "das St\u00fcck", "el pedazo", "nom", "A1"),
    ("le porc", "pig", "das Schwein", "el cerdo", "nom", "A1"),
    ("la pizza", "pizza", "die Pizza", "la pizza", "nom", "A1"),
    ("l'endroit", "place", "der Ort", "el lugar", "nom", "A1"),
    ("le plan", "plan", "der Plan", "el plan", "nom", "A1"),
    ("l'avion", "plane", "das Flugzeug", "el avi\u00f3n", "nom", "A1"),
    ("la plante", "plant", "die Pflanze", "la planta", "nom", "A1"),
    ("jouer", "play", "spielen", "jugar", "verbe", "A1"),
    ("le joueur", "player", "der Spieler", "el jugador", "nom", "A1"),
    ("s'il te pla\u00eet", "please", "bitte", "por favor", "interj", "A1"),
    ("le point", "point", "der Punkt", "el punto", "nom", "A1"),
    ("la police", "police", "die Polizei", "la polic\u00eda", "nom", "A1"),
    ("l'officier de police", "policeman", "der Polizist", "el polic\u00eda", "nom", "A1"),
    ("la piscine", "pool", "der Pool", "la piscina", "nom", "A1"),
    ("pauvre", "poor", "arm", "pobre", "adjectif", "A1"),
    ("populaire", "popular", "beliebt", "popular", "adjectif", "A1"),
    ("positif", "positive", "positiv", "positivo", "adjectif", "A1"),
    ("possible", "possible", "m\u00f6glich", "posible", "adjectif", "A1"),
    ("la pomme de terre", "potato", "die Kartoffel", "la patata", "nom", "A1"),
    ("la livre (monnaie/poids)", "pound", "das Pfund", "la libra", "nom", "A1"),
    ("la pratique", "practice", "die \u00dcbung", "la pr\u00e1ctica", "nom", "A1"),
    ("pratiquer", "practise", "\u00fcben", "practicar", "verbe", "A1"),
    ("pr\u00e9f\u00e9rer", "prefer", "bevorzugen", "preferir", "verbe", "A1"),
    ("pr\u00e9parer", "prepare", "vorbereiten", "preparar", "verbe", "A1"),
    ("le cadeau", "present", "das Geschenk", "el regalo", "nom", "A1"),
    ("le prix", "price", "der Preis", "el precio", "nom", "A1"),
    ("le probl\u00e8me", "problem", "das Problem", "el problema", "nom", "A1"),
    ("le produit", "product", "das Produkt", "el producto", "nom", "A1"),
    ("le projet", "project", "das Projekt", "el proyecto", "nom", "A1"),
    ("le pub", "pub", "die Kneipe", "el pub", "nom", "A1"),
    ("mettre", "put", "legen / setzen", "poner", "verbe", "A1"),

    # --- LETTRE Q ---
    ("le quart", "quarter", "das Viertel", "el cuarto", "nom", "A1"),
    ("la question", "question", "die Frage", "la pregunta", "nom", "A1"),
    ("rapide", "quick", "schnell", "r\u00e1pido", "adjectif", "A1"),
    ("rapidement", "quickly", "schnell", "r\u00e1pidamente", "adverbe", "A1"),
    ("calme", "quiet", "ruhig", "tranquilo", "adjectif", "A1"),
    ("assez / plut\u00f4t", "quite", "ziemlich", "bastante", "adverbe", "A1"),

    # --- LETTRE R ---
    ("la radio", "radio", "das Radio", "la radio", "nom", "A1"),
    ("la pluie", "rain", "der Regen", "la lluvia", "nom", "A1"),
    ("lire", "read", "lesen", "leer", "verbe", "A1"),
    ("le lecteur", "reader", "der Leser", "el lector", "nom", "A1"),
    ("la lecture", "reading", "das Lesen", "la lectura", "nom", "A1"),
    ("pr\u00eat", "ready", "bereit", "listo", "adjectif", "A1"),
    ("vraiment", "really", "wirklich", "realmente", "adverbe", "A1"),
    ("la raison", "reason", "der Grund", "la raz\u00f3n", "nom", "A1"),
    ("rouge", "red", "rot", "rojo", "adjectif", "A1"),
    ("se d\u00e9tendre", "relax", "sich entspannen", "relajarse", "verbe", "A1"),
    ("se souvenir", "remember", "sich erinnern", "recordar", "verbe", "A1"),
    ("le restaurant", "restaurant", "das Restaurant", "el restaurante", "nom", "A1"),
    ("le r\u00e9sultat", "result", "das Ergebnis", "el resultado", "nom", "A1"),
    ("le retour", "return", "die R\u00fcckkehr", "el retorno", "nom", "A1"),
    ("le riz", "rice", "der Reis", "el arroz", "nom", "A1"),
    ("riche", "rich", "reich", "rico", "adjectif", "A1"),
    ("monter (cheval/v\u00e9lo)", "ride", "reiten / fahren", "montar", "verbe", "A1"),
    ("la droite", "right", "rechts", "la derecha", "nom", "A1"),
    ("la rivi\u00e8re", "river", "der Fluss", "el r\u00edo", "nom", "A1"),
    ("la route", "road", "die Stra\u00dfe", "la carretera", "nom", "A1"),
    ("la chambre / la pi\u00e8ce", "room", "das Zimmer", "la habitaci\u00f3n", "nom", "A1"),
    ("la routine", "routine", "die Routine", "la rutina", "nom", "A1"),
    ("la r\u00e8gle", "rule", "die Regel", "la regla", "nom", "A1"),
    ("courir", "run", "rennen", "correr", "verbe", "A1"),

    # --- LETTRE S (Part 1) ---
    ("triste", "sad", "traurig", "triste", "adjectif", "A1"),
    ("la salade", "salad", "der Salat", "la ensalada", "nom", "A1"),
    ("le sel", "salt", "das Salz", "la sal", "nom", "A1"),
    ("le m\u00eame", "same", "das gleiche", "el mismo", "adjectif", "A1"),
    ("le sandwich", "sandwich", "das Sandwich", "el s\u00e1ndwich", "nom", "A1"),
    ("samedi", "Saturday", "Samstag", "s\u00e1bado", "nom", "A1"),
    ("dire", "say", "sagen", "decir", "verbe", "A1"),
    ("l'\u00e9cole", "school", "die Schule", "la escuela", "nom", "A1"),
    ("la science", "science", "die Wissenschaft", "la ciencia", "nom", "A1"),
    ("le scientifique", "scientist", "der Wissenschaftler", "el cient\u00edfico", "nom", "A1"),
    ("la mer", "sea", "das Meer", "el mar", "nom", "A1"),
    ("la saison", "season", "die Jahreszeit", "la estaci\u00f3n", "nom", "A1"),
    ("deuxi\u00e8me", "second", "zweite", "segundo", "num", "A1"),
    ("la seconde (temps)", "second", "die Sekunde", "el segundo", "nom", "A1"),
    ("voir", "see", "sehen", "ver", "verbe", "A1"),
    ("envoyer", "send", "senden", "enviar", "verbe", "A1"),
    ("la phrase", "sentence", "der Satz", "la oraci\u00f3n", "nom", "A1"),
    ("septembre", "September", "September", "septiembre", "nom", "A1"),
    ("sept", "seven", "sieben", "siete", "num", "A1"),
    ("dix-sept", "seventeen", "siebzehn", "diecisiete", "num", "A1"),
    ("soixante-dix", "seventy", "siebzig", "setenta", "num", "A1"),
    ("partager", "share", "teilen", "compartir", "verbe", "A1"),
    ("elle", "she", "sie", "ella", "pron", "A1"),
    ("le mouton", "sheep", "das Schaf", "la oveja", "nom", "A1"),
    ("la chemise", "shirt", "das Hemd", "la camisa", "nom", "A1"),
    ("la chaussure", "shoe", "der Schuh", "el zapato", "nom", "A1"),
    ("le magasin", "shop", "der Laden", "la tienda", "nom", "A1"),
    ("faire les courses", "shopping", "einkaufen", "las compras", "nom", "A1"),
    ("court", "short", "kurz", "corto", "adjectif", "A1"),
    ("devrait", "should", "sollte", "deber\u00eda", "verbe", "A1"),
    ("montrer", "show", "zeigen", "mostrar", "verbe", "A1"),
    ("le spectacle", "show", "die Show", "el espect\u00e1culo", "nom", "A1"),
    ("la douche", "shower", "die Dusche", "la ducha", "nom", "A1"),
    ("malade", "sick", "krank", "enfermo", "adjectif", "A1"),
    ("similaire", "similar", "\u00e4hnlich", "similar", "adjectif", "A1"),
    ("chanter", "sing", "singen", "cantar", "verbe", "A1"),
    ("le chanteur", "singer", "der S\u00e4nger", "el cantante", "nom", "A1"),
    ("la s\u0153ur", "sister", "die Schwester", "la hermana", "nom", "A1"),
    ("s'asseoir", "sit", "sitzen", "sentarse", "verbe", "A1"),
    ("la situation", "situation", "die Situation", "la situaci\u00f3n", "nom", "A1"),
    ("six", "six", "sechs", "seis", "num", "A1"),
    ("seize", "sixteen", "sechzehn", "diecis\u00e9is", "num", "A1"),
    ("soixante", "sixty", "sechzig", "sesenta", "num", "A1"),
    ("la comp\u00e9tence", "skill", "die F\u00e4higkeit", "la habilidad", "nom", "A1"),
    ("la jupe", "skirt", "der Rock", "la falda", "nom", "A1"),
    ("dormir", "sleep", "schlafen", "dormir", "verbe", "A1"),
    ("lent", "slow", "langsam", "lento", "adjectif", "A1"),
    ("petit (taille)", "small", "klein", "peque\u00f1o", "adjectif", "A1"),
    ("intelligent", "smart", "klug", "inteligente", "adjectif", "A1"),
    ("fumer", "smoke", "rauchen", "fumar", "verbe", "A1"),
    ("le serpent", "snake", "die Schlange", "la serpiente", "nom", "A1")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\append_part5.ps1", $new_words, $utf8NoBom)
