$utf8NoBom = New-Object System.Text.UTF8Encoding $False
$content = [System.IO.File]::ReadAllText("$PSScriptRoot\generate_data.py", $utf8NoBom)

$new_words = @"
    ,
    # --- LETTRE E ---
    ("chaque", "each", "jeder", "cada", "det", "A1"),
    ("l'oreille", "ear", "das Ohr", "la oreja", "nom", "A1"),
    ("tôt", "early", "früh", "temprano", "adjectif", "A1"),
    ("l'est (direction)", "east", "der Osten", "el este", "nom", "A1"),
    ("facile", "easy", "einfach", "fácil", "adjectif", "A1"),
    ("manger", "eat", "essen", "comer", "verbe", "A1"),
    ("l'œuf", "egg", "das Ei", "el huevo", "nom", "A1"),
    ("huit", "eight", "acht", "ocho", "num", "A1"),
    ("dix-huit", "eighteen", "achtzehn", "dieciocho", "num", "A1"),
    ("quatre-vingts", "eighty", "achtzig", "ochenta", "num", "A1"),
    ("l'éléphant", "elephant", "der Elefant", "el elefante", "nom", "A1"),
    ("onze", "eleven", "elf", "once", "num", "A1"),
    ("d'autre", "else", "sonst", "más", "adverbe", "A1"),
    ("l'e-mail", "email", "die E-Mail", "el correo", "nom", "A1"),
    ("la fin", "end", "das Ende", "el fin", "nom", "A1"),
    ("profiter", "enjoy", "genießen", "disfrutar", "verbe", "A1"),
    ("assez", "enough", "genug", "suficiente", "det", "A1"),
    ("l'euro", "euro", "der Euro", "el euro", "nom", "A1"),
    ("même", "even", "sogar", "incluso", "adverbe", "A1"),
    ("le soir", "evening", "der Abend", "la noche", "nom", "A1"),
    ("jamais (déjà)", "ever", "jemals", "alguna vez", "adverbe", "A1"),
    ("chaque (2)", "every", "jeder", "cada", "det", "A1"),
    ("tout le monde", "everybody", "jeder", "todos", "pron", "A1"),
    ("chacun", "everyone", "jeder", "todos", "pron", "A1"),
    ("tout", "everything", "alles", "todo", "pron", "A1"),
    ("l'examen", "exam", "die Prüfung", "el examen", "nom", "A1"),
    ("l'exemple", "example", "das Beispiel", "el ejemplo", "nom", "A1"),
    ("excité", "excited", "aufgeregt", "emocionado", "adjectif", "A1"),
    ("passionnant", "exciting", "aufregend", "emocionante", "adjectif", "A1"),
    ("l'exercice", "exercise", "die Übung", "el ejercicio", "nom", "A1"),
    ("cher (prix)", "expensive", "teuer", "caro", "adjectif", "A1"),
    ("expliquer", "explain", "erklären", "explicar", "verbe", "A1"),
    ("supplémentaire", "extra", "zusätzlich", "extra", "adjectif", "A1"),
    ("l'œil", "eye", "das Auge", "el ojo", "nom", "A1"),

    # --- LETTRE F ---
    ("le visage", "face", "das Gesicht", "la cara", "nom", "A1"),
    ("tomber", "fall", "fallen", "caer", "verbe", "A1"),
    ("faux", "false", "falsch", "falso", "adjectif", "A1"),
    ("la famille", "family", "die Familie", "la familia", "nom", "A1"),
    ("célèbre", "famous", "berühmt", "famoso", "adjectif", "A1"),
    ("fantastique", "fantastic", "fantastisch", "fantástico", "adjectif", "A1"),
    ("loin", "far", "weit", "lejos", "adverbe", "A1"),
    ("la ferme", "farm", "der Bauernhof", "la granja", "nom", "A1"),
    ("le fermier", "farmer", "der Bauer", "el granjero", "nom", "A1"),
    ("rapide", "fast", "schnell", "rápido", "adjectif", "A1"),
    ("gros", "fat", "dick", "gordo", "adjectif", "A1"),
    ("le père", "father", "der Vater", "el padre", "nom", "A1"),
    ("préféré", "favourite", "lieblings", "favorito", "adjectif", "A1"),
    ("février", "February", "Februar", "febrero", "nom", "A1"),
    ("ressentir", "feel", "fühlen", "sentir", "verbe", "A1"),
    ("le festival", "festival", "das Festival", "el festival", "nom", "A1"),
    ("peu", "few", "wenige", "pocos", "det", "A1"),
    ("quinze", "fifteen", "fünfzehn", "quince", "num", "A1"),
    ("cinquième", "fifth", "fünfte", "quinto", "num", "A1"),
    ("cinquante", "fifty", "fünfzig", "cincuenta", "num", "A1"),
    ("remplir", "fill", "füllen", "llenar", "verbe", "A1"),
    ("le film", "film", "der Film", "el film", "nom", "A1"),
    ("final", "final", "endgültig", "final", "adjectif", "A1"),
    ("trouver", "find", "finden", "encontrar", "verbe", "A1"),
    ("bien", "fine", "gut", "bien", "adjectif", "A1"),
    ("finir", "finish", "beenden", "terminar", "verbe", "A1"),
    ("le feu", "fire", "das Feuer", "el fuego", "nom", "A1"),
    ("premier", "first", "erste", "primero", "num", "A1"),
    ("le poisson", "fish", "der Fisch", "el pescado", "nom", "A1"),
    ("cinq", "five", "fünf", "cinco", "num", "A1"),
    ("réparer / fixer", "fix", "reparieren", "arreglar", "verbe", "A1"),
    ("l'appartement", "flat", "die Wohnung", "el piso", "nom", "A1"),
    ("le vol", "flight", "der Flug", "el vuelo", "nom", "A1"),
    ("le sol / l'étage", "floor", "der Boden", "el suelo", "nom", "A1"),
    ("la fleur", "flower", "die Blume", "la flor", "nom", "A1"),
    ("voler (air)", "fly", "fliegen", "volar", "verbe", "A1"),
    ("suivre", "follow", "folgen", "seguir", "verbe", "A1"),
    ("la nourriture", "food", "das Essen", "la comida", "nom", "A1"),
    ("le pied", "foot", "der Fuß", "el pie", "nom", "A1"),
    ("le football", "football", "der Fußball", "el fútbol", "nom", "A1"),
    ("pour", "for", "für", "para", "prep", "A1"),
    ("oublier", "forget", "vergessen", "olvidar", "verbe", "A1"),
    ("le formulaire", "form", "das Formular", "el formulario", "nom", "A1"),
    ("quarante", "forty", "vierzig", "cuarenta", "num", "A1"),
    ("quatre", "four", "vier", "cuatro", "num", "A1"),
    ("quatorze", "fourteen", "vierzehn", "catorce", "num", "A1"),
    ("quatrième", "fourth", "vierte", "cuarto", "num", "A1"),
    ("libre / gratuit", "free", "frei", "libre", "adjectif", "A1"),
    ("vendredi", "Friday", "Freitag", "viernes", "nom", "A1"),
    ("l'ami", "friend", "der Freund", "el amigo", "nom", "A1"),
    ("amical", "friendly", "freundlich", "amigable", "adjectif", "A1"),
    ("de (provenance)", "from", "von", "de", "prep", "A1"),
    ("le devant", "front", "die Vorderseite", "el frente", "nom", "A1"),
    ("le fruit", "fruit", "das Obst", "la fruta", "nom", "A1"),
    ("plein", "full", "voll", "lleno", "adjectif", "A1"),
    ("l'amusement", "fun", "der Spaß", "la diversión", "nom", "A1"),
    ("drôle", "funny", "lustig", "divertido", "adjectif", "A1"),
    ("le futur", "future", "die Zukunft", "el futuro", "nom", "A1"),

    # --- LETTRE G ---
    ("le jeu", "game", "das Spiel", "el juego", "nom", "A1"),
    ("le jardin", "garden", "der Garten", "el jardín", "nom", "A1"),
    ("la géographie", "geography", "die Geografie", "la geografía", "nom", "A1"),
    ("obtenir", "get", "bekommen", "conseguir", "verbe", "A1"),
    ("la fille", "girl", "das Mädchen", "la chica", "nom", "A1"),
    ("la petite-amie", "girlfriend", "die Freundin", "la novia", "nom", "A1"),
    ("donner", "give", "geben", "dar", "verbe", "A1"),
    ("le verre", "glass", "das Glas", "el vaso", "nom", "A1"),
    ("aller", "go", "gehen", "ir", "verbe", "A1"),
    ("bon", "good", "gut", "bueno", "adjectif", "A1"),
    ("au revoir", "goodbye", "auf Wiedersehen", "adiós", "interj", "A1"),
    ("le grand-père", "grandfather", "der Großvater", "el abuelo", "nom", "A1"),
    ("la grand-mère", "grandmother", "die Großmutter", "la abuela", "nom", "A1"),
    ("le grand-parent", "grandparent", "das Großelternteil", "el abuelo", "nom", "A1"),
    ("super", "great", "großartig", "genial", "adjectif", "A1"),
    ("vert", "green", "grün", "verde", "adjectif", "A1"),
    ("gris", "grey", "grau", "gris", "adjectif", "A1"),
    ("le groupe", "group", "die Gruppe", "el grupo", "nom", "A1"),
    ("grandir", "grow", "wachsen", "crecer", "verbe", "A1"),
    ("deviner", "guess", "raten", "adivinar", "verbe", "A1"),
    ("la guitare", "guitar", "die Gitarre", "la guitarra", "nom", "A1"),
    ("la salle de sport", "gym", "das Fitnessstudio", "el gimnasio", "nom", "A1"),

    # --- LETTRE H ---
    ("les cheveux", "hair", "die Haare", "el pelo", "nom", "A1"),
    ("la moitié", "half", "die Hälfte", "la mitad", "nom", "A1"),
    ("la main", "hand", "die Hand", "la mano", "nom", "A1"),
    ("se passer", "happen", "passieren", "suceder", "verbe", "A1"),
    ("heureux", "happy", "glücklich", "feliz", "adjectif", "A1"),
    ("dur", "hard", "hart", "duro", "adjectif", "A1"),
    ("le chapeau", "hat", "der Hut", "el sombrero", "nom", "A1"),
    ("détester", "hate", "hassen", "odiar", "verbe", "A1"),
    ("avoir", "have", "haben", "tener", "verbe", "A1"),
    ("devoir", "have to", "müssen", "tener que", "verbe", "A1"),
    ("il", "he", "er", "él", "pron", "A1"),
    ("la tête", "head", "der Kopf", "la cabeza", "nom", "A1"),
    ("la santé", "health", "die Gesundheit", "la salud", "nom", "A1"),
    ("en bonne santé", "healthy", "gesund", "saludable", "adjectif", "A1"),
    ("entendre", "hear", "hören", "oír", "verbe", "A1"),
    ("bonjour", "hello", "hallo", "hola", "interj", "A1"),
    ("aider", "help", "helfen", "ayudar", "verbe", "A1"),
    ("elle / la sienne", "her", "ihr", "su / ella", "pron", "A1"),
    ("ici", "here", "hier", "aquí", "adverbe", "A1"),
    ("hé", "hey", "hey", "oye", "interj", "A1"),
    ("salut", "hi", "hallo", "hola", "interj", "A1"),
    ("haut", "high", "hoch", "alto", "adjectif", "A1"),
    ("lui", "him", "ihn", "él", "pron", "A1"),
    ("son / le sien", "his", "sein", "su", "det", "A1"),
    ("l'histoire", "history", "die Geschichte", "la historia", "nom", "A1"),
    ("le passe-temps", "hobby", "das Hobby", "el pasatiempo", "nom", "A1"),
    ("les vacances", "holiday", "der Urlaub", "las vacaciones", "nom", "A1"),
    ("la maison", "home", "das Zuhause", "el hogar", "nom", "A1"),
    ("les devoirs", "homework", "die Hausaufgaben", "los deberes", "nom", "A1"),
    ("espérer", "hope", "hoffen", "esperar", "verbe", "A1"),
    ("le cheval", "horse", "das Pferd", "el caballo", "nom", "A1"),
    ("l'hôpital", "hospital", "das Krankenhaus", "el hospital", "nom", "A1"),
    ("chaud", "hot", "heiß", "caliente", "adjectif", "A1"),
    ("l'hôtel", "hotel", "das Hotel", "el hotel", "nom", "A1"),
    ("l'heure", "hour", "die Stunde", "la hora", "nom", "A1"),
    ("la maison (bâtiment)", "house", "das Haus", "la casa", "nom", "A1"),
    ("comment", "how", "wie", "cómo", "adverbe", "A1"),
    ("cent", "hundred", "hundert", "cien", "num", "A1"),
    ("affamé", "hungry", "hungrig", "hambriento", "adjectif", "A1"),
    ("le mari", "husband", "der Ehemann", "el marido", "nom", "A1")
"@

$content = $content -replace 'vocab_list = \[', "vocab_list = [$new_words"

[System.IO.File]::WriteAllText("$PSScriptRoot\generate_data.py", $content, $utf8NoBom)
Write-Host "Part 2 (E-H) injected."
