$utf8NoBom = New-Object System.Text.UTF8Encoding $False
$content = [System.IO.File]::ReadAllText("$PSScriptRoot\generate_data.py", $utf8NoBom)

$new_words = @"
    ,
    # --- LETTRE I ---
    ("je", "I", "ich", "yo", "pron", "A1"),
    ("la glace", "ice", "das Eis", "el hielo", "nom", "A1"),
    ("la crème glacée", "ice cream", "das Eis", "el helado", "nom", "A1"),
    ("l'idée", "idea", "die Idee", "la idea", "nom", "A1"),
    ("si (condition)", "if", "wenn", "si", "conjonction", "A1"),
    ("important", "important", "wichtig", "importante", "adjectif", "A1"),
    ("dans", "in", "in", "en", "prep", "A1"),
    ("inclure", "include", "einschließen", "incluir", "verbe", "A1"),
    ("l'information", "information", "die Information", "la información", "nom", "A1"),
    ("l'intérêt", "interest", "das Interesse", "el interés", "nom", "A1"),
    ("intéressé", "interested", "interessiert", "interesado", "adjectif", "A1"),
    ("intéressant", "interesting", "interessant", "interesante", "adjectif", "A1"),
    ("l'internet", "internet", "das Internet", "el internet", "nom", "A1"),
    ("l'entretien", "interview", "das Interview", "la entrevista", "nom", "A1"),
    ("dans (mouvement)", "into", "in", "hacia adentro", "prep", "A1"),
    ("présenter", "introduce", "vorstellen", "presentar", "verbe", "A1"),
    ("l'île", "island", "die Insel", "la isla", "nom", "A1"),
    ("il / elle (objet)", "it", "es", "lo", "pron", "A1"),
    ("son / sa (objet)", "its", "sein", "su", "det", "A1"),

    # --- LETTRE J ---
    ("la veste", "jacket", "die Jacke", "la chaqueta", "nom", "A1"),
    ("janvier", "January", "Januar", "enero", "nom", "A1"),
    ("le jean", "jeans", "die Jeans", "los vaqueros", "nom", "A1"),
    ("le travail", "job", "der Job", "el trabajo", "nom", "A1"),
    ("rejoindre", "join", "beitreten", "unirse", "verbe", "A1"),
    ("le voyage", "journey", "die Reise", "el viaje", "nom", "A1"),
    ("le jus", "juice", "der Saft", "el jugo", "nom", "A1"),
    ("juillet", "July", "Juli", "julio", "nom", "A1"),
    ("juin", "June", "Juni", "junio", "nom", "A1"),
    ("juste", "just", "nur / gerade", "justo", "adverbe", "A1"),

    # --- LETTRE K ---
    ("garder", "keep", "behalten", "mantener", "verbe", "A1"),
    ("la clé", "key", "der Schlüssel", "la llave", "nom", "A1"),
    ("le kilomètre", "kilometre", "der Kilometer", "el kilómetro", "nom", "A1"),
    ("le genre / gentil", "kind", "die Art / nett", "el tipo / amable", "nom", "A1"),
    ("la cuisine (pièce)", "kitchen", "die Küche", "la cocina", "nom", "A1"),
    ("savoir / connaître", "know", "wissen / kennen", "saber / conocer", "verbe", "A1"),

    # --- LETTRE L ---
    ("la terre", "land", "das Land", "la tierra", "nom", "A1"),
    ("la langue", "language", "die Sprache", "el idioma", "nom", "A1"),
    ("grand / large", "large", "groß", "grande", "adjectif", "A1"),
    ("dernier", "last", "letzte", "último", "adjectif", "A1"),
    ("en retard", "late", "spät", "tarde", "adjectif", "A1"),
    ("plus tard", "later", "später", "más tarde", "adverbe", "A1"),
    ("rire", "laugh", "lachen", "reír", "verbe", "A1"),
    ("apprendre", "learn", "lernen", "aprender", "verbe", "A1"),
    ("quitter / laisser", "leave", "verlassen", "dejar", "verbe", "A1"),
    ("gauche", "left", "links", "izquierdo", "adjectif", "A1"),
    ("la jambe", "leg", "das Bein", "la pierna", "nom", "A1"),
    ("la leçon", "lesson", "die Lektion", "la lección", "nom", "A1"),
    ("laisser / permettre", "let", "lassen", "dejar", "verbe", "A1"),
    ("la lettre", "letter", "der Brief", "la carta", "nom", "A1"),
    ("la bibliothèque", "library", "die Bibliothek", "la biblioteca", "nom", "A1"),
    ("s'allonger / mentir", "lie", "liegen / lügen", "mentir / tumbarse", "verbe", "A1"),
    ("la vie", "life", "das Leben", "la vida", "nom", "A1"),
    ("la lumière", "light", "das Licht", "la luz", "nom", "A1"),
    ("comme (similaire)", "like", "wie", "como", "prep", "A1"),
    ("aimer", "like", "mögen", "gustar", "verbe", "A1"),
    ("la ligne", "line", "die Linie", "la línea", "nom", "A1"),
    ("le lion", "lion", "der Löwe", "el león", "nom", "A1"),
    ("la liste", "list", "die Liste", "la lista", "nom", "A1"),
    ("écouter", "listen", "zuhören", "escuchar", "verbe", "A1"),
    ("petit", "little", "klein", "pequeño", "adjectif", "A1"),
    ("vivre", "live", "leben", "vivir", "verbe", "A1"),
    ("long", "long", "lang", "largo", "adjectif", "A1"),
    ("regarder", "look", "schauen", "mirar", "verbe", "A1"),
    ("perdre", "lose", "verlieren", "perder", "verbe", "A1"),
    ("beaucoup", "lot", "viel", "mucho", "nom", "A1"),
    ("aimer (amour)", "love", "lieben", "amar", "verbe", "A1"),
    ("le déjeuner", "lunch", "das Mittagessen", "el almuerzo", "nom", "A1"),

    # --- LETTRE M ---
    ("la machine", "machine", "die Maschine", "la máquina", "nom", "A1"),
    ("le magazine", "magazine", "das Magazin", "la revista", "nom", "A1"),
    ("principal", "main", "Haupt-", "principal", "adjectif", "A1"),
    ("fabriquer / faire", "make", "machen", "hacer", "verbe", "A1"),
    ("l'homme", "man", "der Mann", "el hombre", "nom", "A1"),
    ("beaucoup (dénombrable)", "many", "viele", "muchos", "det", "A1"),
    ("la carte (plan)", "map", "die Karte", "el mapa", "nom", "A1"),
    ("mars", "March", "März", "marzo", "nom", "A1"),
    ("le marché", "market", "der Markt", "el mercado", "nom", "A1"),
    ("marié", "married", "verheiratet", "casado", "adjectif", "A1"),
    ("le match", "match", "das Spiel", "el partido", "nom", "A1"),
    ("mai", "May", "Mai", "mayo", "nom", "A1"),
    ("peut-être", "maybe", "vielleicht", "tal vez", "adverbe", "A1"),
    ("moi", "me", "mich / mir", "mí", "pron", "A1"),
    ("le repas", "meal", "die Mahlzeit", "la comida", "nom", "A1"),
    ("signifier", "mean", "bedeuten", "significar", "verbe", "A1"),
    ("la signification", "meaning", "die Bedeutung", "el significado", "nom", "A1"),
    ("la viande", "meat", "das Fleisch", "la carne", "nom", "A1"),
    ("rencontrer", "meet", "treffen", "encontrar", "verbe", "A1"),
    ("la réunion", "meeting", "das Meeting", "la reunión", "nom", "A1"),
    ("le membre", "member", "das Mitglied", "el miembro", "nom", "A1"),
    ("le menu", "menu", "das Menü", "el menú", "nom", "A1"),
    ("le message", "message", "die Nachricht", "el mensaje", "nom", "A1"),
    ("le mètre", "metre", "der Meter", "el metro", "nom", "A1"),
    ("le milieu", "middle", "die Mitte", "el medio", "nom", "A1"),
    ("minuit", "midnight", "Mitternacht", "medianoche", "nom", "A1"),
    ("le mile", "mile", "die Meile", "la milla", "nom", "A1"),
    ("le lait", "milk", "die Milch", "la leche", "nom", "A1"),
    ("le million", "million", "die Million", "el millón", "num", "A1"),
    ("la minute", "minute", "die Minute", "el minuto", "nom", "A1"),
    ("manquer", "miss", "vermissen", "extrañar", "verbe", "A1"),
    ("l'erreur", "mistake", "der Fehler", "el error", "nom", "A1"),
    ("le modèle", "model", "das Modell", "el modelo", "nom", "A1"),
    ("moderne", "modern", "modern", "moderno", "adjectif", "A1"),
    ("le moment", "moment", "der Moment", "el momento", "nom", "A1"),
    ("lundi", "Monday", "Montag", "lunes", "nom", "A1"),
    ("l'argent", "money", "das Geld", "el dinero", "nom", "A1"),
    ("le mois", "month", "der Monat", "el mes", "nom", "A1"),
    ("plus", "more", "mehr", "más", "adverbe", "A1"),
    ("le matin", "morning", "der Morgen", "la mañana", "nom", "A1"),
    ("le plus", "most", "am meisten", "la mayoría", "adverbe", "A1"),
    ("la mère", "mother", "die Mutter", "la madre", "nom", "A1"),
    ("la montagne", "mountain", "der Berg", "la montaña", "nom", "A1"),
    ("la souris", "mouse", "die Maus", "el ratón", "nom", "A1"),
    ("la bouche", "mouth", "der Mund", "la boca", "nom", "A1"),
    ("bouger / déménager", "move", "bewegen", "mover", "verbe", "A1"),
    ("le film (US)", "movie", "der Film", "la película", "nom", "A1"),
    ("beaucoup (indénombrable)", "much", "viel", "mucho", "adverbe", "A1"),
    ("la maman", "mum", "die Mama", "la mamá", "nom", "A1"),
    ("le musée", "museum", "das Museum", "el museo", "nom", "A1"),
    ("la musique", "music", "die Musik", "la música", "nom", "A1"),
    ("devoir (obligation)", "must", "müssen", "deber", "verbe", "A1"),
    ("mon / ma", "my", "mein", "mi", "det", "A1"),

    # --- LETTRE N ---
    ("le nom", "name", "der Name", "el nombre", "nom", "A1"),
    ("près", "near", "in der Nähe", "cerca", "prep", "A1"),
    ("avoir besoin", "need", "brauchen", "necesitar", "verbe", "A1"),
    ("le voisin", "neighbour", "der Nachbar", "el vecino", "nom", "A1"),
    ("jamais", "never", "nie", "nunca", "adverbe", "A1"),
    ("nouveau", "new", "neu", "nuevo", "adjectif", "A1"),
    ("les nouvelles", "news", "die Nachrichten", "las noticias", "nom", "A1"),
    ("le journal", "newspaper", "die Zeitung", "el periódico", "nom", "A1"),
    ("suivant", "next", "nächste", "siguiente", "adjectif", "A1"),
    ("à côté de", "next to", "neben", "al lado de", "prep", "A1"),
    ("sympa / agréable", "nice", "nett", "agradable", "adjectif", "A1"),
    ("la nuit", "night", "die Nacht", "la noche", "nom", "A1"),
    ("neuf", "nine", "neun", "nueve", "num", "A1"),
    ("dix-neuf", "nineteen", "neunzehn", "diecinueve", "num", "A1"),
    ("quatre-vingt-dix", "ninety", "neunzig", "noventa", "num", "A1"),
    ("non / aucun", "no", "nein / kein", "no / ningún", "det", "A1"),
    ("personne (no one)", "no one", "niemand", "nadie", "pron", "A1"),
    ("personne (nobody)", "nobody", "niemand", "nadie", "pron", "A1"),
    ("midi", "noon", "Mittag", "mediodía", "nom", "A1"),
    ("le nord", "north", "der Norden", "el norte", "nom", "A1"),
    ("le nez", "nose", "die Nase", "la nariz", "nom", "A1"),
    ("ne pas", "not", "nicht", "no", "adverbe", "A1"),
    ("la note", "note", "die Notiz", "la nota", "nom", "A1"),
    ("rien", "nothing", "nichts", "nada", "pron", "A1"),
    ("novembre", "November", "November", "noviembre", "nom", "A1"),
    ("maintenant", "now", "jetzt", "ahora", "adverbe", "A1"),
    ("le nombre", "number", "die Zahl", "el número", "nom", "A1"),
    ("l'infirmière", "nurse", "die Krankenschwester", "la enfermera", "nom", "A1"),

    # --- LETTRE O ---
    ("heure pile (o'clock)", "o'clock", "Uhr", "en punto", "adverbe", "A1"),
    ("octobre", "October", "Oktober", "octubre", "nom", "A1"),
    ("de (appartenance)", "of", "von", "de", "prep", "A1"),
    ("éteint / hors", "off", "aus", "apagado / fuera", "adverbe", "A1"),
    ("le bureau (lieu)", "office", "das Büro", "la oficina", "nom", "A1"),
    ("souvent", "often", "oft", "a menudo", "adverbe", "A1"),
    ("oh", "oh", "oh", "oh", "interj", "A1"),
    ("d'accord", "OK", "okay", "vale", "adjectif", "A1"),
    ("vieux", "old", "alt", "viejo", "adjectif", "A1"),
    ("sur", "on", "auf", "en", "prep", "A1"),
    ("une fois", "once", "einmal", "una vez", "adverbe", "A1"),
    ("un / l'un", "one", "eins", "uno", "num", "A1"),
    ("l'oignon", "onion", "die Zwiebel", "la cebolla", "nom", "A1"),
    ("en ligne", "online", "online", "en línea", "adjectif", "A1"),
    ("seulement", "only", "nur", "solo", "adverbe", "A1"),
    ("ouvrir", "open", "öffnen", "abrir", "verbe", "A1"),
    ("ouvert", "open", "offen", "abierto", "adjectif", "A1"),
    ("opposé / en face", "opposite", "gegenüber", "opuesto", "adjectif", "A1"),
    ("ou", "or", "oder", "o", "conjonction", "A1"),
    ("l'orange", "orange", "die Orange", "la naranja", "nom", "A1"),
    ("commander", "order", "bestellen", "pedir", "verbe", "A1"),
    ("autre", "other", "andere", "otro", "adjectif", "A1"),
    ("notre", "our", "unser", "nuestro", "det", "A1"),
    ("dehors", "out", "heraus", "fuera", "adverbe", "A1"),
    ("à l'extérieur", "outside", "draußen", "afuera", "adverbe", "A1"),
    ("au-dessus de / terminé", "over", "über", "sobre / terminado", "prep", "A1"),
    ("posséder", "own", "besitzen", "poseer", "verbe", "A1")
"@

$content = $content -replace 'vocab_list = \[', "vocab_list = [$new_words"

[System.IO.File]::WriteAllText("$PSScriptRoot\generate_data.py", $content, $utf8NoBom)
Write-Host "Part 3 (I-O) injected."
