$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE A ---
    ("un / une", "a / an", "ein / eine", "un / una", "det", "A1"),
    ("au sujet de", "about", "\u00fcber", "sobre", "prep", "A1"),
    ("au-dessus", "above", "\u00fcber", "encima", "prep", "A1"),
    ("\u00e0 travers", "across", "\u00fcber", "a trav\u00e9s de", "prep", "A1"),
    ("l'action", "action", "die Aktion", "la acci\u00f3n", "nom", "A1"),
    ("l'activit\u00e9", "activity", "die Aktivit\u00e4t", "la actividad", "nom", "A1"),
    ("l'acteur", "actor", "der Schauspieler", "el actor", "nom", "A1"),
    ("l'actrice", "actress", "die Schauspielerin", "la actriz", "nom", "A1"),
    ("ajouter", "add", "hinzuf\u00fcgen", "a\u00f1adir", "verbe", "A1"),
    ("l'adresse", "address", "die Adresse", "la direcci\u00f3n", "nom", "A1"),
    ("l'adulte", "adult", "der Erwachsene", "el adulto", "nom", "A1"),
    ("effray\u00e9", "afraid", "ver\u00e4ngstigt", "asustado", "adjectif", "A1"),
    ("apr\u00e8s", "after", "nach", "despu\u00e9s", "prep", "A1"),
    ("l'apr\u00e8s-midi", "afternoon", "der Nachmittag", "la tarde", "nom", "A1"),
    ("encore", "again", "wieder", "otra vez", "adverbe", "A1"),
    ("l'\u00e2ge", "age", "das Alter", "la edad", "nom", "A1"),
    ("il y a (temps)", "ago", "vor", "hace", "adverbe", "A1"),
    ("l'air", "air", "die Luft", "el aire", "nom", "A1"),
    ("l'a\u00e9roport", "airport", "der Flughafen", "el aeropuerto", "nom", "A1"),
    ("tout", "all", "alles", "todo", "det", "A1"),
    ("d'accord", "all right", "in Ordnung", "de acuerdo", "adjectif", "A1"),
    ("aussi", "also", "auch", "tambi\u00e9n", "adverbe", "A1"),
    ("toujours", "always", "immer", "siempre", "adverbe", "A1"),
    ("incroyable", "amazing", "erstaunlich", "incre\u00edble", "adjectif", "A1"),
    ("et", "and", "und", "y", "conjonction", "A1"),
    ("en col\u00e8re", "angry", "w\u00fctend", "enojado", "adjectif", "A1"),
    ("l'animal", "animal", "das Tier", "el animal", "nom", "A1"),
    ("un autre", "another", "ein anderer", "otro", "det", "A1"),
    ("r\u00e9pondre", "answer", "antworten", "responder", "verbe", "A1"),
    ("la r\u00e9ponse", "answer", "die Antwort", "la respuesta", "nom", "A1"),
    ("n'importe quel", "any", "irgendein", "cualquier", "det", "A1"),
    ("n'importe qui", "anyone", "jemand", "alguien", "pron", "A1"),
    ("n'importe quoi", "anything", "etwas", "algo", "pron", "A1"),
    ("l'appartement", "apartment", "die Wohnung", "el apartamento", "nom", "A1"),
    ("la pomme", "apple", "der Apfel", "la manzana", "nom", "A1"),
    ("avril", "April", "April", "abril", "nom", "A1"),
    ("la zone", "area", "das Gebiet", "el \u00e1rea", "nom", "A1"),
    ("le bras", "arm", "der Arm", "el brazo", "nom", "A1"),
    ("autour", "around", "um", "alrededor", "prep", "A1"),
    ("arriver", "arrive", "ankommen", "llegar", "verbe", "A1"),
    ("l'art", "art", "die Kunst", "el arte", "nom", "A1"),
    ("l'article", "article", "der Artikel", "el art\u00edculo", "nom", "A1"),
    ("l'artiste", "artist", "der K\u00fcnstler", "el artista", "nom", "A1"),
    ("comme", "as", "wie", "como", "prep", "A1"),
    ("demander", "ask", "fragen", "preguntar", "verbe", "A1"),
    ("\u00e0", "at", "an / um", "en", "prep", "A1"),
    ("ao\u00fbt", "August", "August", "agosto", "nom", "A1"),
    ("la tante", "aunt", "die Tante", "la t\u00eda", "nom", "A1"),
    ("l'automne", "autumn", "der Herbst", "el oto\u00f1o", "nom", "A1"),
    ("loin", "away", "weg", "lejos", "adverbe", "A1"),

    # --- LETTRE B ---
    ("le b\u00e9b\u00e9", "baby", "das Baby", "el beb\u00e9", "nom", "A1"),
    ("en arri\u00e8re", "back", "zur\u00fcck", "atr\u00e1s", "adverbe", "A1"),
    ("mauvais", "bad", "schlecht", "malo", "adjectif", "A1"),
    ("le sac", "bag", "die Tasche", "la bolsa", "nom", "A1"),
    ("la balle", "ball", "der Ball", "la pelota", "nom", "A1"),
    ("la banane", "banana", "die Banane", "el pl\u00e1tano", "nom", "A1"),
    ("le groupe", "band", "die Band", "la banda", "nom", "A1"),
    ("la banque", "bank", "die Bank", "el banco", "nom", "A1"),
    ("le bar", "bar", "die Bar", "el bar", "nom", "A1"),
    ("le bain", "bath", "das Bad", "el ba\u00f1o", "nom", "A1"),
    ("la salle de bain", "bathroom", "das Badezimmer", "el ba\u00f1o", "nom", "A1"),
    ("\u00eatre", "be", "sein", "ser / estar", "verbe", "A1"),
    ("la plage", "beach", "der Strand", "la playa", "nom", "A1"),
    ("beau", "beautiful", "sch\u00f6n", "hermoso", "adjectif", "A1"),
    ("parce que", "because", "weil", "porque", "conjonction", "A1"),
    ("devenir", "become", "werden", "convertirse", "verbe", "A1"),
    ("le lit", "bed", "das Bett", "la cama", "nom", "A1"),
    ("la chambre", "bedroom", "das Schlafzimmer", "el dormitorio", "nom", "A1"),
    ("la bi\u00e8re", "beer", "das Bier", "la cerveza", "nom", "A1"),
    ("avant", "before", "vor", "antes", "prep", "A1"),
    ("commencer", "begin", "beginnen", "empezar", "verbe", "A1"),
    ("le d\u00e9but", "beginning", "der Anfang", "el principio", "nom", "A1"),
    ("derri\u00e8re", "behind", "hinter", "detr\u00e1s", "prep", "A1"),
    ("croire", "believe", "glauben", "creer", "verbe", "A1"),
    ("en dessous", "below", "unter", "debajo", "prep", "A1"),
    ("le meilleur", "best", "am besten", "mejor", "adjectif", "A1"),
    ("mieux", "better", "besser", "mejor", "adjectif", "A1"),
    ("entre", "between", "zwischen", "entre", "prep", "A1"),
    ("le v\u00e9lo", "bicycle", "das Fahrrad", "la bicicleta", "nom", "A1"),
    ("grand", "big", "gro\u00df", "grande", "adjectif", "A1"),
    ("le v\u00e9lo (familier)", "bike", "das Fahrrad", "la bici", "nom", "A1"),
    ("l'addition", "bill", "die Rechnung", "la cuenta", "nom", "A1"),
    ("l'oiseau", "bird", "der Vogel", "el p\u00e1jaro", "nom", "A1"),
    ("l'anniversaire", "birthday", "der Geburtstag", "el cumplea\u00f1os", "nom", "A1"),
    ("noir", "black", "schwarz", "negro", "adjectif", "A1"),
    ("le blog", "blog", "der Blog", "el blog", "nom", "A1"),
    ("blond", "blonde", "blond", "rubio", "adjectif", "A1"),
    ("bleu", "blue", "blau", "azul", "adjectif", "A1"),
    ("le bateau", "boat", "das Boot", "el barco", "nom", "A1"),
    ("le corps", "body", "der K\u00f6rper", "el cuerpo", "nom", "A1"),
    ("le livre", "book", "das Buch", "el libro", "nom", "A1"),
    ("la botte", "boot", "der Stiefel", "la bota", "nom", "A1"),
    ("ennuy\u00e9", "bored", "gelangweilt", "aburrido", "adjectif", "A1"),
    ("ennuyeux", "boring", "langweilig", "aburrido", "adjectif", "A1"),
    ("n\u00e9", "born", "geboren", "nacido", "adjectif", "A1"),
    ("les deux", "both", "beide", "ambos", "det", "A1"),
    ("la bouteille", "bottle", "die Flasche", "la botella", "nom", "A1"),
    ("le fond", "bottom", "der Boden", "el fondo", "nom", "A1"),
    ("la bo\u00eete", "box", "die Box", "la caja", "nom", "A1"),
    ("le gar\u00e7on", "boy", "der Junge", "el chico", "nom", "A1"),
    ("le petit-ami", "boyfriend", "der Freund", "el novio", "nom", "A1"),
    ("le pain", "bread", "das Brot", "el pan", "nom", "A1"),
    ("casser", "break", "brechen", "romper", "verbe", "A1"),
    ("le petit-d\u00e9jeuner", "breakfast", "das Fr\u00fchst\u00fcck", "el desayuno", "nom", "A1"),
    ("apporter", "bring", "bringen", "traer", "verbe", "A1"),
    ("le fr\u00e8re", "brother", "der Bruder", "el hermano", "nom", "A1"),
    ("marron", "brown", "braun", "marr\u00f3n", "adjectif", "A1"),
    ("construire", "build", "bauen", "construir", "verbe", "A1"),
    ("le b\u00e2timent", "building", "das Geb\u00e4ude", "el edificio", "nom", "A1"),
    ("le bus", "bus", "der Bus", "el autob\u00fas", "nom", "A1"),
    ("l'entreprise", "business", "das Gesch\u00e4ft", "el negocio", "nom", "A1"),
    ("occup\u00e9", "busy", "besch\u00e4ftigt", "ocupado", "adjectif", "A1"),
    ("mais", "but", "aber", "pero", "conjonction", "A1"),
    ("le beurre", "butter", "die Butter", "la mantequilla", "nom", "A1"),
    ("acheter", "buy", "kaufen", "comprar", "verbe", "A1"),
    ("par", "by", "von / durch", "por", "prep", "A1"),
    ("au revoir", "bye", "tsch\u00fcss", "adi\u00f3s", "interj", "A1"),

    # --- LETTRE C ---
    ("le caf\u00e9 (lieu)", "cafe", "das Caf\u00e9", "la cafeter\u00eda", "nom", "A1"),
    ("le g\u00e2teau", "cake", "der Kuchen", "el pastel", "nom", "A1"),
    ("appeler", "call", "anrufen", "llamar", "verbe", "A1"),
    ("l'appareil photo", "camera", "die Kamera", "la c\u00e1mara", "nom", "A1"),
    ("pouvoir", "can", "k\u00f6nnen", "poder", "verbe", "A1"),
    ("ne pas pouvoir", "cannot", "nicht k\u00f6nnen", "no poder", "verbe", "A1"),
    ("la capitale", "capital", "die Hauptstadt", "la capital", "nom", "A1"),
    ("la voiture", "car", "das Auto", "el coche", "nom", "A1"),
    ("la carte", "card", "die Karte", "la tarjeta", "nom", "A1"),
    ("la carotte", "carrot", "die Karotte", "la zanahoria", "nom", "A1"),
    ("porter", "carry", "tragen", "llevar", "verbe", "A1"),
    ("le chat", "cat", "die Katze", "el gato", "nom", "A1"),
    ("le CD", "CD", "die CD", "el CD", "nom", "A1"),
    ("le centime", "cent", "der Cent", "el c\u00e9ntimo", "nom", "A1"),
    ("le centre", "centre", "das Zentrum", "el centro", "nom", "A1"),
    ("la chaise", "chair", "der Stuhl", "la silla", "nom", "A1"),
    ("changer", "change", "\u00e4ndern", "cambiar", "verbe", "A1"),
    ("le graphique", "chart", "das Diagramm", "el gr\u00e1fico", "nom", "A1"),
    ("bon march\u00e9", "cheap", "billig", "barato", "adjectif", "A1"),
    ("v\u00e9rifier", "check", "\u00fcberpr\u00fcfen", "comprobar", "verbe", "A1"),
    ("le fromage", "cheese", "der K\u00e4se", "el queso", "nom", "A1"),
    ("le poulet", "chicken", "das H\u00e4hnchen", "el pollo", "nom", "A1"),
    ("l'enfant", "child", "das Kind", "el ni\u00f1o", "nom", "A1"),
    ("le chocolat", "chocolate", "die Schokolade", "el chocolate", "nom", "A1"),
    ("choisir", "choose", "w\u00e4hlen", "elegir", "verbe", "A1"),
    ("le cin\u00e9ma", "cinema", "das Kino", "el cine", "nom", "A1"),
    ("la ville", "city", "die Stadt", "la ciudad", "nom", "A1"),
    ("la classe", "class", "die Klasse", "la clase", "nom", "A1"),
    ("la salle de classe", "classroom", "das Klassenzimmer", "el aula", "nom", "A1"),
    ("nettoyer", "clean", "putzen", "limpiar", "verbe", "A1"),
    ("propre", "clean", "sauber", "limpio", "adjectif", "A1"),
    ("grimper", "climb", "klettern", "escalar", "verbe", "A1"),
    ("l'horloge", "clock", "die Uhr", "el reloj", "nom", "A1"),
    ("fermer", "close", "schlie\u00dfen", "cerrar", "verbe", "A1"),
    ("les v\u00eatements", "clothes", "die Kleidung", "la ropa", "nom", "A1"),
    ("le club", "club", "der Club", "el club", "nom", "A1"),
    ("le manteau", "coat", "der Mantel", "el abrigo", "nom", "A1"),
    ("le caf\u00e9 (boisson)", "coffee", "der Kaffee", "el caf\u00e9", "nom", "A1"),
    ("froid", "cold", "kalt", "fr\u00edo", "adjectif", "A1"),
    ("le coll\u00e8ge", "college", "das College", "la universidad", "nom", "A1"),
    ("la couleur", "colour", "die Farbe", "el color", "nom", "A1"),
    ("venir", "come", "kommen", "venir", "verbe", "A1"),
    ("l'entreprise (2)", "company", "das Unternehmen", "la empresa", "nom", "A1"),
    ("compl\u00e9ter", "complete", "vervollst\u00e4ndigen", "completar", "verbe", "A1"),
    ("l'ordinateur", "computer", "der Computer", "el ordenador", "nom", "A1"),
    ("le concert", "concert", "das Konzert", "el concierto", "nom", "A1"),
    ("cuisiner", "cook", "kochen", "cocinar", "verbe", "A1"),
    ("la cuisine (action)", "cooking", "das Kochen", "la cocina", "nom", "A1"),
    ("g\u00e9nial / frais", "cool", "cool", "genial / fresco", "adjectif", "A1"),
    ("correct", "correct", "richtig", "correcto", "adjectif", "A1"),
    ("co\u00fbter", "cost", "kosten", "costar", "verbe", "A1"),
    ("pourrait", "could", "k\u00f6nnte", "podr\u00eda", "verbe", "A1"),
    ("le pays", "country", "das Land", "el pa\u00eds", "nom", "A1"),
    ("le cours", "course", "der Kurs", "el curso", "nom", "A1"),
    ("le cousin", "cousin", "der Cousin", "el primo", "nom", "A1"),
    ("la vache", "cow", "die Kuh", "la vaca", "nom", "A1"),
    ("la cr\u00e8me", "cream", "die Sahne", "la crema", "nom", "A1"),
    ("la tasse", "cup", "die Tasse", "la taza", "nom", "A1"),
    ("le client", "customer", "der Kunde", "el cliente", "nom", "A1"),
    ("couper", "cut", "schneiden", "cortar", "verbe", "A1"),

    # --- LETTRE D ---
    ("le papa", "dad", "der Papa", "el pap\u00e1", "nom", "A1"),
    ("quotidien", "daily", "t\u00e4glich", "diario", "adjectif", "A1"),
    ("danser", "dance", "tanzen", "bailar", "verbe", "A1"),
    ("le danseur", "dancer", "der T\u00e4nzer", "el bailar\u00edn", "nom", "A1"),
    ("la danse", "dancing", "das Tanzen", "el baile", "nom", "A1"),
    ("dangereux", "dangerous", "gef\u00e4hrlich", "peligroso", "adjectif", "A1"),
    ("sombre", "dark", "dunkel", "oscuro", "adjectif", "A1"),
    ("la date", "date", "das Datum", "la fecha", "nom", "A1"),
    ("la fille (enfant)", "daughter", "die Tochter", "la hija", "nom", "A1"),
    ("le jour", "day", "der Tag", "el d\u00eda", "nom", "A1"),
    ("cher (affection)", "dear", "lieb", "querido", "adjectif", "A1"),
    ("d\u00e9cembre", "December", "Dezember", "diciembre", "nom", "A1"),
    ("d\u00e9cider", "decide", "entscheiden", "decidir", "verbe", "A1"),
    ("d\u00e9licieux", "delicious", "k\u00f6stlich", "delicioso", "adjectif", "A1"),
    ("le bureau", "desk", "der Schreibtisch", "el escritorio", "nom", "A1"),
    ("le d\u00e9tail", "detail", "das Detail", "el detalle", "nom", "A1"),
    ("le dialogue", "dialogue", "der Dialog", "el di\u00e1logo", "nom", "A1"),
    ("le dictionnaire", "dictionary", "das W\u00f6rterbuch", "el diccionario", "nom", "A1"),
    ("mourir", "die", "sterben", "morir", "verbe", "A1"),
    ("le r\u00e9gime", "diet", "die Di\u00e4t", "la dieta", "nom", "A1"),
    ("diff\u00e9rent", "different", "anders", "diferente", "adjectif", "A1"),
    ("difficile", "difficult", "schwierig", "dif\u00edcil", "adjectif", "A1"),
    ("le d\u00eener", "dinner", "das Abendessen", "la cena", "nom", "A1"),
    ("sale", "dirty", "schmutzig", "sucio", "adjectif", "A1"),
    ("le plat", "dish", "das Gericht", "el plato", "nom", "A1"),
    ("faire", "do", "tun / machen", "hacer", "verbe", "A1"),
    ("le docteur", "doctor", "der Arzt", "el m\u00e9dico", "nom", "A1"),
    ("le chien", "dog", "der Hund", "el perro", "nom", "A1"),
    ("le dollar", "dollar", "der Dollar", "el d\u00f3lar", "nom", "A1"),
    ("la porte", "door", "die T\u00fcr", "la puerta", "nom", "A1"),
    ("en bas", "down", "unten", "abajo", "adverbe", "A1"),
    ("en bas (escaliers)", "downstairs", "unten", "abajo", "adverbe", "A1"),
    ("dessiner", "draw", "zeichnen", "dibujar", "verbe", "A1"),
    ("la robe", "dress", "das Kleid", "el vestido", "nom", "A1"),
    ("boire", "drink", "trinken", "beber", "verbe", "A1"),
    ("conduire", "drive", "fahren", "conducir", "verbe", "A1"),
    ("le chauffeur", "driver", "der Fahrer", "el conductor", "nom", "A1"),
    ("la conduite", "driving", "das Fahren", "la conducci\u00f3n", "nom", "A1"),
    ("sec", "dry", "trocken", "seco", "adjectif", "A1"),
    ("pendant", "during", "w\u00e4hrend", "durante", "prep", "A1"),
    ("le DVD", "DVD", "die DVD", "el DVD", "nom", "A1")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\append_part1.ps1", $new_words, $utf8NoBom)
