$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE I ---
    ("je", "I", "ich", "yo", "pron", "A1"),
    ("la glace / le gla\u00e7on", "ice", "das Eis", "el hielo", "nom", "A1"),
    ("la cr\u00e8me glac\u00e9e", "ice cream", "das Eis", "el helado", "nom", "A1"),
    ("l'id\u00e9e", "idea", "die Idee", "la idea", "nom", "A1"),
    ("si", "if", "wenn", "si", "conjonction", "A1"),
    ("imaginer", "imagine", "sich vorstellen", "imaginar", "verbe", "A1"),
    ("important", "important", "wichtig", "importante", "adjectif", "A1"),
    ("dans", "in", "in", "en", "prep", "A1"),
    ("inclure", "include", "einschlie\u00dfen", "incluir", "verbe", "A1"),
    ("l'information", "information", "die Information", "la informaci\u00f3n", "nom", "A1"),
    ("int\u00e9ressant", "interesting", "interessant", "interesante", "adjectif", "A1"),
    ("Internet", "internet", "das Internet", "internet", "nom", "A1"),
    ("l'interview", "interview", "das Interview", "la entrevista", "nom", "A1"),
    ("dans / vers l'int\u00e9rieur", "into", "in ... hinein", "hacia adentro", "prep", "A1"),
    ("l'\u00eele", "island", "die Insel", "la isla", "nom", "A1"),
    ("il / elle (chose)", "it", "es", "lo / la", "pron", "A1"),
    ("son / sa (chose)", "its", "sein / ihr", "su", "det", "A1"),

    # --- LETTRE J ---
    ("la veste", "jacket", "die Jacke", "la chaqueta", "nom", "A1"),
    ("janvier", "January", "Januar", "enero", "nom", "A1"),
    ("le jean", "jeans", "die Jeans", "los vaqueros", "nom", "A1"),
    ("le travail (emploi)", "job", "der Job", "el trabajo", "nom", "A1"),
    ("rejoindre", "join", "beitreten", "unirse", "verbe", "A1"),
    ("le voyage (trajet)", "journey", "die Reise", "el viaje", "nom", "A1"),
    ("le jus", "juice", "der Saft", "el jugo", "nom", "A1"),
    ("juillet", "July", "Juli", "julio", "nom", "A1"),
    ("juin", "June", "Juni", "junio", "nom", "A1"),
    ("juste", "just", "nur / gerade", "justo / s\u00f3lo", "adverbe", "A1"),

    # --- LETTRE K ---
    ("garder", "keep", "behalten", "mantener", "verbe", "A1"),
    ("la cl\u00e9", "key", "der Schl\u00fcssel", "la llave", "nom", "A1"),
    ("le kilom\u00e8tre", "kilometre", "der Kilometer", "el kil\u00f3metro", "nom", "A1"),
    ("aimable / gentil", "kind", "freundlich", "amable", "adjectif", "A1"),
    ("la cuisine (pi\u00e8ce)", "kitchen", "die K\u00fcche", "la cocina", "nom", "A1"),
    ("savoir / conna\u00eetre", "know", "wissen / kennen", "saber / conocer", "verbe", "A1"),

    # --- LETTRE L ---
    ("le lac", "lake", "der See", "el lago", "nom", "A1"),
    ("la langue", "language", "die Sprache", "el idioma", "nom", "A1"),
    ("grand (vaste)", "large", "gro\u00df", "grande", "adjectif", "A1"),
    ("dernier", "last", "letzte", "\u00faltimo", "adjectif", "A1"),
    ("tard", "late", "sp\u00e4t", "tarde", "adjectif", "A1"),
    ("plus tard", "later", "sp\u00e4ter", "m\u00e1s tarde", "adverbe", "A1"),
    ("rire", "laugh", "lachen", "re\u00edr", "verbe", "A1"),
    ("apprendre", "learn", "lernen", "aprender", "verbe", "A1"),
    ("quitter / laisser", "leave", "verlassen", "dejar / salir", "verbe", "A1"),
    ("la gauche", "left", "links", "la izquierda", "nom", "A1"),
    ("la jambe", "leg", "das Bein", "la pierna", "nom", "A1"),
    ("la le\u00e7on", "lesson", "die Lektion", "la lecci\u00f3n", "nom", "A1"),
    ("laisser / louer", "let", "lassen", "dejar", "verbe", "A1"),
    ("la lettre (alphabet/courrier)", "letter", "der Brief / der Buchstabe", "la carta / la letra", "nom", "A1"),
    ("la biblioth\u00e8que", "library", "die Bibliothek", "la biblioteca", "nom", "A1"),
    ("le mensonge", "lie", "die L\u00fcge", "la mentira", "nom", "A1"),
    ("la vie", "life", "das Leben", "la vida", "nom", "A1"),
    ("la lumi\u00e8re", "light", "das Licht", "la luz", "nom", "A1"),
    ("aimer", "like", "m\u00f6gen", "gustar", "verbe", "A1"),
    ("comme", "like", "wie", "como", "prep", "A1"),
    ("la ligne", "line", "die Linie", "la l\u00ednea", "nom", "A1"),
    ("le lion", "lion", "der L\u00f6we", "el le\u00f3n", "nom", "A1"),
    ("la liste", "list", "die Liste", "la lista", "nom", "A1"),
    ("\u00e9couter", "listen", "zuh\u00f6ren", "escuchar", "verbe", "A1"),
    ("petit", "little", "klein / wenig", "peque\u00f1o / poco", "adjectif", "A1"),
    ("vivre", "live", "leben", "vivir", "verbe", "A1"),
    ("local", "local", "lokal", "local", "adjectif", "A1"),
    ("long", "long", "lang", "largo", "adjectif", "A1"),
    ("regarder", "look", "schauen", "mirar", "verbe", "A1"),
    ("perdre", "lose", "verlieren", "perder", "verbe", "A1"),
    ("beaucoup", "a lot", "viel", "mucho", "pron", "A1"),
    ("aimer (amour)", "love", "lieben", "amar", "verbe", "A1"),
    ("le d\u00e9jeuner", "lunch", "das Mittagessen", "el almuerzo", "nom", "A1")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\append_part3.ps1", $new_words, $utf8NoBom)
