$utf8NoBom = New-Object System.Text.UTF8Encoding $False
$content = [System.IO.File]::ReadAllText("$PSScriptRoot\generate_data.py", $utf8NoBom)

$new_words = @"
    ,
    # --- LETTRE S (Part 2) ---
    ("la neige", "snow", "der Schnee", "la nieve", "nom", "A1"),
    ("donc / alors", "so", "also", "así que", "conjonction", "A1"),
    ("le canapé", "sofa", "das Sofa", "el sofá", "nom", "A1"),
    ("quelques / du", "some", "einige / etwas", "algunos / algo de", "det", "A1"),
    ("quelqu'un (somebody)", "somebody", "jemand", "alguien", "pron", "A1"),
    ("quelqu'un (someone)", "someone", "jemand", "alguien", "pron", "A1"),
    ("quelque chose", "something", "etwas", "algo", "pron", "A1"),
    ("parfois", "sometimes", "manchmal", "a veces", "adverbe", "A1"),
    ("le fils", "son", "der Sohn", "el hijo", "nom", "A1"),
    ("la chanson", "song", "das Lied", "la canción", "nom", "A1"),
    ("bientôt", "soon", "bald", "pronto", "adverbe", "A1"),
    ("désolé", "sorry", "entschuldigung", "lo siento", "adjectif", "A1"),
    ("le son / le bruit", "sound", "der Klang / das Geräusch", "el sonido", "nom", "A1"),
    ("la soupe", "soup", "die Suppe", "la sopa", "nom", "A1"),
    ("le sud", "south", "der Süden", "el sur", "nom", "A1"),
    ("l'espace", "space", "der Raum / der Platz", "el espacio", "nom", "A1"),
    ("parler", "speak", "sprechen", "hablar", "verbe", "A1"),
    ("spécial", "special", "speziell", "especial", "adjectif", "A1"),
    ("épeler", "spell", "buchstabieren", "deletrear", "verbe", "A1"),
    ("l'orthographe", "spelling", "die Rechtschreibung", "la ortografía", "nom", "A1"),
    ("dépenser / passer (temps)", "spend", "verbringen / ausgeben", "gastar / pasar", "verbe", "A1"),
    ("le sport", "sport", "der Sport", "el deporte", "nom", "A1"),
    ("le printemps", "spring", "der Frühling", "la primavera", "nom", "A1"),
    ("se tenir debout", "stand", "stehen", "estar de pie", "verbe", "A1"),
    ("commencer", "start", "anfangen", "empezar", "verbe", "A1"),
    ("la gare / la station", "station", "der Bahnhof / die Station", "la estación", "nom", "A1"),
    ("arrêter", "stop", "stoppen", "parar", "verbe", "A1"),
    ("l'histoire", "story", "die Geschichte", "la historia", "nom", "A1"),
    ("la rue", "street", "die Straße", "la calle", "nom", "A1"),
    ("fort", "strong", "stark", "fuerte", "adjectif", "A1"),
    ("l'étudiant", "student", "der Student", "el estudiante", "nom", "A1"),
    ("étudier", "study", "studieren / lernen", "estudiar", "verbe", "A1"),
    ("le style", "style", "der Stil", "el estilo", "nom", "A1"),
    ("le sujet / la matière", "subject", "das Thema / das Fach", "el tema / la asignatura", "nom", "A1"),
    ("le sucre", "sugar", "der Zucker", "el azúcar", "nom", "A1"),
    ("l'été", "summer", "der Sommer", "el verano", "nom", "A1"),
    ("le soleil", "sun", "die Sonne", "el sol", "nom", "A1"),
    ("dimanche", "Sunday", "Sonntag", "domingo", "nom", "A1"),
    ("le supermarché", "supermarket", "der Supermarkt", "el supermercado", "nom", "A1"),
    ("sûr", "sure", "sicher", "seguro", "adjectif", "A1"),
    ("le pull", "sweater", "der Pullover", "el suéter", "nom", "A1"),
    ("nager", "swim", "schwimmen", "nadar", "verbe", "A1"),
    ("la natation", "swimming", "das Schwimmen", "la natación", "nom", "A1"),

    # --- LETTRE T ---
    ("la table", "table", "der Tisch", "la mesa", "nom", "A1"),
    ("prendre", "take", "nehmen", "tomar", "verbe", "A1"),
    ("parler", "talk", "reden", "hablar", "verbe", "A1"),
    ("grand (taille)", "tall", "groß", "alto", "adjectif", "A1"),
    ("le taxi", "taxi", "das Taxi", "el taxi", "nom", "A1"),
    ("le thé", "tea", "der Tee", "el té", "nom", "A1"),
    ("enseigner", "teach", "unterrichten", "enseñar", "verbe", "A1"),
    ("le professeur", "teacher", "der Lehrer", "el profesor", "nom", "A1"),
    ("l'équipe", "team", "das Team", "el equipo", "nom", "A1"),
    ("l'adolescent", "teenager", "der Teenager", "el adolescente", "nom", "A1"),
    ("le téléphone", "telephone", "das Telefon", "el teléfono", "nom", "A1"),
    ("la télévision", "television", "das Fernsehen", "la televisión", "nom", "A1"),
    ("raconter / dire", "tell", "erzählen", "contar / decir", "verbe", "A1"),
    ("dix", "ten", "zehn", "diez", "num", "A1"),
    ("le tennis", "tennis", "das Tennis", "el tenis", "nom", "A1"),
    ("terrible", "terrible", "schrecklich", "terrible", "adjectif", "A1"),
    ("le test", "test", "der Test", "la prueba", "nom", "A1"),
    ("le texte", "text", "der Text", "el texto", "nom", "A1"),
    ("que (comparaison)", "than", "als", "que", "conjonction", "A1"),
    ("remercier", "thank", "danken", "agradecer", "verbe", "A1"),
    ("merci", "thanks", "danke", "gracias", "interj", "A1"),
    ("que / cela", "that", "dass / das", "que / eso", "det", "A1"),
    ("le / la / les", "the", "der / die / das", "el / la / los / las", "det", "A1"),
    ("le théâtre", "theatre", "das Theater", "el teatro", "nom", "A1"),
    ("leur", "their", "ihr", "su", "det", "A1"),
    ("eux / les", "them", "sie / ihnen", "ellos / los", "pron", "A1"),
    ("ensuite / alors", "then", "dann", "luego / entonces", "adverbe", "A1"),
    ("là-bas", "there", "dort", "allí", "adverbe", "A1"),
    ("ils / elles", "they", "sie", "ellos", "pron", "A1"),
    ("la chose", "thing", "das Ding", "la cosa", "nom", "A1"),
    ("penser", "think", "denken", "pensar", "verbe", "A1"),
    ("troisième", "third", "dritte", "tercero", "num", "A1"),
    ("assoiffé", "thirsty", "durstig", "sediento", "adjectif", "A1"),
    ("treize", "thirteen", "dreizehn", "trece", "num", "A1"),
    ("trente", "thirty", "dreißig", "treinta", "num", "A1"),
    ("ce / ceci", "this", "dies", "este / esto", "det", "A1"),
    ("mille", "thousand", "tausend", "mil", "num", "A1"),
    ("trois", "three", "drei", "tres", "num", "A1"),
    ("à travers / par", "through", "durch", "a través de", "prep", "A1"),
    ("jeudi", "Thursday", "Donnerstag", "jueves", "nom", "A1"),
    ("le billet / ticket", "ticket", "das Ticket", "el billete", "nom", "A1"),
    ("le temps / l'heure", "time", "die Zeit", "el tiempo", "nom", "A1"),
    ("fatigué", "tired", "müde", "cansado", "adjectif", "A1"),
    ("le titre", "title", "der Titel", "el título", "nom", "A1"),
    ("à / vers", "to", "zu", "a / hacia", "prep", "A1"),
    ("aujourd'hui", "today", "heute", "hoy", "adverbe", "A1"),
    ("ensemble", "together", "zusammen", "juntos", "adverbe", "A1"),
    ("les toilettes", "toilet", "die Toilette", "el baño", "nom", "A1"),
    ("la tomate", "tomato", "die Tomate", "el tomate", "nom", "A1"),
    ("demain", "tomorrow", "morgen", "mañana", "adverbe", "A1"),
    ("ce soir", "tonight", "heute Abend", "esta noche", "adverbe", "A1"),
    ("aussi / trop", "too", "auch / zu", "también / demasiado", "adverbe", "A1"),
    ("le haut / sommet", "top", "oben", "arriba / cima", "nom", "A1"),
    ("la dent", "tooth", "der Zahn", "el diente", "nom", "A1"),
    ("le touriste", "tourist", "der Tourist", "el turista", "nom", "A1"),
    ("la ville", "town", "die Stadt", "el pueblo", "nom", "A1"),
    ("le trafic / circulation", "traffic", "der Verkehr", "el tráfico", "nom", "A1"),
    ("le train", "train", "der Zug", "el tren", "nom", "A1"),
    ("voyager", "travel", "reisen", "viajar", "verbe", "A1"),
    ("l'arbre", "tree", "der Baum", "el árbol", "nom", "A1"),
    ("le voyage (court)", "trip", "die Reise", "el viaje", "nom", "A1"),
    ("le pantalon", "trousers", "die Hose", "los pantalones", "nom", "A1"),
    ("vrai", "true", "wahr", "verdadero", "adjectif", "A1"),
    ("essayer", "try", "versuchen", "intentar", "verbe", "A1"),
    ("le t-shirt", "T-shirt", "das T-Shirt", "la camiseta", "nom", "A1"),
    ("mardi", "Tuesday", "Dienstag", "martes", "nom", "A1"),
    ("tourner", "turn", "drehen", "girar", "verbe", "A1"),
    ("la télé", "TV", "der Fernseher", "la tele", "nom", "A1"),
    ("douze", "twelve", "zwölf", "doce", "num", "A1"),
    ("vingt", "twenty", "zwanzig", "veinte", "num", "A1"),
    ("deux fois", "twice", "zweimal", "dos veces", "adverbe", "A1"),
    ("deux", "two", "zwei", "dos", "num", "A1"),
    ("le type / genre", "type", "der Typ", "el tipo", "nom", "A1"),

    # --- LETTRE U ---
    ("le parapluie", "umbrella", "der Regenschirm", "el paraguas", "nom", "A1"),
    ("l'oncle", "uncle", "der Onkel", "el tío", "nom", "A1"),
    ("sous", "under", "unter", "debajo", "prep", "A1"),
    ("comprendre", "understand", "verstehen", "entender", "verbe", "A1"),
    ("l'université", "university", "die Universität", "la universidad", "nom", "A1"),
    ("jusqu'à", "until", "bis", "hasta", "conjonction", "A1"),
    ("en haut", "up", "auf / hoch", "arriba", "adverbe", "A1"),
    ("en haut (escaliers)", "upstairs", "oben", "arriba", "adverbe", "A1"),
    ("nous", "us", "uns", "nos", "pron", "A1"),
    ("utiliser", "use", "benutzen", "usar", "verbe", "A1"),
    ("habituellement", "usually", "normalerweise", "usualmente", "adverbe", "A1")
"@

$content = $content -replace 'vocab_list = \[', "vocab_list = [$new_words"

[System.IO.File]::WriteAllText("$PSScriptRoot\generate_data.py", $content, $utf8NoBom)
Write-Host "Part 5 (S2-U) injected."
