$utf8NoBom = New-Object System.Text.UTF8Encoding $False

$new_words = @"
    # --- LETTRE S (Part 2) ---
    ("la neige", "snow", "der Schnee", "la nieve", "nom", "A1"),
    ("donc / alors", "so", "also", "as\u00ed que", "conjonction", "A1"),
    ("le canap\u00e9", "sofa", "das Sofa", "el sof\u00e1", "nom", "A1"),
    ("quelques / du", "some", "einige / etwas", "algunos / algo de", "det", "A1"),
    ("quelqu'un (somebody)", "somebody", "jemand", "alguien", "pron", "A1"),
    ("quelqu'un (someone)", "someone", "jemand", "alguien", "pron", "A1"),
    ("quelque chose", "something", "etwas", "algo", "pron", "A1"),
    ("parfois", "sometimes", "manchmal", "a veces", "adverbe", "A1"),
    ("le fils", "son", "der Sohn", "el hijo", "nom", "A1"),
    ("la chanson", "song", "das Lied", "la canci\u00f3n", "nom", "A1"),
    ("bient\u00f4t", "soon", "bald", "pronto", "adverbe", "A1"),
    ("d\u00e9sol\u00e9", "sorry", "entschuldigung", "lo siento", "adjectif", "A1"),
    ("le son / le bruit", "sound", "der Klang / das Ger\u00e4usch", "el sonido", "nom", "A1"),
    ("la soupe", "soup", "die Suppe", "la sopa", "nom", "A1"),
    ("le sud", "south", "der S\u00fcden", "el sur", "nom", "A1"),
    ("l'espace", "space", "der Raum / der Platz", "el espacio", "nom", "A1"),
    ("parler", "speak", "sprechen", "hablar", "verbe", "A1"),
    ("sp\u00e9cial", "special", "speziell", "especial", "adjectif", "A1"),
    ("\u00e9peler", "spell", "buchstabieren", "deletrear", "verbe", "A1"),
    ("l'orthographe", "spelling", "die Rechtschreibung", "la ortograf\u00eda", "nom", "A1"),
    ("d\u00e9penser / passer (temps)", "spend", "verbringen / ausgeben", "gastar / pasar", "verbe", "A1"),
    ("le sport", "sport", "der Sport", "el deporte", "nom", "A1"),
    ("le printemps", "spring", "der Fr\u00fchling", "la primavera", "nom", "A1"),
    ("se tenir debout", "stand", "stehen", "estar de pie", "verbe", "A1"),
    ("commencer", "start", "anfangen", "empezar", "verbe", "A1"),
    ("la gare / la station", "station", "der Bahnhof / die Station", "la estaci\u00f3n", "nom", "A1"),
    ("arr\u00eater", "stop", "stoppen", "parar", "verbe", "A1"),
    ("l'histoire", "story", "die Geschichte", "la historia", "nom", "A1"),
    ("la rue", "street", "die Stra\u00dfe", "la calle", "nom", "A1"),
    ("fort", "strong", "stark", "fuerte", "adjectif", "A1"),
    ("l'\u00e9tudiant", "student", "der Student", "el estudiante", "nom", "A1"),
    ("\u00e9tudier", "study", "studieren / lernen", "estudiar", "verbe", "A1"),
    ("le style", "style", "der Stil", "el estilo", "nom", "A1"),
    ("le sujet / la mati\u00e8re", "subject", "das Thema / das Fach", "el tema / la asignatura", "nom", "A1"),
    ("le sucre", "sugar", "der Zucker", "el az\u00facar", "nom", "A1"),
    ("l'\u00e9t\u00e9", "summer", "der Sommer", "el verano", "nom", "A1"),
    ("le soleil", "sun", "die Sonne", "el sol", "nom", "A1"),
    ("dimanche", "Sunday", "Sonntag", "domingo", "nom", "A1"),
    ("le supermarch\u00e9", "supermarket", "der Supermarkt", "el supermercado", "nom", "A1"),
    ("s\u00fbr", "sure", "sicher", "seguro", "adjectif", "A1"),
    ("le pull", "sweater", "der Pullover", "el su\u00e9ter", "nom", "A1"),
    ("nager", "swim", "schwimmen", "nadar", "verbe", "A1"),
    ("la natation", "swimming", "das Schwimmen", "la nataci\u00f3n", "nom", "A1"),

    # --- LETTRE T ---
    ("la table", "table", "der Tisch", "la mesa", "nom", "A1"),
    ("prendre", "take", "nehmen", "tomar", "verbe", "A1"),
    ("parler", "talk", "reden", "hablar", "verbe", "A1"),
    ("grand (taille)", "tall", "gro\u00df", "alto", "adjectif", "A1"),
    ("le taxi", "taxi", "das Taxi", "el taxi", "nom", "A1"),
    ("le th\u00e9", "tea", "der Tee", "el t\u00e9", "nom", "A1"),
    ("enseigner", "teach", "unterrichten", "ense\u00f1ar", "verbe", "A1"),
    ("le professeur", "teacher", "der Lehrer", "el profesor", "nom", "A1"),
    ("l'\u00e9quipe", "team", "das Team", "el equipo", "nom", "A1"),
    ("l'adolescent", "teenager", "der Teenager", "el adolescente", "nom", "A1"),
    ("le t\u00e9l\u00e9phone", "telephone", "das Telefon", "el tel\u00e9fono", "nom", "A1"),
    ("la t\u00e9l\u00e9vision", "television", "das Fernsehen", "la televisi\u00f3n", "nom", "A1"),
    ("raconter / dire", "tell", "erz\u00e4hlen", "contar / decir", "verbe", "A1"),
    ("dix", "ten", "zehn", "diez", "num", "A1"),
    ("le tennis", "tennis", "das Tennis", "el tenis", "nom", "A1"),
    ("terrible", "terrible", "schrecklich", "terrible", "adjectif", "A1"),
    ("le test", "test", "der Test", "la prueba", "nom", "A1"),
    ("le texte", "text", "der Text", "el texto", "nom", "A1"),
    ("que (comparaison)", "than", "als", "que", "conjonction", "A1"),
    ("remercier", "thank", "danken", "agradecer", "verbe", "A1"),
    ("merci", "thanks", "danke", "gracias", "interj", "A1"),
    ("que / cela", "that", "dass / das", "que / eso", "det", "A1"),
    ("le / la / les", "the", "der / die / das", "el / la / los / las", "det", "A1"),
    ("le th\u00e9\u00e2tre", "theatre", "das Theater", "el teatro", "nom", "A1"),
    ("leur", "their", "ihr", "su", "det", "A1"),
    ("eux / les", "them", "sie / ihnen", "ellos / los", "pron", "A1"),
    ("ensuite / alors", "then", "dann", "luego / entonces", "adverbe", "A1"),
    ("l\u00e0-bas", "there", "dort", "all\u00ed", "adverbe", "A1"),
    ("ils / elles", "they", "sie", "ellos", "pron", "A1"),
    ("la chose", "thing", "das Ding", "la cosa", "nom", "A1"),
    ("penser", "think", "denken", "pensar", "verbe", "A1"),
    ("troisi\u00e8me", "third", "dritte", "tercero", "num", "A1"),
    ("assoiff\u00e9", "thirsty", "durstig", "sediento", "adjectif", "A1"),
    ("treize", "thirteen", "dreizehn", "trece", "num", "A1"),
    ("trente", "thirty", "drei\u00dfig", "treinta", "num", "A1"),
    ("ce / ceci", "this", "dies", "este / esto", "det", "A1"),
    ("mille", "thousand", "tausend", "mil", "num", "A1"),
    ("trois", "three", "drei", "tres", "num", "A1"),
    ("\u00e0 travers / par", "through", "durch", "a trav\u00e9s de", "prep", "A1"),
    ("jeudi", "Thursday", "Donnerstag", "jueves", "nom", "A1"),
    ("le billet / ticket", "ticket", "das Ticket", "el billete", "nom", "A1"),
    ("le temps / l'heure", "time", "die Zeit", "el tiempo", "nom", "A1"),
    ("fatigu\u00e9", "tired", "m\u00fcde", "cansado", "adjectif", "A1"),
    ("le titre", "title", "der Titel", "el t\u00edtulo", "nom", "A1"),
    ("\u00e0 / vers", "to", "zu", "a / hacia", "prep", "A1"),
    ("aujourd'hui", "today", "heute", "hoy", "adverbe", "A1"),
    ("ensemble", "together", "zusammen", "juntos", "adverbe", "A1"),
    ("les toilettes", "toilet", "die Toilette", "el ba\u00f1o", "nom", "A1"),
    ("la tomate", "tomato", "die Tomate", "el tomate", "nom", "A1"),
    ("demain", "tomorrow", "morgen", "ma\u00f1ana", "adverbe", "A1"),
    ("ce soir", "tonight", "heute Abend", "esta noche", "adverbe", "A1"),
    ("aussi / trop", "too", "auch / zu", "tambi\u00e9n / demasiado", "adverbe", "A1"),
    ("le haut / sommet", "top", "oben", "arriba / cima", "nom", "A1"),
    ("la dent", "tooth", "der Zahn", "el diente", "nom", "A1"),
    ("le touriste", "tourist", "der Tourist", "el turista", "nom", "A1"),
    ("la ville", "town", "die Stadt", "el pueblo", "nom", "A1"),
    ("le trafic / circulation", "traffic", "der Verkehr", "el tr\u00e1fico", "nom", "A1"),
    ("le train", "train", "der Zug", "el tren", "nom", "A1"),
    ("voyager", "travel", "reisen", "viajar", "verbe", "A1"),
    ("l'arbre", "tree", "der Baum", "el \u00e1rbol", "nom", "A1"),
    ("le voyage (court)", "trip", "die Reise", "el viaje", "nom", "A1"),
    ("le pantalon", "trousers", "die Hose", "los pantalones", "nom", "A1"),
    ("vrai", "true", "wahr", "verdadero", "adjectif", "A1"),
    ("essayer", "try", "versuchen", "intentar", "verbe", "A1"),
    ("le t-shirt", "T-shirt", "das T-Shirt", "la camiseta", "nom", "A1"),
    ("mardi", "Tuesday", "Dienstag", "martes", "nom", "A1"),
    ("tourner", "turn", "drehen", "girar", "verbe", "A1"),
    ("la t\u00e9l\u00e9", "TV", "der Fernseher", "la tele", "nom", "A1"),
    ("douze", "twelve", "zw\u00f6lf", "doce", "num", "A1"),
    ("vingt", "twenty", "zwanzig", "veinte", "num", "A1"),
    ("deux fois", "twice", "zweimal", "dos veces", "adverbe", "A1"),
    ("deux", "two", "zwei", "dos", "num", "A1"),
    ("le type / genre", "type", "der Typ", "el tipo", "nom", "A1"),

    # --- LETTRE U ---
    ("le parapluie", "umbrella", "der Regenschirm", "el paraguas", "nom", "A1"),
    ("l'oncle", "uncle", "der Onkel", "el t\u00edo", "nom", "A1"),
    ("sous", "under", "unter", "debajo", "prep", "A1"),
    ("comprendre", "understand", "verstehen", "entender", "verbe", "A1"),
    ("l'universit\u00e9", "university", "die Universit\u00e4t", "la universidad", "nom", "A1"),
    ("jusqu'\u00e0", "until", "bis", "hasta", "conjonction", "A1"),
    ("en haut", "up", "auf / hoch", "arriba", "adverbe", "A1"),
    ("en haut (escaliers)", "upstairs", "oben", "arriba", "adverbe", "A1"),
    ("nous", "us", "uns", "nos", "pron", "A1"),
    ("utiliser", "use", "benutzen", "usar", "verbe", "A1"),
    ("habituellement", "usually", "normalerweise", "usualmente", "adverbe", "A1"),

    # --- LETTRE V ---
    ("les vacances (US)", "vacation", "der Urlaub", "las vacaciones", "nom", "A1"),
    ("le l\u00e9gume", "vegetable", "das Gem\u00fcse", "la verdura", "nom", "A1"),
    ("tr\u00e8s", "very", "sehr", "muy", "adverbe", "A1"),
    ("la vid\u00e9o", "video", "das Video", "el v\u00eddeo", "nom", "A1"),
    ("le village", "village", "das Dorf", "la aldea", "nom", "A1"),
    ("visiter", "visit", "besuchen", "visitar", "verbe", "A1"),
    ("le visiteur", "visitor", "der Besucher", "el visitante", "nom", "A1"),

    # --- LETTRE W ---
    ("attendre", "wait", "warten", "esperar", "verbe", "A1"),
    ("le serveur", "waiter", "der Kellner", "el camarero", "nom", "A1"),
    ("se r\u00e9veiller", "wake", "aufwachen", "despertar", "verbe", "A1"),
    ("marcher", "walk", "gehen", "caminar", "verbe", "A1"),
    ("le mur", "wall", "die Wand", "la pared", "nom", "A1"),
    ("vouloir", "want", "wollen", "querer", "verbe", "A1"),
    ("chaud / chaleureux", "warm", "warm", "c\u00e1lido", "adjectif", "A1"),
    ("laver", "wash", "waschen", "lavar", "verbe", "A1"),
    ("la montre", "watch", "die Uhr", "el reloj", "nom", "A1"),
    ("regarder (TV)", "watch", "schauen", "mirar", "verbe", "A1"),
    ("l'eau", "water", "das Wasser", "el agua", "nom", "A1"),
    ("le chemin / la fa\u00e7on", "way", "der Weg / die Art", "el camino / la manera", "nom", "A1"),
    ("nous", "we", "wir", "nosotros", "pron", "A1"),
    ("porter (v\u00eatements)", "wear", "tragen", "llevar puesto", "verbe", "A1"),
    ("le temps (m\u00e9t\u00e9o)", "weather", "das Wetter", "el clima", "nom", "A1"),
    ("le site web", "website", "die Website", "el sitio web", "nom", "A1"),
    ("mercredi", "Wednesday", "Mittwoch", "mi\u00e9rcoles", "nom", "A1"),
    ("la semaine", "week", "die Woche", "la semana", "nom", "A1"),
    ("le week-end", "weekend", "das Wochenende", "el fin de semana", "nom", "A1"),
    ("bien", "well", "gut", "bien", "adverbe", "A1"),
    ("l'ouest", "west", "der Westen", "el oeste", "nom", "A1"),
    ("quoi", "what", "was", "qu\u00e9", "pron", "A1"),
    ("quand", "when", "wann", "cu\u00e1ndo", "adverbe", "A1"),
    ("o\u00f9", "where", "wo", "d\u00f3nde", "adverbe", "A1"),
    ("lequel", "which", "welcher", "cu\u00e1l", "pron", "A1"),
    ("blanc", "white", "wei\u00df", "blanco", "adjectif", "A1"),
    ("qui", "who", "wer", "qui\u00e9n", "pron", "A1"),
    ("pourquoi", "why", "warum", "por qu\u00e9", "adverbe", "A1"),
    ("la femme (\u00e9pouse)", "wife", "die Ehefrau", "la esposa", "nom", "A1"),
    ("gagner", "win", "gewinnen", "ganar", "verbe", "A1"),
    ("la fen\u00eatre", "window", "das Fenster", "la ventana", "nom", "A1"),
    ("le vin", "wine", "der Wein", "el vino", "nom", "A1"),
    ("l'hiver", "winter", "der Winter", "el invierno", "nom", "A1"),
    ("avec", "with", "mit", "con", "prep", "A1"),
    ("sans", "without", "ohne", "sin", "prep", "A1"),
    ("la femme", "woman", "die Frau", "la mujer", "nom", "A1"),
    ("merveilleux", "wonderful", "wunderbar", "maravilloso", "adjectif", "A1"),
    ("le mot", "word", "das Wort", "la palabra", "nom", "A1"),
    ("le travail", "work", "die Arbeit", "el trabajo", "nom", "A1"),
    ("travailler", "work", "arbeiten", "trabajar", "verbe", "A1"),
    ("le travailleur", "worker", "der Arbeiter", "el trabajador", "nom", "A1"),
    ("le monde", "world", "die Welt", "el mundo", "nom", "A1"),
    ("voudrait", "would", "w\u00fcrde", "har\u00eda (condicional)", "verbe", "A1"),
    ("\u00e9crire", "write", "schreiben", "escribir", "verbe", "A1"),
    ("l'\u00e9crivain", "writer", "der Autor", "el escritor", "nom", "A1"),
    ("l'\u00e9criture", "writing", "das Schreiben", "la escritura", "nom", "A1"),
    ("faux (erreur)", "wrong", "falsch", "equivocado", "adjectif", "A1"),

    # --- LETTRE Y & Z ---
    ("l'ann\u00e9e", "year", "das Jahr", "el a\u00f1o", "nom", "A1"),
    ("jaune", "yellow", "gelb", "amarillo", "adjectif", "A1"),
    ("oui", "yes", "ja", "s\u00ed", "adverbe", "A1"),
    ("hier", "yesterday", "gestern", "ayer", "adverbe", "A1"),
    ("toi / vous", "you", "du / ihr / Sie", "t\u00fa / usted / vosotros", "pron", "A1"),
    ("jeune", "young", "jung", "joven", "adjectif", "A1"),
    ("ton / votre", "your", "dein / euer / Ihr", "tu / su / vuestro", "det", "A1"),
    ("le zoo", "zoo", "der Zoo", "el zool\u00f3gico", "nom", "A1")
"@

[System.IO.File]::WriteAllText("$PSScriptRoot\append_part6.ps1", $new_words, $utf8NoBom)
