$utf8NoBom = New-Object System.Text.UTF8Encoding $False
$content = [System.IO.File]::ReadAllText("$PSScriptRoot\generate_data.py", $utf8NoBom)

$new_words = @"
    ,
    # --- LETTRE P ---
    ("la page", "page", "die Seite", "la página", "nom", "A1"),
    ("peindre", "paint", "malen", "pintar", "verbe", "A1"),
    ("la peinture", "painting", "das Gemälde", "la pintura", "nom", "A1"),
    ("la paire", "pair", "das Paar", "el par", "nom", "A1"),
    ("le papier", "paper", "das Papier", "el papel", "nom", "A1"),
    ("le paragraphe", "paragraph", "der Absatz", "el párrafo", "nom", "A1"),
    ("le parent", "parent", "das Elternteil", "el padre / la madre", "nom", "A1"),
    ("le parc", "park", "der Park", "el parque", "nom", "A1"),
    ("la partie", "part", "der Teil", "la parte", "nom", "A1"),
    ("le partenaire", "partner", "der Partner", "el compañero", "nom", "A1"),
    ("la fête", "party", "die Party", "la fiesta", "nom", "A1"),
    ("le passeport", "passport", "der Reisepass", "el pasaporte", "nom", "A1"),
    ("le passé", "past", "die Vergangenheit", "el pasado", "nom", "A1"),
    ("les pâtes", "pasta", "die Nudeln", "la pasta", "nom", "A1"),
    ("payer", "pay", "bezahlen", "pagar", "verbe", "A1"),
    ("le stylo", "pen", "der Stift", "el bolígrafo", "nom", "A1"),
    ("le crayon", "pencil", "der Bleistift", "el lápiz", "nom", "A1"),
    ("les gens", "people", "die Leute", "la gente", "nom", "A1"),
    ("le poivre", "pepper", "der Pfeffer", "la pimienta", "nom", "A1"),
    ("parfait", "perfect", "perfekt", "perfecto", "adjectif", "A1"),
    ("la période", "period", "der Zeitraum", "el período", "nom", "A1"),
    ("la personne", "person", "die Person", "la persona", "nom", "A1"),
    ("personnel", "personal", "persönlich", "personal", "adjectif", "A1"),
    ("le téléphone", "phone", "das Telefon", "el teléfono", "nom", "A1"),
    ("la photo", "photo", "das Foto", "la foto", "nom", "A1"),
    ("la photographie", "photograph", "die Fotografie", "la fotografía", "nom", "A1"),
    ("la phrase", "phrase", "der Satz", "la frase", "nom", "A1"),
    ("le piano", "piano", "das Klavier", "el piano", "nom", "A1"),
    ("l'image", "picture", "das Bild", "la imagen", "nom", "A1"),
    ("le morceau", "piece", "das Stück", "el trozo", "nom", "A1"),
    ("le cochon", "pig", "das Schwein", "el cerdo", "nom", "A1"),
    ("rose", "pink", "rosa", "rosa", "adjectif", "A1"),
    ("la pizza", "pizza", "die Pizza", "la pizza", "nom", "A1"),
    ("l'endroit", "place", "der Ort", "el lugar", "nom", "A1"),
    ("le plan", "plan", "der Plan", "el plan", "nom", "A1"),
    ("l'avion", "plane", "das Flugzeug", "el avión", "nom", "A1"),
    ("la plante", "plant", "die Pflanze", "la planta", "nom", "A1"),
    ("jouer", "play", "spielen", "jugar", "verbe", "A1"),
    ("le joueur", "player", "der Spieler", "el jugador", "nom", "A1"),
    ("s'il vous plaît", "please", "bitte", "por favor", "interj", "A1"),
    ("le point", "point", "der Punkt", "el punto", "nom", "A1"),
    ("la police", "police", "die Polizei", "la policía", "nom", "A1"),
    ("le policier", "policeman", "der Polizist", "el policía", "nom", "A1"),
    ("la piscine", "pool", "der Pool", "la piscina", "nom", "A1"),
    ("pauvre", "poor", "arm", "pobre", "adjectif", "A1"),
    ("pop (musique)", "pop", "Pop", "pop", "nom", "A1"),
    ("populaire", "popular", "beliebt", "popular", "adjectif", "A1"),
    ("possible", "possible", "möglich", "posible", "adjectif", "A1"),
    ("le courrier", "post", "die Post", "el correo", "nom", "A1"),
    ("la pomme de terre", "potato", "die Kartoffel", "la patata", "nom", "A1"),
    ("la livre (monnaie)", "pound", "das Pfund", "la libra", "nom", "A1"),
    ("la pratique", "practice", "die Übung", "la práctica", "nom", "A1"),
    ("pratiquer", "practise", "üben", "practicar", "verbe", "A1"),
    ("le présent / cadeau", "present", "das Geschenk / die Gegenwart", "el regalo / presente", "nom", "A1"),
    ("joli", "pretty", "hübsch", "bonito", "adjectif", "A1"),
    ("le prix", "price", "der Preis", "el precio", "nom", "A1"),
    ("le problème", "problem", "das Problem", "el problema", "nom", "A1"),
    ("le programme", "programme", "das Programm", "el programa", "nom", "A1"),
    ("le projet", "project", "das Projekt", "el proyecto", "nom", "A1"),
    ("violet", "purple", "lila", "morado", "adjectif", "A1"),
    ("mettre", "put", "stellen / legen", "poner", "verbe", "A1"),

    # --- LETTRE Q ---
    ("le quart", "quarter", "das Viertel", "el cuarto", "nom", "A1"),
    ("la question", "question", "die Frage", "la pregunta", "nom", "A1"),
    ("rapide", "quick", "schnell", "rápido", "adjectif", "A1"),
    ("rapidement", "quickly", "schnell", "rápidamente", "adverbe", "A1"),
    ("silencieux", "quiet", "leise", "silencioso", "adjectif", "A1"),
    ("assez / plutôt", "quite", "ziemlich", "bastante", "adverbe", "A1"),

    # --- LETTRE R ---
    ("le lapin", "rabbit", "das Kaninchen", "el conejo", "nom", "A1"),
    ("la radio", "radio", "das Radio", "la radio", "nom", "A1"),
    ("la pluie", "rain", "der Regen", "la lluvia", "nom", "A1"),
    ("lire", "read", "lesen", "leer", "verbe", "A1"),
    ("le lecteur", "reader", "der Leser", "el lector", "nom", "A1"),
    ("la lecture", "reading", "das Lesen", "la lectura", "nom", "A1"),
    ("prêt", "ready", "bereit", "listo", "adjectif", "A1"),
    ("réel", "real", "echt", "real", "adjectif", "A1"),
    ("vraiment", "really", "wirklich", "realmente", "adverbe", "A1"),
    ("la raison", "reason", "der Grund", "la razón", "nom", "A1"),
    ("rouge", "red", "rot", "rojo", "adjectif", "A1"),
    ("se détendre", "relax", "entspannen", "relajarse", "verbe", "A1"),
    ("se souvenir", "remember", "erinnern", "recordar", "verbe", "A1"),
    ("répéter", "repeat", "wiederholen", "repetir", "verbe", "A1"),
    ("le rapport", "report", "der Bericht", "el informe", "nom", "A1"),
    ("le restaurant", "restaurant", "das Restaurant", "el restaurante", "nom", "A1"),
    ("revenir / retourner", "return", "zurückkehren", "volver", "verbe", "A1"),
    ("le riz", "rice", "der Reis", "el arroz", "nom", "A1"),
    ("riche", "rich", "reich", "rico", "adjectif", "A1"),
    ("monter / conduire", "ride", "reiten / fahren", "montar", "verbe", "A1"),
    ("droite", "right", "rechts", "derecho", "adjectif", "A1"),
    ("la rivière", "river", "der Fluss", "el río", "nom", "A1"),
    ("la route", "road", "die Straße", "la carretera", "nom", "A1"),
    ("le rocher", "rock", "der Fels", "la roca", "nom", "A1"),
    ("la pièce / la chambre", "room", "das Zimmer", "la habitación", "nom", "A1"),
    ("la règle", "rule", "die Regel", "la regla", "nom", "A1"),
    ("courir", "run", "rennen", "correr", "verbe", "A1"),

    # --- LETTRE S (Part 1) ---
    ("triste", "sad", "traurig", "triste", "adjectif", "A1"),
    ("la salade", "salad", "der Salat", "la ensalada", "nom", "A1"),
    ("le sel", "salt", "das Salz", "la sal", "nom", "A1"),
    ("même (identique)", "same", "gleich", "mismo", "adjectif", "A1"),
    ("le sandwich", "sandwich", "das Sandwich", "el sándwich", "nom", "A1"),
    ("samedi", "Saturday", "Samstag", "sábado", "nom", "A1"),
    ("dire", "say", "sagen", "decir", "verbe", "A1"),
    ("l'école", "school", "die Schule", "la escuela", "nom", "A1"),
    ("la science", "science", "die Wissenschaft", "la ciencia", "nom", "A1"),
    ("le scientifique", "scientist", "der Wissenschaftler", "el científico", "nom", "A1"),
    ("la mer", "sea", "das Meer", "el mar", "nom", "A1"),
    ("la seconde / deuxième", "second", "die Sekunde / zweite", "el segundo", "nom", "A1"),
    ("la section", "section", "der Abschnitt", "la sección", "nom", "A1"),
    ("voir", "see", "sehen", "ver", "verbe", "A1"),
    ("envoyer", "send", "senden", "enviar", "verbe", "A1"),
    ("la phrase", "sentence", "der Satz", "la oración", "nom", "A1"),
    ("septembre", "September", "September", "septiembre", "nom", "A1"),
    ("sept", "seven", "sieben", "siete", "num", "A1"),
    ("dix-sept", "seventeen", "siebzehn", "diecisiete", "num", "A1"),
    ("soixante-dix", "seventy", "siebzig", "setenta", "num", "A1"),
    ("elle", "she", "sie", "ella", "pron", "A1"),
    ("le mouton", "sheep", "das Schaf", "la oveja", "nom", "A1"),
    ("la chemise", "shirt", "das Hemd", "la camisa", "nom", "A1"),
    ("la chaussure", "shoe", "der Schuh", "el zapato", "nom", "A1"),
    ("le magasin", "shop", "das Geschäft", "la tienda", "nom", "A1"),
    ("les courses", "shopping", "das Einkaufen", "las compras", "nom", "A1"),
    ("court", "short", "kurz", "corto", "adjectif", "A1"),
    ("devrait", "should", "sollte", "debería", "verbe", "A1"),
    ("montrer", "show", "zeigen", "mostrar", "verbe", "A1"),
    ("la douche", "shower", "die Dusche", "la ducha", "nom", "A1"),
    ("malade", "sick", "krank", "enfermo", "adjectif", "A1"),
    ("chanter", "sing", "singen", "cantar", "verbe", "A1"),
    ("le chanteur", "singer", "der Sänger", "el cantante", "nom", "A1"),
    ("la sœur", "sister", "die Schwester", "la hermana", "nom", "A1"),
    ("s'asseoir", "sit", "sitzen", "sentarse", "verbe", "A1"),
    ("six", "six", "sechs", "seis", "num", "A1"),
    ("seize", "sixteen", "sechzehn", "dieciséis", "num", "A1"),
    ("soixante", "sixty", "sechzig", "sesenta", "num", "A1"),
    ("la jupe", "skirt", "der Rock", "la falda", "nom", "A1"),
    ("dormir", "sleep", "schlafen", "dormir", "verbe", "A1"),
    ("lent", "slow", "langsam", "lento", "adjectif", "A1"),
    ("petit", "small", "klein", "pequeño", "adjectif", "A1"),
    ("le serpent", "snake", "die Schlange", "la serpiente", "nom", "A1")
"@

$content = $content -replace 'vocab_list = \[', "vocab_list = [$new_words"

[System.IO.File]::WriteAllText("$PSScriptRoot\generate_data.py", $content, $utf8NoBom)
Write-Host "Part 4 (P-S1) injected."
