import json

def get_base_vocabulary():
    """
    Returns the comprehensive base vocabulary list for drillFlow.
    Each tuple contains: (fr_word, en_word, de_word, es_word, type, level)
    Levels: A1, A2, B1
    Types: nom, verbe, adjectif, adverbe, conjonction, det, pron, interj, num, prep
    """
    # Liste compléte basée sur l'ESL Lounge A1 Word List demandée par l'utilisateur.
    vocab_list = [    ,
    # --- LETTRE V ---
    ("les vacances (US)", "vacation", "der Urlaub", "las vacaciones", "nom", "A1"),
    ("le lÃ©gume", "vegetable", "das GemÃ¼se", "la verdura", "nom", "A1"),
    ("trÃ¨s", "very", "sehr", "muy", "adverbe", "A1"),
    ("la vidÃ©o", "video", "das Video", "el vÃ­deo", "nom", "A1"),
    ("le village", "village", "das Dorf", "la aldea", "nom", "A1"),
    ("visiter", "visit", "besuchen", "visitar", "verbe", "A1"),
    ("le visiteur", "visitor", "der Besucher", "el visitante", "nom", "A1"),

    # --- LETTRE W ---
    ("attendre", "wait", "warten", "esperar", "verbe", "A1"),
    ("le serveur", "waiter", "der Kellner", "el camarero", "nom", "A1"),
    ("se rÃ©veiller", "wake", "aufwachen", "despertar", "verbe", "A1"),
    ("marcher", "walk", "gehen", "caminar", "verbe", "A1"),
    ("le mur", "wall", "die Wand", "la pared", "nom", "A1"),
    ("vouloir", "want", "wollen", "querer", "verbe", "A1"),
    ("chaud / chaleureux", "warm", "warm", "cÃ¡lido", "adjectif", "A1"),
    ("laver", "wash", "waschen", "lavar", "verbe", "A1"),
    ("la montre", "watch", "die Uhr", "el reloj", "nom", "A1"),
    ("regarder (TV)", "watch", "schauen", "mirar", "verbe", "A1"),
    ("l'eau", "water", "das Wasser", "el agua", "nom", "A1"),
    ("le chemin / la faÃ§on", "way", "der Weg / die Art", "el camino / la manera", "nom", "A1"),
    ("nous", "we", "wir", "nosotros", "pron", "A1"),
    ("porter (vÃªtements)", "wear", "tragen", "llevar puesto", "verbe", "A1"),
    ("le temps (mÃ©tÃ©o)", "weather", "das Wetter", "el clima", "nom", "A1"),
    ("le site web", "website", "die Website", "el sitio web", "nom", "A1"),
    ("mercredi", "Wednesday", "Mittwoch", "miÃ©rcoles", "nom", "A1"),
    ("la semaine", "week", "die Woche", "la semana", "nom", "A1"),
    ("le week-end", "weekend", "das Wochenende", "el fin de semana", "nom", "A1"),
    ("bien", "well", "gut", "bien", "adverbe", "A1"),
    ("l'ouest", "west", "der Westen", "el oeste", "nom", "A1"),
    ("quoi", "what", "was", "quÃ©", "pron", "A1"),
    ("quand", "when", "wann", "cuÃ¡ndo", "adverbe", "A1"),
    ("oÃ¹", "where", "wo", "dÃ³nde", "adverbe", "A1"),
    ("lequel", "which", "welcher", "cuÃ¡l", "pron", "A1"),
    ("blanc", "white", "weiÃŸ", "blanco", "adjectif", "A1"),
    ("qui", "who", "wer", "quiÃ©n", "pron", "A1"),
    ("pourquoi", "why", "warum", "por quÃ©", "adverbe", "A1"),
    ("la femme (Ã©pouse)", "wife", "die Ehefrau", "la esposa", "nom", "A1"),
    ("gagner", "win", "gewinnen", "ganar", "verbe", "A1"),
    ("la fenÃªtre", "window", "das Fenster", "la ventana", "nom", "A1"),
    ("le vin", "wine", "der Wein", "el vino", "nom", "A1"),
    ("l'hiver", "winter", "der Winter", "el invierno", "nom", "A1"),
    ("avec", "with", "mit", "con", "prep", "A1"),
    ("sans", "without", "ohne", "sin", "prep", "A1"),
    ("la femme", "woman", "die Frau", "la mujer", "nom", "A1"),
    ("merveilleux", "wonderful", "wunderbar", "maravilloso", "adjectif", "A1"),
    ("le mot", "word", "das Wort", "la palabra", "nom", "A1"),
    ("le travail", "work", "die Arbeit", "el trabajo", "nom", "A1"),
    ("travailler", "work", "arbeiten", "trabajar", "verbe", "A1"),
    ("le travailleur", "worker", "der Arbeiter", "el trabajador", "nom", "A1"),
    ("le monde", "world", "die Welt", "el mundo", "nom", "A1"),
    ("voudrait", "would", "wÃ¼rde", "harÃ­a (condicional)", "verbe", "A1"),
    ("Ã©crire", "write", "schreiben", "escribir", "verbe", "A1"),
    ("l'Ã©crivain", "writer", "der Autor", "el escritor", "nom", "A1"),
    ("l'Ã©criture", "writing", "das Schreiben", "la escritura", "nom", "A1"),
    ("faux (erreur)", "wrong", "falsch", "equivocado", "adjectif", "A1"),

    # --- LETTRE Y & Z ---
    ("l'annÃ©e", "year", "das Jahr", "el aÃ±o", "nom", "A1"),
    ("jaune", "yellow", "gelb", "amarillo", "adjectif", "A1"),
    ("oui", "yes", "ja", "sÃ­", "adverbe", "A1"),
    ("hier", "yesterday", "gestern", "ayer", "adverbe", "A1"),
    ("toi / vous", "you", "du / ihr / Sie", "tÃº / usted / vosotros", "pron", "A1"),
    ("jeune", "young", "jung", "joven", "adjectif", "A1"),
    ("ton / votre", "your", "dein / euer / Ihr", "tu / su / vuestro", "det", "A1"),
    ("le zoo", "zoo", "der Zoo", "el zoolÃ³gico", "nom", "A1")    ,
    # --- LETTRE S (Part 2) ---
    ("la neige", "snow", "der Schnee", "la nieve", "nom", "A1"),
    ("donc / alors", "so", "also", "asÃ­ que", "conjonction", "A1"),
    ("le canapÃ©", "sofa", "das Sofa", "el sofÃ¡", "nom", "A1"),
    ("quelques / du", "some", "einige / etwas", "algunos / algo de", "det", "A1"),
    ("quelqu'un (somebody)", "somebody", "jemand", "alguien", "pron", "A1"),
    ("quelqu'un (someone)", "someone", "jemand", "alguien", "pron", "A1"),
    ("quelque chose", "something", "etwas", "algo", "pron", "A1"),
    ("parfois", "sometimes", "manchmal", "a veces", "adverbe", "A1"),
    ("le fils", "son", "der Sohn", "el hijo", "nom", "A1"),
    ("la chanson", "song", "das Lied", "la canciÃ³n", "nom", "A1"),
    ("bientÃ´t", "soon", "bald", "pronto", "adverbe", "A1"),
    ("dÃ©solÃ©", "sorry", "entschuldigung", "lo siento", "adjectif", "A1"),
    ("le son / le bruit", "sound", "der Klang / das GerÃ¤usch", "el sonido", "nom", "A1"),
    ("la soupe", "soup", "die Suppe", "la sopa", "nom", "A1"),
    ("le sud", "south", "der SÃ¼den", "el sur", "nom", "A1"),
    ("l'espace", "space", "der Raum / der Platz", "el espacio", "nom", "A1"),
    ("parler", "speak", "sprechen", "hablar", "verbe", "A1"),
    ("spÃ©cial", "special", "speziell", "especial", "adjectif", "A1"),
    ("Ã©peler", "spell", "buchstabieren", "deletrear", "verbe", "A1"),
    ("l'orthographe", "spelling", "die Rechtschreibung", "la ortografÃ­a", "nom", "A1"),
    ("dÃ©penser / passer (temps)", "spend", "verbringen / ausgeben", "gastar / pasar", "verbe", "A1"),
    ("le sport", "sport", "der Sport", "el deporte", "nom", "A1"),
    ("le printemps", "spring", "der FrÃ¼hling", "la primavera", "nom", "A1"),
    ("se tenir debout", "stand", "stehen", "estar de pie", "verbe", "A1"),
    ("commencer", "start", "anfangen", "empezar", "verbe", "A1"),
    ("la gare / la station", "station", "der Bahnhof / die Station", "la estaciÃ³n", "nom", "A1"),
    ("arrÃªter", "stop", "stoppen", "parar", "verbe", "A1"),
    ("l'histoire", "story", "die Geschichte", "la historia", "nom", "A1"),
    ("la rue", "street", "die StraÃŸe", "la calle", "nom", "A1"),
    ("fort", "strong", "stark", "fuerte", "adjectif", "A1"),
    ("l'Ã©tudiant", "student", "der Student", "el estudiante", "nom", "A1"),
    ("Ã©tudier", "study", "studieren / lernen", "estudiar", "verbe", "A1"),
    ("le style", "style", "der Stil", "el estilo", "nom", "A1"),
    ("le sujet / la matiÃ¨re", "subject", "das Thema / das Fach", "el tema / la asignatura", "nom", "A1"),
    ("le sucre", "sugar", "der Zucker", "el azÃºcar", "nom", "A1"),
    ("l'Ã©tÃ©", "summer", "der Sommer", "el verano", "nom", "A1"),
    ("le soleil", "sun", "die Sonne", "el sol", "nom", "A1"),
    ("dimanche", "Sunday", "Sonntag", "domingo", "nom", "A1"),
    ("le supermarchÃ©", "supermarket", "der Supermarkt", "el supermercado", "nom", "A1"),
    ("sÃ»r", "sure", "sicher", "seguro", "adjectif", "A1"),
    ("le pull", "sweater", "der Pullover", "el suÃ©ter", "nom", "A1"),
    ("nager", "swim", "schwimmen", "nadar", "verbe", "A1"),
    ("la natation", "swimming", "das Schwimmen", "la nataciÃ³n", "nom", "A1"),

    # --- LETTRE T ---
    ("la table", "table", "der Tisch", "la mesa", "nom", "A1"),
    ("prendre", "take", "nehmen", "tomar", "verbe", "A1"),
    ("parler", "talk", "reden", "hablar", "verbe", "A1"),
    ("grand (taille)", "tall", "groÃŸ", "alto", "adjectif", "A1"),
    ("le taxi", "taxi", "das Taxi", "el taxi", "nom", "A1"),
    ("le thÃ©", "tea", "der Tee", "el tÃ©", "nom", "A1"),
    ("enseigner", "teach", "unterrichten", "enseÃ±ar", "verbe", "A1"),
    ("le professeur", "teacher", "der Lehrer", "el profesor", "nom", "A1"),
    ("l'Ã©quipe", "team", "das Team", "el equipo", "nom", "A1"),
    ("l'adolescent", "teenager", "der Teenager", "el adolescente", "nom", "A1"),
    ("le tÃ©lÃ©phone", "telephone", "das Telefon", "el telÃ©fono", "nom", "A1"),
    ("la tÃ©lÃ©vision", "television", "das Fernsehen", "la televisiÃ³n", "nom", "A1"),
    ("raconter / dire", "tell", "erzÃ¤hlen", "contar / decir", "verbe", "A1"),
    ("dix", "ten", "zehn", "diez", "num", "A1"),
    ("le tennis", "tennis", "das Tennis", "el tenis", "nom", "A1"),
    ("terrible", "terrible", "schrecklich", "terrible", "adjectif", "A1"),
    ("le test", "test", "der Test", "la prueba", "nom", "A1"),
    ("le texte", "text", "der Text", "el texto", "nom", "A1"),
    ("que (comparaison)", "than", "als", "que", "conjonction", "A1"),
    ("remercier", "thank", "danken", "agradecer", "verbe", "A1"),
    ("merci", "thanks", "danke", "gracias", "interj", "A1"),
    ("que / cela", "that", "dass / das", "que / eso", "det", "A1"),
    ("le / la / les", "the", "der / die / das", "el / la / los / las", "det", "A1"),
    ("le thÃ©Ã¢tre", "theatre", "das Theater", "el teatro", "nom", "A1"),
    ("leur", "their", "ihr", "su", "det", "A1"),
    ("eux / les", "them", "sie / ihnen", "ellos / los", "pron", "A1"),
    ("ensuite / alors", "then", "dann", "luego / entonces", "adverbe", "A1"),
    ("lÃ -bas", "there", "dort", "allÃ­", "adverbe", "A1"),
    ("ils / elles", "they", "sie", "ellos", "pron", "A1"),
    ("la chose", "thing", "das Ding", "la cosa", "nom", "A1"),
    ("penser", "think", "denken", "pensar", "verbe", "A1"),
    ("troisiÃ¨me", "third", "dritte", "tercero", "num", "A1"),
    ("assoiffÃ©", "thirsty", "durstig", "sediento", "adjectif", "A1"),
    ("treize", "thirteen", "dreizehn", "trece", "num", "A1"),
    ("trente", "thirty", "dreiÃŸig", "treinta", "num", "A1"),
    ("ce / ceci", "this", "dies", "este / esto", "det", "A1"),
    ("mille", "thousand", "tausend", "mil", "num", "A1"),
    ("trois", "three", "drei", "tres", "num", "A1"),
    ("Ã  travers / par", "through", "durch", "a travÃ©s de", "prep", "A1"),
    ("jeudi", "Thursday", "Donnerstag", "jueves", "nom", "A1"),
    ("le billet / ticket", "ticket", "das Ticket", "el billete", "nom", "A1"),
    ("le temps / l'heure", "time", "die Zeit", "el tiempo", "nom", "A1"),
    ("fatiguÃ©", "tired", "mÃ¼de", "cansado", "adjectif", "A1"),
    ("le titre", "title", "der Titel", "el tÃ­tulo", "nom", "A1"),
    ("Ã  / vers", "to", "zu", "a / hacia", "prep", "A1"),
    ("aujourd'hui", "today", "heute", "hoy", "adverbe", "A1"),
    ("ensemble", "together", "zusammen", "juntos", "adverbe", "A1"),
    ("les toilettes", "toilet", "die Toilette", "el baÃ±o", "nom", "A1"),
    ("la tomate", "tomato", "die Tomate", "el tomate", "nom", "A1"),
    ("demain", "tomorrow", "morgen", "maÃ±ana", "adverbe", "A1"),
    ("ce soir", "tonight", "heute Abend", "esta noche", "adverbe", "A1"),
    ("aussi / trop", "too", "auch / zu", "tambiÃ©n / demasiado", "adverbe", "A1"),
    ("le haut / sommet", "top", "oben", "arriba / cima", "nom", "A1"),
    ("la dent", "tooth", "der Zahn", "el diente", "nom", "A1"),
    ("le touriste", "tourist", "der Tourist", "el turista", "nom", "A1"),
    ("la ville", "town", "die Stadt", "el pueblo", "nom", "A1"),
    ("le trafic / circulation", "traffic", "der Verkehr", "el trÃ¡fico", "nom", "A1"),
    ("le train", "train", "der Zug", "el tren", "nom", "A1"),
    ("voyager", "travel", "reisen", "viajar", "verbe", "A1"),
    ("l'arbre", "tree", "der Baum", "el Ã¡rbol", "nom", "A1"),
    ("le voyage (court)", "trip", "die Reise", "el viaje", "nom", "A1"),
    ("le pantalon", "trousers", "die Hose", "los pantalones", "nom", "A1"),
    ("vrai", "true", "wahr", "verdadero", "adjectif", "A1"),
    ("essayer", "try", "versuchen", "intentar", "verbe", "A1"),
    ("le t-shirt", "T-shirt", "das T-Shirt", "la camiseta", "nom", "A1"),
    ("mardi", "Tuesday", "Dienstag", "martes", "nom", "A1"),
    ("tourner", "turn", "drehen", "girar", "verbe", "A1"),
    ("la tÃ©lÃ©", "TV", "der Fernseher", "la tele", "nom", "A1"),
    ("douze", "twelve", "zwÃ¶lf", "doce", "num", "A1"),
    ("vingt", "twenty", "zwanzig", "veinte", "num", "A1"),
    ("deux fois", "twice", "zweimal", "dos veces", "adverbe", "A1"),
    ("deux", "two", "zwei", "dos", "num", "A1"),
    ("le type / genre", "type", "der Typ", "el tipo", "nom", "A1"),

    # --- LETTRE U ---
    ("le parapluie", "umbrella", "der Regenschirm", "el paraguas", "nom", "A1"),
    ("l'oncle", "uncle", "der Onkel", "el tÃ­o", "nom", "A1"),
    ("sous", "under", "unter", "debajo", "prep", "A1"),
    ("comprendre", "understand", "verstehen", "entender", "verbe", "A1"),
    ("l'universitÃ©", "university", "die UniversitÃ¤t", "la universidad", "nom", "A1"),
    ("jusqu'Ã ", "until", "bis", "hasta", "conjonction", "A1"),
    ("en haut", "up", "auf / hoch", "arriba", "adverbe", "A1"),
    ("en haut (escaliers)", "upstairs", "oben", "arriba", "adverbe", "A1"),
    ("nous", "us", "uns", "nos", "pron", "A1"),
    ("utiliser", "use", "benutzen", "usar", "verbe", "A1"),
    ("habituellement", "usually", "normalerweise", "usualmente", "adverbe", "A1")    ,
    # --- LETTRE P ---
    ("la page", "page", "die Seite", "la pÃ¡gina", "nom", "A1"),
    ("peindre", "paint", "malen", "pintar", "verbe", "A1"),
    ("la peinture", "painting", "das GemÃ¤lde", "la pintura", "nom", "A1"),
    ("la paire", "pair", "das Paar", "el par", "nom", "A1"),
    ("le papier", "paper", "das Papier", "el papel", "nom", "A1"),
    ("le paragraphe", "paragraph", "der Absatz", "el pÃ¡rrafo", "nom", "A1"),
    ("le parent", "parent", "das Elternteil", "el padre / la madre", "nom", "A1"),
    ("le parc", "park", "der Park", "el parque", "nom", "A1"),
    ("la partie", "part", "der Teil", "la parte", "nom", "A1"),
    ("le partenaire", "partner", "der Partner", "el compaÃ±ero", "nom", "A1"),
    ("la fÃªte", "party", "die Party", "la fiesta", "nom", "A1"),
    ("le passeport", "passport", "der Reisepass", "el pasaporte", "nom", "A1"),
    ("le passÃ©", "past", "die Vergangenheit", "el pasado", "nom", "A1"),
    ("les pÃ¢tes", "pasta", "die Nudeln", "la pasta", "nom", "A1"),
    ("payer", "pay", "bezahlen", "pagar", "verbe", "A1"),
    ("le stylo", "pen", "der Stift", "el bolÃ­grafo", "nom", "A1"),
    ("le crayon", "pencil", "der Bleistift", "el lÃ¡piz", "nom", "A1"),
    ("les gens", "people", "die Leute", "la gente", "nom", "A1"),
    ("le poivre", "pepper", "der Pfeffer", "la pimienta", "nom", "A1"),
    ("parfait", "perfect", "perfekt", "perfecto", "adjectif", "A1"),
    ("la pÃ©riode", "period", "der Zeitraum", "el perÃ­odo", "nom", "A1"),
    ("la personne", "person", "die Person", "la persona", "nom", "A1"),
    ("personnel", "personal", "persÃ¶nlich", "personal", "adjectif", "A1"),
    ("le tÃ©lÃ©phone", "phone", "das Telefon", "el telÃ©fono", "nom", "A1"),
    ("la photo", "photo", "das Foto", "la foto", "nom", "A1"),
    ("la photographie", "photograph", "die Fotografie", "la fotografÃ­a", "nom", "A1"),
    ("la phrase", "phrase", "der Satz", "la frase", "nom", "A1"),
    ("le piano", "piano", "das Klavier", "el piano", "nom", "A1"),
    ("l'image", "picture", "das Bild", "la imagen", "nom", "A1"),
    ("le morceau", "piece", "das StÃ¼ck", "el trozo", "nom", "A1"),
    ("le cochon", "pig", "das Schwein", "el cerdo", "nom", "A1"),
    ("rose", "pink", "rosa", "rosa", "adjectif", "A1"),
    ("la pizza", "pizza", "die Pizza", "la pizza", "nom", "A1"),
    ("l'endroit", "place", "der Ort", "el lugar", "nom", "A1"),
    ("le plan", "plan", "der Plan", "el plan", "nom", "A1"),
    ("l'avion", "plane", "das Flugzeug", "el aviÃ³n", "nom", "A1"),
    ("la plante", "plant", "die Pflanze", "la planta", "nom", "A1"),
    ("jouer", "play", "spielen", "jugar", "verbe", "A1"),
    ("le joueur", "player", "der Spieler", "el jugador", "nom", "A1"),
    ("s'il vous plaÃ®t", "please", "bitte", "por favor", "interj", "A1"),
    ("le point", "point", "der Punkt", "el punto", "nom", "A1"),
    ("la police", "police", "die Polizei", "la policÃ­a", "nom", "A1"),
    ("le policier", "policeman", "der Polizist", "el policÃ­a", "nom", "A1"),
    ("la piscine", "pool", "der Pool", "la piscina", "nom", "A1"),
    ("pauvre", "poor", "arm", "pobre", "adjectif", "A1"),
    ("pop (musique)", "pop", "Pop", "pop", "nom", "A1"),
    ("populaire", "popular", "beliebt", "popular", "adjectif", "A1"),
    ("possible", "possible", "mÃ¶glich", "posible", "adjectif", "A1"),
    ("le courrier", "post", "die Post", "el correo", "nom", "A1"),
    ("la pomme de terre", "potato", "die Kartoffel", "la patata", "nom", "A1"),
    ("la livre (monnaie)", "pound", "das Pfund", "la libra", "nom", "A1"),
    ("la pratique", "practice", "die Ãœbung", "la prÃ¡ctica", "nom", "A1"),
    ("pratiquer", "practise", "Ã¼ben", "practicar", "verbe", "A1"),
    ("le prÃ©sent / cadeau", "present", "das Geschenk / die Gegenwart", "el regalo / presente", "nom", "A1"),
    ("joli", "pretty", "hÃ¼bsch", "bonito", "adjectif", "A1"),
    ("le prix", "price", "der Preis", "el precio", "nom", "A1"),
    ("le problÃ¨me", "problem", "das Problem", "el problema", "nom", "A1"),
    ("le programme", "programme", "das Programm", "el programa", "nom", "A1"),
    ("le projet", "project", "das Projekt", "el proyecto", "nom", "A1"),
    ("violet", "purple", "lila", "morado", "adjectif", "A1"),
    ("mettre", "put", "stellen / legen", "poner", "verbe", "A1"),

    # --- LETTRE Q ---
    ("le quart", "quarter", "das Viertel", "el cuarto", "nom", "A1"),
    ("la question", "question", "die Frage", "la pregunta", "nom", "A1"),
    ("rapide", "quick", "schnell", "rÃ¡pido", "adjectif", "A1"),
    ("rapidement", "quickly", "schnell", "rÃ¡pidamente", "adverbe", "A1"),
    ("silencieux", "quiet", "leise", "silencioso", "adjectif", "A1"),
    ("assez / plutÃ´t", "quite", "ziemlich", "bastante", "adverbe", "A1"),

    # --- LETTRE R ---
    ("le lapin", "rabbit", "das Kaninchen", "el conejo", "nom", "A1"),
    ("la radio", "radio", "das Radio", "la radio", "nom", "A1"),
    ("la pluie", "rain", "der Regen", "la lluvia", "nom", "A1"),
    ("lire", "read", "lesen", "leer", "verbe", "A1"),
    ("le lecteur", "reader", "der Leser", "el lector", "nom", "A1"),
    ("la lecture", "reading", "das Lesen", "la lectura", "nom", "A1"),
    ("prÃªt", "ready", "bereit", "listo", "adjectif", "A1"),
    ("rÃ©el", "real", "echt", "real", "adjectif", "A1"),
    ("vraiment", "really", "wirklich", "realmente", "adverbe", "A1"),
    ("la raison", "reason", "der Grund", "la razÃ³n", "nom", "A1"),
    ("rouge", "red", "rot", "rojo", "adjectif", "A1"),
    ("se dÃ©tendre", "relax", "entspannen", "relajarse", "verbe", "A1"),
    ("se souvenir", "remember", "erinnern", "recordar", "verbe", "A1"),
    ("rÃ©pÃ©ter", "repeat", "wiederholen", "repetir", "verbe", "A1"),
    ("le rapport", "report", "der Bericht", "el informe", "nom", "A1"),
    ("le restaurant", "restaurant", "das Restaurant", "el restaurante", "nom", "A1"),
    ("revenir / retourner", "return", "zurÃ¼ckkehren", "volver", "verbe", "A1"),
    ("le riz", "rice", "der Reis", "el arroz", "nom", "A1"),
    ("riche", "rich", "reich", "rico", "adjectif", "A1"),
    ("monter / conduire", "ride", "reiten / fahren", "montar", "verbe", "A1"),
    ("droite", "right", "rechts", "derecho", "adjectif", "A1"),
    ("la riviÃ¨re", "river", "der Fluss", "el rÃ­o", "nom", "A1"),
    ("la route", "road", "die StraÃŸe", "la carretera", "nom", "A1"),
    ("le rocher", "rock", "der Fels", "la roca", "nom", "A1"),
    ("la piÃ¨ce / la chambre", "room", "das Zimmer", "la habitaciÃ³n", "nom", "A1"),
    ("la rÃ¨gle", "rule", "die Regel", "la regla", "nom", "A1"),
    ("courir", "run", "rennen", "correr", "verbe", "A1"),

    # --- LETTRE S (Part 1) ---
    ("triste", "sad", "traurig", "triste", "adjectif", "A1"),
    ("la salade", "salad", "der Salat", "la ensalada", "nom", "A1"),
    ("le sel", "salt", "das Salz", "la sal", "nom", "A1"),
    ("mÃªme (identique)", "same", "gleich", "mismo", "adjectif", "A1"),
    ("le sandwich", "sandwich", "das Sandwich", "el sÃ¡ndwich", "nom", "A1"),
    ("samedi", "Saturday", "Samstag", "sÃ¡bado", "nom", "A1"),
    ("dire", "say", "sagen", "decir", "verbe", "A1"),
    ("l'Ã©cole", "school", "die Schule", "la escuela", "nom", "A1"),
    ("la science", "science", "die Wissenschaft", "la ciencia", "nom", "A1"),
    ("le scientifique", "scientist", "der Wissenschaftler", "el cientÃ­fico", "nom", "A1"),
    ("la mer", "sea", "das Meer", "el mar", "nom", "A1"),
    ("la seconde / deuxiÃ¨me", "second", "die Sekunde / zweite", "el segundo", "nom", "A1"),
    ("la section", "section", "der Abschnitt", "la secciÃ³n", "nom", "A1"),
    ("voir", "see", "sehen", "ver", "verbe", "A1"),
    ("envoyer", "send", "senden", "enviar", "verbe", "A1"),
    ("la phrase", "sentence", "der Satz", "la oraciÃ³n", "nom", "A1"),
    ("septembre", "September", "September", "septiembre", "nom", "A1"),
    ("sept", "seven", "sieben", "siete", "num", "A1"),
    ("dix-sept", "seventeen", "siebzehn", "diecisiete", "num", "A1"),
    ("soixante-dix", "seventy", "siebzig", "setenta", "num", "A1"),
    ("elle", "she", "sie", "ella", "pron", "A1"),
    ("le mouton", "sheep", "das Schaf", "la oveja", "nom", "A1"),
    ("la chemise", "shirt", "das Hemd", "la camisa", "nom", "A1"),
    ("la chaussure", "shoe", "der Schuh", "el zapato", "nom", "A1"),
    ("le magasin", "shop", "das GeschÃ¤ft", "la tienda", "nom", "A1"),
    ("les courses", "shopping", "das Einkaufen", "las compras", "nom", "A1"),
    ("court", "short", "kurz", "corto", "adjectif", "A1"),
    ("devrait", "should", "sollte", "deberÃ­a", "verbe", "A1"),
    ("montrer", "show", "zeigen", "mostrar", "verbe", "A1"),
    ("la douche", "shower", "die Dusche", "la ducha", "nom", "A1"),
    ("malade", "sick", "krank", "enfermo", "adjectif", "A1"),
    ("chanter", "sing", "singen", "cantar", "verbe", "A1"),
    ("le chanteur", "singer", "der SÃ¤nger", "el cantante", "nom", "A1"),
    ("la sÅ“ur", "sister", "die Schwester", "la hermana", "nom", "A1"),
    ("s'asseoir", "sit", "sitzen", "sentarse", "verbe", "A1"),
    ("six", "six", "sechs", "seis", "num", "A1"),
    ("seize", "sixteen", "sechzehn", "diecisÃ©is", "num", "A1"),
    ("soixante", "sixty", "sechzig", "sesenta", "num", "A1"),
    ("la jupe", "skirt", "der Rock", "la falda", "nom", "A1"),
    ("dormir", "sleep", "schlafen", "dormir", "verbe", "A1"),
    ("lent", "slow", "langsam", "lento", "adjectif", "A1"),
    ("petit", "small", "klein", "pequeÃ±o", "adjectif", "A1"),
    ("le serpent", "snake", "die Schlange", "la serpiente", "nom", "A1")    ,
    # --- LETTRE I ---
    ("je", "I", "ich", "yo", "pron", "A1"),
    ("la glace", "ice", "das Eis", "el hielo", "nom", "A1"),
    ("la crÃ¨me glacÃ©e", "ice cream", "das Eis", "el helado", "nom", "A1"),
    ("l'idÃ©e", "idea", "die Idee", "la idea", "nom", "A1"),
    ("si (condition)", "if", "wenn", "si", "conjonction", "A1"),
    ("important", "important", "wichtig", "importante", "adjectif", "A1"),
    ("dans", "in", "in", "en", "prep", "A1"),
    ("inclure", "include", "einschlieÃŸen", "incluir", "verbe", "A1"),
    ("l'information", "information", "die Information", "la informaciÃ³n", "nom", "A1"),
    ("l'intÃ©rÃªt", "interest", "das Interesse", "el interÃ©s", "nom", "A1"),
    ("intÃ©ressÃ©", "interested", "interessiert", "interesado", "adjectif", "A1"),
    ("intÃ©ressant", "interesting", "interessant", "interesante", "adjectif", "A1"),
    ("l'internet", "internet", "das Internet", "el internet", "nom", "A1"),
    ("l'entretien", "interview", "das Interview", "la entrevista", "nom", "A1"),
    ("dans (mouvement)", "into", "in", "hacia adentro", "prep", "A1"),
    ("prÃ©senter", "introduce", "vorstellen", "presentar", "verbe", "A1"),
    ("l'Ã®le", "island", "die Insel", "la isla", "nom", "A1"),
    ("il / elle (objet)", "it", "es", "lo", "pron", "A1"),
    ("son / sa (objet)", "its", "sein", "su", "det", "A1"),

    # --- LETTRE J ---
    ("la veste", "jacket", "die Jacke", "la chaqueta", "nom", "A1"),
    ("janvier", "January", "Januar", "enero", "nom", "A1"),
    ("le jean", "jeans", "die Jeans", "los vaqueros", "nom", "A1"),
    ("le travail", "job", "der Job", "el trabajo", "nom", "A1"),
    ("rejoindre", "join", "beitreten", "unirse", "verbe", "A1"),
    ("le voyage", "journey", "die Reise", "el viaje", "nom", "A1"),
    ("le jus", "juice", "der Saft", "el jugo", "nom", "A1"),
    ("juillet", "July", "Juli", "julio", "nom", "A1"),
    ("juin", "June", "Juni", "junio", "nom", "A1"),
    ("juste", "just", "nur / gerade", "justo", "adverbe", "A1"),

    # --- LETTRE K ---
    ("garder", "keep", "behalten", "mantener", "verbe", "A1"),
    ("la clÃ©", "key", "der SchlÃ¼ssel", "la llave", "nom", "A1"),
    ("le kilomÃ¨tre", "kilometre", "der Kilometer", "el kilÃ³metro", "nom", "A1"),
    ("le genre / gentil", "kind", "die Art / nett", "el tipo / amable", "nom", "A1"),
    ("la cuisine (piÃ¨ce)", "kitchen", "die KÃ¼che", "la cocina", "nom", "A1"),
    ("savoir / connaÃ®tre", "know", "wissen / kennen", "saber / conocer", "verbe", "A1"),

    # --- LETTRE L ---
    ("la terre", "land", "das Land", "la tierra", "nom", "A1"),
    ("la langue", "language", "die Sprache", "el idioma", "nom", "A1"),
    ("grand / large", "large", "groÃŸ", "grande", "adjectif", "A1"),
    ("dernier", "last", "letzte", "Ãºltimo", "adjectif", "A1"),
    ("en retard", "late", "spÃ¤t", "tarde", "adjectif", "A1"),
    ("plus tard", "later", "spÃ¤ter", "mÃ¡s tarde", "adverbe", "A1"),
    ("rire", "laugh", "lachen", "reÃ­r", "verbe", "A1"),
    ("apprendre", "learn", "lernen", "aprender", "verbe", "A1"),
    ("quitter / laisser", "leave", "verlassen", "dejar", "verbe", "A1"),
    ("gauche", "left", "links", "izquierdo", "adjectif", "A1"),
    ("la jambe", "leg", "das Bein", "la pierna", "nom", "A1"),
    ("la leÃ§on", "lesson", "die Lektion", "la lecciÃ³n", "nom", "A1"),
    ("laisser / permettre", "let", "lassen", "dejar", "verbe", "A1"),
    ("la lettre", "letter", "der Brief", "la carta", "nom", "A1"),
    ("la bibliothÃ¨que", "library", "die Bibliothek", "la biblioteca", "nom", "A1"),
    ("s'allonger / mentir", "lie", "liegen / lÃ¼gen", "mentir / tumbarse", "verbe", "A1"),
    ("la vie", "life", "das Leben", "la vida", "nom", "A1"),
    ("la lumiÃ¨re", "light", "das Licht", "la luz", "nom", "A1"),
    ("comme (similaire)", "like", "wie", "como", "prep", "A1"),
    ("aimer", "like", "mÃ¶gen", "gustar", "verbe", "A1"),
    ("la ligne", "line", "die Linie", "la lÃ­nea", "nom", "A1"),
    ("le lion", "lion", "der LÃ¶we", "el leÃ³n", "nom", "A1"),
    ("la liste", "list", "die Liste", "la lista", "nom", "A1"),
    ("Ã©couter", "listen", "zuhÃ¶ren", "escuchar", "verbe", "A1"),
    ("petit", "little", "klein", "pequeÃ±o", "adjectif", "A1"),
    ("vivre", "live", "leben", "vivir", "verbe", "A1"),
    ("long", "long", "lang", "largo", "adjectif", "A1"),
    ("regarder", "look", "schauen", "mirar", "verbe", "A1"),
    ("perdre", "lose", "verlieren", "perder", "verbe", "A1"),
    ("beaucoup", "lot", "viel", "mucho", "nom", "A1"),
    ("aimer (amour)", "love", "lieben", "amar", "verbe", "A1"),
    ("le dÃ©jeuner", "lunch", "das Mittagessen", "el almuerzo", "nom", "A1"),

    # --- LETTRE M ---
    ("la machine", "machine", "die Maschine", "la mÃ¡quina", "nom", "A1"),
    ("le magazine", "magazine", "das Magazin", "la revista", "nom", "A1"),
    ("principal", "main", "Haupt-", "principal", "adjectif", "A1"),
    ("fabriquer / faire", "make", "machen", "hacer", "verbe", "A1"),
    ("l'homme", "man", "der Mann", "el hombre", "nom", "A1"),
    ("beaucoup (dÃ©nombrable)", "many", "viele", "muchos", "det", "A1"),
    ("la carte (plan)", "map", "die Karte", "el mapa", "nom", "A1"),
    ("mars", "March", "MÃ¤rz", "marzo", "nom", "A1"),
    ("le marchÃ©", "market", "der Markt", "el mercado", "nom", "A1"),
    ("mariÃ©", "married", "verheiratet", "casado", "adjectif", "A1"),
    ("le match", "match", "das Spiel", "el partido", "nom", "A1"),
    ("mai", "May", "Mai", "mayo", "nom", "A1"),
    ("peut-Ãªtre", "maybe", "vielleicht", "tal vez", "adverbe", "A1"),
    ("moi", "me", "mich / mir", "mÃ­", "pron", "A1"),
    ("le repas", "meal", "die Mahlzeit", "la comida", "nom", "A1"),
    ("signifier", "mean", "bedeuten", "significar", "verbe", "A1"),
    ("la signification", "meaning", "die Bedeutung", "el significado", "nom", "A1"),
    ("la viande", "meat", "das Fleisch", "la carne", "nom", "A1"),
    ("rencontrer", "meet", "treffen", "encontrar", "verbe", "A1"),
    ("la rÃ©union", "meeting", "das Meeting", "la reuniÃ³n", "nom", "A1"),
    ("le membre", "member", "das Mitglied", "el miembro", "nom", "A1"),
    ("le menu", "menu", "das MenÃ¼", "el menÃº", "nom", "A1"),
    ("le message", "message", "die Nachricht", "el mensaje", "nom", "A1"),
    ("le mÃ¨tre", "metre", "der Meter", "el metro", "nom", "A1"),
    ("le milieu", "middle", "die Mitte", "el medio", "nom", "A1"),
    ("minuit", "midnight", "Mitternacht", "medianoche", "nom", "A1"),
    ("le mile", "mile", "die Meile", "la milla", "nom", "A1"),
    ("le lait", "milk", "die Milch", "la leche", "nom", "A1"),
    ("le million", "million", "die Million", "el millÃ³n", "num", "A1"),
    ("la minute", "minute", "die Minute", "el minuto", "nom", "A1"),
    ("manquer", "miss", "vermissen", "extraÃ±ar", "verbe", "A1"),
    ("l'erreur", "mistake", "der Fehler", "el error", "nom", "A1"),
    ("le modÃ¨le", "model", "das Modell", "el modelo", "nom", "A1"),
    ("moderne", "modern", "modern", "moderno", "adjectif", "A1"),
    ("le moment", "moment", "der Moment", "el momento", "nom", "A1"),
    ("lundi", "Monday", "Montag", "lunes", "nom", "A1"),
    ("l'argent", "money", "das Geld", "el dinero", "nom", "A1"),
    ("le mois", "month", "der Monat", "el mes", "nom", "A1"),
    ("plus", "more", "mehr", "mÃ¡s", "adverbe", "A1"),
    ("le matin", "morning", "der Morgen", "la maÃ±ana", "nom", "A1"),
    ("le plus", "most", "am meisten", "la mayorÃ­a", "adverbe", "A1"),
    ("la mÃ¨re", "mother", "die Mutter", "la madre", "nom", "A1"),
    ("la montagne", "mountain", "der Berg", "la montaÃ±a", "nom", "A1"),
    ("la souris", "mouse", "die Maus", "el ratÃ³n", "nom", "A1"),
    ("la bouche", "mouth", "der Mund", "la boca", "nom", "A1"),
    ("bouger / dÃ©mÃ©nager", "move", "bewegen", "mover", "verbe", "A1"),
    ("le film (US)", "movie", "der Film", "la pelÃ­cula", "nom", "A1"),
    ("beaucoup (indÃ©nombrable)", "much", "viel", "mucho", "adverbe", "A1"),
    ("la maman", "mum", "die Mama", "la mamÃ¡", "nom", "A1"),
    ("le musÃ©e", "museum", "das Museum", "el museo", "nom", "A1"),
    ("la musique", "music", "die Musik", "la mÃºsica", "nom", "A1"),
    ("devoir (obligation)", "must", "mÃ¼ssen", "deber", "verbe", "A1"),
    ("mon / ma", "my", "mein", "mi", "det", "A1"),

    # --- LETTRE N ---
    ("le nom", "name", "der Name", "el nombre", "nom", "A1"),
    ("prÃ¨s", "near", "in der NÃ¤he", "cerca", "prep", "A1"),
    ("avoir besoin", "need", "brauchen", "necesitar", "verbe", "A1"),
    ("le voisin", "neighbour", "der Nachbar", "el vecino", "nom", "A1"),
    ("jamais", "never", "nie", "nunca", "adverbe", "A1"),
    ("nouveau", "new", "neu", "nuevo", "adjectif", "A1"),
    ("les nouvelles", "news", "die Nachrichten", "las noticias", "nom", "A1"),
    ("le journal", "newspaper", "die Zeitung", "el periÃ³dico", "nom", "A1"),
    ("suivant", "next", "nÃ¤chste", "siguiente", "adjectif", "A1"),
    ("Ã  cÃ´tÃ© de", "next to", "neben", "al lado de", "prep", "A1"),
    ("sympa / agrÃ©able", "nice", "nett", "agradable", "adjectif", "A1"),
    ("la nuit", "night", "die Nacht", "la noche", "nom", "A1"),
    ("neuf", "nine", "neun", "nueve", "num", "A1"),
    ("dix-neuf", "nineteen", "neunzehn", "diecinueve", "num", "A1"),
    ("quatre-vingt-dix", "ninety", "neunzig", "noventa", "num", "A1"),
    ("non / aucun", "no", "nein / kein", "no / ningÃºn", "det", "A1"),
    ("personne (no one)", "no one", "niemand", "nadie", "pron", "A1"),
    ("personne (nobody)", "nobody", "niemand", "nadie", "pron", "A1"),
    ("midi", "noon", "Mittag", "mediodÃ­a", "nom", "A1"),
    ("le nord", "north", "der Norden", "el norte", "nom", "A1"),
    ("le nez", "nose", "die Nase", "la nariz", "nom", "A1"),
    ("ne pas", "not", "nicht", "no", "adverbe", "A1"),
    ("la note", "note", "die Notiz", "la nota", "nom", "A1"),
    ("rien", "nothing", "nichts", "nada", "pron", "A1"),
    ("novembre", "November", "November", "noviembre", "nom", "A1"),
    ("maintenant", "now", "jetzt", "ahora", "adverbe", "A1"),
    ("le nombre", "number", "die Zahl", "el nÃºmero", "nom", "A1"),
    ("l'infirmiÃ¨re", "nurse", "die Krankenschwester", "la enfermera", "nom", "A1"),

    # --- LETTRE O ---
    ("heure pile (o'clock)", "o'clock", "Uhr", "en punto", "adverbe", "A1"),
    ("octobre", "October", "Oktober", "octubre", "nom", "A1"),
    ("de (appartenance)", "of", "von", "de", "prep", "A1"),
    ("Ã©teint / hors", "off", "aus", "apagado / fuera", "adverbe", "A1"),
    ("le bureau (lieu)", "office", "das BÃ¼ro", "la oficina", "nom", "A1"),
    ("souvent", "often", "oft", "a menudo", "adverbe", "A1"),
    ("oh", "oh", "oh", "oh", "interj", "A1"),
    ("d'accord", "OK", "okay", "vale", "adjectif", "A1"),
    ("vieux", "old", "alt", "viejo", "adjectif", "A1"),
    ("sur", "on", "auf", "en", "prep", "A1"),
    ("une fois", "once", "einmal", "una vez", "adverbe", "A1"),
    ("un / l'un", "one", "eins", "uno", "num", "A1"),
    ("l'oignon", "onion", "die Zwiebel", "la cebolla", "nom", "A1"),
    ("en ligne", "online", "online", "en lÃ­nea", "adjectif", "A1"),
    ("seulement", "only", "nur", "solo", "adverbe", "A1"),
    ("ouvrir", "open", "Ã¶ffnen", "abrir", "verbe", "A1"),
    ("ouvert", "open", "offen", "abierto", "adjectif", "A1"),
    ("opposÃ© / en face", "opposite", "gegenÃ¼ber", "opuesto", "adjectif", "A1"),
    ("ou", "or", "oder", "o", "conjonction", "A1"),
    ("l'orange", "orange", "die Orange", "la naranja", "nom", "A1"),
    ("commander", "order", "bestellen", "pedir", "verbe", "A1"),
    ("autre", "other", "andere", "otro", "adjectif", "A1"),
    ("notre", "our", "unser", "nuestro", "det", "A1"),
    ("dehors", "out", "heraus", "fuera", "adverbe", "A1"),
    ("Ã  l'extÃ©rieur", "outside", "drauÃŸen", "afuera", "adverbe", "A1"),
    ("au-dessus de / terminÃ©", "over", "Ã¼ber", "sobre / terminado", "prep", "A1"),
    ("possÃ©der", "own", "besitzen", "poseer", "verbe", "A1")    ,
    # --- LETTRE E ---
    ("chaque", "each", "jeder", "cada", "det", "A1"),
    ("l'oreille", "ear", "das Ohr", "la oreja", "nom", "A1"),
    ("tÃ´t", "early", "frÃ¼h", "temprano", "adjectif", "A1"),
    ("l'est (direction)", "east", "der Osten", "el este", "nom", "A1"),
    ("facile", "easy", "einfach", "fÃ¡cil", "adjectif", "A1"),
    ("manger", "eat", "essen", "comer", "verbe", "A1"),
    ("l'Å“uf", "egg", "das Ei", "el huevo", "nom", "A1"),
    ("huit", "eight", "acht", "ocho", "num", "A1"),
    ("dix-huit", "eighteen", "achtzehn", "dieciocho", "num", "A1"),
    ("quatre-vingts", "eighty", "achtzig", "ochenta", "num", "A1"),
    ("l'Ã©lÃ©phant", "elephant", "der Elefant", "el elefante", "nom", "A1"),
    ("onze", "eleven", "elf", "once", "num", "A1"),
    ("d'autre", "else", "sonst", "mÃ¡s", "adverbe", "A1"),
    ("l'e-mail", "email", "die E-Mail", "el correo", "nom", "A1"),
    ("la fin", "end", "das Ende", "el fin", "nom", "A1"),
    ("profiter", "enjoy", "genieÃŸen", "disfrutar", "verbe", "A1"),
    ("assez", "enough", "genug", "suficiente", "det", "A1"),
    ("l'euro", "euro", "der Euro", "el euro", "nom", "A1"),
    ("mÃªme", "even", "sogar", "incluso", "adverbe", "A1"),
    ("le soir", "evening", "der Abend", "la noche", "nom", "A1"),
    ("jamais (dÃ©jÃ )", "ever", "jemals", "alguna vez", "adverbe", "A1"),
    ("chaque (2)", "every", "jeder", "cada", "det", "A1"),
    ("tout le monde", "everybody", "jeder", "todos", "pron", "A1"),
    ("chacun", "everyone", "jeder", "todos", "pron", "A1"),
    ("tout", "everything", "alles", "todo", "pron", "A1"),
    ("l'examen", "exam", "die PrÃ¼fung", "el examen", "nom", "A1"),
    ("l'exemple", "example", "das Beispiel", "el ejemplo", "nom", "A1"),
    ("excitÃ©", "excited", "aufgeregt", "emocionado", "adjectif", "A1"),
    ("passionnant", "exciting", "aufregend", "emocionante", "adjectif", "A1"),
    ("l'exercice", "exercise", "die Ãœbung", "el ejercicio", "nom", "A1"),
    ("cher (prix)", "expensive", "teuer", "caro", "adjectif", "A1"),
    ("expliquer", "explain", "erklÃ¤ren", "explicar", "verbe", "A1"),
    ("supplÃ©mentaire", "extra", "zusÃ¤tzlich", "extra", "adjectif", "A1"),
    ("l'Å“il", "eye", "das Auge", "el ojo", "nom", "A1"),

    # --- LETTRE F ---
    ("le visage", "face", "das Gesicht", "la cara", "nom", "A1"),
    ("tomber", "fall", "fallen", "caer", "verbe", "A1"),
    ("faux", "false", "falsch", "falso", "adjectif", "A1"),
    ("la famille", "family", "die Familie", "la familia", "nom", "A1"),
    ("cÃ©lÃ¨bre", "famous", "berÃ¼hmt", "famoso", "adjectif", "A1"),
    ("fantastique", "fantastic", "fantastisch", "fantÃ¡stico", "adjectif", "A1"),
    ("loin", "far", "weit", "lejos", "adverbe", "A1"),
    ("la ferme", "farm", "der Bauernhof", "la granja", "nom", "A1"),
    ("le fermier", "farmer", "der Bauer", "el granjero", "nom", "A1"),
    ("rapide", "fast", "schnell", "rÃ¡pido", "adjectif", "A1"),
    ("gros", "fat", "dick", "gordo", "adjectif", "A1"),
    ("le pÃ¨re", "father", "der Vater", "el padre", "nom", "A1"),
    ("prÃ©fÃ©rÃ©", "favourite", "lieblings", "favorito", "adjectif", "A1"),
    ("fÃ©vrier", "February", "Februar", "febrero", "nom", "A1"),
    ("ressentir", "feel", "fÃ¼hlen", "sentir", "verbe", "A1"),
    ("le festival", "festival", "das Festival", "el festival", "nom", "A1"),
    ("peu", "few", "wenige", "pocos", "det", "A1"),
    ("quinze", "fifteen", "fÃ¼nfzehn", "quince", "num", "A1"),
    ("cinquiÃ¨me", "fifth", "fÃ¼nfte", "quinto", "num", "A1"),
    ("cinquante", "fifty", "fÃ¼nfzig", "cincuenta", "num", "A1"),
    ("remplir", "fill", "fÃ¼llen", "llenar", "verbe", "A1"),
    ("le film", "film", "der Film", "el film", "nom", "A1"),
    ("final", "final", "endgÃ¼ltig", "final", "adjectif", "A1"),
    ("trouver", "find", "finden", "encontrar", "verbe", "A1"),
    ("bien", "fine", "gut", "bien", "adjectif", "A1"),
    ("finir", "finish", "beenden", "terminar", "verbe", "A1"),
    ("le feu", "fire", "das Feuer", "el fuego", "nom", "A1"),
    ("premier", "first", "erste", "primero", "num", "A1"),
    ("le poisson", "fish", "der Fisch", "el pescado", "nom", "A1"),
    ("cinq", "five", "fÃ¼nf", "cinco", "num", "A1"),
    ("rÃ©parer / fixer", "fix", "reparieren", "arreglar", "verbe", "A1"),
    ("l'appartement", "flat", "die Wohnung", "el piso", "nom", "A1"),
    ("le vol", "flight", "der Flug", "el vuelo", "nom", "A1"),
    ("le sol / l'Ã©tage", "floor", "der Boden", "el suelo", "nom", "A1"),
    ("la fleur", "flower", "die Blume", "la flor", "nom", "A1"),
    ("voler (air)", "fly", "fliegen", "volar", "verbe", "A1"),
    ("suivre", "follow", "folgen", "seguir", "verbe", "A1"),
    ("la nourriture", "food", "das Essen", "la comida", "nom", "A1"),
    ("le pied", "foot", "der FuÃŸ", "el pie", "nom", "A1"),
    ("le football", "football", "der FuÃŸball", "el fÃºtbol", "nom", "A1"),
    ("pour", "for", "fÃ¼r", "para", "prep", "A1"),
    ("oublier", "forget", "vergessen", "olvidar", "verbe", "A1"),
    ("le formulaire", "form", "das Formular", "el formulario", "nom", "A1"),
    ("quarante", "forty", "vierzig", "cuarenta", "num", "A1"),
    ("quatre", "four", "vier", "cuatro", "num", "A1"),
    ("quatorze", "fourteen", "vierzehn", "catorce", "num", "A1"),
    ("quatriÃ¨me", "fourth", "vierte", "cuarto", "num", "A1"),
    ("libre / gratuit", "free", "frei", "libre", "adjectif", "A1"),
    ("vendredi", "Friday", "Freitag", "viernes", "nom", "A1"),
    ("l'ami", "friend", "der Freund", "el amigo", "nom", "A1"),
    ("amical", "friendly", "freundlich", "amigable", "adjectif", "A1"),
    ("de (provenance)", "from", "von", "de", "prep", "A1"),
    ("le devant", "front", "die Vorderseite", "el frente", "nom", "A1"),
    ("le fruit", "fruit", "das Obst", "la fruta", "nom", "A1"),
    ("plein", "full", "voll", "lleno", "adjectif", "A1"),
    ("l'amusement", "fun", "der SpaÃŸ", "la diversiÃ³n", "nom", "A1"),
    ("drÃ´le", "funny", "lustig", "divertido", "adjectif", "A1"),
    ("le futur", "future", "die Zukunft", "el futuro", "nom", "A1"),

    # --- LETTRE G ---
    ("le jeu", "game", "das Spiel", "el juego", "nom", "A1"),
    ("le jardin", "garden", "der Garten", "el jardÃ­n", "nom", "A1"),
    ("la gÃ©ographie", "geography", "die Geografie", "la geografÃ­a", "nom", "A1"),
    ("obtenir", "get", "bekommen", "conseguir", "verbe", "A1"),
    ("la fille", "girl", "das MÃ¤dchen", "la chica", "nom", "A1"),
    ("la petite-amie", "girlfriend", "die Freundin", "la novia", "nom", "A1"),
    ("donner", "give", "geben", "dar", "verbe", "A1"),
    ("le verre", "glass", "das Glas", "el vaso", "nom", "A1"),
    ("aller", "go", "gehen", "ir", "verbe", "A1"),
    ("bon", "good", "gut", "bueno", "adjectif", "A1"),
    ("au revoir", "goodbye", "auf Wiedersehen", "adiÃ³s", "interj", "A1"),
    ("le grand-pÃ¨re", "grandfather", "der GroÃŸvater", "el abuelo", "nom", "A1"),
    ("la grand-mÃ¨re", "grandmother", "die GroÃŸmutter", "la abuela", "nom", "A1"),
    ("le grand-parent", "grandparent", "das GroÃŸelternteil", "el abuelo", "nom", "A1"),
    ("super", "great", "groÃŸartig", "genial", "adjectif", "A1"),
    ("vert", "green", "grÃ¼n", "verde", "adjectif", "A1"),
    ("gris", "grey", "grau", "gris", "adjectif", "A1"),
    ("le groupe", "group", "die Gruppe", "el grupo", "nom", "A1"),
    ("grandir", "grow", "wachsen", "crecer", "verbe", "A1"),
    ("deviner", "guess", "raten", "adivinar", "verbe", "A1"),
    ("la guitare", "guitar", "die Gitarre", "la guitarra", "nom", "A1"),
    ("la salle de sport", "gym", "das Fitnessstudio", "el gimnasio", "nom", "A1"),

    # --- LETTRE H ---
    ("les cheveux", "hair", "die Haare", "el pelo", "nom", "A1"),
    ("la moitiÃ©", "half", "die HÃ¤lfte", "la mitad", "nom", "A1"),
    ("la main", "hand", "die Hand", "la mano", "nom", "A1"),
    ("se passer", "happen", "passieren", "suceder", "verbe", "A1"),
    ("heureux", "happy", "glÃ¼cklich", "feliz", "adjectif", "A1"),
    ("dur", "hard", "hart", "duro", "adjectif", "A1"),
    ("le chapeau", "hat", "der Hut", "el sombrero", "nom", "A1"),
    ("dÃ©tester", "hate", "hassen", "odiar", "verbe", "A1"),
    ("avoir", "have", "haben", "tener", "verbe", "A1"),
    ("devoir", "have to", "mÃ¼ssen", "tener que", "verbe", "A1"),
    ("il", "he", "er", "Ã©l", "pron", "A1"),
    ("la tÃªte", "head", "der Kopf", "la cabeza", "nom", "A1"),
    ("la santÃ©", "health", "die Gesundheit", "la salud", "nom", "A1"),
    ("en bonne santÃ©", "healthy", "gesund", "saludable", "adjectif", "A1"),
    ("entendre", "hear", "hÃ¶ren", "oÃ­r", "verbe", "A1"),
    ("bonjour", "hello", "hallo", "hola", "interj", "A1"),
    ("aider", "help", "helfen", "ayudar", "verbe", "A1"),
    ("elle / la sienne", "her", "ihr", "su / ella", "pron", "A1"),
    ("ici", "here", "hier", "aquÃ­", "adverbe", "A1"),
    ("hÃ©", "hey", "hey", "oye", "interj", "A1"),
    ("salut", "hi", "hallo", "hola", "interj", "A1"),
    ("haut", "high", "hoch", "alto", "adjectif", "A1"),
    ("lui", "him", "ihn", "Ã©l", "pron", "A1"),
    ("son / le sien", "his", "sein", "su", "det", "A1"),
    ("l'histoire", "history", "die Geschichte", "la historia", "nom", "A1"),
    ("le passe-temps", "hobby", "das Hobby", "el pasatiempo", "nom", "A1"),
    ("les vacances", "holiday", "der Urlaub", "las vacaciones", "nom", "A1"),
    ("la maison", "home", "das Zuhause", "el hogar", "nom", "A1"),
    ("les devoirs", "homework", "die Hausaufgaben", "los deberes", "nom", "A1"),
    ("espÃ©rer", "hope", "hoffen", "esperar", "verbe", "A1"),
    ("le cheval", "horse", "das Pferd", "el caballo", "nom", "A1"),
    ("l'hÃ´pital", "hospital", "das Krankenhaus", "el hospital", "nom", "A1"),
    ("chaud", "hot", "heiÃŸ", "caliente", "adjectif", "A1"),
    ("l'hÃ´tel", "hotel", "das Hotel", "el hotel", "nom", "A1"),
    ("l'heure", "hour", "die Stunde", "la hora", "nom", "A1"),
    ("la maison (bÃ¢timent)", "house", "das Haus", "la casa", "nom", "A1"),
    ("comment", "how", "wie", "cÃ³mo", "adverbe", "A1"),
    ("cent", "hundred", "hundert", "cien", "num", "A1"),
    ("affamÃ©", "hungry", "hungrig", "hambriento", "adjectif", "A1"),
    ("le mari", "husband", "der Ehemann", "el marido", "nom", "A1")    # --- LETTRE A ---
    ("un / une", "a / an", "ein / eine", "un / una", "det", "A1"),
    ("au sujet de", "about", "Ã¼ber", "sobre", "prep", "A1"),
    ("au-dessus", "above", "Ã¼ber", "encima", "prep", "A1"),
    ("Ã  travers", "across", "Ã¼ber", "a travÃ©s de", "prep", "A1"),
    ("l'action", "action", "die Aktion", "la acciÃ³n", "nom", "A1"),
    ("l'activitÃ©", "activity", "die AktivitÃ¤t", "la actividad", "nom", "A1"),
    ("l'acteur", "actor", "der Schauspieler", "el actor", "nom", "A1"),
    ("l'actrice", "actress", "die Schauspielerin", "la actriz", "nom", "A1"),
    ("ajouter", "add", "hinzufÃ¼gen", "aÃ±adir", "verbe", "A1"),
    ("l'adresse", "address", "die Adresse", "la direcciÃ³n", "nom", "A1"),
    ("l'adulte", "adult", "der Erwachsene", "el adulto", "nom", "A1"),
    ("effrayÃ©", "afraid", "verÃ¤ngstigt", "asustado", "adjectif", "A1"),
    ("aprÃ¨s", "after", "nach", "despuÃ©s", "prep", "A1"),
    ("l'aprÃ¨s-midi", "afternoon", "der Nachmittag", "la tarde", "nom", "A1"),
    ("encore", "again", "wieder", "otra vez", "adverbe", "A1"),
    ("l'Ã¢ge", "age", "das Alter", "la edad", "nom", "A1"),
    ("il y a (temps)", "ago", "vor", "hace", "adverbe", "A1"),
    ("l'air", "air", "die Luft", "el aire", "nom", "A1"),
    ("l'aÃ©roport", "airport", "der Flughafen", "el aeropuerto", "nom", "A1"),
    ("tout", "all", "alles", "todo", "det", "A1"),
    ("d'accord", "all right", "in Ordnung", "de acuerdo", "adjectif", "A1"),
    ("aussi", "also", "auch", "tambiÃ©n", "adverbe", "A1"),
    ("toujours", "always", "immer", "siempre", "adverbe", "A1"),
    ("incroyable", "amazing", "erstaunlich", "increÃ­ble", "adjectif", "A1"),
    ("et", "and", "und", "y", "conjonction", "A1"),
    ("en colÃ¨re", "angry", "wÃ¼tend", "enojado", "adjectif", "A1"),
    ("l'animal", "animal", "das Tier", "el animal", "nom", "A1"),
    ("un autre", "another", "ein anderer", "otro", "det", "A1"),
    ("rÃ©pondre", "answer", "antworten", "responder", "verbe", "A1"),
    ("la rÃ©ponse", "answer", "die Antwort", "la respuesta", "nom", "A1"),
    ("n'importe quel", "any", "irgendein", "cualquier", "det", "A1"),
    ("n'importe qui", "anyone", "jemand", "alguien", "pron", "A1"),
    ("n'importe quoi", "anything", "etwas", "algo", "pron", "A1"),
    ("l'appartement", "apartment", "die Wohnung", "el apartamento", "nom", "A1"),
    ("la pomme", "apple", "der Apfel", "la manzana", "nom", "A1"),
    ("avril", "April", "April", "abril", "nom", "A1"),
    ("la zone", "area", "das Gebiet", "el Ã¡rea", "nom", "A1"),
    ("le bras", "arm", "der Arm", "el brazo", "nom", "A1"),
    ("autour", "around", "um", "alrededor", "prep", "A1"),
    ("arriver", "arrive", "ankommen", "llegar", "verbe", "A1"),
    ("l'art", "art", "die Kunst", "el arte", "nom", "A1"),
    ("l'article", "article", "der Artikel", "el artÃ­culo", "nom", "A1"),
    ("l'artiste", "artist", "der KÃ¼nstler", "el artista", "nom", "A1"),
    ("comme", "as", "wie", "como", "prep", "A1"),
    ("demander", "ask", "fragen", "preguntar", "verbe", "A1"),
    ("Ã ", "at", "an / um", "en", "prep", "A1"),
    ("aoÃ»t", "August", "August", "agosto", "nom", "A1"),
    ("la tante", "aunt", "die Tante", "la tÃ­a", "nom", "A1"),
    ("l'automne", "autumn", "der Herbst", "el otoÃ±o", "nom", "A1"),
    ("loin", "away", "weg", "lejos", "adverbe", "A1"),

    # --- LETTRE B ---
    ("le bÃ©bÃ©", "baby", "das Baby", "el bebÃ©", "nom", "A1"),
    ("en arriÃ¨re", "back", "zurÃ¼ck", "atrÃ¡s", "adverbe", "A1"),
    ("mauvais", "bad", "schlecht", "malo", "adjectif", "A1"),
    ("le sac", "bag", "die Tasche", "la bolsa", "nom", "A1"),
    ("la balle", "ball", "der Ball", "la pelota", "nom", "A1"),
    ("la banane", "banana", "die Banane", "el plÃ¡tano", "nom", "A1"),
    ("le groupe", "band", "die Band", "la banda", "nom", "A1"),
    ("la banque", "bank", "die Bank", "el banco", "nom", "A1"),
    ("le bar", "bar", "die Bar", "el bar", "nom", "A1"),
    ("le bain", "bath", "das Bad", "el baÃ±o", "nom", "A1"),
    ("la salle de bain", "bathroom", "das Badezimmer", "el baÃ±o", "nom", "A1"),
    ("Ãªtre", "be", "sein", "ser / estar", "verbe", "A1"),
    ("la plage", "beach", "der Strand", "la playa", "nom", "A1"),
    ("beau", "beautiful", "schÃ¶n", "hermoso", "adjectif", "A1"),
    ("parce que", "because", "weil", "porque", "conjonction", "A1"),
    ("devenir", "become", "werden", "convertirse", "verbe", "A1"),
    ("le lit", "bed", "das Bett", "la cama", "nom", "A1"),
    ("la chambre", "bedroom", "das Schlafzimmer", "el dormitorio", "nom", "A1"),
    ("la biÃ¨re", "beer", "das Bier", "la cerveza", "nom", "A1"),
    ("avant", "before", "vor", "antes", "prep", "A1"),
    ("commencer", "begin", "beginnen", "empezar", "verbe", "A1"),
    ("le dÃ©but", "beginning", "der Anfang", "el principio", "nom", "A1"),
    ("derriÃ¨re", "behind", "hinter", "detrÃ¡s", "prep", "A1"),
    ("croire", "believe", "glauben", "creer", "verbe", "A1"),
    ("en dessous", "below", "unter", "debajo", "prep", "A1"),
    ("le meilleur", "best", "am besten", "mejor", "adjectif", "A1"),
    ("mieux", "better", "besser", "mejor", "adjectif", "A1"),
    ("entre", "between", "zwischen", "entre", "prep", "A1"),
    ("le vÃ©lo", "bicycle", "das Fahrrad", "la bicicleta", "nom", "A1"),
    ("grand", "big", "groÃŸ", "grande", "adjectif", "A1"),
    ("le vÃ©lo (familier)", "bike", "das Fahrrad", "la bici", "nom", "A1"),
    ("l'addition", "bill", "die Rechnung", "la cuenta", "nom", "A1"),
    ("l'oiseau", "bird", "der Vogel", "el pÃ¡jaro", "nom", "A1"),
    ("l'anniversaire", "birthday", "der Geburtstag", "el cumpleaÃ±os", "nom", "A1"),
    ("noir", "black", "schwarz", "negro", "adjectif", "A1"),
    ("le blog", "blog", "der Blog", "el blog", "nom", "A1"),
    ("blond", "blonde", "blond", "rubio", "adjectif", "A1"),
    ("bleu", "blue", "blau", "azul", "adjectif", "A1"),
    ("le bateau", "boat", "das Boot", "el barco", "nom", "A1"),
    ("le corps", "body", "der KÃ¶rper", "el cuerpo", "nom", "A1"),
    ("le livre", "book", "das Buch", "el libro", "nom", "A1"),
    ("la botte", "boot", "der Stiefel", "la bota", "nom", "A1"),
    ("ennuyÃ©", "bored", "gelangweilt", "aburrido", "adjectif", "A1"),
    ("ennuyeux", "boring", "langweilig", "aburrido", "adjectif", "A1"),
    ("nÃ©", "born", "geboren", "nacido", "adjectif", "A1"),
    ("les deux", "both", "beide", "ambos", "det", "A1"),
    ("la bouteille", "bottle", "die Flasche", "la botella", "nom", "A1"),
    ("le fond", "bottom", "der Boden", "el fondo", "nom", "A1"),
    ("la boÃ®te", "box", "die Box", "la caja", "nom", "A1"),
    ("le garÃ§on", "boy", "der Junge", "el chico", "nom", "A1"),
    ("le petit-ami", "boyfriend", "der Freund", "el novio", "nom", "A1"),
    ("le pain", "bread", "das Brot", "el pan", "nom", "A1"),
    ("casser", "break", "brechen", "romper", "verbe", "A1"),
    ("le petit-dÃ©jeuner", "breakfast", "das FrÃ¼hstÃ¼ck", "el desayuno", "nom", "A1"),
    ("apporter", "bring", "bringen", "traer", "verbe", "A1"),
    ("le frÃ¨re", "brother", "der Bruder", "el hermano", "nom", "A1"),
    ("marron", "brown", "braun", "marrÃ³n", "adjectif", "A1"),
    ("construire", "build", "bauen", "construir", "verbe", "A1"),
    ("le bÃ¢timent", "building", "das GebÃ¤ude", "el edificio", "nom", "A1"),
    ("le bus", "bus", "der Bus", "el autobÃºs", "nom", "A1"),
    ("l'entreprise", "business", "das GeschÃ¤ft", "el negocio", "nom", "A1"),
    ("occupÃ©", "busy", "beschÃ¤ftigt", "ocupado", "adjectif", "A1"),
    ("mais", "but", "aber", "pero", "conjonction", "A1"),
    ("le beurre", "butter", "die Butter", "la mantequilla", "nom", "A1"),
    ("acheter", "buy", "kaufen", "comprar", "verbe", "A1"),
    ("par", "by", "von / durch", "por", "prep", "A1"),
    ("au revoir", "bye", "tschÃ¼ss", "adiÃ³s", "interj", "A1"),

    # --- LETTRE C ---
    ("le cafÃ© (lieu)", "cafe", "das CafÃ©", "la cafeterÃ­a", "nom", "A1"),
    ("le gÃ¢teau", "cake", "der Kuchen", "el pastel", "nom", "A1"),
    ("appeler", "call", "anrufen", "llamar", "verbe", "A1"),
    ("l'appareil photo", "camera", "die Kamera", "la cÃ¡mara", "nom", "A1"),
    ("pouvoir", "can", "kÃ¶nnen", "poder", "verbe", "A1"),
    ("ne pas pouvoir", "cannot", "nicht kÃ¶nnen", "no poder", "verbe", "A1"),
    ("la capitale", "capital", "die Hauptstadt", "la capital", "nom", "A1"),
    ("la voiture", "car", "das Auto", "el coche", "nom", "A1"),
    ("la carte", "card", "die Karte", "la tarjeta", "nom", "A1"),
    ("la carotte", "carrot", "die Karotte", "la zanahoria", "nom", "A1"),
    ("porter", "carry", "tragen", "llevar", "verbe", "A1"),
    ("le chat", "cat", "die Katze", "el gato", "nom", "A1"),
    ("le CD", "CD", "die CD", "el CD", "nom", "A1"),
    ("le centime", "cent", "der Cent", "el cÃ©ntimo", "nom", "A1"),
    ("le centre", "centre", "das Zentrum", "el centro", "nom", "A1"),
    ("la chaise", "chair", "der Stuhl", "la silla", "nom", "A1"),
    ("changer", "change", "Ã¤ndern", "cambiar", "verbe", "A1"),
    ("le graphique", "chart", "das Diagramm", "el grÃ¡fico", "nom", "A1"),
    ("bon marchÃ©", "cheap", "billig", "barato", "adjectif", "A1"),
    ("vÃ©rifier", "check", "Ã¼berprÃ¼fen", "comprobar", "verbe", "A1"),
    ("le fromage", "cheese", "der KÃ¤se", "el queso", "nom", "A1"),
    ("le poulet", "chicken", "das HÃ¤hnchen", "el pollo", "nom", "A1"),
    ("l'enfant", "child", "das Kind", "el niÃ±o", "nom", "A1"),
    ("le chocolat", "chocolate", "die Schokolade", "el chocolate", "nom", "A1"),
    ("choisir", "choose", "wÃ¤hlen", "elegir", "verbe", "A1"),
    ("le cinÃ©ma", "cinema", "das Kino", "el cine", "nom", "A1"),
    ("la ville", "city", "die Stadt", "la ciudad", "nom", "A1"),
    ("la classe", "class", "die Klasse", "la clase", "nom", "A1"),
    ("la salle de classe", "classroom", "das Klassenzimmer", "el aula", "nom", "A1"),
    ("nettoyer", "clean", "putzen", "limpiar", "verbe", "A1"),
    ("propre", "clean", "sauber", "limpio", "adjectif", "A1"),
    ("grimper", "climb", "klettern", "escalar", "verbe", "A1"),
    ("l'horloge", "clock", "die Uhr", "el reloj", "nom", "A1"),
    ("fermer", "close", "schlieÃŸen", "cerrar", "verbe", "A1"),
    ("les vÃªtements", "clothes", "die Kleidung", "la ropa", "nom", "A1"),
    ("le club", "club", "der Club", "el club", "nom", "A1"),
    ("le manteau", "coat", "der Mantel", "el abrigo", "nom", "A1"),
    ("le cafÃ© (boisson)", "coffee", "der Kaffee", "el cafÃ©", "nom", "A1"),
    ("froid", "cold", "kalt", "frÃ­o", "adjectif", "A1"),
    ("le collÃ¨ge", "college", "das College", "la universidad", "nom", "A1"),
    ("la couleur", "colour", "die Farbe", "el color", "nom", "A1"),
    ("venir", "come", "kommen", "venir", "verbe", "A1"),
    ("l'entreprise (2)", "company", "das Unternehmen", "la empresa", "nom", "A1"),
    ("complÃ©ter", "complete", "vervollstÃ¤ndigen", "completar", "verbe", "A1"),
    ("l'ordinateur", "computer", "der Computer", "el ordenador", "nom", "A1"),
    ("le concert", "concert", "das Konzert", "el concierto", "nom", "A1"),
    ("cuisiner", "cook", "kochen", "cocinar", "verbe", "A1"),
    ("la cuisine (action)", "cooking", "das Kochen", "la cocina", "nom", "A1"),
    ("gÃ©nial / frais", "cool", "cool", "genial / fresco", "adjectif", "A1"),
    ("correct", "correct", "richtig", "correcto", "adjectif", "A1"),
    ("coÃ»ter", "cost", "kosten", "costar", "verbe", "A1"),
    ("pourrait", "could", "kÃ¶nnte", "podrÃ­a", "verbe", "A1"),
    ("le pays", "country", "das Land", "el paÃ­s", "nom", "A1"),
    ("le cours", "course", "der Kurs", "el curso", "nom", "A1"),
    ("le cousin", "cousin", "der Cousin", "el primo", "nom", "A1"),
    ("la vache", "cow", "die Kuh", "la vaca", "nom", "A1"),
    ("la crÃ¨me", "cream", "die Sahne", "la crema", "nom", "A1"),
    ("la tasse", "cup", "die Tasse", "la taza", "nom", "A1"),
    ("le client", "customer", "der Kunde", "el cliente", "nom", "A1"),
    ("couper", "cut", "schneiden", "cortar", "verbe", "A1"),

    # --- LETTRE D ---
    ("le papa", "dad", "der Papa", "el papÃ¡", "nom", "A1"),
    ("quotidien", "daily", "tÃ¤glich", "diario", "adjectif", "A1"),
    ("danser", "dance", "tanzen", "bailar", "verbe", "A1"),
    ("le danseur", "dancer", "der TÃ¤nzer", "el bailarÃ­n", "nom", "A1"),
    ("la danse", "dancing", "das Tanzen", "el baile", "nom", "A1"),
    ("dangereux", "dangerous", "gefÃ¤hrlich", "peligroso", "adjectif", "A1"),
    ("sombre", "dark", "dunkel", "oscuro", "adjectif", "A1"),
    ("la date", "date", "das Datum", "la fecha", "nom", "A1"),
    ("la fille (enfant)", "daughter", "die Tochter", "la hija", "nom", "A1"),
    ("le jour", "day", "der Tag", "el dÃ­a", "nom", "A1"),
    ("cher (affection)", "dear", "lieb", "querido", "adjectif", "A1"),
    ("dÃ©cembre", "December", "Dezember", "diciembre", "nom", "A1"),
    ("dÃ©cider", "decide", "entscheiden", "decidir", "verbe", "A1"),
    ("dÃ©licieux", "delicious", "kÃ¶stlich", "delicioso", "adjectif", "A1"),
    ("le bureau", "desk", "der Schreibtisch", "el escritorio", "nom", "A1"),
    ("le dÃ©tail", "detail", "das Detail", "el detalle", "nom", "A1"),
    ("le dialogue", "dialogue", "der Dialog", "el diÃ¡logo", "nom", "A1"),
    ("le dictionnaire", "dictionary", "das WÃ¶rterbuch", "el diccionario", "nom", "A1"),
    ("mourir", "die", "sterben", "morir", "verbe", "A1"),
    ("le rÃ©gime", "diet", "die DiÃ¤t", "la dieta", "nom", "A1"),
    ("diffÃ©rent", "different", "anders", "diferente", "adjectif", "A1"),
    ("difficile", "difficult", "schwierig", "difÃ­cil", "adjectif", "A1"),
    ("le dÃ®ner", "dinner", "das Abendessen", "la cena", "nom", "A1"),
    ("sale", "dirty", "schmutzig", "sucio", "adjectif", "A1"),
    ("le plat", "dish", "das Gericht", "el plato", "nom", "A1"),
    ("faire", "do", "tun / machen", "hacer", "verbe", "A1"),
    ("le docteur", "doctor", "der Arzt", "el mÃ©dico", "nom", "A1"),
    ("le chien", "dog", "der Hund", "el perro", "nom", "A1"),
    ("le dollar", "dollar", "der Dollar", "el dÃ³lar", "nom", "A1"),
    ("la porte", "door", "die TÃ¼r", "la puerta", "nom", "A1"),
    ("en bas", "down", "unten", "abajo", "adverbe", "A1"),
    ("en bas (escaliers)", "downstairs", "unten", "abajo", "adverbe", "A1"),
    ("dessiner", "draw", "zeichnen", "dibujar", "verbe", "A1"),
    ("la robe", "dress", "das Kleid", "el vestido", "nom", "A1"),
    ("boire", "drink", "trinken", "beber", "verbe", "A1"),
    ("conduire", "drive", "fahren", "conducir", "verbe", "A1"),
    ("le chauffeur", "driver", "der Fahrer", "el conductor", "nom", "A1"),
    ("la conduite", "driving", "das Fahren", "la conducciÃ³n", "nom", "A1"),
    ("sec", "dry", "trocken", "seco", "adjectif", "A1"),
    ("pendant", "during", "wÃ¤hrend", "durante", "prep", "A1"),
    ("le DVD", "DVD", "die DVD", "el DVD", "nom", "A1")
    ]
    
    # Transformation en liste de dictionnaires
    formatted_vocab = []
    for index, (fr, en, de, es, type_word, level) in enumerate(vocab_list):
        formatted_vocab.append({
            "id": f"v_{index + 1}",
            "fr": fr,
            "en": en,
            "de": de,
            "es": es,
            "type": type_word,
            "level": level
        })
        
    return formatted_vocab

if __name__ == "__main__":
    vocab = get_base_vocabulary()
    print(json.dumps(vocab, ensure_ascii=False, indent=2))
